### ISSUE TITLE
RecorderEndpoint callbacks are not called when recording fails

### ISSUE THREAD

**Issue by glennjgonzales** [Kurento/bugtracker#100]
**KMS Version**:
```
$ kurento-media-server -v
Version: 6.5.1~5.g4bc4363
Found modules:
	Module: 'core' version '6.5.1~58.ga86e575'
	Module: 'elements' version '6.5.1~34.g9b960a3'
	Module: 'filters' version '6.5.1~1.ge5b1703'
```

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running
```
$ dpkg -l|egrep -i "kurento|gst.*1.5|nice"
ii  gstreamer1.5-libav:amd64             1.8.2.1~20160629121554.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160712121041.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160609065146.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160712121041.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.1~20160712140020.58.ga86e575.trusty    amd64        Kurento core module
ii  kms-elements-6.0                     6.5.1~20160712141125.34.g9b960a3.trusty    amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.1~20160712142634.1.ge5b1703.trusty     amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.2~20160531124242.1.g2fa3dea.trusty     amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.1~20160712144523.5.g4bc4363.trusty     amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160706093049.167.g0d8d50e.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)
```

**Client libraries**
- Language: Java
- Version: 6.5.1-SNAPSHOT

**Browsers tested**
- Only on Chrome

**Does it happen with one of the tutorials?**

Yes, tested on the kurento-tutorial-java/kurento-one2one-call-recording

**Issue Description**

I'm trying to do one-to-one recording and currently using the example from `kurento-tutorial-java/kurento-one2one-call-recording`. I have it running very well -- recording happens when all requirements are met, and the videos can be viewed, downloaded, and are otherwise perfect.

In the RecorderEndpoint interface, you can supposedly use the following:
```
RecorderEndpoint.addErrorListener(EventListener<ErrorEvent>)
RecorderEndpoint.record(Continuation<Void>)
```
to receive notifications of errors (and success, in the case of Continuation). In my case, I'm trying to detect when the kurento user (running kms) has no write permissions on the directory specified to contain the video recording(s); for example:
```
public static final String RECORDING_PATH = "file:///some/media/dir" 
```
of `CallMediaPipeline.java` in the tutorial. Another scenario is when the kms runs out of disk space and can no longer write any video.

However, the callbacks above don't get called when there is an error in recording. What should be expected from these methods? What situations would cause them to be called?

I have tried the `MediaPipeline.addErrorListener(EventListener<ErrorEvent>)` and this does work (receives the appropriate error), but I would have thought the callbacks on `RecorderEndpoint` should also have been notified, especially with `RecorderEndpoint.record(Continuation<Void>)`. Why is it like this?

So in a nutshell, basically when the permissions are wrong and kms can't write to the directory this is what I see:
```
RecorderEndpoint.addErrorListener(EventListener<ErrorEvent>) --> NOT CALLED
RecorderEndpoint.record(Continuation<Void>) --> NOT CALLED
```
but:
```
MediaPipeline.addErrorListener(EventListener<ErrorEvent>) --> YES, GETS CALLED (sample output from my logs: "pipeline got error -> Could not open file "/some/media/dir/my_video.webm" for writing. -> gstfilesink.c(438): gst_file_sink_open_file (): /GstPipeline:pipeline1/GstFileSink:filesink0:
system error: No such file or directory; errCode=6; type=UNEXPECTED_PIPELINE_ERROR")
```

In the dev version, the error messages from kms are like this:
```
2016-07-14 15:55:52.895 ERROR 6735 --- [ventExec-e2-t16] o.k.t.one2onecallrec.CallMediaPipeline   : pipeline got error -> Could not open file "/some/media/dir/my_video.webm" for writing. -> gstfilesink.c(438): gst_file_sink_open_file (): /GstPipeline:pipeline8/GstFileSink:filesink5:
system error: Permission denied; errCode=6; type=UNEXPECTED_PIPELINE_ERROR

2016-07-14 15:55:52.895 ERROR 6735 --- [ventExec-e2-t21] o.k.t.one2onecallrec.CallMediaPipeline   : pipeline got error -> GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. -> gstbasesink.c(5244): gst_base_sink_change_state (): /GstPipeline:pipeline8/GstFileSink:filesink5:
Failed to start; errCode=4; type=UNEXPECTED_PIPELINE_ERROR
```
So now the error message is correct ("Permission denied" instead of "No such file or directory"), plus there's a message about some element not posting a proper error message.

**Expected Behavior**

These callbacks
```
RecorderEndpoint.addErrorListener(EventListener<ErrorEvent>)
RecorderEndpoint.record(Continuation<Void>)
```
should be invoked when there's an error condition related to recording.

**Other Info**

Related thread is [here](https://groups.google.com/forum/#!topic/kurento/6jhe5Ieucjs)

**Comment by dfernandezlop** [comment]
Hi,

The issue has been fixed with this patch https://github.com/Kurento/kms-elements/commit/538b12fe436f1c8a6b62e2968ddf8f8f9258388f

Thanks for the report.
Regards,

**Comment by suryansht93** [comment]
hi, can you help in recording and saving video in one to many call.
