### ISSUE TITLE
KMS 6.5.0, Ubuntu 14.04 LTS, cannot play recorded files or cannot record with remote kurento repository

### ISSUE THREAD

**Issue by hdlopesrocha** [Kurento/bugtracker#101]
**KMS Version**: 6.5.0
**Kurento Repository Version**: 6.5.0

**Other libraries versions**:

> ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
> ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
> ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
> ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
> ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
> ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
> ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
> ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
> ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
> ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
> ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
> ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
> ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
> ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
> ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
> ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
> ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
> ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: Java
- Version: 8

**Browsers tested**
- Firefox: 47.0
- Chrome: 51.0.2704.103 

**System description:**
    I deployed my system using docker: kurento repository, kurento media server and mongodb (they have different names and they are in the same network) 

**What steps will reproduce the problem?**
1. Create an item with Kurento Repository API (Java)
2. Record Video using the item url
3. Let it record (stop and release)
4. Get item by using its item ID (error 404 not found)

**What is the expected result?**
From step 1 you can see on kurento repository logs

> 2016-07-15 16:22:04,887 DEBUG [http-nio-7676-exec-7] repository.RepositoryService (getEndpointUrl(195)) - Created recorder for repo item #57890dace4b095937a63416a
>   url=http://kurento-repository-000:7676/repository_servlet/dabbqmpvvcervjq0a4olrhmglc

Probably I would see some log entries for step 2,3 and 4

**What happens instead?**
The recorded file cannot be found

> 2016-07-15 16:22:17,573 DEBUG [http-nio-7676-exec-1] repository.RepositoryService (findRepositoryItemById(241)) - Provided id is not valid
> java.util.NoSuchElementException: The repository item with id "57890dace4b095937a63416a" does not exist
>   at org.kurento.repository.internal.repoimpl.mongo.MongoRepository.findRepositoryItemById(MongoRepository.java:81)
>   at org.kurento.repository.RepositoryService.findRepositoryItemById(RepositoryService.java:239)
>   at org.kurento.repository.RepositoryService.getEndpointUrl(RepositoryService.java:170)
>   at org.kurento.repository.RepositoryService.getReadEndpoint(RepositoryService.java:89)
>   at org.kurento.repository.RepositoryController.getReadEndpoint(RepositoryController.java:74)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
>   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
>   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
>   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
>   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
>   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
>   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
>   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
>   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
>   at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
>   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
>   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
>   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
>   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
>   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
>   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
>   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
>   at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
>   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Thread.java:745)

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

```
  I am using STUN and TURN and everything works except the recorder. I have used kurento-repository 6.4.0 with all stuff installed in a single machine and it worked perfectly.
```

This is my kurento-repo config:

```
 {
   "repository": {
     "port": 7676,
     "hostname": "kurento-repository-000",
     "type": "mongodb",
     "mongodb": {
       "dbName": "kurento",
       "gridName": "kfs",
       "urlConn": "mongodb://mongodb-000"
     },
     "filesystem": {
       "folder": "/tmp/repository"
     }
   }
 }
```

The recorder works if I record directly to file system.

This is my recorder code:

```
item = KurentoManager.repository.createRepositoryItem(Collections.emptyMap());
url = item.getUrl();

RecorderEndpoint.Builder builder = new RecorderEndpoint.Builder(pipeline, url);
builder.withMediaProfile(MediaProfileSpecType.WEBM).stopOnEndOfStream();

recorder = builder.build();
endPoint.connect(recorder);
recorder.record();
Thread.sleep(10000);
recorder.stop();
recorder.release();
```

This is my player code:

```
RepositoryItemPlayer item = KurentoManager.repository.getReadEndpoint(itemId); // error 404 not found
itemUrl = item.getUrl();
PlayerEndpoint tempAudio = new PlayerEndpoint.Builder(pipeline, itemUrl).build();
```

And this is how I am running the docker containers:

```
docker network create bullray.net
docker run --net=bullray.net --name mongodb-000 -v ~/mongodb-000:/data/db -d mongo 
docker run --net=bullray.net --name kurento-repository-000 -d bullray/kurento-repository
docker run --net=bullray.net --name kurento-media-server-000 -d bullray/kurento-media-server
docker run --net=bullray.net --name webserver-000 -v ~/webserver-000:/root/code -p 80:2080 -p 443:2443 -p 2080:2080 -p 2443:2443 bullray/webserver
```

**Comment by jrpedrianes** [comment]
Hello,

Any news of this?, I have the same error in 6.10.0 version. Do we need add additional config to Kurento Media Server docker container to support external repository?

I'm doing the same test, but with 6.10.0 version, and I have the same result, is possible to record to local filesystem but is not possible to record in the repository server.

**Comment by micaelgallego** [comment]
Kurento Repository is not maintained in the last years... It is possible that some bug have appeared during that time.

If your commercial application relay on this, remember that dev team offers commercial services for these kind of issues.

**Comment by jrpedrianes** [comment]
Ooook, 

One question more, Does Kurento Media Server have an endpoint to request the local stored file? or we need to go to the filesystem directly

**Comment by micaelgallego** [comment]
Yes... with PlayerEndpoint you can use local file paths

**Comment by jrpedrianes** [comment]
But, is posible to obtain the file?

**Comment by micaelgallego** [comment]
If file is written in MongoDB, you first should extract the file from it.

In any case, KurentoRepository have a mode to work with FileSystem.. without MondoDB that maybe you can use.

**Comment by jrpedrianes** [comment]
Yap, but the problem is that kurento-media-server image doesn't send the video to the repository.

I started the three services kurento-media-server, kurento-hello-world-recording, kurento-repository (configured to store the files into filesystem) and seems that kurento-media-server never send the file to the kurento-repository, I putted a breackpoint in the Servlet and never is called.

- kurento-media-server: I'm using the docker version https://hub.docker.com/r/kurento/kurento-media-server
- kurento-hello-world-recording: https://github.com/Kurento/kurento-tutorial-java/tree/master/kurento-hello-world-recording/
- kurento-hello-world-recording: https://github.com/Kurento/kurento-java/tree/master/kurento-repository

**Comment by micaelgallego** [comment]
Then you will have to store the video in the KMS machine and then sent it to other place...

**Comment by jrpedrianes** [comment]
Ooook, thanks we can use a sidecar to do this, If I have time, I'll try to figure out what happen with the repository invocation in KMS

**Comment by jrpedrianes** [comment]
Debugging the system I found that the 'http' protocol is not supported. Do you know if we need to add some configuration to the docker container?

```
0:00:58.771535600     1 0x7f4340001e90 ERROR                   glib GLib-GObject:0:: g_object_set: assertion 'G_IS_OBJECT (object)' failed
0:00:58.771553700     1 0x7f4340001e90 ERROR         basemediamuxer kmsbasemediamuxer.c:224:kms_base_media_muxer_get_sink:<KmsAVMuxer@0x7f4354029c90> No URI handler implemented for "http".
0:00:58.771562200     1 0x7f4340001e90 ERROR         basemediamuxer kmsbasemediamuxer.c:248:kms_base_media_muxer_create_sink_impl:<KmsAVMuxer@0x7f4354029c90> No available sink for uri http://host.docker.internal:7676/repository_servlet/269k99o0gi6j1frsmfid05tqaj
```

**Comment by micaelgallego** [comment]
Use 6.9.0 version as we had a regression with 6.10.0 regarding to that

**Comment by j1elo** [comment]
Closing old issues. A lot has improved, current version is 6.14.

> Debugging the system I found that the 'http' protocol is not supported. Do you know if we need to add some configuration to the docker container?

We've been working on this for Kurento 6.15. HTTP is now re-enabled, and available in nightly repositories.
