### ISSUE TITLE
Keyframe issue when connecting two RtpEndpoints

### ISSUE THREAD

**Issue by isaacrj** [Kurento/bugtracker#103]
I'm just trying to use Kurento to relay a H264 video feed from one gstreamer pipeline (Alice) to another (Bob).  Alice is encoding a simple videotestsrc to H264, and  Bob is decoding it and rendering to a AutoVideoSink. To do this, I'm using two RtpEndpoints connected together. One of them receives Alice's video feed, the other one sends this feed to Bob.

If Alice's pipeline is started before Bob's, no video is ever shown.

If I start Bob's pipeline first, and then start Alice's everything works as expected: RTP packets flow and Bob shows Alice's video on screen. If Bob's pipeline is restarted, the video is not shown anymore.

It looks like Kurento is only relaying the very first keyframe that Alice is sending. If Bob is not already listening when this keyframe is relayed, he receives the RTP packets but is not able to decode the H264 stream on them.

If I set-up Alice's pipeline to send its packets directly to Bob, without using Kurento as a relay, video works no matter what order I follow starting the pipelines, so it seems that Alice is generating keyframes properly.

To reproduce the issue, please find [here](https://github.com/Kurento/bugtracker/files/368626/KurentoTest.zip), a java code snippet and bash scripts for gstreamer, and follow this steps:
1. Edit KurentoTest.java and change IP's and ports as neccesary.
2. Run KurentoTest and look into its console output for the media ports for Alice and Bob.
3. Run alice-send-pipeline.sh kurento_ip alice_media_port
4. Run bob-receive-pipeline.sh bob_media_port
   
   Bob's pipeline does not show video. 
   
   Repeat the sequence above, reversing steps 3 and 4, and it'll work.

**KMS Version**:

> Version: 6.5.1~5.g4bc4363
> Found modules:
>   Module: 'core' version '6.5.1~58.ga86e575'
>   Module: 'elements' version '6.5.1~35.g2e3613f'
>   Module: 'filters' version '6.5.1~1.ge5b1703'
> 
> This issue did also happen while using **Kurento Media Server 6.5.0**

**Other libraries versions**:
i

> i  gstreamer1.5-libav:amd64                              1.8.2.1~20160629121554.96.g493eee4.trusty  amd64        libav plugin for GStreamer
> ii  gstreamer1.5-nice:amd64                               0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
> ii  gstreamer1.5-plugins-bad:amd64                        1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
> ii  gstreamer1.5-plugins-base:amd64                       1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
> ii  gstreamer1.5-plugins-good:amd64                       1.8.1.1~20160712121041.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
> ii  gstreamer1.5-plugins-ugly:amd64                       1.8.1.1~20160609065146.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
> ii  gstreamer1.5-pulseaudio:amd64                         1.8.1.1~20160712121041.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
> ii  gstreamer1.5-tools                                    1.8.1.1~20160706093049.167.g0d8d50e.trusty amd64        Tools for use with GStreamer
> ii  gstreamer1.5-x:amd64                                  1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
> ii  kms-core-6.0                                          6.5.1~20160712140020.58.ga86e575.trusty    amd64        Kurento core module
> ii  kms-elements-6.0                                      6.5.1~20160714074059.35.g2e3613f.trusty    amd64        Kurento elements module
> ii  kms-filters-6.0                                       6.5.1~20160714075755.1.ge5b1703.trusty     amd64        Kurento filters module
> ii  kms-jsonrpc-1.0                                       1.1.2~20160531124242.1.g2fa3dea.trusty     amd64        Kurento jsonrpc library
> ii  kmsjsoncpp                                            1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
> ii  kurento-media-server-6.0                              6.5.1~20160714081635.5.g4bc4363.trusty     amd64        Kurento Media Server
> ii  libgstreamer-plugins-bad1.5-0:amd64                   1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
> ii  libgstreamer-plugins-base1.5-0:amd64                  1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
> ii  libgstreamer1.5-0:amd64                               1.8.1.1~20160706093049.167.g0d8d50e.trusty amd64        Core GStreamer libraries and elements
> ii  libnice10:amd64                                       0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**

> ```
> Language: Java
> Version: 6.5.1-SNAPSHOT
> ```

 **System description:**

> Kurento Media Server host, Alice and Bob are on the same LAN, no firewalls or routers between 
> them

**Comment by isaacrj** [comment]
Hi again!

Do you need me to provide additional info or to do any further testing to help with the investigation?

**Comment by prlanzarin** [comment]
Hello,

Was there any progress regarding this issue?  I think I've stumbled on the same problem and we are currently perfoming some tests to investigate this.

**Comment by j1elo** [comment]
@prlanzarin do you know if this is still a problem with current versions of Kurento?

**Comment by j1elo** [comment]
This was probably a matter of not getting timely keyframes from the source; later fixes such as https://github.com/Kurento/kms-elements/commit/aab2b9cc9a53d2534da4df8c359bdd71a363f50e and the addition of a `requestKeyframe()` method on the sink element (https://github.com/Kurento/kms-core/commit/a3466ae9fe7c1a0472cd2eb6b8d12bfe86a8d145) should help alleviate the problem.
