### ISSUE TITLE
Bug in room demo: 

### ISSUE THREAD

**Issue by abes-dabir** [Kurento/bugtracker#105]
I noticed a small bug in the Kurento Room Demo v6.5.0 involving the participant switching feature.  The JS code keeps switching to the newly detected active participant, even if that participant is already the main speaker.  This causes a flickering in the video being shown in the browser.  It's a simple fix and I've put in a pull request here for your consideration:

https://github.com/Kurento/kurento-room/pull/7

**KMS Version**: 6.5.0

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: FAIL
- Firefox:
- Native:

**System description:**
    Please describe your setup (where is KMS located, where are the
    clients, STUN, TURN...)

**What steps will reproduce the problem?**
1. Run the room demo and get more then one participant in the room
2. Create noise/audio input at one of the participants so that the others will switch their main speaker to this one.
3.  If you keep creating noise at the same participant, you are likely to see a flickering of the main speaker video at the other participants' browsers.

**Comment by igracia** [comment]
@abes-dabir I think this is fixed now. We did some changes not long ago in that room. Can you please confirm that the issue got solved with the latest code?
