### ISSUE TITLE
node.js playerEndpoint.setPosition(position); is complaining  "Could not check position, unknown type int64"

### ISSUE THREAD

**Issue by pc-cfa** [Kurento/bugtracker#106]
Still appears to be working, cosmetic bug only

.../node_modules/kurento-client/node_modules/kurento-client-elements/lib/PlayerEndpoint.js
#168 checkType('int64', 'position', position, {required: true});

Version  6.5.0 of everything

**Comment by pooja1pathak** [comment]
I am facing the same issue. Is it fixed? or any workaround is available?

**Comment by j1elo** [comment]
Closing old issues. If someone still sees this with Kurento 6.14 or later, please reopen and provide some more information.
