### ISSUE TITLE
KMS 6.5.0: "Too many threads" check fails when it shouldn't

### ISSUE THREAD

**Issue by daniloarcidiacono** [Kurento/bugtracker#107]
**KMS Version**:

Version: 6.5.0
Found modules:
        Module: 'core' version '6.5.0'
        Module: 'elements' version '6.5.0'
        Module: 'filters' version '6.5.0'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: Java, JavaScript
- Version: JDK 8

**What steps will reproduce the problem?**
Launch the KMS using the docker image.
The kurento-room server tries to join a room.

**What is the expected result?**
The KMS creates the media pipeline linked to the new room.

**What happens instead?**
The KMS fails throwing a "Too many threads" exception.

**Does it happen with one of the tutorials?**
I don't know.

**Please provide any additional information below.**
Once the KMS is up, if I type `ulimit -a` I see that there is no upper limit set on the number of user processes. From [ResourceManager.cpp](https://github.com/Kurento/kurento-media-server/blob/master/server/ResourceManager.cpp):

```
static int getMaxThreads() {
  if (maxThreads == 0) {
    struct rlimit limits;
    getrlimit (RLIMIT_NPROC, &limits);
    maxThreads = limits.rlim_cur;
  }

  return maxThreads;
}
```

The absence of such upper limit is encoded as -1 in `limits.rlim_cur`, so `getMaxThreads()` returns `-1` as the maximum number of threads.
Because of that the KMS fails _**horribly**_ when it checks for the number of threads:

```
static void checkThreads(float limit_percent) {
  int nThreads;
  nThreads = getNumberOfThreads ();

  if (nThreads > getMaxThreads () * limit_percent ) {
    throw KurentoException (NOT_ENOUGH_RESOURCES, "Too many threads");
  }
}
```

Manually setting an upper limit with `ulimit -u 4096 `after the KMS is up is not effective because `maxThreads` is cached. As suggested by Radu Tom Vlad [here](https://groups.google.com/forum/#!topic/kurento/aKfjb1JaQzQ), a possible workaround is to add `ulimit -u 65536` to `entrypoint.sh`.

**Comment by jcaden** [comment]
This commit https://github.com/Kurento/kurento-media-server/commit/ad1fda48096d1f0b18bf181560317ea04096c5f3 should fix the issue.
