### ISSUE TITLE
Reconnect to server undefined

### ISSUE THREAD

**Issue by suhail339** [Kurento/bugtracker#109]
I am accessing remote KMS at http://93.104.213.28:8888 from my locally setup tutorial project for one2manycall.

I am getting error Reconnect To Server 1 10000 undefined

Denug Log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Suhail\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--ws_uri=ws://http://93.104.213.28:8888/kurento' ]
2 info using npm@3.10.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kurento-one2many-call@6.5.0~prestart: kurento-one2many-call@6.5.0
6 silly lifecycle kurento-one2many-call@6.5.0~prestart: no script for prestart, continuing
7 info lifecycle kurento-one2many-call@6.5.0~start: kurento-one2many-call@6.5.0
8 verbose lifecycle kurento-one2many-call@6.5.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle kurento-one2many-call@6.5.0~start: PATH: C:\Users\Suhail\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Suhail\Desktop\Kurento\kurento-tutorial-node\kurento-one2many-call\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Suhail\AppData\Roaming\npm
10 verbose lifecycle kurento-one2many-call@6.5.0~start: CWD: C:\Users\Suhail\Desktop\Kurento\kurento-tutorial-node\kurento-one2many-call
11 silly lifecycle kurento-one2many-call@6.5.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'node server.js "--ws_uri=ws://http://93.104.213.28:8888/kurento"' ]
12 silly lifecycle kurento-one2many-call@6.5.0~start: Returned: code: 1  signal: null
13 info lifecycle kurento-one2many-call@6.5.0~start: Failed to exec start script
14 verbose stack Error: kurento-one2many-call@6.5.0 start: `node server.js "--ws_uri=ws://http://93.104.213.28:8888/kurento"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Suhail\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Suhail\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid kurento-one2many-call@6.5.0
16 verbose cwd C:\Users\Suhail\Desktop\Kurento\kurento-tutorial-node\kurento-one2many-call
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Suhail\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--ws_uri=ws://http://93.104.213.28:8888/kurento"
19 error node v4.4.5
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error kurento-one2many-call@6.5.0 start: `node server.js "--ws_uri=ws://http://93.104.213.28:8888/kurento"`
22 error Exit status 1
23 error Failed at the kurento-one2many-call@6.5.0 start script 'node server.js "--ws_uri=ws://http://93.104.213.28:8888/kurento"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the kurento-one2many-call package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js "--ws_uri=ws://http://93.104.213.28:8888/kurento"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs kurento-one2many-call
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls kurento-one2many-call
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

May be i am doing something stupid, i hope someone will help if its an issue.

**Comment by jcaden** [comment]
@suhail339  What was the problem?

**Comment by suhail339** [comment]
I have closed this issue due to my some stupid mistakes.
-> kurento.config.json on remote server(server port missing)
-> npm start -- --ws_uri=ws://93.104.213.28:8888/kurento(didnt use kurento at the end)

**Comment by jcaden** [comment]
Thanks for the explanation.

**Comment by vishrutiPawar** [comment]
Hi @suhail339, I am also trying to achieve the same flow but I'm getting following error, when I goto the URL in browser

```
reconnect to server 4 500 undefined
reconnect to server 5 800 undefined
reconnect to server 6 1300 undefined
reconnect to server 7 2100 undefined
reconnect to server 8 3400 undefined
reconnect to server 9 5500 undefined
``` 
I have no clue how to resolve this. 
On browsing the URl I can see only the local stream and the Remote stream keeps on loading but never starts
My use case is that I want to get live stream from Rpi in one of the Azure VM's.
Please let me know how to configure the same.
