### ISSUE TITLE
Ubuntu Wily packages...

### ISSUE THREAD

**Issue by virtualfunction** [Kurento/bugtracker#11]
It seems the distro packages for Ubuntu no longer work due to dependencies not being meet since upgrading from vivid. Hopefully it should just be a case of just tweaking these surely to line up with wily's packages? Currently I'm working round this by using Docker with --net=host

**Comment by igracia** [comment]
They are not supposed to, as the reference distro is Ubuntu 14.04.3. However, I'll check if someone around here is using Wily, but I think none of us has upgraded yet.

P.S. I've assigned the `invalid` flag since the distro is not officially supported

**Comment by jcaden** [comment]
I've upgraded to wily and what I am doing is generating packages myself, this is something not recommended for not advanced users and something that we are not supporting at all. Nevertheless, I had to solve many compilation issues that arised in wily.

**Comment by igracia** [comment]
I'm closing this issue as it is not really a bug, and no feedback has been provided.
