### ISSUE TITLE
Not able to debug the pointerdetector module the test suite fails.

### ISSUE THREAD

**Issue by swetabedmutha09** [Kurento/bugtracker#110]
**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

**What steps will reproduce the problem?**
1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by swetabedmutha09** [comment]
KMS version:

Version: 6.5.0
Found modules:
	Module: 'core' version '6.5.0'
	Module: 'elements' version '6.5.0'
	Module: 'filters' version '6.5.0'
	Module: 'pointerdetector' version '6.5.0'

Other libraries version:

ii  gir1.2-gst-plugins-base-1.5                           1.8.0~20160530103212.387.g21728a3.trusty            amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                                  1.8.0~20160530103131.368.g0fb3a08.trusty            amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer0.10-nice:amd64                              0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                               0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64                              1.7.0.1~20160530102916.35.g90e6470.trusty           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                               0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64                        1.8.0~20160530103612.645.gb68ba3e.trusty            amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64                       1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64                       1.8.0~20160530103259.265.geca7cfe.trusty            amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64                       1.8.0~20160530103107.83.g4885bb3.trusty             amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64                         1.8.0~20160530103259.265.geca7cfe.trusty            amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                                  1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer plugins for X11 and Pango
ii  kms-cmake-utils                                       1.3.1.trusty                                        all          Kurento cmake utils
ii  kms-core-6.0                                          6.5.0.20160530141614.trusty                         amd64        Kurento core module
ii  kms-core-6.0-dev                                      6.5.0.20160530141614.trusty                         amd64        Kurento core module
ii  kms-elements-6.0                                      6.5.0.20160530154355.trusty                         amd64        Kurento elements module
ii  kms-elements-6.0-dev                                  6.5.0.20160530154355.trusty                         amd64        Kurento elements module
ii  kms-filters-6.0                                       6.5.0.20160530155443.trusty                         amd64        Kurento filters module
ii  kms-filters-6.0-dev                                   6.5.0.20160530155443.trusty                         amd64        Kurento filters module
ii  kms-jsonrpc-1.0                                       1.1.1.trusty                                        amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                                   1.1.1.trusty                                        amd64        Kurento jsonrpc library
ii  kms-pointerdetector-6.0                               6.5.0.20160531100405.trusty                         amd64        Kurento Pointer Detector Filter
ii  kmsjsoncpp                                            1.6.3~20160530102631.40.gd78deb7.trusty             amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                                        1.6.3~20160530102631.40.gd78deb7.trusty             amd64        Kurento jsonrpc library
ii  kurento-media-server-6.0                              6.5.0.20160530172436.trusty                         amd64        Kurento Media Server
ii  kurento-media-server-6.0-dev                          6.5.0.20160530172436.trusty                         amd64        Kurento media server, development files and tools
ii  kurento-module-creator-4.0                            4.0.5.trusty                                        all          Kurento module creator
ii  libgstreamer-plugins-bad1.5-0:amd64                   1.8.0~20160530103612.645.gb68ba3e.trusty            amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64                  1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev                      1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64                               1.8.0~20160530103131.368.g0fb3a08.trusty            amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                                   1.8.0~20160530103131.368.g0fb3a08.trusty            amd64        GStreamer core development files
ii  libnice-dev                                           0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (development files)
ii  libnice10:amd64                                       0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (shared library)

Browser tested:

Firefox: fail

Steps to reproduce the problem:
1.Download the pointerdetector development module.
2. mkdir build
3. execute cmake -i .. command 
4. execute make command
5.then go to build/tests/check/element folder
6. run the executable test_pointerdetector  

What is the expected result?
display a video with the box on right hand side and then calibrate that region and display similar region

What happens instead?
got this error.
Running suite(s): pointerdetector
50%: Checks: 2, Failures: 0, Errors: 1

/kms-pointerdetector/tests/check/element/pointerdetector.c:165:E:element:player_with_pointer:0: (after this point) Test timeout expired

Does it happen with one of the tutorials?
yes . Pointer detector module

Please provide any additional information below.

**Comment by dfernandezlop** [comment]
Hi,

In order to execute module tests you should run `make check` in the build directory. I just check tests and they are working fine:

```
make check
[ 25%] Built target kmstestutils
[ 75%] Built target pointerdetector
[100%] Built target test_pointerdetector
[100%] Built target check_build
Test project /home/dlopez/kurentoCode/kms-pointerdetector/build
    Start 1: test_pointerdetector
1/1 Test #1: test_pointerdetector .............   Passed    6.65 sec

100% tests passed, 0 tests failed out of 1

```

These tests are code tests, you are not going to view any window. If you want to see demos related to modules, you should take a look to kurento tutorials in any flavour (java, js, or node).

I'm closing the bug.
Regards.
David.

**Comment by swetabedmutha09** [comment]
What do you mean by code check?  

I don't really understand the purpose of the test folder because it doesn't really call any functionality for the src folder.

Thanks

**Comment by jcaden** [comment]
They are unit test of the plugin. Tests load the plugin and perform some actions that imply this module. Is the way we use to tests the plugins, this folders are in all our repositories.

Maybe you don't see direct call to any function in the src folder, but they are implicitly done by the GStreamer plugin system.

Cheers
