### ISSUE TITLE
Amazon Web Services - usage of Kurento with Elastic Load Balance which provides server certificate

### ISSUE THREAD

**Issue by memreas** [Kurento/bugtracker#112]
Hi,

I'm trying to integrate Kurento with my Amazon Web Services backend.  I've found that the tutorial samples have an included server cert which raises an unknown server cert exception on chrome, firefox, etc.  I would like to know how to remove the server cert so I can user Elastic Load Balancer's DNS and server certificate.  I've tried to modify the server.js code but I'm fairly new to node.js.

Elastic Load Balancer allows me to use Route53 for DNS setup and let's me specify a wildcard server cert so I can then route to my Kurento instance without security since access is covered by DNS.

Let me know if you need more info.  If you can provide a sample of how to remove that would help also.  I would reciprocate the updated code for the tutorials.

Regards,
John Meah

**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

**What steps will reproduce the problem?**
1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by jcaden** [comment]
Please see guidelines before reporting. This is a question and should be addressed to mailing list.
