### ISSUE TITLE
KMS memory grows up and not release when i use rtpEndpoint for presenter

### ISSUE THREAD

**Issue by Lisitskiy** [Kurento/bugtracker#114]
@**KMS Version**:

Version: 6.5.0
Found modules:
        Module: 'core' version '6.5.0'
        Module: 'elements' version '6.5.0'
        Module: 'filters' version '6.5.0'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.7.0.1~20160224182850.34.g1d2c0c1.trusty  amd64        libav plugin for GStreamer

ii  gstreamer1.5-nice:amd64              0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (GStreamer plugin)

ii  gstreamer1.5-plugins-bad:amd64       1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer plugins from the "bad" set

ii  gstreamer1.5-plugins-base:amd64      1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins from the "base" set

ii  gstreamer1.5-plugins-good:amd64      1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugins from the "good" set

ii  gstreamer1.5-plugins-ugly:amd64      1.7.1.1~20160224182649.23.g036c2d2.trusty  amd64        GStreamer plugins from the "ugly" set

ii  gstreamer1.5-pulseaudio:amd64        1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugin for PulseAudio

ii  gstreamer1.5-x:amd64                 1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins for X11 and Pango

ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module

ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module

ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module

ii  kms-jsonrpc-1.0                      1.1.0.trusty                               amd64        Kurento jsonrpc library

ii  kmsjsoncpp                           1.6.3~20160224182314.38.g263929e.trusty    amd64        Kurento jsoncpp library

ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server

ii  libgstreamer-plugins-bad1.5-0:amd64  1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer development files for libraries from the "b                                                                                       ad" set

ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set

ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements

ii  libnice10:amd64                      0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: Node.js
- Version: v5.10.1 

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome

**System description:**
	Kms located on the same machine as application
        We use stun and turn in kms config

**What steps will reproduce the problem?**
1. 
`git clone https://github.com/Lisitskiy/kurento-one2many.git`

start server 
`npm start -- --ws_uri=ws://example.com:8888/kurento`
2. Open 3-5 page https://host:8443 in chrome tabs
3. Click Presenter button - on all opened pages

**What is the expected result?**
Stable memory usage, without leaking
Memory release, when stop all presenters

**What happens instead?**
Memory usage grows up
Not releasing after stop Presenter

**Does it happen with one of the tutorials?**
I have modify kurento-one2many-call tutorial (branch 6.5.0) by adding rtpEndpoint to presenter

**Please provide any additional information below.**
Such situation with memory happen with a oficial docker also.
I see, that memory grows up  - when i add rtpEndpoint
Example for reproducing - https://github.com/Lisitskiy/kurento-one2many/tree/master/kurento-one2many-call
Memory usage chart  in Mb
<img src="http://i.piccy.info/i9/4d24a336071e048588df42a482841663/1470826605/87223/1059359/kurento_rtp_memory_leak.jpg">
[http://i.piccy.info/i9/4d24a336071e048588df42a482841663/1470826605/87223/1059359/kurento_rtp_memory_leak.jpg](url)
<img src="http://i.piccy.info/i9/671812fac08b57708334bc1c2127232a/1470831025/72692/1059359/kurento_rtp_memory_leak_2.jpg">

**Comment by igracia** [comment]
Does it happen with the latest dev version?

**Comment by Lisitskiy** [comment]
I Test it in docker with dev too

**Comment by Lisitskiy** [comment]
Sory, i forgot send link to axample for reproducing 
[https://github.com/Lisitskiy/kurento-one2many](url)

**Comment by Lisitskiy** [comment]
Hello, have you reproduce it?

**Comment by igracia** [comment]
Sorry, half of the time is out these days. It will take some time till we can get someone to look into this.

**Comment by jcaden** [comment]
Seems to be related with #85 

Have you tried with development version, it's not completely fixed, but it should be better.

**Comment by Lisitskiy** [comment]
I have a same result with dev kms.

Can  you test my attached app. Unlike  task #85,  memory in my app starts leaking at first seconds after starting second presenter.

**Comment by jcaden** [comment]
@Lisitskiy thanks, we will try your app.

@sancane can you have a look at @Lisitskiy application when you have a chance?

**Comment by sancane** [comment]
Of course I will

**Comment by Lisitskiy** [comment]
Hi @sancane, have you some info about thos task?
Thanks alot.

**Comment by sancane** [comment]
Hi @Lisitskiy,
I still have not a clear image about what is happening in there, all that i can see are small accumulative leaks in external libraries, perhaps they might justify that amount of memory consumtion when used in huge pipelines.
Still working on it, I'll keep you update
