### ISSUE TITLE
KMS 6.5.0 -- No audio on RtpEndpoint [H264/AAC]

### ISSUE THREAD

**Issue by spiermar** [Kurento/bugtracker#115]
**KMS Version**:

Version: 6.5.0
Found modules:
       	Module: 'core' version '6.5.0'
       	Module: 'elements' version '6.5.0'
       	Module: 'filters' version '6.5.0'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: JavaScript
- Version: kurento-client: master, kurento-utils: master

**Browsers tested**

- Chrome: 52.0.2743.116 (64-bit)

**System description:**

Client: Chrome on MAC OSX
Kurento: 6.5.0 on `Server 1`
Wowza: 4.5.0 on `Server 2`

Firewall is all open, allow all incoming and outgoing traffic on both servers.

**What steps will reproduce the problem?**
1. Start http-server running the attached code, pointing the Kurento IP.
2. Start the stream.
3. Open the HLS, MGEGDash or RTMP stream on Wowza's test player or VLC.

**What is the expected result?**

The webcam/mic live stream on the player, with audio and video.

**What happens instead?**

The video stream works perfectly, but there is no audio. The audio stream is present (see attached), but no data is being received by the client.

**Does it happen with one of the tutorials?**

No tutorial found for this use case.

**Please provide any additional information below.**

* Already tried changing the port used for the audio stream in the SDP file (see attached), but no results.
* Already tried changing the codec to OPUS/48000/1, but no result.
* It's not a problem with the audio source, since if I change the WebRTC connection to `Sendrecv`, I can hear the audio in the lookback stream.
* TCPDUMP shows packets going out of the KMS server on the `video` port, but no packets on the `audio` port.
* Problem was discussed in the GG (https://groups.google.com/forum/#!topic/kurento/SXabYxoV2uw)
* No errors or warnings in the KMS logs (see attached)
* The `kurento-record` tutorial was used as base

[media-server_2016-08-18_00-02-31.00000.pid7026.txt](https://github.com/Kurento/bugtracker/files/425518/media-server_2016-08-18_00-02-31.00000.pid7026.txt)
[index.js.txt](https://github.com/Kurento/bugtracker/files/425521/index.js.txt)
[channel.sdp.txt](https://github.com/Kurento/bugtracker/files/425523/channel.sdp.txt)
![screen shot 2016-08-15 at 2 31 57 pm](https://cloud.githubusercontent.com/assets/2207415/17783983/7e8567fe-652f-11e6-8820-8aefdba9d2ac.png)

**Comment by spiermar** [comment]
Just noticed something interesting in the config files. No AAC. I'll try adding it and report back.

**Comment by spiermar** [comment]
Problem solved. Missing the codec in the SDP configuration. Had to add

```
{
    "name": "MPEG4-GENERIC/44100/2"
}

 to /etc/kurento/modules/kurento/SdpEndpoint.conf.json

**Comment by igracia** [comment]
Should have filed the bug on the first place: you would have solved that faster!

Thanks a lot for the feedback.

**Comment by spiermar** [comment]
True! I was always checking the logs for errors and couldn't find anything. Only when I copied the full log I noticed the beginning of the file, with the config files. Tks again @igracia !
