### ISSUE TITLE
kurento-client always crashes on node.js >=6.3 (dependency bug)

### ISSUE THREAD

**Issue by bschmitlin** [Kurento/bugtracker#116]
using node 6.4 with kurento-client@6.5.0 connected to latest master branch kurento-server.

Due to (from my understanding) an incompatibility of the ws library with node.js 6.3, when opening the websocket kurento-client crashes the node app:

2016-08-19T09:13:32.432Z - error: RangeError: out of range index
    at RangeError (native)
    at fastCopy (/Users/benoit/git/rtc/node_modules/ws/lib/Receiver.js:317:24)
    at Receiver.add (/Users/benoit/git/rtc/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (/Users/benoit/git/rtc/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

seems to be https://github.com/websockets/ws/issues/778
which would affect ws@0.4.32 used by kurento-client. This bug is apparently fixed in ws@1.1.0.

**Comment by bschmitlin** [comment]
@igracia @gortazar @rbenitez 
Hi guys, any triage on this? AFAIK this basically blocks Kurento being usable on any recent nodejs deployments. Of course it would be great to also take this opportunity to update the super old ws lib version (over 2 years old) for some nice security and perf fixes.
Thanks!

**Comment by lotas** [comment]
I +1 this, as I also experience problems right now, after upgrading to latest node.js.
My setup:
```
$node -v
v6.5.0
$kurento-media-server -v
Version: 6.5.0
Found modules:
        Module: 'core' version '6.5.0'
        Module: 'elements' version '6.5.0'
        Module: 'filters' version '6.5.0'

$npm list
...
├─┬ kurento-client@6.5.0
│ ├── async@1.2.1
│ ├── error-tojson@0.0.1
│ ├── es6-promise@2.3.0
│ ├── extend@2.0.1
│ ├── inherits@2.0.1
│ ├── kurento-client-core@6.5.0
│ ├── kurento-client-elements@6.5.0
│ ├── kurento-client-filters@6.5.0
│ ├─┬ kurento-jsonrpc@5.1.2
│ │ ├─┬ sockjs-client@1.1.1
│ │ │ ├─┬ eventsource@0.1.6
│ │ │ │ └─┬ original@1.0.0
│ │ │ │   └── url-parse@1.0.5
│ │ │ ├─┬ faye-websocket@0.11.0
│ │ │ │ └─┬ websocket-driver@0.6.5
│ │ │ │   └── websocket-extensions@0.1.1
│ │ │ ├── json3@3.3.2
│ │ │ └─┬ url-parse@1.1.3
│ │ │   ├── querystringify@0.0.4
│ │ │   └── requires-port@1.0.0
│ │ └─┬ ws@0.4.32
│ │   ├── commander@2.1.0
│ │   ├── nan@1.0.0
│ │   └── tinycolor@0.0.1
│ ├── minimist@1.2.0
│ ├── promisecallback@0.0.4
│ └─┬ reconnect-ws@0.0.0 (git://github.com/kurentoforks/reconnect-ws.git#7fb7020e3ca1ffeaaa8bb4ddd690cf28c8d02a2b)
│   ├─┬ reconnect-core@1.0.0 (git://github.com/kurentoforks/reconnect-core.git#921d43e91578abb2fb2613f585c010c1939cf734)
│   │ └── backoff@2.3.0
│   └─┬ websocket-stream@0.5.1
│     ├── isbuffer@0.0.0
│     └── ws@0.4.32
```

And I get this error: 
```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/codeship-kms-app-server/kms-app-server/source/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:317:24)
    at Receiver.add (/home/codeship-kms-app-server/kms-app-server/source/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (/home/codeship-kms-app-server/kms-app-server/source/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

Which leads to the same `ws@1.1.0` fix.
thanks!

**Comment by haggholm** [comment]
I hate to say +1, but…+1. 

* `kurento-client` depends on `kurento-jsonrpc`, which depends on `ws@~0.4.31`.
* Also, `kurento-client` depends on `KurentoForks/reconnect-ws`, which depends on `ws@~0.4.31` through `websocket-stream@~0.5.1`.

`websocket-stream@~0.5.1` is at least two years old—it hit `1.1.1` in November 2014. `ws@~0.4.31` is also two years old; it hit `0.5.0` in November 2014. So, two dependencies are two years out of date.

I’m not sure how to fix this. The naïve approach of forking the repositories and updating the dependency does not work, which isn’t surprising (I’m sure many APIs may have changed). This gives me the rather bizarre error message

    TypeError: Invalid JsonRPC version 'undefined': {"id":0,"jsonrpc":"2.0","result":{"value":"pong"}}
    at Object.unpack (...snip.../node_modules/kurento-jsonrpc/lib/packers/JsonRPC.js:74:11)

**Comment by igracia** [comment]
We'd really like to update those deps too. The thing is that we can't estimate how long it would take us to fix things for the new versions, and since it's working in the LTS version of node.js, we haven't scheduled that yet.

**Comment by bschmitlin** [comment]
Great to see the bug being assigned :-D.

> it's working in the LTS version of node.js
Just in case you hadn't notice, it looks like you have 14 days left to complete the work for your statement to remain true... https://github.com/nodejs/LTS#lts_schedule

For the reconnect feature perhaps it would be worth looking at what engine.io (socket.io engine) is doing? 
Btw, it would be nice if the console.log('reconnect to server') from kurento-client that are cluttering our production logs could go away as part of this modernisation work. 

Thanks and good luck!

**Comment by igracia** [comment]
@bschmitlin yeah, we postponed this for too long, sorry! First we are going to try and update the forks, so it stops pestering devs using node >6.3. After that, we'll try and go for something like what you pointed or maybe [reconnecting-websocket](https://www.npmjs.com/package/reconnecting-websocket)

Will try and make the log more configurable, probably using winston or loglevel

**Comment by igracia** [comment]
@bschmitlin We've submitted a [patch](https://github.com/Kurento/kurento-client-js/commit/a54a836ab9bff568def1aa345072a4153e6235dd) that should fix this for now, until we move to a more stable ws with reconnection library. Can you please check that this patch does indeed solves the issue?

**Comment by bschmitlin** [comment]
@igracia Thanks for the super quick patch. It works fine on node 6.7.0 in the somewhat limited testing I've done.

**Comment by igracia** [comment]
@bschmitlin Thanks for the feedback. It works also in all the other tests that we have. It seems like we can close this issue then.

Haven't done anything about logging yet, sorry! Will tackle that later on, as we have more pressing matters right now. Sorry it's bothering you, you'll have to put up with that a little longer ;-)

**Comment by superdump** [comment]
The version of websocket-stream used depends on ws 0.4.32 and triggers this issue.

**Comment by igracia** [comment]
@superdump In which version of node? Can you be a bit more specific with the report?

**Comment by superdump** [comment]
v6.9.1

**Comment by superdump** [comment]
That is with KMS 6.6.1 and nightlies.

**Comment by peffis** [comment]
@haggholm The error you see when upgrading are from these lines in kurento-jsonrpc-js: https://github.com/Kurento/kurento-jsonrpc-js/blob/master/lib/packers/JsonRPC.js#L63-L75

The reason is that when you bump the version of websocket-stream  to something more modern (my testing indicates that the breaking change occurs when you go over 1.*) the unpack is no longer being called with a String but with an object. This object however can easily be made into a string (which is what is happening in the error printout later in the above code - when it is doing the "+ message") so the obvious patch is to introduce an extra toString when the message is not a String:
```
result = JSON.parse(message.toString());
```
This seems to, with very limited testing, make the kurento client work also with latest websocket-stream. At least it does not stop on that error and the traffic seems to go through.

**Comment by progre** [comment]
I created PR for fix it.
Please check those.
