### ISSUE TITLE
Media server crashes when calling proccessOffer with an empty string using the node library

### ISSUE THREAD

**Issue by kapetan** [Kurento/bugtracker#12]
We are using `kurento-client` version `6.1.0` module in Node.js.

When calling `WebRtcEndpoint.processOffer('')` with an empty string the the media server crashes. The error log contains following entry.

```text
** (kurento-media-server:21255): CRITICAL **: kms_ref_struct_ref: assertion 'refstruct != NULL' failed
```

The same error occurs when calling `processAnswer` with an empty string. It can also be reproduced by using a `RtpEndpoint`.

We're running `Ubuntu 14.04 LTS` and the following Kurento version.

```text
Version: 6.1.1
Found modules:
	Module: 'core' version '6.1.2'
	Module: 'elements' version '6.1.1'
	Module: 'filters' version '6.1.1'
```

**Comment by igracia** [comment]
@jcaden Could you have a look at this, please? It seems that the `WebRtcEndpoint.processOffer()` chokes on empty string params, and wreaks havoc in the KMS.

**Comment by jcaden** [comment]
I think that I fixed this in the development version a couple of weeks ago. Could you please try with dev version to confirm that it is fixed?

**Comment by kapetan** [comment]
It's seems to have been fixed.

I tried it with development version:

```text
Version: 6.1.2~4.g3c371d0
Found modules:
	Module: 'core' version '6.1.3~41.g3d7be7b'
	Module: 'elements' version '6.1.2~35.gc88c519'
	Module: 'filters' version '6.1.2~3.gf1efe25'
```

And got an `Empty offer not valid` error back.

Thanks for the quick reply.

**Comment by igracia** [comment]
Ok, I'm closing this issue then. Next time, please make sure to check first with the development version.
