### ISSUE TITLE
how to install kmsfec plugin

### ISSUE THREAD

**Issue by fengcc** [Kurento/bugtracker#120]
Hi, all:
I want to make my kurento-media-server support FEC, and I found the following code in kmsbasertpendpoint.c :
```
static gboolean
is_fec_supported ()
{
  GstPlugin *plugin = NULL;
  gboolean supported;

  plugin = gst_plugin_load_by_name ("kmsfec");

  supported = plugin != NULL;

  g_clear_object (&plugin);

  return supported;
}
```
Is there a plugin named kmsfec ? I cann't find any information on internet about how to install kmsfec, Does any know how to install it ? My system is ununtu 12.04 LTS, thanks !

**Comment by dfernandezlop** [comment]
Hi,

Sorry, but this is not a bug. Questions are answered in the public list (https://groups.google.com/forum/#!forum/kurento).

Regards.
David.
