### ISSUE TITLE
will not start without ipv6 interface

### ISSUE THREAD

**Issue by gregoliver** [Kurento/bugtracker#121]
**KMS Version**:

kurento-media-server -v
libdc1394 error: Failed to initialize libdc1394
Version: 6.5.0
Found modules:
    Module: 'core' version '6.5.0'
    Module: 'elements' version '6.5.0'
    Module: 'filters' version '6.5.0'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  kurento-server                       6.5.0.20160530172436.trusty                amd64        Meta package for kurento server side
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version: n/a

**Browsers tested**
  n/a

**System description:**
    n/a
**What steps will reproduce the problem?**
1.  Disable ipv6 on host
2.
3.

**What is the expected result?**
Kurento starts
**What happens instead?**
kurento fails to start with WebSocket cannot bind to port error until ipv6 is re-enabled
**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by DieMyst** [comment]
+

**Comment by dev-mraj** [comment]
+1

**Comment by shyshkin** [comment]
Same problem. Any ideas?

**Comment by Klawfinger** [comment]
same exact problem: "error KurentoWebSocketTransport WebSocketTransport.cpp:123 WebSocketTransport()  Error starting listen for websocket transport on port 8888: Underlying Transport Error"
Not happening if ipv6 is enabled.
