### ISSUE TITLE
High cpu consumption when kms handle more pipeline

### ISSUE THREAD

**Issue by w01fer** [Kurento/bugtracker#122]
**KMS Version**:

Version: 6.5.1~1949.g0916a7f
Found modules:
    Module: 'core' version '6.5.1~2628.ge7c82e4'
    Module: 'elements' version '6.5.1~.g17359cc'
    Module: 'filters' version '6.5.1~1.ge5b1703'

**Other libraries versions**:
ii  gir1.2-gst-plugins-base-1.5               1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                      1.8.1.1~20160706093049.167.g0d8d50e.trusty amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64                  1.8.2.1~20160629121554.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                   0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64            1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64           1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64           1.8.1.1~20160712121041.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64           1.8.1.1~20160609065146.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64             1.8.1.1~20160712121041.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                      1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-filters-6.0                           6.5.0                                      amd64        Kurento filters module
ii  kms-jsonrpc-1.0                           1.1.1                                      amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                1.6.2                                      amd64        Kurento jsoncpp library
ii  libgstreamer-plugins-bad1.5-0:amd64       1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64      1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev          1.8.1.1~20160608155102.55.g7b19cfd.trusty  amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64                   1.8.1.1~20160706093049.167.g0d8d50e.trusty amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                       1.8.1.1~20160706093049.167.g0d8d50e.trusty amd64        GStreamer core development files
ii  libnice-dev                               0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (development files)
ii  libnice10:amd64                           0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64        1.8.1.1~20160609064038.99.gf836e53.trusty  amd64        GStreamer plugins from openh264

**Client libraries**
- Language: java
- Version: N/A

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:
- Firefox: OK
- Native:

**System description:**
kms server deploy on a server:

CPU:48 CPU (hyper-threading)
MEM:256G

**What steps will reproduce the problem?**
1. use a RS like one2many in kms
2. open many firefox
3. when the client increase to about 70+

**What is the expected result?**

CPU linear growth

**What happens instead?**

when the pipeline get to 70, the CPU blow up from about 25% to 95% (total cpu)

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

top -H -p <pid> //kms's pid, there are many rtpjitterbuffer thread (70+), each thread cosume about 60% ~ 95% CPU (one cpu)

**Comment by jcaden** [comment]
This is normal, because as you increase the number of users, network becomes more saturated and you start to have more losses. This threads you see consuming resouces are working more trying to re-order packages and sending nacks to notify the missing packages to the remote. You can check that with your clients, when the CPU blows up you should see that the clients receiving more nacks from the server.

**Comment by w01fer** [comment]
If the network become saturated, it did make sence, the fact is, when the
CPU blowed up, the network bandwidth was only about 15MB(~120Mb).

2016-08-29 16:35 GMT+08:00 José Antonio Santos Cadenas <
notifications@github.com>:
