### ISSUE TITLE
KMS 6.5.0 crashed

### ISSUE THREAD

**Issue by xenyou** [Kurento/bugtracker#124]
KMS 6.5.0 crashed several times. 
Sorry but this is production environment. So I can not debug it.
I will just report it.

```
Segmentation fault (thread 140015353415424, pid 61970)
Stack trace:
[SSLv3_client_method]
/lib/x86_64-linux-gnu/libssl.so.1.0.0:0x23C4E
[SSL_check_chain]
/lib/x86_64-linux-gnu/libssl.so.1.0.0:0x33E87
0xCBA2 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
0xECEC at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
0x61C1 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
0x644A at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6DF85
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x75C5E
0x9550 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6DF85
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x75C5E
[gst_proxy_pad_chain_default]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x5F18B
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6DF85
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x75C5E
[gst_base_src_wait_playing]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x2FB65
[gst_tag_setter_get_tag_merge_mode]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x9FD7E
```

**KMS Version**:
libdc1394 error: Failed to initialize libdc1394
Version: 6.5.0
Found modules:
    Module: 'core' version '6.5.0'
    Module: 'elements' version '6.5.0'
    Module: 'filters' version '6.5.0'

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: Node.js
- Version: kurento-client@6.4.1

**What steps will reproduce the problem?**
I don't know.

**What is the expected result?**
KMS doesn't crash.

**What happens instead?**
KMS crashed.

**Comment by jcaden** [comment]
What version of openssl do you have?

    dpkg -l | grep libssl

**Comment by xenyou** [comment]
Thanks for responding.

```
# dpkg -l | grep libssl
ii  libssl1.0.0:amd64                    1.0.2d-0ubuntu1                            amd64        Secure Sockets Layer toolkit - shared libraries
```

**Comment by jcaden** [comment]
Yesterday we deployed a new version of that library, could you try with the new one, as it seems that the crash is happening there.

**Comment by xenyou** [comment]
Thanks!! I'll try it.

**Comment by xenyou** [comment]
There are no crashes since I updated libssl to the new version.
Maybe it fixed.

BTW, I currently use this repository to install kurento 6.5.0 for locking KMS version.
deb http://ubuntu.kurento.org/6.5.0 trusty kms6

Please provide the new version of libssl for the repository. Thanks.

**Comment by codexander** [comment]
We are facing with the same problem, can you please give details of versions you switched from to?

**Comment by codexander** [comment]
Hey There did you solve this problem, updating libssl didnt help.
