### ISSUE TITLE
Error gathering candidates when running under kubernetes

### ISSUE THREAD

**Issue by yehiyam** [Kurento/bugtracker#126]
**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running
`
libdc1394 error: Failed to initialize libdc1394
0:00:00.222398887     1      0x28ee090 INFO    KurentoModuleManager ModuleManager.cpp:156:loadModules: Looking for modules in /usr/lib/x86_64-linux-gnu/kurento/modules
0:00:00.222872276     1      0x28ee090 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
0:00:00.222892503     1      0x28ee090 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded core version 6.5.0 generated at May 30 2016 14:20:56
0:00:00.225785932     1      0x28ee090 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
0:00:00.225802834     1      0x28ee090 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded elements version 6.5.0 generated at May 30 2016 15:46:36
0:00:00.226286711     1      0x28ee090 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
0:00:00.226298817     1      0x28ee090 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded filters version 6.5.0 generated at May 30 2016 15:55:46
Version: 6.5.0
Found modules:
    Module: 'core' version '6.5.0'
    Module: 'elements' version '6.5.0'
    Module: 'filters' version '6.5.0'
`
**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running
`
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

`
**Client libraries**
nodeJS signalling (one-to-many tutorial)
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:
  6.5
  **Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
  have tested this issue:
- Chrome: OK

**System description:**
    Please describe your setup (where is KMS located, where are the
    clients, STUN, TURN...)
Single machine setup.
Kurento runs as a docker container in kubernetes 1.3.6

**What steps will reproduce the problem?**
1. run a cluster of kubernetes 1.3.6
2. run kurento in a container without network=host
3. with your prefered signalling app, create a webrtc endpoint, and
3. call gatherCandidates

**What is the expected result?**
Candidates are collected 
**What happens instead?**
An error is printed in the log: 
`
0:03:32.966410516     1 0x7f7294002380 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:423:processMessage: Response: >{"error":{"code":40400,"data":{"type":"ICE_GATHER_CANDIDATES_ERROR"},"message":"Error gathering candidates"},"id":13,"jsonrpc":"2.0"}
`
**Does it happen with one of the tutorials?**
Yes. I've tried it with the node tutorial one2many
**Please provide any additional information below.**

Kubernetes version 1.3.6 creates a network interface in the docker container. The interface has an IPv4 address, and an IPv6 address.
The IPv6 address is marked as duplicate (I think this is a bug in kubernetes).
Because the address is marked as duplicate, libnice fails to bind to it.
Your version of libnice fails to gather local candidates when one of the local addresses fails to bind. It doesn't skip it and continue to the next one.
The upstream libnice has changed and it just skips the bad address, and completes the candidate gathering.

**Comment by igracia** [comment]
@yehiyam Can you check with the latest release version?

**Comment by yehiyam** [comment]
@igracia what is the latest version? 6.6?
Did you fix libnice?

**Comment by igracia** [comment]
6.6.1, but a `sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade` should set you up.

**Comment by yehiyam** [comment]
@igracia Unfortunately, it is still the same with 6.6 1.

**Comment by j1elo** [comment]
Hi, https://github.com/Kurento/bugtracker/issues/278 is now closed, with the addition of a new setting that allows to specify the external ip address.
I'm closing this old issue; for any further feedback you have please open a new one.
