### ISSUE TITLE
can not receive audio when a peer has video:false constraints

### ISSUE THREAD

**Issue by xenyou** [Kurento/bugtracker#129]
**KMS Version**:
Version: 6.5.0
Found modules:
	Module: 'core' version '6.5.0'
	Module: 'elements' version '6.5.0'
	Module: 'filters' version '6.5.0'

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: <Node.js, JavaScript>
- Version:

**What steps will reproduce the problem?**
1.  clone kurento-tutorial-node
2.  cd kurento-one2one-acll
3. apply this patch

[bug.txt](https://github.com/Kurento/bugtracker/files/494759/bug.txt)

**What is the expected result?**
peerA (audio only) receives video+audio.
peerB (video+audio) receives only audio.

**What happens instead?**
peerA (audio only) receives audio.
peerB (video+audio) does not receives audio.

**Does it happen with one of the tutorials?**
kurento-one2one-call (customized)

**Comment by xenyou** [comment]
Browsers are both Chrome.

**Comment by igracia** [comment]
That's because Chrome can't negotiate audio and video, and receive only one of them. Check with FF, and it should work there.

**Comment by igracia** [comment]
@xenyou I'm closing the issue, as we haven't had any feedback. I'm assuming that it was related to the bug in Chrome.
