### ISSUE TITLE
a remb related bug

### ISSUE THREAD

**Issue by w01fer** [Kurento/bugtracker#130]
kms-core/src/gst-plugins/common/kmsremb.c

SHA-1: 11c04d74f3ca6c66381a45c0fe963130fb0894a0

* remb: make increment phase more aggressive

Now, the remb base took into account is the max of
the last REMB and the max bitrate.
With this, we avoid stopping raising the REMB value
if the sender peer does not increase the bitrate for some
reason.
Anyway, we limit the REMB value to the double of the max bitrate.

-------------------
this commit involes a problem under the situation "Too losses", the remb will always drop to 0,  dure to this line
"
326  rl->remb = MIN (rl->remb, rl->max_br * REMB_MAX_FACTOR_INPUT_BR);
"
because max_br was set to 0.

**Comment by jcaden** [comment]
@mparis Can you please have a look on this?

**Comment by mparis** [comment]
Hello @w01fer,
the minimum REMB announced by KMS must be:

- 100kbps if you are using the default configuration where minVideoRecvBandwidth is 100kbps ([1])
- or the value you set with minVideoRecvBandwidth property ([1]), unless it is set to 0. In that case it is 30 kbps ([2])

Refs
[1] https://github.com/Kurento/kms-core/blob/0a3f33532de59524409f4fdd518bb7c0edf121cb/src/gst-plugins/commons/kmsremb.c#L415
[2] https://github.com/Kurento/kms-core/blob/0a3f33532de59524409f4fdd518bb7c0edf121cb/src/gst-plugins/commons/kmsremb.c#L417

**Comment by w01fer** [comment]
In my case, it is 30kbps, just as you said.what I mean is, is it right
according to your design? According to my understanding, in the ’too
losses’ condition, the bitrate should drop just by the deferment_factor,
not derectly to the min number set. And the commit you put is to  make
increment phase more aggressive, am i right?

2016-09-30 22:07 GMT+08:00 Miguel París <notifications@github.com>:

**Comment by w01fer** [comment]
by the way, when you said "00kbps if you are using the default
configuration where minVideoRecvBandwidth is 100kbps ([1])”, what the
meaning of the ‘default configuration’, if it’s mean the
MIN_VEDEO_RECV_BW_DEFAULT, it is 0, or you means some configure file or
something else, in that case, please let me know.

2016-09-30 22:07 GMT+08:00 Miguel París <notifications@github.com>:

**Comment by mparis** [comment]
Hello @w01fer,
you were right, there was a problem in the algorithm and in the doc.
Is is now fixed in master branch.

Thanks for the report!! :D
