### ISSUE TITLE
Kurento js client prevents exiting the application

### ISSUE THREAD

**Issue by zdila** [Kurento/bugtracker#131]
**KMS Version**: 6.6.1

**Client libraries**
- Language: Node.js
- Version: 6.6.0

**What steps will reproduce the problem?**

``` javascript
const kurento = require('kurento-client');

kurento('ws://192.168.2.190:8888/kurento', function (error, client) {
  if (error) {
    console.error('Error creating Kurento client:', err);
  } else {
    console.log('OK');
    client.close();
  }
});
```

**What is the expected result?**
It should print `OK` and exit.

**What happens instead?**
It prints `OK` and hangs. User must press Ctrl+C.

**Comment by JoseGoncalves** [comment]
In the process of reporting something similar that happened to me, I found this issue, so I'll add my comments here.

This issue still happens in the latest version (tested with 6.12.0).

Digging into the Kurento client code I've found that what prevents the Node.js process from exiting is the timer that exists to keep alive sessions. The following patch solved this issue to me:

```patch
diff --git a/lib/KurentoClient.js b/lib/KurentoClient.js
index 0809d72..7ce1aa9 100644
--- a/lib/KurentoClient.js
+++ b/lib/KurentoClient.js
@@ -925,6 +925,10 @@ function KurentoClient(ws_uri, options, callback) {
      */
     this.close = function () {
       closed = true;
+
+      enabledPings = false;
+      clearInterval(pingInterval);
+      pingPongStarted = false;
 
       prevRpc_result.then(re.disconnect.bind(re));
     };
```
