### ISSUE TITLE
Promise API is broken in nodejs kurento-client

### ISSUE THREAD

**Issue by zdila** [Kurento/bugtracker#133]
Call like `pipeline.create('WebRtcEndpoint').then(function (webRtcEndpoint) { console.log('OK'); });` correctly prints `OK`.

On the other hand `Promise.resolve(pipeline.create('WebRtcEndpoint')).then(function (webRtcEndpoint) { console.log('OK'); });` never resolves or rejects.

The problem is that `webRtcEndpoint` variable from the first exampe is thenable and `Promise.resolve` (and others like `Promise.all`, ...) wants to resolve it immediately but the webRtcEndpoint "promise" will stay in pending forever.

**Comment by igracia** [comment]
@zdila Could it be related to #71? We are using non-native promises.

**Comment by zdila** [comment]
It could be. Tested again and it also eats 100% of single CPU core.

**Comment by igracia** [comment]
Ok, let's see if it is. We are right now taking a look at that. Subscribe to that thread, as we'll post notifications there.

**Comment by dev-mraj** [comment]
+1

**Comment by knnan** [comment]
could anyone please tell me if this issue has been resolved

**Comment by micaelgallego** [comment]
yep, is solved.

**Comment by j1elo** [comment]
> yep, is solved.
