### ISSUE TITLE
Feature Request: Fire event when recorded file is finished writing to disk

### ISSUE THREAD

**Issue by spongessuck** [Kurento/bugtracker#14]
It would be helpful to have a way to know when recorded files are finished writing to disk.

I need to be able to play my recorded files soon after stopping the recording, and knowing when they're ready to play would be nice.

**Comment by spongessuck** [comment]
It might be helpful if the API allowed passing in a keyframe interval to the RecorderEndpoint. If a few keyframes were dropped into the file, it would make it possible to play it/seek through it before it's completely written to disk.

**Comment by igracia** [comment]
@jcaden We can keep this unassigned here until you decide when/if this goes in.

**Comment by jcaden** [comment]
@igracia Perfect, let's dot this way until we have the chance to implement it.

**Comment by dfernandezlop** [comment]
This feature has been implemented in the dev-version. The RecorderEndpoint has a new event called "Stopped" [1].

I'm closing the thread.

[1] https://github.com/Kurento/kms-elements/blob/master/src/server/interface/elements.RecorderEndpoint.kmd.json#L65

**Comment by vhmth** [comment]
Awesome! Will this event also propagate to other SDKs that implement the media elements interface? For instance, will this event be triggered on a node javascript representation of a RecorderEndpoint element?

**Comment by dfernandezlop** [comment]
Of course, the event must be used through the APIs.

**Comment by vhmth** [comment]
:zap:

**Comment by spongessuck** [comment]
Will this end up in 6.4.0?

**Comment by dfernandezlop** [comment]
In the next release.
