### ISSUE TITLE
Please, update instruction for installing kurento-media server from sources

### ISSUE THREAD

**Issue by anton-petrov** [Kurento/bugtracker#140]
It will be better instruction for novice, IMHO:
0) cd ~
1) `echo "deb http://ubuntu.kurento.org trusty-dev kms6" | sudo tee /etc/apt/sources.list.d/kurento-dev.list` for ubuntu 14.04
or
`echo "deb http://ubuntu.kurento.org xenial-dev kms6" | sudo tee /etc/apt/sources.list.d/kurento-dev.list` for ubuntu 16.04
2) `wget -O - http://ubuntu.kurento.org/kurento.gpg.key | sudo apt-key add -`
3) `sudo apt-get update`
4) `sudo apt-get install git`
5) `sudo apt-get install build-essential`
6) `git clone https://github.com/Kurento/kurento-media-server.git`
7) `cd kurento-media-server`
8) `sudo apt-get install $(cat debian/control | sed -e "s/$/\!\!/g" | tr -d '\n' | sed "s/\!\! / /g" | sed "s/\!\!/\n/g" | grep "Build-Depends" | sed "s/Build-Depends: //g" | sed "s/([^)]*)//g" | sed "s/, */ /g")`
9) `mkdir -p build`
10) `cd build`
11) `cmake ..`
12) `make -j4`

**Comment by johnbenzee** [comment]
I followed you installtion guide, and kurento-media-server installed successfully. But I can not start the kurento server, it says the kurento-media-server service not found.
plzz hlp.

**Comment by johnbenzee** [comment]
s

**Comment by geogeorgiev** [comment]
> sudo make install
> sudo service kurento-media-server-6.0 start

**Comment by j1elo** [comment]
https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#build-from-sources
