### ISSUE TITLE
KMS dont working correct if IPv6 is disabled [bug]

### ISSUE THREAD

**Issue by anton-petrov** [Kurento/bugtracker#142]
I'm permanently disable IPv6 on my system, resulting that KMS don't work.

**KMS Version**: 
Version: 6.6.2~1.gd44e10d
Found modules:
    Module: 'core' version '6.6.2~4.g988f8fe'
    Module: 'elements' version '6.6.2~2.g7595ce1'
    Module: 'filters' version '6.6.2~1.g8af2ae8'

**Other libraries versions**:

ii  gir1.2-gst-plugins-base-1.5            1.8.1.1.xenial~20160909144420.55.7b19cfd  amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                   1.8.1.1.xenial~20160909144634.170.0d6031b amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64               1.8.2.1.xenial~20160909142943.96.493eee4  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                0.1.13.1.xenial~20160930090920.81.eebfdab amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64         1.8.1.1.xenial~20161005125505.100.3db37b1 amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64        1.8.1.1.xenial~20160909144420.55.7b19cfd  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64        1.8.1.1.xenial~20160909143716.112.9ee4248 amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64        1.8.1.1.xenial~20160909143419.89.2685b0f  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64          1.8.1.1.xenial~20160909143716.112.9ee4248 amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                   1.8.1.1.xenial~20160909144420.55.7b19cfd  amd64        GStreamer plugins for X11 and Pango
ii  kms-cmake-utils                        1.3.3.xenial~20160930150934.1.24e0763     all          Kurento cmake utils
ii  kms-core-6.0                           6.6.2.xenial~20161005120120.4.988f8fe     amd64        Kurento core module
ii  kms-core-6.0-dev                       6.6.2.xenial~20161005120120.4.988f8fe     amd64        Kurento core module
ii  kms-elements-6.0                       6.6.2.xenial~20161007100721.2.7595ce1     amd64        Kurento elements module
ii  kms-elements-6.0-dev                   6.6.2.xenial~20161007100721.2.7595ce1     amd64        Kurento elements module
ii  kms-filters-6.0                        6.6.2.xenial~20161007101945.1.8af2ae8     amd64        Kurento filters module
ii  kms-filters-6.0-dev                    6.6.2.xenial~20161007101945.1.8af2ae8     amd64        Kurento filters module
ii  kms-jsonrpc-1.0                        1.1.3.xenial~20160930151233.1.60a4ad4     amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                    1.1.3.xenial~20160930151233.1.60a4ad4     amd64        Kurento jsonrpc library
ii  kmsjsoncpp                             1.6.3.xenial~20160909192519.40.d78deb7    amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                         1.6.3.xenial~20160909192519.40.d78deb7    amd64        Kurento jsonrpc library
ii  kurento-media-server-6.0               6.6.2.xenial~20161007103526.1.d44e10d     amd64        Kurento Media Server
ii  kurento-module-creator-4.0             4.0.8.xenial~20160930152301.1.9662c2f     all          Kurento module creator
ii  kurento-server                         6.6.2.xenial~20161007103526.1.d44e10d     amd64        Meta package for kurento server side
ii  libgstreamer-plugins-bad1.5-0:amd64    1.8.1.1.xenial~20161005125505.100.3db37b1 amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64   1.8.1.1.xenial~20160909144420.55.7b19cfd  amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev       1.8.1.1.xenial~20160909144420.55.7b19cfd  amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64                1.8.1.1.xenial~20160909144634.170.0d6031b amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0-dbg:amd64            1.8.1.1.xenial~20160909144634.170.0d6031b amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                    1.8.1.1.xenial~20160909144634.170.0d6031b amd64        GStreamer core development files
ii  libnice-dev                            0.1.13.1.xenial~20160930090920.81.eebfdab amd64        ICE library (development files)
ii  libnice10:amd64                        0.1.13.1.xenial~20160930090920.81.eebfdab amd64        ICE library (shared library)

**Client libraries**
- Language: Java
- Version: 1.8

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:
- Firefox:
- Native:

**System description:**
Ubuntu 16.04 in VirutalBox, static IP

**What steps will reproduce the problem?**

While KMS server is running, netstat results is:
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 _:ssh                   *:_                     LISTEN

**What is the expected result?**
KMS server running on port 8888

**What happens instead?**
KMS server don't listen on port 8888

**Does it happen with one of the tutorials?**
Yes

**Please provide any additional information below.**

**Comment by yellowmegaman** [comment]
Same here, sad it's still not fixed
