### ISSUE TITLE
RTSP Player Endpoint Issue

### ISSUE THREAD

**Issue by tjmcclure0501** [Kurento/bugtracker#144]
me (Tim McClure change) 	

Oct 11

I am using a player endpoint to consume a live RTSP endpoint.  The player endpoint is being created server-side and then distributed to through Kurento to clients as they connect to save on the transcoding from RTSP to OP8.  It is working well except for one scenario as described below:

1.  If the RTSP is streaming before the player endpoint is created everything works well.
2.  If the player is created before the RTSP stream is streaming and the RTSP source starts streaming before any client webRTCEndpoints connect everything works fine.
3.  If the player is created and a client webRTCEndpoint connects before the RTSP source starts streaming no video is ever rendered.  It appears the RTSP source needs to be streaming before any client webRTCEndpoints can connect.

**KMS Version**:

Version 6.6

Using NodeJS server side - Chrome Browser Javascript

**Comment by sampleref** [comment]
Yes I too observed same problem. Basically our use case issues comes up where steps are like:

1. RTSP Stream available
2. PlayerEndpoint created and play is invoked on it
3. RecorderEndpoint and WebrtcEndpoint connected to above player, everything works fine
4. RTSP Stream disconnected, PlayerEndpoint throws error event
5. PlayerEndpoint I keep into pause() state and wait for 3-4 secs
6. Check if RTSP stream is alive again, once available
7. Trigger play() on PlayerEndpoint above
8. It just hangs, nothing further in logs too

**Comment by zhangalex** [comment]
@sampleref   Could you please tell me how to check if rtsp stream is disconnected? And I tried to play() it again, it failed! I'm using kurento-utils-js.

**Comment by sampleref** [comment]
I am using https://github.com/bramp/ffmpeg-cli-wrapper to check RTSP is alive or not after I get Error/EndOfStream Event

**Comment by j1elo** [comment]
Please check if KMS version 6.8.1 fixes this issue
