### ISSUE TITLE
Significant delay in audio when connecting new endpoint to old composite

### ISSUE THREAD

**Issue by SecurityConscious** [Kurento/bugtracker#146]
**KMS Version**:
Version: 6.6.2 ~ 1.gd44e10d
Found modules:
	Module: 'core' version '6.6.2 ~ 4.g988f8fe'
	Module: 'elements' version '6.6.2 ~ 2.g7595ce1'
	Module: 'filters' version '6.6.2 ~ 1.g8af2ae8'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.8.2.1 ~ 20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1 ~ 20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1 ~ 20161005125237.100.g3db37b1.trusty amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1 ~ 20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1 ~ 20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1 ~ 20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1 ~ 20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1 ~ 20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.2 ~ 20161031112905.4.g988f8fe.trusty     amd64        Kurento core module
ii  kms-elements-6.0                     6.6.2 ~ 20161031115140.2.g7595ce1.trusty     amd64        Kurento elements module
ii  kms-filters-6.0                      6.6.2 ~ 20161031120534.1.g8af2ae8.trusty     amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.3 ~ 20160930150652.1.g60a4ad4.trusty     amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3 ~ 20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.6.2 ~ 20161031122403.1.gd44e10d.trusty     amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1 ~ 20161005125237.100.g3db37b1.trusty amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1 ~ 20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1 ~ 20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1 ~ 20160930090742.81.geebfdab.trusty amd64        ICE library (shared library)

**Browsers tested**
- Chrome: None
- Firefox:  dpkg -l | grep firefox
 firefox   50.0+build2-0ubuntu0.16.04.2     amd64    Safe and easy web browser from Mozilla
- Native: Android

**System description:**
I am using a public STUN server.
I have kurento running on a VM with 4 Core and 2GBs of memory.  
The signaling server is on a separate VM.
I have tried the client running in the firefox browser on the host machine, and also android native.

**What steps will reproduce the problem?**
In all tests Endpoint 1 and Endpoint 2 are the same version clients.
1. Endpoint 1 is connected through a hubport to the composite for 30 minutes, the endpoint is muted and not sending audio.
2. Endpoint 2 then connects through the hubport to the composite.  googCurrentDelayMs is ranges from 800 - 1600ms, and no voice can be heard by endpoint 1 or endpoint 2.  (Endpoint 1 reports a googCurrentDelayMs < 300ms).
3. When googCurrentDelayMs drops under 300ms on Endpoint 2 all Endpoints can send and receive audio. Usually takes about 30 seconds.
4. During the whole test Memory and CPU usage are both about 9%.
5. If either Endpoint 1 or 2 disconnect, and then connect up again, there is another 30 second delay before any of the endpoints can send and receive voice.
6. The delay before voice can be sent or received when a new endpoint connects happens every time, until the pipeline is destroyed.

**What is the expected result?**
When Endpoint 2 connects to the hubport after 30 minutes, Endpoint 1 and 2 should be able to communicate immediately (or 1-2 second delay).  If endpoint 1 or 2 disconnects and connects back again, there should again be only a 1-2 second delay when sending/receiving voice.

**What happens instead?**
When Endpoint 2 connects to the hubport after 30 minutes, Endpoint 1 and 2 do not send/receive audio for 30 seconds.  Each time a new Endpoint connects there is another 30 second delay.  When Endpoint 1 is connected for 12 hours there is a delay of about 4 minutes before the endpoints can send/receive audio.

**Does it happen with one of the tutorials?**
https://github.com/Nileshwagh22/kurento-composite-media-element-for-audio.git.

**Please provide any additional information below.**
The following post on Kurento groups describes several different test cases we ran through:
Re: Delay when third users joins an mcu endpoint
https://groups.google.com/forum/#!searchin/kurento/mcu$20delay%7Csort:relevance/kurento/m-pA9Nx25F0/bdmlEcZrBwAJ

For the past three days I have constructed some additional tests.  Below are results to some of the more interesting tests...

**Test #2**
1. When endpoint 1 requests a connection to a composite: the composite and 10 hubports are created.  Endpoint 1 is attached to one of the hubports for 30 minutes.
2. Endpoint 2 connects to one of the hubports created above.
3. Endpoint 2 can hear Endpoint 1 immediately, but Endpoint 1 cannot hear Endpoint 2 for 10-20 seconds.  
Our Conclusion: While not ideal, creating the hubports when the composite is created, does seem to have an improved performance, though there is still a significant delay (which increases with time) before the new endpoint can send vice.  The delay occurs any time an endpoint is attached.

**Test #3**
1. At t0 the composite and 1 hubport is created, and Endpoint 1 is created and connected.
2. After t0 + 10 minutes we:
     a. Release the composite and the hubport
     b. Create a new composite and a new hubport
     c. Attach Endpoint 1 to one of the new hubports.
     d. Endpoint 2 connects to a new hubport
     e. Delay of 10 seconds when Endpoint 2 tries to send voice immediately after the peer connection is established.
     f. Endpoint 2 disconnects
3. After t0 + 20 minutes we:
     a. Release the composite and the hubport
     b. Create a new composite and a new hubport
     c. Attach Endpoint 1 to one of the new hubports.
     d. Endpoint 2 connects to a new hubport
     e. Delay of 10 seconds when Endpoint 2 tries to send voice immediately after the peer connection is established.
     f. Endpoint 2 disconnects
3. After t0 + 30 minutes we:
     a. Release the composite and the hubport
     b. Create a new composite and a new hubport
     c. Attach Endpoint 1 to one of the new hubports.
     d. Endpoint 2 connects to a new hubport
     e. Delay of 10 seconds when Endpoint 2 tries to send voice immediately after the peer connection is established.
     f. Endpoint 2 disconnects
Our Conclusion: Releasing the composite and hubports and re-creating them have no effect, it seems like once there is a delay in the pipeline, it remains in the pipeline until it is released.

**Test #4**
1. At t0 the composite and 10 hubports are created.
2. At t0 + 30 minutes, one at a time, Endpoint 1-5 are connected to the composite (through a hubport).  Each time an endpoint connects there is NO DELAY in sending audio to the existing endpoints connected.
3. One at a time, each endpoint disconnects from the hubport, and then connects to a new hubport.  Each one experiences a 10 SECOND DELAY before they can send audio.
Our Conclusion: This is really weird

**Test #5**
1. At t0 the composite and 10 hubports are created, and Endpoint 1 is connected
3. At t0 + 30 minutes a new composite and 10 hubports are created.  
4. Endpoint 3 and 4 conncect to the new composite and can send and receive audio immediately.
Out Conclusion: This kind of implies that the delay is tied to a composite, and not due to resources being constrained.

**Test #6**
1. At t0 the composite and the 10 hubports are created, and Endpoint 1 is created and connected.
2. Endpoint 1 connects and then disconnects about every 10 seconds for 30 minutes.
3. Endpoint 1 connects and Endpoint 2 connects, there is a still a 30 second delay before Endpoint 1 can hear audio from endpoint 2
Our Conclusion: This makes me think it has nothing to do with how we create, connect, disconnect endpoints

**Test #7**
1. At t0 the composite 10 hubports and 10 endpoints areWe have also run tests to make sure that if the  created.  Endpoint 1 is connected to the hubport, and the media connection is established (sdp and ice candidates exchanged, DTLS established).  (The rest of the endpoints sit idle).
2. At t0 + 30, Endpoint 2 media connection is established (sdp and ice candidates exchanged, and DTLS established).
3. There is a 30 second delay before Endpoint 2 receives audio.
Our Conclusion: Creating the hubports when the composite was created seemed to have the benefit that only the newly attached endpoint would have a delay before sending voice (rather than all endpoints attached to the composite having a delay before sending/receiving audio).  There does not seem to be any added benefit in creating the Endpoints ahead.

To rule out any problems with CPU/memory load on the machine, while experiencing the delay as described in the above tests, we create a new pipeline and composite and join endpoints to it.  The endpoints connected to the new composite don't have any delay.

**Comment by FredLuart** [comment]
Hello,

Is there a status about this issue ? I think I can reproduce it in audio only with KMS 6.6.1

When connecting with video : video of composite is well received as soon as we connect, but audio is only established after some delay : when audio is connected, it seems that the delay is not present : Maybe thanks to synchronisation between audio and video ?

**Comment by sebastian-greco** [comment]
I'm having the same problem in 6.6.1

**Comment by sebastian-greco** [comment]
Looks like there is a bounty for this issue:
https://www.bountysource.com/issues/39413996-significant-delay-in-audio-when-connecting-new-endpoint-to-old-composite

**Comment by quickstreamingmedia** [comment]
Hello let me know who are facing similar issues I can show solution my Skype: quickstreamingmedia

**Comment by slacher13** [comment]
Hi, we are also developing a voice-only chat and have a similar issue. In our case, the trigger for the delay seems to be repeated connects and disconnects to/from a composite. As the quantity of re-connects increases, the amount of delay/lag tends to increase. In some cases, it may take several dozen re-connects for the lag to increase to being more than a few seconds. Eventually, it grows to the point where the application is unusable. When starting over with a new MediaPipeline, the lag disappears. This will be a show-stopper for us if we can't fix it.

Is any progress still being made on this issue? Thanks.

**Comment by sebastian-greco** [comment]
@slacher13 I managed to solve the problem and actually did a PR, I just saw you commented there as well.
My fix works perfectly, we have been using it since then, if you want to try it for yourself and give some feedback so maybe the @adminkurento will accept it or at least tell us what's wrong on my pull request.

https://github.com/Kurento/kms-core/pull/10

Sadly you will have to compile the `kurento-core` in order to test it.

**Comment by adu89** [comment]
@sebastian-greco @adminkurento Experiencing the same issues running kurento 6.7.1.

**Comment by mariogasparoni** [comment]
I have tested @sebastian-greco solution but it didn't work in our use case. 
I have submitted PR Kurento/kms-core#13 , which i believe solves it for all cases.

**Comment by htaito** [comment]
Has the problem been solved?

**Comment by slacher13** [comment]
> Has the problem been solved?

I'm not sure, but we couldn't wait any longer. Our Kurento-based solution was not usable due to audio issues. As a result, we were facing serious fallout with our customer, potentially resulting in a greater than seven figure (USD) loss. We switched to mediasoup, which has worked extremely well for our needs and has been problem-free.

**Comment by j1elo** [comment]
The composite component has _very_ low usage numbers, so it doesn't really get much priority as part of the **open-source** development roadmap. I will review Kurento/kms-core#13 but to be honest this issue has been under the radar for the last year.

> @slacher13 
> potentially resulting in a greater than seven figure (USD) loss

The source code is public and you are free to change it as you please, to accommodate your needs. Otherwise, citing from the [Support page](https://doc-kurento.readthedocs.io/en/latest/user/support.html#commercial-support):

> Kurento is formed by a small team of people. This means that our task pipeline is quite restricted, and **most feature or support requests end up being stored in the backlog for a long time**. We advance as fast as we can, but time and resources are limited and at the end of the day there is so much that we can do.
> 
> **If you have some needs that require urgent attention, [...] we offer consultancy and support services on demand**

It's only ironic that a project that could potentially extract SEVEN figures USD of *value* from Kurento, could not spend a minimal fraction of that in sending a simple email and asking for commercial support. Food for thought, I guess.
