### ISSUE TITLE
seg fault in ICE negotiation 

### ISSUE THREAD

**Issue by pauluxprobe** [Kurento/bugtracker#150]
Segmentation fault (thread 140547092113152, pid 1557)
Stack trace:
[__nss_hosts_lookup]
/lib/x86_64-linux-gnu/libc.so.6:0x1405F8
[gst_sdp_media_get_attribute_val_n]
/usr/lib/x86_64-linux-gnu/libgstsdp-1.5.so.0:0x87CB
[sdp_utils_media_is_inactive]
/usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.6:0x2BE30
[kms_webrtc_session_set_remote_ice_candidate]

I am on Ubuntu 14.04
Kurento 6.6 (newest according to apt-get)

**Comment by pauluxprobe** [comment]
here is another

Segmentation fault (thread 33;1m140203722655488, pid 33;1m19254)
Stack trace:
[__nss_hosts_lookup]
/lib/x86_64-linux-gnu/libc.so.632;1m:0x13FE16
[gst_sdp_media_get_attribute_val_n]
/usr/lib/x86_64-linux-gnu/libgstsdp-1.5.so.032;1m:0x87CB
[sdp_utils_media_is_inactive]
/usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.632;1m:0x2BE30
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.632;1m:0xE670
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.632;1m:0xE9A1
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.632;1m:0xEB57
[__kms_webrtc_marshal_BOOLEAN__VOID]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.632;1m:0x1439D
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x2A899
[g_signal_emit_by_name]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x2B5F5
[kms_webrtc_session_set_callbacks]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.632;1m:0x1011C
[__kms_webrtc_marshal_BOOLEAN__STRING]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.632;1m:0x145B5
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.032;1m:0x2A899

this system has become very unreliable

**Comment by pauluxprobe** [comment]
kurento-media-server -v
libdc1394 error: Failed to initialize libdc1394
Version: 6.6.1
Found modules:
        Module: 'core' version '6.6.1'
        Module: 'elements' version '6.6.1'
        Module: 'filters' version '6.6.1'

**Comment by pauluxprobe** [comment]
*** Error in `/usr/bin/kurento-media-server': realloc(): invalid pointer: 0x00007f95a857002d ***
Aborted (thread 140280443418368, pid 1409)
Stack trace:
[gsignal]
/lib/x86_64-linux-gnu/libc.so.6:0x36C37
[abort]
/lib/x86_64-linux-gnu/libc.so.6:0x3A028
[__fsetlocking]
/lib/x86_64-linux-gnu/libc.so.6:0x732A4
[_IO_str_seekoff]
/lib/x86_64-linux-gnu/libc.so.6:0x7DFF7
[realloc]
/lib/x86_64-linux-gnu/libc.so.6:0x830A2
[g_realloc]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x4F638
[g_static_private_free]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x1D469
[g_array_append_vals]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x1D7E8
[gst_sdp_media_add_attribute]
/usr/lib/x86_64-linux-gnu/libgstsdp-1.5.so.0:0x7022
[kms_webrtc_transport_disable_latency_notification]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xC76C
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xE93F
[__kms_webrtc_marshal_BOOLEAN__OBJECT]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x14465
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2A899
[g_signal_emit_by_name]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2B5F5

**Comment by pauluxprobe** [comment]
Is there anything I can add to this bug report to provide more context?

**Comment by jcaden** [comment]
It will be useful to have a reproducer. What steps do you execute to reproduce the problem?

**Comment by pauluxprobe** [comment]
This occurs with a webrtc ice connection. We have a very simple use case of a pipeline with a WebRTCWndpoint connected to a Recorder and that's it.

I built up a VM from scratch this morning and reproduced the bug in a few tries.

**Comment by jcaden** [comment]
Can you describe further the client you are using and what are the steps to reproduce the problem?

 * Browser, Mobile OS version...
 * Network topology (client and server)
 * Network conditions

**Comment by pauluxprobe** [comment]
We are using Chrome on Windows and Mac to connect to a NodeJS which connects the the Kurento on the same VM. VM is hosted on Google Cloud and has an external IP address. We have our own coturn server which can relay. We have a similar test system (exact same setup but running latest dev sprint rather than master) and this system has not crashed ever (there is no seg fault in the kurento error log).

**Comment by pauluxprobe** [comment]
Crash from this morning:

[gst_sdp_media_get_attribute_val_n]
/usr/lib/x86_64-linux-gnu/libgstsdp-1.5.so.0:0x87A0
[sdp_utils_media_is_inactive]
/usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.6:0x2BE30
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xE670
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xE9A1
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xEB57
[__kms_webrtc_marshal_BOOLEAN__VOID]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x1439D
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2A899
[g_signal_emit_by_name]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2B5F5
[kms_webrtc_session_set_callbacks]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x1011C
[__kms_webrtc_marshal_BOOLEAN__STRING]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x145B5
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2A899
[g_signal_emit_by_name]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2B5F5

**Comment by pauluxprobe** [comment]
lsb_release -d
Description:    Ubuntu 14.04.5 LTS

**Comment by pauluxprobe** [comment]
Segmentation fault (thread 140010825180928, pid 1403)
Stack trace:
[g_static_private_free]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x1D416
[g_array_append_vals]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x1D7E8
[gst_sdp_media_add_attribute]
/usr/lib/x86_64-linux-gnu/libgstsdp-1.5.so.0:0x7022
[kms_webrtc_transport_disable_latency_notification]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xC76C
[kms_webrtc_session_set_remote_ice_candidate]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0xE93F
[__kms_webrtc_marshal_BOOLEAN__OBJECT]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x14465
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2A899
[g_signal_emit_by_name]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2B5F5
[kms_webrtc_session_set_callbacks]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x10239
[__kms_webrtc_marshal_BOOLEAN__STRING_OBJECT]
/usr/lib/x86_64-linux-gnu/libkmswebrtcendpointlib.so.6:0x14679
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x10015
[g_signal_handler_disconnect]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2260E
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2A899
[g_signal_emit_by_name]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2B5F5

**Comment by pauluxprobe** [comment]
paul_davies@uxprobe-eu-media-f-1:/opt/kurento-app$ dpkg -l | egrep -i "kurento|gst.*1.5|nice"
ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.1.20160930110533.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.6.1.20160930122545.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.6.1.20160930131150.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.2.20160930094018.trusty                amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.6.1.20160930143513.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (shared library)

**Comment by pauluxprobe** [comment]
We have downgraded to 6.4 - server is now stable and does not crash. Latest kurento with latest 14.04 ubuntu is not stable 

current stable setup

lsb_release -d
Description:    Ubuntu 14.04.4 LTS

kurento-media-server -v
Version: 6.4.0
Found modules:
        Module: 'core' version '6.4.0'
        Module: 'elements' version '6.4.0'
        Module: 'filters' version '6.4.0'
