### ISSUE TITLE
About create filter,not find  CodeGenerator of kms-core ?

### ISSUE THREAD

**Issue by chris0927** [Kurento/bugtracker#151]
If KurentoHelpers is not found, then it is necessary to install
          kms-cmake-utils package from the kurento repository
If CodeGenerator is not found, then it is necessary to install
          kms-core package from the kurento repository
CMake Error at CMakeLists.txt:14 (include):
  include could not find load file:

    CodeGenerator

CMake Error at CMakeLists.txt:16 (get_values_from_model):
  Unknown CMake command "get_values_from_model".

**Comment by wayspurrchen** [comment]
I experienced this same issue on Ubuntu 14.04, but was able to solve it by installing the dependencies specified on the Compilation Instructions at https://github.com/Kurento/kurento-media-server.

```
  echo "deb http://ubuntu.kurento.org trusty-dev kms6" | sudo tee /etc/apt/sources.list.d/kurento-dev.list
  wget -O - http://ubuntu.kurento.org/kurento.gpg.key | sudo apt-key add -
  sudo apt-get update
  sudo apt-get install $(cat debian/control | sed -e "s/$/\!\!/g" | tr -d '\n' | sed "s/\!\! / /g" | sed "s/\!\!/\n/g" | grep "Build-Depends" | sed "s/Build-Depends: //g" | sed "s/([^)]*)//g" | sed "s/, */ /g")
```
