### ISSUE TITLE
Unable to install kurento server on Debian deb8u2

### ISSUE THREAD

**Issue by izemize** [Kurento/bugtracker#152]
gstreamer1.5-pulseaudio is requires libpulse0 (>= 1:2.0) but is not installable.  Only 5.0-13 exist in jessie.

[search libpulse0 in packages](https://packages.debian.org/search?keywords=libpulse0&searchon=names&suite=all&section=all)

**Comment by igracia** [comment]
Ubuntu is the officially supported distribution, sorry! Maybe someone in the list can help you.
