### ISSUE TITLE
hello-world demo couldn't stream video

### ISSUE THREAD

**Issue by Bjtujsone** [Kurento/bugtracker#153]
**KMS Version**:
kurento-media-server version 6.6.1

**Client libraries**
- hello-world demo
- Language: Java, JavaScript

**Environment：**
KMS is running  in public network，Ubuntu 14.04 64bit ，1G RAM

**Browsers tested**
- Chrome 

**additional information below**
All the service have been running well.when I open the website ,the browsers can open the webcam,but couldn't stream the video to the KMS,So I can't receive the “remote stream”.
1.Brower alert the website certificate is not secure.
2.hello-world demo show the error:
        _Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
        Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)_
3.The last log in the console of brower is:
Remote URL:
'blob:https%3A//<ipadress>%3A8443/72fbf521-48b5-4ee4-8522-d160f5eb2d69'
4.I ever test the one2one-demo、room-demo,It still could stream the video.

**Comment by akocmark** [comment]
+1 this is exactly what im facing right now

**Comment by Bjtujsone** [comment]
I have resolved！Because the public network have a question that it behind the NAT.But the public stun server is not work well,at least,it can't gather the public IP .So I install a coturn in my pc and it is OK.

**Comment by akocmark** [comment]
hey @Bjtujsone can you please post your WebRtcEndpoint.conf.ini
Im really lost
Thanks!

**Comment by akocmark** [comment]
I resolved it as well. thank you for the hint :)

**Comment by igracia** [comment]
You should use the list for this kind of questions. I'll close the issue since you already got that solved.
