### ISSUE TITLE
fetch kurento packages, got 403 forbidden

### ISSUE THREAD

**Issue by supernow** [Kurento/bugtracker#154]
I follow this 
```
echo "deb http://ubuntu.kurento.org trusty kms6" | sudo tee /etc/apt/sources.list.d/kurento.list
wget -O - http://ubuntu.kurento.org/kurento.gpg.key | sudo apt-key add -
sudo apt-get update
```
when I　execute apt-get update, I got this error:
```
W: Failed to fetch http://ubuntu.kurento.org/dists/trusty-dev/kms6/binary-amd64/Packages  403  Forbidden [IP: 112.124.140.210 80]

W: Failed to fetch http://ubuntu.kurento.org/dists/trusty-dev/kms6/binary-i386/Packages  403  Forbidden [IP: 112.124.140.210 80]

W: Failed to fetch http://ubuntu.kurento.org/dists/trusty/kms6/binary-amd64/Packages  403  Forbidden [IP: 112.124.140.210 80]

W: Failed to fetch http://ubuntu.kurento.org/dists/trusty/kms6/binary-i386/Packages  403  Forbidden [IP: 112.124.140.210 80]
```
I use "wget" to test  whether I can fetch "pakcages"
```
wget http://ubuntu.kurento.org/dists/trusty/kms6/binary-amd64/Packages
```
I can download the packege.

How can I solve the problem.

**Comment by zhourui392** [comment]
I got the same error. It caused by the proxy of apt. After I removed the 'apt.conf' in the Dir '/etc/apt/', it works well. Maybe you can try this.

**Comment by igracia** [comment]
The list is the appropriate place for this questions.

**Comment by substitute05** [comment]
After I removed the 'apt.conf' in the Dir '/etc/apt/', because the 'apt.conf' configure download source.

**Comment by karlli1976** [comment]
I follow kurento's official installation guide: 

https://doc-kurento.readthedocs.io/en/6.9.0/user/installation.html#local-installation

to upgrade kms from 6.7.1 to 6.9.0 on Ubuntu 14.04 (Trusty)

I can run below cmd to retrieve kms ver:

dpkg-query -l kurento-media-server | awk '$1 == "ii" { print $3; exit }'

6.7.1.trusty.20180322174246.dd49a2c

However, I found 403 forbidden error with apt-get update:

sudo apt-get update

Err http://ubuntu.openvidu.io trusty/kms6 amd64 Packages
  403  Forbidden
Ign http://ubuntu.openvidu.io trusty/kms6 Translation-en
W: Failed to fetch http://ubuntu.openvidu.io/6.9.0/dists/trusty/kms6/binary-amd64/Packages  403  Forbidden

Can anyone give me some hints?

Thanks.

**Comment by M-Dominguez** [comment]
Make sure you are using Ubuntu 16.04 or 18.04
