### ISSUE TITLE
Kurento didn't work to play rtsp with the parameter setting enabled, "useEncodedMedia"

### ISSUE THREAD

**Issue by arthor84** [Kurento/bugtracker#155]
**KMS Version**:
OS:Ubuntu 14.04
Version: 6.6.1
Found modules:
        Module: 'core' version '6.6.1'
        Module: 'elements' version '6.6.1'
        Module: 'filters' version '6.6.1'

**Other libraries versions**:

ii  gstreamer0.10-nice:amd64                              0.1.4-1                                             amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                               0.1.4-1                                             amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64                              1.8.2.1~20160909143244.96.g493eee4.trusty           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                               0.1.13.1~20160930090742.81.geebfdab.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64                        1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64                       1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64                       1.8.1.1~20160909143047.112.g9ee4248.trusty          amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64                       1.8.1.1~20160909192513.89.g2685b0f.trusty           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64                         1.8.1.1~20160909143047.112.g9ee4248.trusty          amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                                  1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                          6.6.1.20160930110533.trusty                         amd64        Kurento core module
ii  kms-elements-6.0                                      6.6.1.20160930122545.trusty                         amd64        Kurento elements module
ii  kms-filters-6.0                                       6.6.1.20160930131150.trusty                         amd64        Kurento filters module
ii  kms-jsonrpc-1.0                                       1.1.2.20160930094018.trusty                         amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                            1.6.3~20160909143252.40.gd78deb7.trusty             amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                              6.6.1.20160930143513.trusty                         amd64        Kurento Media Server
ii  kurento-server                                        6.6.1.20160930143513.trusty                         amd64        Meta package for kurento server side
ii  libgstreamer-plugins-bad1.5-0:amd64                   1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64                  1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                               1.8.1.1~20160909144007.170.g0d6031b.trusty          amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                                       0.1.13.1~20160930090742.81.geebfdab.trusty          amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64                    1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer plugins from openh264

**Client libraries**
- Language: Java
- Version: 6.6.1

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: 55.0.2883.87

**System description:**
	All in the same LAN

**What steps will reproduce the problem?**
1. get the kurento-player from java tutorials 
2. modify PlayerEndpoint and add useEncodedMedia 
3. run 
4. put rtsp with h.264 encoded streaming
5. play

**What is the expected result?**

browser should play video stream without transcoding.

**What happens instead?**

From client:
INFO 14364 --- [ventExec-e2-t18] o.kurento.tutorial.player.PlayerHandler  : ErrorEvent: Internal data flow error. -> gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline13/KmsPlayerEndpoint:kmsplayerendpoint13/GstAppSrc:appsrc16:
streaming task paused, reason not-linked (-1)

From server:
[0x00007fed30ff9700]   error playerendpoint            kmsplayerendpoint.c:671 kms_player_end_point_add_appsrc()  Could not link appsrc1 to element kmsagnosticbin2-0
[0x00007fed90f4a8c0]   error KurentoMediaPipelineImpl  MediaPipelineImpl.cpp:42 busMessage()  Error on bus: error message: 0x7fed680c60b0, time 99:99:99.999999999, seq-num 530, element 'appsrc1', GstMessageError, gerror=(GError)NULL, debug=(string)"gstbasesrc.c\(2948\):\ gst_base_src_loop\ \(\):\ /GstPipeline:pipeline0/KmsPlayerEndpoint:kmsplayerendpoint0/GstAppSrc:appsrc1:\012streaming\ task\ paused\,\ reason\ not-linked\ \(-1\)";
[0x00007fed90f4a8c0]   error KurentoMediaElementImpl   MediaElementImpl.cpp:261 _media_element_impl_bus_message()  MediaElement error: error message: 0x7fed680c60b0, time 99:99:99.999999999, seq-num 530, element 'appsrc1', GstMessageError, gerror=(GError)NULL, debug=(string)"gstbasesrc.c\(2948\):\ gst_base_src_loop\ \(\):\ /GstPipeline:pipeline0/KmsPlayerEndpoint:kmsplayerendpoint0/GstAppSrc:appsrc1:\012streaming\ task\ paused\,\ reason\ not-linked\ \(-1\)";
[0x00007fed437fe700]   debug KurentoWebSocketEventHandler WebSocketEventHandler.cpp:54 sendEvent()  Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"description":"Internal data flow error. -> gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/KmsPlayerEndpoint:kmsplayerendpoint0/GstAppSrc:appsrc1:\nstreaming task paused, reason not-linked 

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by juicechu** [comment]
i have the same problem? some one help?

**Comment by sampleref** [comment]
We too are facing same problem. Basically our requirement is to take from source which is RTSP with H.264 to Kurento Media Server to Browser (WebRTC with H.264) without any transcoding. So we set flag **useEncodedMedia: true** and we have **disabled VP8 at SdpEndpoint.json config of Kurento.** Facing the same error as above. Any suggestion would be highly helpfull

**Comment by raghugunnaiah** [comment]
Any one able to resolve this issue? if so please let me know the fix.

**Comment by ArgusMagnus** [comment]
I have the same problem, any progress on this?

**Comment by keyan007** [comment]
I am having this issue with Audio Codec (PCMU)too, When connecting PlayerEndpoint (by setting the useEncodeMedia to true)with RTPEndpoint. After received the MediaConnectedEvent, issued Play command and listened for MediaTranscodingStateChangeEvent.

MediaTranscodingStateChangeEvent was TRANSCODING while playing the media.

**Comment by j1elo** [comment]
Please comment or open a new report if this still happens.
