### ISSUE TITLE
how to use the cluster for Kurento? 

### ISSUE THREAD

**Issue by MrsZ** [Kurento/bugtracker#158]

**Comment by arpitshukla16** [comment]
I am finding the same solution  for a little while what i  got is reply on stackoverflow from @igracia .
http://stackoverflow.com/questions/30965288/kurento-multiple-one-to-many-broadcast-sessions
two option there -
create  multiple pipeline on same media server
or launch dynamic instance by application logic

Another option is use elastic rtc cluster . I dont know exactly how but they are providing very much functionality like this.
