### ISSUE TITLE
Video rotated by 90 degrees - iOS native - Kurento  

### ISSUE THREAD

**Issue by MichaelSiddi** [Kurento/bugtracker#160]
Hi, 
I'm using Kurento 6.6.1 with the r56 revision of the native WebRTC iOS code and I'm facing a video orientation issue. 
My setup is: 
[iOS-A] <--> WebRtcEndpoint(a) <--> WebRtcEndpoint(b)  <--> [iOS-B].

The video stream received by **iOS-B** is rotated by 90 degrees. This do not happen when the two iOS devices go peer-to-peer.

The problem could be related to the fact that **iOS-A** sends the RTP packets with a header that follows the **urn:3gpp:video-orientation** extension but it looks like the orientation header is stripped by _Kurento_ when the RTP packets are forwarded to **iOS-B**.

Should Kurento retain the RTP header extensions from the original packets to the new ones it creates?

Thank you.

**KMS Version**:
Version: 6.6.1
Found modules:
    Module: 'core' version '6.6.1'
    Module: 'elements' version '6.6.1'
    Module: 'filters' version '6.6.1'

**Comment by j1elo** [comment]
iOS Safari earlier than 13.0 had bugs related to the rotation. Info in this issue: https://github.com/Kurento/bugtracker/issues/484
