### ISSUE TITLE
Kurento Utils JS - remoteVideo.pause is not a function

### ISSUE THREAD

**Issue by Ullaakut** [Kurento/bugtracker#163]
**KMS Version**:

`Version: 6.6.0
Found modules:
        Module: 'core' version '6.6.0'
        Module: 'elements' version '6.6.0'
        Module: 'filters' version '6.6.0'`

**Other libraries versions**:

`gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer`
`gstreamer1.5-nice:amd64              0.1.13.1~20160909144510.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)`
`gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set`
`gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set`
`gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set`
`gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set`
`gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio`
`gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango`
`kms-core-6.0                         6.6.0.20160909201132.trusty                amd64        Kurento core module`
`kms-elements-6.0                     6.6.0.20160912112100.trusty                amd64        Kurento elements module`
`kms-filters-6.0                      6.6.0.20160912114031.trusty                amd64        Kurento filters module`
`kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library`
`kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento 
jsoncpp library`
`kurento-media-server-6.0             6.6.0.20160912115811.trusty                amd64        Kurento Media Server`
`libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set`
`libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set`
`libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements`
`libnice10:amd64                      0.1.13.1~20160909144510.80.gd9ef50e.trusty amd64        ICE library (shared library)`

**Client libraries**
- Language: JavaScript
- Version: `6.6.1-dev`

**Browsers tested**
- Chrome:
     - KO on Chrome OSX 56
     - KO on Chrome Linux 56
- Firefox: KO on Firefox Linux 52

**System description:**
- KMS is located on a testing server, protected by a firewall
- A signaling server is in the cloud
- A TURN server is in the cloud (same machine as the signaling server)
- The web application is in the cloud

**What steps will reproduce the problem?**
1. Click the start button in the web application

**What is the expected result?**
After the sdp answer is received from KMS, the stream is shown in the user's web browser.

**What happens instead?**
After the sdp answer is received from KMS, the Kurento Utils JS library encounters a TypeError and doesn't get to the `load()` call which prevents the user from getting any stream in his browser.

**Please provide any additional information below.**
All browsers tell me that [remoteVideo.pause is not a function](https://github.com/Kurento/kurento-utils-js/blob/ac776b2d1958b971da1cada641be8ed5c44883bd/lib/WebRtcPeer.js#L430). I believe that due to this TypeError, the code that is above it is not ran, which is why no stream gets to the browser.

It used to work flawlessly, but somehow for a few days now this error happens.

When the error happens, the ICE negotiation still seems to be working as expected, KMS sends the stream to the webapp and the ping/pong works without any issues. The only effect of the bug is the absence of a stream in the video element.

The `remoteVideo` property of the `options` argument for `kurentoUtils.WebRtcPeer.WebRtcPeerRecvonly` is set to the `<video id="videoOutput" autoplay></video>` element, just like in the One to Many demo, so I don't believe that this is the cause of the problem.

**Comment by Ullaakut** [comment]
My bad, it was indeed the remoteVideo property of the options that was wrong. Sorry for the inconvenience.

**Comment by icejudo** [comment]
Hi, I'm facing the exact same problem you explained. If you still remenber, could you tell me how did you fix it? thanks.

**Comment by Ullaakut** [comment]
Hi @icejudo, from what I see in the ticket the issue is that the element I used for the `remoteVideo` attribute was wrong. Not sure what I did to fix it though since this was over 3 years ago :(

Maybe double-check that the element exists and is valid, and maybe the issue was with the `autoplay` property? I'm not sure, I haven't been using Kurento for a very long time.

**Comment by icejudo** [comment]
Hi @Ullaakut, thank you for answering. I finally fixed it but the truth is I don't know how. I think it had to do with the timing of launching the process, but my knowledge is limited. Thank you anyway.
