### ISSUE TITLE
How to Run Korrent Media Server on OSX

### ISSUE THREAD

**Issue by zaigham-mt** [Kurento/bugtracker#164]
Is it possible to run it on OSX.

https://github.com/Kurento/kurento-media-server

**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

**What steps will reproduce the problem?**
1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by petergerten** [comment]
@zaigham-mt did you get any further with this? I am interested in running it on OSX as well.

**Comment by zaigham-mt** [comment]
@petergerten I tried it using virtual box on mac. Installed debian. Then run on kms on debian machine.

Did not go much on detail for mac.

**Comment by petergerten** [comment]
@zaigham-mt ok, yes - that's what I am currently doing as well. Looking for native mac binaries though.

**Comment by j1elo** [comment]
We can only afford to support one platform (Ubuntu). Support for other platforms must come from user contributions. Anyway to run in Mac probably the best option is to use the Docker images.
