### ISSUE TITLE
ICE failed only on Firefox 43

### ISSUE THREAD

**Issue by N00D13** [Kurento/bugtracker#167]
**KMS Version**: 6.6.0 (Docker)

```
0:00:00.019878971   731      0x1202500 INFO    KurentoModuleManager ModuleManager.cpp:156:loadModules: Looking for modules in /usr/lib/x86_64-linux-gnu/kurento/modules
0:00:00.020520697   731      0x1202500 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
0:00:00.020567546   731      0x1202500 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded core version 6.6.0 generated at Sep  9 2016 20:15:45
0:00:00.025712090   731      0x1202500 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
0:00:00.025770200   731      0x1202500 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded elements version 6.6.0 generated at Sep 12 2016 11:26:04
0:00:00.026690056   731      0x1202500 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
0:00:00.026730744   731      0x1202500 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded filters version 6.6.0 generated at Sep 12 2016 11:42:56
Version: 6.6.0
Found modules:
	Module: 'core' version '6.6.0'
	Module: 'elements' version '6.6.0'
	Module: 'filters' version '6.6.0'
``` 
**Other libraries versions**:

```
ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160909144510.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.0.20160909201132.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.6.0.20160912112100.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.6.0.20160912114031.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.6.0.20160912115811.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160909144510.80.gd9ef50e.trusty amd64        ICE library (shared library)

```
**Client libraries**
- Language: Node.js  
- Version: 7.4.0 

**Browsers tested**
- Chrome:ok
- Firefox: fail (42 okay 43 error)

**System description:**
KMS and broadcaster are located on a Ubuntu server.
The Client (one2many Broadcast) are located on a webserver

**What steps will reproduce the problem?**
1. Connecting with the javascript client 
2. no Video
3. get ```ICE failed: add a TURN server... ```

**What is the expected result?**
On Firefox 42 and Chrome i got the LiveStream

**What happens instead?**
Black Screen

**Does it happen with one of the tutorials?**
one2many Broadcast

**Please provide any additional information below.**

**Comment by cupuyc** [comment]
Same for me with **kurento-hello-world** and **kurento/kurento-media-server:6.6.3** with FF 57. 
However demo works in Chrome.

<details>
<summary>Firefox log</summary>

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): failed to create passive TCP host candidate: 3

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): failed to create passive TCP host candidate: 3

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): failed to create passive TCP host candidate: 3

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): failed to create passive TCP host candidate: 3

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) has no stream matching stream 0-1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#) aLevel=1

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) no streams with non-empty check lists

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) no streams with pre-answer requests

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) no checks to start

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/CAND-PAIR(DtsY): setting pair to state FROZEN: DtsY|IP4:192.168.1.154:64966/UDP|IP4:172.19.0.2:36049/UDP(host(IP4:192.168.1.154:64966/UDP)|candidate:1 1 UDP 2013266431 172.19.0.2 36049 typ host)

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#))/CAND-PAIR(DtsY): Pairing candidate IP4:192.168.1.154:64966/UDP (7e7f00ff):IP4:172.19.0.2:36049/UDP (780001ff) priority=8646913483524145663 (780001fffcfe01ff)

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/ICE-STREAM(0-1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#) aLevel=0): Starting check timer for stream.

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/CAND-PAIR(DtsY): setting pair to state WAITING: DtsY|IP4:192.168.1.154:64966/UDP|IP4:172.19.0.2:36049/UDP(host(IP4:192.168.1.154:64966/UDP)|candidate:1 1 UDP 2013266431 172.19.0.2 36049 typ host)

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/CAND-PAIR(DtsY): setting pair to state IN_PROGRESS: DtsY|IP4:192.168.1.154:64966/UDP|IP4:172.19.0.2:36049/UDP(host(IP4:192.168.1.154:64966/UDP)|candidate:1 1 UDP 2013266431 172.19.0.2 36049 typ host)

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) is now checking

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/CAND-PAIR(iUjN): setting pair to state FROZEN: iUjN|IP4:192.168.1.154:58097/TCP|IP4:172.19.0.2:45451/TCP(host(IP4:192.168.1.154:58097/TCP) active|candidate:3 1 TCP 1015021823 172.19.0.2 45451 typ host tcptype passive)

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#))/CAND-PAIR(iUjN): Pairing candidate IP4:192.168.1.154:58097/TCP (7d7fc0ff):IP4:172.19.0.2:45451/TCP (3c8000ff) priority=4359485538722349567 (3c8000fffaff81ff)

Peer offered candidates for disabled local component

Peer offered candidates for disabled local component

Peer offered candidates for disabled local component

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/CAND-PAIR(iUjN): setting pair to state WAITING: iUjN|IP4:192.168.1.154:58097/TCP|IP4:172.19.0.2:45451/TCP(host(IP4:192.168.1.154:58097/TCP) active|candidate:3 1 TCP 1015021823 172.19.0.2 45451 typ host tcptype passive)

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default)/CAND-PAIR(iUjN): setting pair to state IN_PROGRESS: iUjN|IP4:192.168.1.154:58097/TCP|IP4:172.19.0.2:45451/TCP(host(IP4:192.168.1.154:58097/TCP) active|candidate:3 1 TCP 1015021823 172.19.0.2 45451 typ host tcptype passive)

Write buffer not empty for IP4:172.19.0.2:45451/TCP 98 - already armed (@0x15a0bf1f4), not connected

STUN-CLIENT(srflx(IP4:192.168.1.154:64966/UDP|stun3.l.google.com:19302)): Received response; processing

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) pairing local trickle ICE candidate srflx(IP4:192.168.1.154:64966/UDP|stun3.l.google.com:19302)

ICE-PEER(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default): no pairs for 0-1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#) aLevel=0

Skipping SOURCE-ADDRESS

Skipping CHANGED-ADDRESS

Translating obsolete XOR-MAPPED-ADDRESS type

Skipping SOURCE-ADDRESS

Skipping CHANGED-ADDRESS

Translating obsolete XOR-MAPPED-ADDRESS type

STUN-CLIENT(srflx(IP4:192.168.1.154:64966/UDP|stun.voxgratia.org:3478)): Received response; processing

STUN-CLIENT(srflx(IP4:192.168.1.154:58362/UDP|stun3.l.google.com:19302)): Received response; processing

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) pairing local trickle ICE candidate srflx(IP4:192.168.1.154:58362/UDP|stun3.l.google.com:19302)

Skipping SOURCE-ADDRESS

Skipping CHANGED-ADDRESS

Translating obsolete XOR-MAPPED-ADDRESS type

STUN-CLIENT(srflx(IP4:192.168.1.154:58362/UDP|stun.voxgratia.org:3478)): Received response; processing

Skipping SOURCE-ADDRESS

Skipping CHANGED-ADDRESS

Translating obsolete XOR-MAPPED-ADDRESS type

ICE(PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#)): peer (PC:1512379849257077 (id=2147485068 url=https://local.trembit.com:8443/index.html?ws_uri=wss://local.trembit.com:8889/kurento#):default) Trickle grace period is over; marking every component with only failed pairs as failed.

+++++++ END ++++++++
</details>

**Comment by khuslen** [comment]
The **kurento-hello-world** demo doesn't seem to work with any Firefox versions after 56.

I've been trying to get [this tutorial](https://webrtc.ventures/2018/08/tutorial-%E2%80%8Bhow-%E2%80%8Bto-%E2%80%8Bbuild-%E2%80%8Ba-%E2%80%8Bvideo-conference-%E2%80%8Bapplication-%E2%80%8Bwith-webrtc-%E2%80%8B-%E2%80%8Bkurento-%E2%80%8Bmedia-%E2%80%8Bserver/) to work with Firefox versions 56+ but I just get an error saying ICE failed (add a TURN server). Upon adding TURN and STUN servers, the error just indicates that ICE failed. Everything works as expected on Chrome.

**Comment by j1elo** [comment]
KMS 6.12.0 added support for the empty candidate that Firefox sends to signal the end of Trickle ICE:

https://doc-kurento.readthedocs.io/en/6.12.0/project/relnotes/v6_12_0.html

This empty candidate had broken ICE gathering between Firefox and Kurento, and is now working fine.

Also, for 6.13 (still a work in progress) we have just now added a new feature: to [specify the external IP to the media server](https://github.com/Kurento/kms-elements/commit/a276bd57bbe15b00f362b62602792047c09e1d27), so it can skip the ICE gathering altogether. This can be useful in virtual environments or some cloud providers such as AWS.

Please open a new issue if there are still problems after having tried the latest versions of Kurento and Firefox.

**Comment by akashiice** [comment]
Hi @j1elo ,

We are getting the same issue while streaming group call over  mozilla firefox latest version although it is working fine with chrome browser. Below is the error that we are getting while using group call feature in mozilla firefox:

ice failed, add a TURN server and see about:webrtc

Kurento Media server: 6.13 Latest

Please help/suggest as we already tried all of the suggestions given over internet.

**Comment by j1elo** [comment]
You probably need to configure a STUN or TURN server, here you can read more: [When is STUN needed?](https://doc-kurento.readthedocs.io/en/latest/user/faq.html#when-is-stun-needed).

Also don't resurrect old topics that were already closed. Read the [Documents about STUN/TURN](https://doc-kurento.readthedocs.io/en/latest/user/faq.html#readings-about-nat-ice-stun-turn) and if you still have questions, use the [Kurento forums](https://groups.google.com/forum/#!forum/kurento).
