### ISSUE TITLE
Segmentation fault when adding a new stream source

### ISSUE THREAD

**Issue by davidertel** [Kurento/bugtracker#168]
When running KMS with our custom application server, we connect a remote client and video and audio are indeed flowing correctly. We then enable screen sharing on the client which adds a new local stream source. I see no messages being sent to KMS through our application server, KMS just  segmentation faults and dies. Our application server continues to run but obviously the socket connection dies.

the logs from the application server show the following
May05 10:58:05.817 [nioEventLoopGroup-2-1] INFO  [ient.JsonRpcClientNettyWebSocket] - [KurentoClient]  channel closed
May05 10:58:05.823 [nioEventLoopGroup-4-1] INFO  [ient.JsonRpcClientNettyWebSocket] - [KurentoClient]  Inititating new Netty channel. Will create new handler too!
May05 10:58:05.849 [AbstractJsonRpcClientWebSocket-disconnectExec-e3-t0] WARN  [t.AbstractJsonRpcClientWebSocket] - [KurentoClient]  Exception trying to reconnect to server 

**KMS Version**:
Version: 6.6.1
Found modules:
	Module: 'core' version '6.6.1'
	Module: 'elements' version '6.6.1'
	Module: 'filters' version '6.6.1'

**Other libraries versions**:
dpkg -l | egrep -i "kurento|gstreamer|nice
ii  gir1.2-gst-plugins-base-1.0                           1.2.4-1~ubuntu1                                     amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.0                                  1.2.4-0ubuntu1                                      amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer0.10-alsa:amd64                              0.10.36-1.1ubuntu2                                  amd64        GStreamer plugin for ALSA
ii  gstreamer0.10-nice:amd64                              0.1.4-1                                             amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer0.10-plugins-base:amd64                      0.10.36-1.1ubuntu2                                  amd64        GStreamer plugins from the "base" set
ii  gstreamer0.10-plugins-base-apps                       0.10.36-1.1ubuntu2                                  amd64        GStreamer helper programs from the "base" set
ii  gstreamer0.10-plugins-good:amd64                      0.10.31-3+nmu1ubuntu5                               amd64        GStreamer plugins from the "good" set
ii  gstreamer0.10-pulseaudio:amd64                        0.10.31-3+nmu1ubuntu5                               amd64        GStreamer plugin for PulseAudio
ii  gstreamer0.10-tools                                   0.10.36-1.2ubuntu3                                  amd64        Tools for use with GStreamer
ii  gstreamer0.10-x:amd64                                 0.10.36-1.1ubuntu2                                  amd64        GStreamer plugins for X11 and Pango
ii  gstreamer1.0-alsa:amd64                               1.2.4-1~ubuntu1                                     amd64        GStreamer plugin for ALSA
ii  gstreamer1.0-clutter                                  2.0.8-1build1                                       amd64        Clutter PLugin for GStreamer 1.0
ii  gstreamer1.0-nice:amd64                               0.1.4-1                                             amd64        ICE library (GStreamer plugin)
ii  gstreamer1.0-plugins-base-apps                        1.2.4-1~ubuntu1                                     amd64        GStreamer helper programs from the "base" set
ii  gstreamer1.0-plugins-good:amd64                       1.2.4-1~ubuntu1                                     amd64        GStreamer plugins from the "good" set
ii  gstreamer1.0-pulseaudio:amd64                         1.2.4-1~ubuntu1                                     amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.0-tools                                    1.2.4-0ubuntu1                                      amd64        Tools for use with GStreamer
ii  gstreamer1.0-x:amd64                                  1.2.4-1~ubuntu1                                     amd64        GStreamer plugins for X11 and Pango
ii  gstreamer1.5-libav:amd64                              1.8.2.1~20160909143244.96.g493eee4.trusty           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                               0.1.13.1~20160909144510.80.gd9ef50e.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64                        1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64                       1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64                       1.8.1.1~20160909143047.112.g9ee4248.trusty          amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64                       1.8.1.1~20160909192513.89.g2685b0f.trusty           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64                         1.8.1.1~20160909143047.112.g9ee4248.trusty          amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                                  1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                          6.6.1.20160930110533.trusty                         amd64        Kurento core module
ii  kms-elements-6.0                                      6.6.1.20160930122545.trusty                         amd64        Kurento elements module
ii  kms-filters-6.0                                       6.6.1.20160930131150.trusty                         amd64        Kurento filters module
ii  kms-jsonrpc-1.0                                       1.1.1.trusty                                        amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                            1.6.3~20160909143252.40.gd78deb7.trusty             amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                              6.6.1.20160930143513.trusty                         amd64        Kurento Media Server
ii  libclutter-gst-2.0-0:amd64                            2.0.8-1build1                                       amd64        Open GL based interactive canvas library GStreamer elements
ii  libgstreamer-plugins-bad1.5-0:amd64                   1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base0.10-0:amd64                 0.10.36-1.1ubuntu2                                  amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-0:amd64                  1.2.4-1~ubuntu1                                     amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-0:amd64                  1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-good1.0-0:amd64                  1.2.4-1~ubuntu1                                     amd64        GStreamer development files for libraries from the "good" set
ii  libgstreamer0.10-0:amd64                              0.10.36-1.2ubuntu3                                  amd64        Core GStreamer libraries and elements
ii  libgstreamer1.0-0:amd64                               1.2.4-0ubuntu1                                      amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0:amd64                               1.8.1.1~20160909144007.170.g0d6031b.trusty          amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                                       0.1.13.1~20160930090742.81.geebfdab.trusty          amd64        ICE library (shared library)
ii  libreoffice-avmedia-backend-gstreamer                 1:4.2.8-0ubuntu2                                    amd64        GStreamer backend for LibreOffice
ii  openwebrtc-gst-plugins                                0.10.0.20160909214034.trusty                        amd64        OpenWebRTC specific GStreamer plugins
ii  totem                                                 3.10.1-1ubuntu4                                     amd64        Simple media player for the GNOME desktop based on GStreamer

**Client libraries**
- Language: home brewed javascript app
- Version:

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: 58.0.3029.96 (64-bit)
- Firefox: NA
- Native: NA

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)
KMS is running inside an Ubuntu docker container on a macbook pro

**What steps will reproduce the problem?**
1. Start a video conference from the UI, create a pipeline, webRTCendpoint that connects to itself as a loopback, create a recorder endpoint and connect it to the webRTCEndpoint. When switching to screen sharing the issue occurs. The enabling of screen sharing on our client causes it to add a new stream source locally. I don't see any messages getting sent to KMS about the new source, it just seg faults and dies.  I am trying to track it down further and will add more debug as it becomes available.
2.
3.

**What is the expected result?**
not a segmentation fault
**What happens instead?**
segmentation fault on KMS
**Does it happen with one of the tutorials?**
No this is are custom application server
**Please provide any additional information below.**

**Comment by davidertel** [comment]
bueller bueller bueller

**Comment by ruddell** [comment]
Did you create a new Peer Connection the Screen Sharing stream?  Kurento doesn't support multiple streams in one WebrtcEndpoint

Seems someone had a similar issue on the mailing list a year ago:
> Re-negotiations and multistream, are not supported on WebrtcEndpoint
https://groups.google.com/forum/#!topic/kurento/B0HRH6HQvDk/discussion

**Comment by davidertel** [comment]
Yes we were trying to add another stream to the webrtcendpoint on the kurento server. If KMS doesn't support that, that is something we can work around. But causing a segmentation fault and having the process die because of it? This should be a critical issue

**Comment by davidertel** [comment]
Specifically from the logs the error is below

(kurento-media-server:4032): GLib-CRITICAL **: g_strsplit: assertion 'string != NULL' failed
[31;1mSegmentation fault[0m (thread [33;1m140264246703872[0m, pid [33;1m4032[0m)

pretty hard to split null

**Comment by suldashi** [comment]
I am having the same issue as well, as soon as a client from the browser adds a stream to an established WebRTC connection, the KMS crashes. This bug should be upgraded to the highest priority, as any user of your service will be able to crash your server whenever he wants.

**Comment by j1elo** [comment]
Closing old issues. I believe this should be fixed already; please comment if the issue still happens.
