### ISSUE TITLE
Docker image severely updated

### ISSUE THREAD

**Issue by chauffer** [Kurento/bugtracker#171]
https://hub.docker.com/r/kurento/kurento-media-server/

kurento/kurento-media-server
Last pushed: 9 months ago

**Comment by nordri** [comment]
Copy that!
We expect to relase new KMS docker image within this week.
regards!

**Comment by nenadalm** [comment]
hi. I see that last version in docker is 6.6.0 (https://hub.docker.com/r/kurento/kurento-media-server/tags/), but if I visit documentation (https://doc-kurento.readthedocs.io/en/stable/), it looks like 6.6.1 is newest stable version.

**Comment by nordri** [comment]
Hi there @nenadalm 
Last stable version of KMS is 6.6.3 which is now available on Docker Hub.
Have a nice day.

**Comment by nenadalm** [comment]
thanks.
