### ISSUE TITLE
BaseRtpEndpoint.conf.ini minPort and maxPort configuration is ignored

### ISSUE THREAD

**Issue by a-sync** [Kurento/bugtracker#174]
**KMS Version**:
> Version: 6.6.1
> Found modules:
>         Module: 'core' version '6.6.1'
>         Module: 'elements' version '6.6.1'
>         Module: 'filters' version '6.6.1'

**Other libraries versions**:
> ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial~20160909142943.96.493eee4   amd64        libav plugin for GStreamer
> ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial~20160930090920.81.eebfdab  amd64        ICE library (GStreamer plugin)
> ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial~20160909144829.99.f836e53   amd64        GStreamer plugins from the "bad" set
> ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial~20160909144420.55.7b19cfd   amd64        GStreamer plugins from the "base" set
> ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial~20160909143716.112.9ee4248  amd64        GStreamer plugins from the "good" set
> ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial~20160909143419.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
> ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial~20160909143716.112.9ee4248  amd64        GStreamer plugin for PulseAudio
> ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial~20160909144420.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
> ii  kms-core-6.0                         6.6.1.xenial.20160930114056.0a3f335        amd64        Kurento core module
> ii  kms-elements-6.0                     6.6.1.xenial.20160930123835.39af73b        amd64        Kurento elements module
> ii  kms-filters-6.0                      6.6.1.xenial.20160930140650.18511ab        amd64        Kurento filters module
> ii  kms-jsonrpc-1.0                      1.1.2.xenial.20160930094059.46f4be8        amd64        Kurento jsonrpc library
> ii  kmsjsoncpp                           1.6.3.xenial.20170421092414.d78deb7        amd64        Kurento jsoncpp library
> ii  kurento-media-server-6.0             6.6.1.xenial.20160930143723.f01e888        amd64        Kurento Media Server
> ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial~20160909144829.99.f836e53   amd64        GStreamer development files for libraries from the "bad" set
> ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial~20160909144420.55.7b19cfd   amd64        GStreamer libraries from the "base" set
> ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial~20170403111704.170.0d6031b  amd64        Core GStreamer libraries and elements
> ii  libnice10:amd64                      0.1.13.1.xenial~20160930090920.81.eebfdab  amd64        ICE library (shared library)

**Client libraries**
- Language: Node.js
- Version: kurento-client-js#master

**System description:**
	KMS running as service in a VPS env. connected to VPN or simply running on a development machine.
        _We tried adding kurento/coturn docker service and configuring it on the same host, but that made no difference._

**What steps will reproduce the problem?**
1. uncomment the minPort and maxPort options in /etc/kurento/modules/kurento/BaseRtpEndpoint.conf.ini
eg.: 
`minPort=50000`
`maxPort=65535`
2. restart service
3. make a call

**What is the expected result?**
Kurento should connect to webrtc peers on a port within the configured min and max range.

**What happens instead?**
Kurento is using random ports, even those outside of the given range.

**Does it happen with one of the tutorials?**
Yes.

**Please provide any additional information below.**
The server is accessible to the clients over VPN:
server ip: 192.169.1.1
client ips: 192.168.1.x

**Comment by a-sync** [comment]
:point_right: Bump. :confused:

**Comment by t4deon** [comment]
Any updates on this?

**Comment by evgeny-iteora** [comment]
Bump.

**Comment by peterforgacs** [comment]
Bump

**Comment by f4ndor** [comment]
bump

**Comment by neilyoung** [comment]
bump

**Comment by imranrajjad** [comment]
same problem..port ranges not taking effect on docker-deployment

**Comment by j1elo** [comment]
`minPort` and `maxPort` set the range of _listening ports_, for incoming connections. Is this not working?
If this is really wrong in recent versions of Kurento, please comment or reopen.

**Comment by lhbug** [comment]
docker-deployment port ranges not taking effect?

**Comment by j1elo** [comment]
The port range settings are working fine, including Docker deployments:

```
$ docker run --rm --name kms --network host \
    -e KMS_MIN_PORT=45000 \
    -e KMS_MAX_PORT=45003 \
    kurento/kurento-media-server:latest 2>&1 | grep '"BaseRtpEndpoint":' -A 2
```

==>
```
            "BaseRtpEndpoint": {
                "minPort": "45000",
                "maxPort": "45003",
```

And any SDP Offer or Answer generated by KMS will include ports only in that range.

**Comment by Trolldemorted** [comment]
Are you sure?

With this docker-compose file:
```
  kurento-media-server:
    image: kurento/kurento-media-server
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5000
```

my KMS sometimes establishes connections from 5001:
```
sudo tcpdump -i any not port 22 and host CLIENTIP
[...]
23:07:59.443549 IP 172.20.0.2.5001 > CLIENTIP.6130: UDP, length 88
```

No log output suggests an error with the configuration:
```
kurento-media-server_1  | 0:00:00.055888474     1 0x562dd0a53670 INFO       KurentoLoadConfig loadConfig.cpp:271:loadConfig: Loaded config in effect:
kurento-media-server_1  | {
[...]
kurento-media-server_1  |             "BaseRtpEndpoint": {
kurento-media-server_1  |                 "minPort": "5000",
kurento-media-server_1  |                 "maxPort": "5000",
kurento-media-server_1  |                 "configPath": "\/etc\/kurento\/modules\/kurento"
kurento-media-server_1  |             },
```

What can I do to make KMS use only one port? I got to admit this was easier with the jitsi video bridge :P
