### ISSUE TITLE
KMS crashed while one to many broadcasting with error segmentation fault in KMS error.log

### ISSUE THREAD

**Issue by manojverma086** [Kurento/bugtracker#175]
**KMS Version**:
6.5.0

**kurento-client**:
"6.2.0"

** Other libraries versions
gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server**:

**Client libraries**
- Language: < Node.js, JavaScript>
- Version: v0.10.36

**Browsers tested**
- Chrome: Fail
- Firefox: Fail

**System description:**
	KMS is located on our server and we are using stun server 
stunServerAddress=74.125.23.127
stunServerPort=19302 

**What steps will reproduce the problem?**
1. We are not able to reproduce the problem

**What is the expected result?**
We were broadcasting video call among 24 students with one presenter and initially, all was going well but after 30 mins KMS crashed.

**What happens instead?**
We didn't get any node error on our server. Kurento was taking very high CPU. There were some errors in KMS log file error.log

Here is snapshot of log file:

[34;1m[gst_base_src_wait_playing] [0m
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0 [32;1m:0x2FB65 [0m
 [34;1m[gst_tag_setter_get_tag_merge_mode] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x9FD7E [0m
 
(kurento-media-server:596): GLib-CRITICAL **: g_ascii_strcasecmp: assertion 's1 != NULL' failed

(kurento-media-server:596): GLib-CRITICAL **: g_ascii_strcasecmp: assertion 's1 != NULL' failed

(kurento-media-server:596): GLib-CRITICAL **: g_ascii_strcasecmp: assertion 's1 != NULL' failed

(kurento-media-server:596): GLib-CRITICAL **: g_ascii_strcasecmp: assertion 's1 != NULL' failed
 [31;1mSegmentation fault [0m (thread  [33;1m140420464244480 [0m, pid  [33;1m596 [0m)
Stack trace:
 [34;1m[SSLv3_client_method] [0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0 [32;1m:0x23C4E [0m
 [34;1m[SSL_check_chain] [0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0 [32;1m:0x33E87 [0m
 [32;1m0xCBA2 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0xECEC [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0x61C1 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0x644A [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [32;1m0x9550 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [34;1m[gst_proxy_pad_chain_default] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x5F18B [0m
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [34;1m[gst_base_src_wait_playing] [0m
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0 [32;1m:0x2FB65 [0m
 [34;1m[gst_tag_setter_get_tag_merge_mode] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x9FD7E [0m
  [31;1mSegmentation fault [0m (thread  [33;1m139847204787968 [0m, pid  [33;1m25462 [0m)
Stack trace:
 [34;1m[SSLv3_client_method] [0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0 [32;1m:0x23C4E [0m
 [34;1m[SSL_check_chain] [0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0 [32;1m:0x33E87 [0m
 [32;1m0xCBA2 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0xECEC [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0x61C1 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0x644A [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [32;1m0x9550 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [34;1m[gst_proxy_pad_chain_default] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x5F18B [0m
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [34;1m[gst_base_src_wait_playing] [0m
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0 [32;1m:0x2FB65 [0m
 [34;1m[gst_tag_setter_get_tag_merge_mode] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x9FD7E [0m
  [31;1mSegmentation fault [0m (thread  [33;1m140234775623424 [0m, pid  [33;1m26227 [0m)
Stack trace:
 [34;1m[SSLv3_client_method] [0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0 [32;1m:0x23C4E [0m
 [34;1m[SSL_check_chain] [0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0 [32;1m:0x33E87 [0m
 [32;1m0xCBA2 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0xECEC [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0x61C1 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [32;1m0x644A [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [32;1m0x9550 [0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [34;1m[gst_proxy_pad_chain_default] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x5F18B [0m
 [34;1m[gst_flow_get_name] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x6DF85 [0m
 [34;1m[gst_pad_push] [0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0 [32;1m:0x75C5E [0m
 [34;1m[gst_base_src_wait_playing] [0m
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0 [32;1m:0x2FB65 [0m
 [34;1m[gst_tag_setter_get_tag_merge_mode] [0m

**Does it happen with one of the tutorials?**
**Please provide any additional information below.**

**Comment by tvandergeer** [comment]
Did you manage to find a solution to this? We're facing the same issue. This is one of the stack traces we got:

^[[31;1mSegmentation fault^[[0m (thread ^[[33;1m140375925704448^[[0m, pid ^[[33;1m25481^[[0m)
Stack trace:
^[[34;1m[SSLv3_client_method]^[[0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0^[[32;1m:0x23CFE^[[0m
^[[34;1m[SSL_check_chain]^[[0m
/lib/x86_64-linux-gnu/libssl.so.1.0.0^[[32;1m:0x34237^[[0m
^[[32;1m0xC9CE^[[0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
^[[32;1m0xEAB1^[[0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
^[[32;1m0x6162^[[0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
^[[32;1m0x63FA^[[0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
^[[34;1m[gst_flow_get_name]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x6E6FF^[[0m
^[[34;1m[gst_pad_push]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x76663^[[0m
^[[32;1m0x94CC^[[0m at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
^[[34;1m[gst_flow_get_name]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x6E6FF^[[0m
^[[34;1m[gst_pad_push]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x76663^[[0m
^[[34;1m[gst_proxy_pad_chain_default]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x5F5E3^[[0m
^[[34;1m[gst_flow_get_name]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x6E6FF^[[0m
^[[34;1m[gst_pad_push]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0x76663^[[0m
^[[34;1m[gst_base_src_wait_playing]^[[0m
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0^[[32;1m:0x30D75^[[0m
^[[34;1m[gst_tag_setter_get_tag_merge_mode]^[[0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0^[[32;1m:0xA0D8B^[[0m
^@

**Comment by tvandergeer** [comment]
I'm reporting my progress on this issue in the Kurento group on Google Groups. See [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kurento/AJdjdJvFmyg)

**Comment by manojverma086** [comment]
No, we have not found any solution so we are using an alternate media server like opentok after the crash of KMS. But we are not able to reproduce this issue again. Maybe it was some issue with the client's machine which causes kms crash.

**Comment by j1elo** [comment]
Lots of fixes and improvements since Kurento 6.5.0. This got probably fixed along the way.
