### ISSUE TITLE
KMS - iOS and Android devices

### ISSUE THREAD

**Issue by renalain** [Kurento/bugtracker#178]
**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

Version: 6.6.1
Found modules:
	Module: 'core' version '6.6.1'
	Module: 'elements' version '6.6.1'
	Module: 'filters' version '6.6.1'

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

ii  gstreamer1.5-libav:amd64                    1.8.2.1.xenial~20160909142943.96.493eee4      amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                     0.1.13.1.xenial~20160930090920.81.eebfdab     amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64              1.8.1.1.xenial~20160909144829.99.f836e53      amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64             1.8.1.1.xenial~20160909144420.55.7b19cfd      amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64             1.8.1.1.xenial~20160909143716.112.9ee4248     amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64             1.8.1.1.xenial~20160909143419.89.2685b0f      amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64               1.8.1.1.xenial~20160909143716.112.9ee4248     amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                        1.8.1.1.xenial~20160909144420.55.7b19cfd      amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                6.6.1.xenial.20160930114056.0a3f335           amd64        Kurento core module
ii  kms-elements-6.0                            6.6.1.xenial.20160930123835.39af73b           amd64        Kurento elements module
ii  kms-filters-6.0                             6.6.1.xenial.20160930140650.18511ab           amd64        Kurento filters module
ii  kms-jsonrpc-1.0                             1.1.2.xenial.20160930094059.46f4be8           amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                  1.6.3.xenial.20170623081130.d78deb7           amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                    6.6.1.xenial.20160930143723.f01e888           amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64         1.8.1.1.xenial~20160909144829.99.f836e53      amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64        1.8.1.1.xenial~20160909144420.55.7b19cfd      amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                     1.8.1.1.xenial~20170403111704.170.0d6031b     amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                             0.1.13.1.xenial~20160930090920.81.eebfdab     amd64        ICE library (shared library)
ii  libreoffice-avmedia-backend-gstreamer       1:5.1.6~rc2-0ubuntu1~xenial2                  amd64        GStreamer backend for LibreOffice

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:

Using: Tutorial 3: Video Call 1 to N with WebRTC

- Chrome: Fail as Viewer on some Android devices, version 59.0.3071.117 (307111700)
- Firefox:
- Native: Fail as Viewer on Safari on iOS 11 Beta 2.

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

Localhost machine, running KMS ver. 6.6.1

Several clients running either on Android or iOS 11 Beta 2

**What steps will reproduce the problem?**
1. Run Kurento Tutorial 3: Video Call 1 to N with WebRTC as _Presenter_
2. Connect several clients as _Viewer_
3.

**What is the expected result?**
It should work fine on any OS running Chrome (apart from iOS  11 Beta 2, running Safari)

**What happens instead?**
- Works ok with laptops / desktops (any OS)
- Works ok with some Android devices but not others (session negotiated but no image comes up or sometimes just first frame)
- Doesn't work with iOS 11 Beta with or without WebRTC legacy enabled.

**Does it happen with one of the tutorials?**
Tutorial 3 - One to many video call 

**Please provide any additional information below.**

**Comment by j1elo** [comment]
Nowadays tutorials work fine with recent versions of Android and iOS. Note that iOS 12.x had bugs, recommended version is iOS 13.
