### ISSUE TITLE
Can't record composite hub

### ISSUE THREAD

**Issue by TF-Michael** [Kurento/bugtracker#18]
I'm getting this error when I try to create a recording from a composite hub:

Error occured in media pipeline: Internal data flow error. -> gstbasesrc.c(2943): gst_base_src_loop (): /GstPipeline:pipeline32/KmsCompositeMixer:kmscompositemixer14/GstVideoTestSrc:videotestsrc14:
streaming task paused, reason not-negotiated (-4) 1 UNEXPECTED_PIPELINE_ERROR

Sample Reproduction Code:

callerWebRtcEP.connect(calleeWebRtcEP);
calleeWebRtcEP.connect(callerWebRtcEP);
			
composite = new Composite.Builder(pipeline).build();
			
calleeHubPort = new HubPort.Builder(composite).build();
callerHubPort = new HubPort.Builder(composite).build();
			
calleeWebRtcEP.connect(calleeHubPort);
callerWebRtcEP.connect(callerHubPort);
			
callerHubPort.connect(recorderEP);

recorderEP.record();

**Comment by dfernandezlop** [comment]
We are working on fix this problem. We will try to upload a patch as soon as possible.

Thanks for the report.
Best.

**Comment by dfernandezlop** [comment]
Hi,

Sorry for the delay. We are still working on that. A change in GStreamer caps has affected to the link of some of our elements. We are close to get a solution.

**Comment by dfernandezlop** [comment]
This problem was fixed. Is it your code working?

**Comment by TF-Michael** [comment]
Yes. We are currently recording in this manner using version 6.3.0.

**Comment by dfernandezlop** [comment]
Ok. I'm going to close this bug.

Thanks!

**Comment by sshsun1990** [comment]
Hello, where can I find this submission
