### ISSUE TITLE
DTLS Handshake is not suceeding for helloworld program on docker, loopback call is not through 4 out of 5 time on average

### ISSUE THREAD

**Issue by tarun-iitd** [Kurento/bugtracker#180]
**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running
Version: 6.6.1
Found modules:
        Module: 'core' version '6.6.1'
        Module: 'elements' version '6.6.1'
        Module: 'filters' version '6.6.1'

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
Java, hello world loopback 
Kurento Java Tutorial - Hello World 6.6.0
- Version:
Kurento Java Tutorial - Hello World 6.6.0

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:  OK for 1 out of 5 time helloworld loopback call
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

**What steps will reproduce the problem?**
1. Install Kurento media server 6.6.1 on docker 
2. Start the KMS. 
3. run hello world loopback program

**What is the expected result?**
Loopback call should be sucessful all the time on docker KMS 6.6.1

**What happens instead?**
First while staring KMS, one error is coming 
service kurento-media-server-6.0 start
/etc/init.d/kurento-media-server-6.0: 20: ulimit: error setting limit (Operation not permitted)
 * Starting Kurento Media Server

Next while making loopback call from browser, one out of 4/5 call is sucessful.
Here i found that DTLS handshake is failing when call is not sucessful.
**Does it happen with one of the tutorials?**

**Please provide any additional information below.**
somewhere on blog, i read it was issue of openssl. below is openssl version.
OpenSSL 1.0.1f 6 Jan 2014 (Library: OpenSSL 1.0.2g-fips  1 Mar 2016)

Even i tried with KMS 6.5 but then also helloworld call was sucessful. then i moved to KMS 6.6.1

**Comment by cutty201** [comment]
Im having a similar problem, Not sure where to begin debugging.

**Comment by petergerten** [comment]
@tarun-iitd Any hints on where to look further?

**Comment by petergerten** [comment]
Could anyone figure out this problem? I am stuck with it since weeks now. I don't know where to begin debugging.

**Comment by crfeliz** [comment]
Was this solved? I'm running into the same issue.

**Comment by crfeliz** [comment]
Switching to the `xenial-latest` docker image fixed this for me. The problem for me was that openssl version was too old on the `trusty-latest` image.

**Comment by j1elo** [comment]
OpenSSL has been updated and Docker images should work fine now.
