### ISSUE TITLE
kurento callback not called in one2many tutorial

### ISSUE THREAD

**Issue by ZenPylon** [Kurento/bugtracker#183]
**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

libdc1394 error: Failed to initialize libdc1394
Version: 6.6.1
Found modules:
        Module: 'core' version '6.6.1'
        Module: 'elements' version '6.6.1'
        Module: 'filters' version '6.6.1'

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for G
Streamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStre
amer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins 
from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins 
from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins 
from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins 
from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin f
or PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins 
for X11 and Pango
ii  kms-core-6.0                         6.6.1.20160930110533.trusty                amd64        Kurento core modul
e
ii  kms-elements-6.0                     6.6.1.20160930122545.trusty                amd64        Kurento elements m
odule
ii  kms-filters-6.0                      6.6.1.20160930131150.trusty                amd64        Kurento filters mo
dule
ii  kms-jsonrpc-1.0                      1.1.2.20160930094018.trusty                amd64        Kurento jsonrpc li
brary
ii  kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp li
brary
ii  kurento-media-server-6.0             6.6.1.20160930143513.trusty                amd64        Kurento Media Serv
er
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer developm
ent files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer librarie
s from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer lib
raries and elements
ii  libnice10:amd64                      0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (share
d library)

**Client libraries**
- Language: Node.js, JavaScript
- Version: node -v --> v.4.8.4

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: FAIL
- Firefox: FAIL
- Native: N/A

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

The KMS server is located on a Google Compute Engine instance which is accessed through the domain notingonmymind.com  (temporary URL I URL I happen to own).  

**What steps will reproduce the problem?**
Here's what I did:
1.  Install kurento media server
2. Create SSL cert/key with let's encrypt, concatenate cert.pem with privkey.pem into cert_key.pem
3. Enable SSL in /etc/kurento/kurento.conf.json on port 8433, using cert_key.pem
4. Run `npm start` in kurento-tutorial-node/kurento-one2many-call
5. Connect via browser
6  Hit "presenter" button

**What is the expected result?**
The one2many server.js should process connections correctly.

**What happens instead?**
kurento() is called on line [Line 158](https://github.com/ZenPylon/kurento-tutorial-node/blob/master/kurento-one2many-call/server.js), but the callback is never fired.

Then I get messages like these:

reconnect to server 3 300 undefined
reconnect to server 4 500 undefined
reconnect to server 5 800 undefined

Something similar happened [here](https://github.com/Kurento/bugtracker/issues/109), but as best I can tell, my config is correct in server.js and index.js 

**Does it happen with one of the tutorials?**
Yes

**Please provide any additional information below.**

On server.js, the uri's are set to

        as_uri: 'https://localhost:8443/',
        ws_uri: 'wss://localhost:8433/kurento'

The kurento logs don't show anything suspicious.  Initially, they complained about a missing private key, which is then corrected by concatenating the cert.pem and privkey.pem files.  I wonder about the error "libdc1394 error: Failed to initialize libdc1394", though.

Any help would be much appreciated.  Thanks!

**Comment by goroya** [comment]
Me too

**Comment by devWaleed** [comment]
Same here. I get reconnect to server error as well in server console

**Comment by j1elo** [comment]
https://doc-kurento.readthedocs.io/en/latest/features/security.html
and the instructions on the tutorials have been updated to cover the usage of certificates. All tutorials should now work correctly.

If that's not the case please comment here / reopen / open a new issue.
