### ISSUE TITLE
Library gstreamer-sctp-1.5 not found

### ISSUE THREAD

**Issue by wisherzhang** [Kurento/bugtracker#184]
**What steps will reproduce the problem?**
1.git clone https://github.com/Kurento/kms-elements.git
2.make -p build
3.cd build 
4.cmake ../

**What is the expected result?**
no error!
**What happens instead?**

-- gstreamer-sdp-1.5 Already found
-- gstreamer-rtp-1.5 Already found
-- gstreamer-pbutils-1.5 Already found
-- checking for module 'gstreamer-sctp-1.5'
--   package 'gstreamer-sctp-1.5' not found
CMake Error at /usr/share/cmake-2.8/Modules/GenericFind.cmake:131 (message):
  Library gstreamer-sctp-1.5 not found
Call Stack (most recent call first):
  CMakeLists.txt:73 (generic_find)

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by Necromantos** [comment]
Hi!

follow this:
git clone https://github.com/Kurento/openwebrtc-gst-plugins.git
cd openwebrtc-gst-plugins/
sh autogen.sh 
./configure
make
make install

best regards!
