### ISSUE TITLE
Renegotiation in Kurento Media Server

### ISSUE THREAD

**Issue by krish-dev** [Kurento/bugtracker#189]
How does renegotiation work with Kurento? I want to switch camera stream to screen stream while calling in the process from the presenter and want to record the full session as a single file.

**Comment by micaelgallego** [comment]
WebRTC renegotiation is not implemented in KMS.

ElasticRTC is no longer available as a product.

Regards

**Comment by brunsy** [comment]
@micaelgallego Is there somewhere we can add a note about this to the docs?

**Comment by shubhddn01** [comment]
Any update?

**Comment by brunsy** [comment]
@shubhddn01 still not supported (and still not in the docs)

**Comment by micaelgallego** [comment]
If you want to record camera and switch to screenshare you can do it changing media source at browser level. Renegotiation is not needed in this use case.

**Comment by brunsy** [comment]
@micaelgallego Would you accept a PR to the docs to show it is unsupported?

A couple of cases we have had to add workarounds for it are: 
Clients changing networks (coming in/out of wifi).
Adding video after an audio call has already been established.

**Comment by micaelgallego** [comment]
We are working on SipRtpEndpoint, a new RtpEndpoint supporting a reset-and-reconnect re-negotiation. Maybe it can help you.

**Comment by j1elo** [comment]
Note however the experimental SipRtpEndpoint mentioned here (https://github.com/Kurento/kms-elements/pull/21) is only meant to implement renegotiation for SIP phones that adhere to the SIP 183 standard.

Kurento does not support SDP Offer/Answer renegotiation as commonly known for WebRTC. You'd have to re-create the WebRtcEndpoint (or RtpEndpoint) for that.

Closing this as not-a-bug. Feel free to reopen if you think otherwise.

**Comment by logcy** [comment]
> We are working on SipRtpEndpoint, a new RtpEndpoint supporting a reset-and-reconnect re-negotiation. Maybe it can help you.
> 
> [Kurento/kms-elements#21](https://github.com/Kurento/kms-elements/pull/21)

Hello, can you tell me what you do? How to get the code that supports sip, how to compile and how to run?
