### ISSUE TITLE
setMaxVideoxxx to 0 does not set unlimited upper values, and there is a typo in setMaxOuputBitrate

### ISSUE THREAD

**Issue by hunternet93** [Kurento/bugtracker#19]
I'm trying to stream with a high bitrate, but no matter what I do Kurento (6.2.0) always sets `target-bitrate` to 300000 on the encoder. Here's my latest attempt:

        viewer.element = create('WebRtcEndpoint');
        viewer.element.setMaxVideoRecvBandwidth(0);
        viewer.element.setMaxVideoSendBandwidth(0);
        viewer.element.setMinVideoRecvBandwidth(1000);
        viewer.element.setMinVideoSendBandwidth(1000);
        viewer.element.setMaxOuputBitrate(1000000);

Oddly enough, the property `max-output-bitrate` gets correctly set to 1000000 on the KmsWebrtcEndpoint bin, but that doesn't seem to affect vp8enc. The setMin/MaxVideoSend/RecvBandwidth family of functions appear to have to effect whatsoever as far as I can tell.

Also, `setMaxOuputBitrate` should probably be spelled `setMaxOutputBitrate`, unless I'm missing something.

**Comment by igracia** [comment]
I think you are using it wrong. Could you explain what's the expected behavior, and describe your pipeline? If you want to exchange higher rate video between two endpoints, you need to `setMaxOutputBitrate` in the source. That means that if you have a presenter, you'd do something like this
```Java
presenter.setMaxOutputBitrate(1000000);
presenter.connect(viewer);
```
As for the other parameters, at this moment setting 0 as the max value, is not setting unlimited bandwidth. We've opened a bug about that, and it shouldn't take long. In the mean time, set a ridiculously high value in those max settings if you want unlimited bandwidth.

One more thing, it is important that those `setMax` and `setMin` are done before the negotiation of SDPs takes place, or they will have no effect. We are also working on fixing that.

**Comment by igracia** [comment]
@mparis You already filed the internal bug, but just for traceability I'm assigning this here, too.

**Comment by hunternet93** [comment]
I'm streaming from an h.264 RTSP source (using PlayerEndpoint) to a WebRTC endpoint. I just tried `setMaxOutputBitrate` on the PlayerEndpoint, but it didn't change the encoder's `target-bitrate`.

Here's a PDF (because GitHub won't let me upload SVG) of the pipeline's GstreamerDot: [rtsp-to-webrtc-vp8-incorrect-bitrate.pdf](https://github.com/Kurento/bugtracker/files/65626/rtsp-to-webrtc-vp8-incorrect-bitrate.pdf)

[SDP of the WebRTC connection](https://gist.github.com/hunternet93/830068d9bc5dec63c97c)

**Comment by hunternet93** [comment]
Just dug through the code a bit, setMaxOuputBitrate sets the the element's MAX_OUTPUT_BITRATE and MAX_OUTPUT_BITRATE GObject properties. Oddly enough, I couldn't find any other mentions of those constants except for their #defines, is setMaxOuputBitrate just a no-op at the moment? If so, it should probably be mentioned in the docs.

**Comment by hunternet93** [comment]
After poking around a bit, I found something odd in kmsenctreebin.c:

    #define KMS_ENC_TREE_BIN_LIMIT(obj, value) \
      MAX((obj)->priv->min_bitrate,MIN((obj)->priv->max_bitrate, (value)))

That seems a bit off, it means that if max_bitrate is greater than the default target bitrate (from kmsagnosticbin.c), then target-bitrate is set to the default instead of the user-defined target. 

Maybe instead kms_enc_tree_bin_new should only take min_bitrate and max_bitrate arguments, and use max_bitrate as the target bitrate.

**Comment by igracia** [comment]
@mparis  Could you please check this?

**Comment by jcaden** [comment]
I'll review this

**Comment by dfernandezlop** [comment]
Hi,

In the last KMS release (6.5.0) we have fixed the wrong behaviour of the properties and typos in properties.

Thanks for the report.
