### ISSUE TITLE
Unable to install Kurento Media Server

### ISSUE THREAD

**Issue by sampleref** [Kurento/bugtracker#190]
I tried to install Kurento Media Server based on instructions at 
http://doc-kurento.readthedocs.io/en/stable/installation_guide.html

Only thing I changed is from trusty to xenial for Ubuntu 16.04
echo "deb http://ubuntu.kurento.org xenial kms6" | sudo tee /etc/apt/sources.list.d/kurento.list

I am facing below error for command:
sudo apt-get install kurento-media-server-6.0

As:
_root@user:/home/user# apt-get install kurento-media-server-6.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0 libfluidsynth1
  libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0 libmpeg2encpp-2.1-0
  libmpg123-0 libmplex2-2.1-0 libnice10 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0 libvo-amrwbenc0
  libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
Suggested packages:
  frei0r-plugins libvisual-0.4-plugins gstreamer1.5-tools sidplay-base srtp-utils
The following NEW packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  kurento-media-server-6.0 libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0
  libfluidsynth1 libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0
  libvo-amrwbenc0 libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
The following packages will be upgraded:
  libnice10
1 upgraded, 42 newly installed, 0 to remove and 38 not upgraded.
Need to get 44.9 MB of archives.
After this operation, 90.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libwildmidi-config all 0.3.8-2 [7,378 B]
Get:2 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libwildmidi1 amd64 0.3.8-2 [38.3 kB]
Get:3 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libvo-aacenc0 amd64 0.1.3-1 [71.0 kB]
Get:4 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libvo-amrwbenc0 amd64 0.1.3-1 [66.4 kB]
Get:5 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 freepats all 20060219-1 [29.0 MB]
Get:6 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libmpg123-0 amd64 1.22.4-1 [124 kB]
Get:7 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libsidplay1v5 amd64 1.36.59-8 [63.6 kB]
Get:8 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libde265-0 amd64 1.0.2-2 [234 kB]
Get:9 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libfluidsynth1 amd64 1.1.6-3 [130 kB]
Get:10 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libmimic0 amd64 1.0.4-2.3 [15.0 kB]
Get:11 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libmjpegutils-2.1-0 amd64 1:2.1.0+debian-4 [24.6 kB]
Get:12 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libmms0 amd64 0.6.4-1 [27.4 kB]
Get:13 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libmpeg2encpp-2.1-0 amd64 1:2.1.0+debian-4 [70.5 kB]
Get:14 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libmplex2-2.1-0 amd64 1:2.1.0+debian-4 [44.2 kB]
Get:15 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libofa0 amd64 0.9.3-10ubuntu1 [50.3 kB]
Get:16 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libsoundtouch1 amd64 1.9.2-2 [39.8 kB]
Get:17 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libspandsp2 amd64 0.0.6-2.1 [273 kB]
Get:18 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 libzbar0 amd64 0.10+doc-10ubuntu1 [75.6 kB]
Get:19 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libboost-regex1.58.0 amd64 1.58.0+dfsg-5ubuntu3.1 [261 kB]
Get:20 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libboost-thread1.58.0 amd64 1.58.0+dfsg-5ubuntu3.1 [47.0 kB]
Get:21 http://in.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 libboost-log1.58.0 amd64 1.58.0+dfsg-5ubuntu3.1 [422 kB]
Get:22 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libboost-program-options1.58.0 amd64 1.58.0+dfsg-5ubuntu3.1 [138 kB]
66% [Waiting for headers]^C
root@drone:/home/drone# apt-get install kurento-media-server-6.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0 libfluidsynth1
  libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0 libmpeg2encpp-2.1-0
  libmpg123-0 libmplex2-2.1-0 libnice10 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0 libvo-amrwbenc0
  libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
Suggested packages:
  frei0r-plugins libvisual-0.4-plugins gstreamer1.5-tools sidplay-base srtp-utils
The following NEW packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  kurento-media-server-6.0 libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0
  libfluidsynth1 libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0
  libvo-amrwbenc0 libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
The following packages will be upgraded:
  libnice10
1 upgraded, 42 newly installed, 0 to remove and 38 not upgraded.
Need to get 13.7 MB/44.9 MB of archives.
After this operation, 90.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ubuntu.kurento.org xenial/kms6 amd64 libgstreamer1.5-0 amd64 1.8.1.1.xenial~20170725152356.170.0d6031b [967 kB]
68% [Waiting for headers]^C
root@drone:/home/drone# apt-get install kurento-media-server-6.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0 libfluidsynth1
  libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0 libmpeg2encpp-2.1-0
  libmpg123-0 libmplex2-2.1-0 libnice10 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0 libvo-amrwbenc0
  libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
Suggested packages:
  frei0r-plugins libvisual-0.4-plugins gstreamer1.5-tools sidplay-base srtp-utils
The following NEW packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  kurento-media-server-6.0 libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0
  libfluidsynth1 libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0
  libvo-amrwbenc0 libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
The following packages will be upgraded:
  libnice10
1 upgraded, 42 newly installed, 0 to remove and 38 not upgraded.
Need to get 12.8 MB/44.9 MB of archives.
After this operation, 90.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://ubuntu.kurento.org xenial/kms6 amd64 libgstreamer-plugins-base1.5-0 amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd
  Connection failed
68% [Waiting for headers]^C
root@drone:/home/drone# apt-get install kurento-media-server-6.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0 libfluidsynth1
  libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0 libmpeg2encpp-2.1-0
  libmpg123-0 libmplex2-2.1-0 libnice10 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0 libvo-amrwbenc0
  libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
Suggested packages:
  frei0r-plugins libvisual-0.4-plugins gstreamer1.5-tools sidplay-base srtp-utils
The following NEW packages will be installed:
  freepats gstreamer1.5-libav gstreamer1.5-nice gstreamer1.5-plugins-bad gstreamer1.5-plugins-base gstreamer1.5-plugins-good
  gstreamer1.5-plugins-ugly gstreamer1.5-pulseaudio gstreamer1.5-x kms-core-6.0 kms-elements-6.0 kms-filters-6.0 kms-jsonrpc-1.0 kmsjsoncpp
  kurento-media-server-6.0 libboost-log1.58.0 libboost-program-options1.58.0 libboost-regex1.58.0 libboost-thread1.58.0 libde265-0
  libfluidsynth1 libgstreamer-plugins-bad1.5-0 libgstreamer-plugins-base1.5-0 libgstreamer1.5-0 libmimic0 libmjpegutils-2.1-0 libmms0
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libofa0 libsidplay1v5 libsoundtouch1 libspandsp2 libsrtp1 libusrsctp libvo-aacenc0
  libvo-amrwbenc0 libwildmidi-config libwildmidi1 libzbar0 openwebrtc-gst-plugins
The following packages will be upgraded:
  libnice10
1 upgraded, 42 newly installed, 0 to remove and 38 not upgraded.
Need to get 12.8 MB/44.9 MB of archives.
After this operation, 90.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://ubuntu.kurento.org xenial/kms6 amd64 libgstreamer-plugins-base1.5-0 amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd
  Connection failed
Err:2 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-libav amd64 1.8.2.1.xenial~20170725171352.96.493eee4
  Connection failed
Err:3 http://ubuntu.kurento.org xenial/kms6 amd64 libnice10 amd64 0.1.13.1.xenial~20170725160546.81.eebfdab
  Connection failed
Get:4 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-nice amd64 0.1.13.1.xenial~20170725160546.81.eebfdab [26.3 kB]
Get:5 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-plugins-base amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd [527 kB]
Get:6 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-pulseaudio amd64 1.8.1.1.xenial~20170725161537.112.9ee4248 [79.2 kB]
Err:7 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-plugins-good amd64 1.8.1.1.xenial~20170725161537.112.9ee4248
  Connection failed
Err:8 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-plugins-ugly amd64 1.8.1.1.xenial~20170725170621.89.2685b0f
  Connection failed
Get:9 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-x amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd [103 kB]
Get:10 http://ubuntu.kurento.org xenial/kms6 amd64 kmsjsoncpp amd64 1.6.3.xenial.20170725151047.d78deb7 [66.4 kB]
Get:11 http://ubuntu.kurento.org xenial/kms6 amd64 kms-jsonrpc-1.0 amd64 1.2.0.xenial~20170811181902.1.8cee9d8 [23.4 kB]
Err:12 http://ubuntu.kurento.org xenial/kms6 amd64 libgstreamer-plugins-bad1.5-0 amd64 1.8.1.1.xenial~20170725164047.100.3db37b1
  Connection failed
Err:13 http://ubuntu.kurento.org xenial/kms6 amd64 libsrtp1 amd64 1.5.2.1.xenial~20170725145031.11.837f48c
  502  Bad Gateway
Get:14 http://ubuntu.kurento.org xenial/kms6 amd64 gstreamer1.5-plugins-bad amd64 1.8.1.1.xenial~20170725164047.100.3db37b1 [1,463 kB]
Get:15 http://ubuntu.kurento.org xenial/kms6 amd64 kms-core-6.0 amd64 6.6.3.xenial.20170811182512.2704d13 [615 kB]
Get:16 http://ubuntu.kurento.org xenial/kms6 amd64 libusrsctp amd64 0.9.2.1.xenial~20170725150252.8.668b2ba [208 kB]
Get:17 http://ubuntu.kurento.org xenial/kms6 amd64 openwebrtc-gst-plugins amd64 0.10.0.1.xenial~20170725173413.1.33ccf19 [22.7 kB]
Get:18 http://ubuntu.kurento.org xenial/kms6 amd64 kms-elements-6.0 amd64 6.6.3.xenial.20170812234356.9e3fff4 [375 kB]
Err:19 http://ubuntu.kurento.org xenial/kms6 amd64 kms-filters-6.0 amd64 6.7.0.xenial~20170813001324.1.0314843
  Connection failed
Err:20 http://ubuntu.kurento.org xenial/kms6 amd64 kurento-media-server-6.0 amd64 6.7.0.xenial~20170813003033.1.6ebaa27
  Connection failed
Fetched 3,509 kB in 30min 43s (1,903 B/s)
E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/g/gst-plugins-base1.5/libgstreamer-plugins-base1.5-0_1.8.1.1.xenial~20170725154709.55.7b19cfd_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/g/gst-libav1.5/gstreamer1.5-libav_1.8.2.1.xenial~20170725171352.96.493eee4_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/libn/libnice/libnice10_0.1.13.1.xenial~20170725160546.81.eebfdab_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/g/gst-plugins-good1.5/gstreamer1.5-plugins-good_1.8.1.1.xenial~20170725161537.112.9ee4248_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/g/gst-plugins-ugly1.5/gstreamer1.5-plugins-ugly_1.8.1.1.xenial~20170725170621.89.2685b0f_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/g/gst-plugins-bad1.5/libgstreamer-plugins-bad1.5-0_1.8.1.1.xenial~20170725164047.100.3db37b1_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/s/srtp/libsrtp1_1.5.2.1.xenial~20170725145031.11.837f48c_amd64.deb  502  Bad Gateway

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/k/kms-filters-6.0/kms-filters-6.0_6.7.0.xenial~20170813001324.1.0314843_amd64.deb  Connection failed

E: Failed to fetch http://ubuntu.kurento.org/pool/kms6/k/kurento-media-server-6.0/kurento-media-server-6.0_6.7.0.xenial~20170813003033.1.6ebaa27_amd64.deb  Connection failed

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?_

I tried to check one of them, http://ubuntu.kurento.org/pool/kms6/g/gst-plugins-bad1.5/libgstreamer-plugins-bad1.5-0_1.8.1.1.xenial~20170725164047.100.3db37b1_amd64.deb in web browser and its not reachable. 

Is the ubuntu kurento repo down or I am mission something? Please let me know

**Comment by nordri** [comment]
Hello @sampleref 
Everything looks fine here.
Please, check the repo, you wrote _xenail_ instead of xenial
Let me know if i can help you.

**Comment by sampleref** [comment]
Thanks @nordri Its fine now. Also I tired to install from Kurento docker https://github.com/Kurento/kurento-docker/tree/master/kurento-media-server which was also more easy way

Thanks again

**Comment by nordri** [comment]
Glad you finally could make it! @sampleref
