### ISSUE TITLE
KMS 6.7.0, rtp to webrtc h264 video is not working properly on Safari 11

### ISSUE THREAD

**Issue by Absor** [Kurento/bugtracker#193]
**KMS Version**:

Version: 6.7.0\~2.g428fcd9
Found modules:
	Module: 'core' version '6.7.0\~1.g1a05fae'
	Module: 'elements' version '6.7.0\~2.ga478df5'
	Module: 'filters' version '6.7.0\~1.g0314843'

**Other libraries versions**:

ii  gir1.2-gst-plugins-base-1.5            1.8.1.1.xenial\~20170725154709.55.7b19cfd   amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.0                   1.8.3-1\~ubuntu0.1                          amd64        GObject introspection data for the GStreamer library
ii  gir1.2-gstreamer-1.5                   1.8.1.1.xenial\~20170725152356.170.0d6031b  amd64        Description: GObject introspection data for the GStreamer library
ii  gir1.2-nice-0.1:amd64                  0.1.15.xenial\~20170919124012.83.28531a4    amd64        ICE library (GObject introspection)
ii  gstreamer1.0-nice:amd64                0.1.15.xenial\~20170919124012.83.28531a4    amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64               1.8.2.1.xenial\~20170725171352.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                0.1.13.1.xenial\~20170725160546.81.eebfdab  amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64         1.8.1.1.xenial\~20170725164047.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64        1.8.1.1.xenial\~20170725154709.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64        1.8.1.1.xenial\~20170725161537.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64        1.8.1.1.xenial\~20170725170621.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64          1.8.1.1.xenial\~20170725161537.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                   1.8.1.1.xenial\~20170725154709.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-cmake-utils                        1.5.0.xenial\~20170811181647.1.68ec0fc      all          Kurento cmake utils
ii  kms-core-6.0                           6.7.0.xenial\~20170919123208.1.1a05fae      amd64        Kurento core module
ii  kms-core-6.0-dbg                       6.7.0.xenial\~20170919123208.1.1a05fae      amd64        Kurento core module
ii  kms-core-6.0-dev                       6.7.0.xenial\~20170919123208.1.1a05fae      amd64        Kurento core module
ii  kms-elements-6.0                       6.7.0.xenial\~20170919125800.2.a478df5      amd64        Kurento elements module
ii  kms-elements-6.0-dbg                   6.7.0.xenial\~20170919125800.2.a478df5      amd64        Kurento elements module
ii  kms-elements-6.0-dev                   6.7.0.xenial\~20170919125800.2.a478df5      amd64        Kurento elements module
ii  kms-filters-6.0                        6.7.0.xenial\~20170813001324.1.0314843      amd64        Kurento filters module
ii  kms-filters-6.0-dev                    6.7.0.xenial\~20170813001324.1.0314843      amd64        Kurento filters module
ii  kms-jsonrpc-1.0                        1.2.0.xenial\~20170811181902.1.8cee9d8      amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                    1.2.0.xenial\~20170811181902.1.8cee9d8      amd64        Kurento jsonrpc library
ii  kmsjsoncpp                             1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                         1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsonrpc library
ii  kurento-media-server-6.0               6.7.0.xenial\~20170919130225.2.428fcd9      amd64        Kurento Media Server
ii  kurento-media-server-6.0-dbg           6.7.0.xenial\~20170919130225.2.428fcd9      amd64        Debugging symbols for Kurento Media Server
ii  kurento-media-server-6.0-dev           6.7.0.xenial\~20170919130225.2.428fcd9      amd64        Kurento media server, development files and tools
ii  kurento-module-creator-4.0             4.0.8.xenial\~20170725174309.1.9662c2f      all          Kurento module creator
ii  kurento-server                         6.7.0.xenial\~20170919130225.2.428fcd9      amd64        Meta package for kurento server side
ii  libgstreamer-plugins-bad1.5-0:amd64    1.8.1.1.xenial\~20170725164047.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64   1.8.1.1.xenial\~20170725154709.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev       1.8.1.1.xenial\~20170725154709.55.7b19cfd   amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.0-0:amd64                1.8.3-1\~ubuntu0.1                          amd64        Core GStreamer libraries and elements
ii  libgstreamer1.0-dev                    1.8.3-1\~ubuntu0.1                          amd64        GStreamer core development files
ii  libgstreamer1.5-0:amd64                1.8.1.1.xenial\~20170725152356.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                    1.8.1.1.xenial\~20170725152356.170.0d6031b  amd64        GStreamer core development files
ii  libnice-dbg:amd64                      0.1.15.xenial\~20170919124012.83.28531a4    amd64        ICE library (debugging symbols)
ii  libnice-dev                            0.1.15.xenial\~20170919124012.83.28531a4    amd64        ICE library (development files)
ii  libnice-doc                            0.1.15.xenial\~20170919124012.83.28531a4    all          ICE library (documentation)
ii  libnice10:amd64                        0.1.15.xenial\~20170919124012.83.28531a4    amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64     1.8.1.1.xenial\~20170725164047.100.3db37b1  amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                 0.10.0.1.xenial\~20170725173413.1.33ccf19   amd64        OpenWebRTC specific GStreamer plugins
ii  openwebrtc-gst-plugins-dev             0.10.0.1.xenial\~20170725173413.1.33ccf19   amd64        OpenWebRTC specific GStreamer plugins

**Client libraries**
- Language: homebrewed (python)

**Browsers tested**
- Chrome: OKish, Video with frames dropped
- Safari 11: FAIL, all video frames dropped

**System description:**

kurento-media-server is self built from sources, same result can be achieved with packaged kurento.

System is configured for h264 only:

openh264-gst-plugins-bad-1.5 is installed

SdpEndpoint configuration has only H264 in videoCodecs:

```
"videoCodecs" : [
  {
    "name": "H264/90000"
  }
]
```

**What steps will reproduce the problem?**
1. Create elements

* pipeline
* rtpendpoint
* webrtcendpoint
* connect rtpendpoint to webrtcendpoint

2. Negotiate RTP SDP

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
t=0 0
a=tool:libavformat 57.71.100
m=video 54288 RTP/AVP 96
c=IN IP4 34.252.69.59
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
m=audio 52188 RTP/AVP 14
c=IN IP4 34.252.69.59
```

Parse video port from SDP answer.

3. Send video to Kurento

ffmpeg -re -i input.mp4 -an -vcodec libx264 -f rtp rtp://server-ip:port-parsed-from-sdp

4. Negotiate WebRTC and start receiving video on client.

**What is the expected result?**

Video is watchable on clients.

**What happens instead?**

When watching on chrome frames and packets are dropped and video is visible but gets stuck every now and then for a fraction of a second.

When watching on safari 11 (new webrtc with only h264 support) all frames are dropped and no video is visible.

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

RTP to WebRTC h264 video fails to transcode properly or transcoding does not happend (h264 profile to another).

Incoming video to RtpEndpoint is h264 with different profiles depending on source (defined in sdp offer with profile-level-id etc.).

When using recorder to record video locally the recorded video plays flawlessly without any frame drops so incoming video is "understood" properly.

**Comment by chenxiemin** [comment]
I faced the same issue, can anybody help on this?

**Comment by gunjotSinghMansa** [comment]
The basic Hello world (http://doc-kurento.readthedocs.io/en/stable/tutorials/node/tutorial-helloworld.html) is not working for me in Safari 11.

Send and Receive both connections are working fine, but Safari is not receiving own video stream. It is working fine on all other browsers.

I followed all the suggestions:

Replace src with srcObject, while assigning stream.
Installed openh264-gst-plugins-bad-1.5
Replaced all deprecated methods with the new one.
I also tried setting audio to false audio:false

Thoughts:
In this case, sender and receiver streams, both are using H264 encoding and should have worked fine.

Any help!

**Comment by mayeaux** [comment]
I don't think Safari or Edge are supported yet.

**Comment by jlongman** [comment]
@gunjotSinghMansa  can you post what you've done? I was speaking with someone and they suggested that the way `kurento-utils.js` uses MSE/WebRTC _won't_ work with Safari, so maybe your work could be verified and/or expanded on.

**Comment by gabrielmicko** [comment]
We fixed kurento-utils already internally (it's been fixed in the main kurento-utils-js as well, but hasn't been merged), but it won't help fixing this problem.
Safari drops every frame! When using lower resolution it works. Ubuntu 16.04.

**Comment by j1elo** [comment]
Fixed since this issue was reported.

As of today, however, usage of kurento-utils-js is discouraged because, while it has been updated over time, and it works for simple cases, there is no one actively maintaining it.
