### ISSUE TITLE
Docker images healthcheck

### ISSUE THREAD

**Issue by nenadalm** [Kurento/bugtracker#195]
Hi. You dockerfiles can specify healthchecks (https://docs.docker.com/engine/reference/builder/#healthcheck). Maybe it would be good to add something like:

```shell
[[ "$(curl -w '%{http_code}' -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: 127.0.0.1:8888" -H "Origin: 127.0.0.1" http://127.0.0.1:8888/kurento)" == 500 ]] && exit 0 || exit 1
```
?

So that if something happens with Kurento server, it can be automatically restarted?

**Comment by nordri** [comment]
Hi @nenadalm 
Thank you very much for you contribution.
You can find now new images for Kurento Media Server in Docker hub.
Regards
