### ISSUE TITLE
Composite Hub making audio choppy. KMS 6.6.3+

### ISSUE THREAD

**Issue by sebastian-greco** [Kurento/bugtracker#197]
Looks like any audio being passed through the Composite Hub is being broken, the audio breaks and it's all choppy. Even if you only add one source to the Composite Hub, the audio output is broken.
Same happen if you mix multiple streams.
I narrowed this down till a point where I'm sure it's a problem in the server not my code nor the streams I'm using. Using the [Java Client Integration Test CompositeAudioRecorderTest](https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/test/functional/composite/CompositeAudioRecorderTest.java) makes a broken output.
This is the output that that test makes:
[VideoExample.webm](https://drive.google.com/file/d/0B81Kw_Wkxl7nWXNsbFdBMHlueGs/view?usp=sharing)

I have also created my own test method because at some point those videos weren't working, that test can be found here:
https://gist.github.com/sebastian-greco/aea6a6b8c7147ea6d8e44dca9711f698

**I have downgraded to 6.6.1 and it's working fine there.**

**KMS Version**: 
Version: 6.7.0\~1.g6ebaa27
Found modules:
        Module: 'core' version '6.6.3'
        Module: 'elements' version '6.6.3'
        Module: 'filters' version '6.7.0~1.g0314843'

**Other libraries versions**:

```
ii  gstreamer1.5-libav:amd64                    1.8.2.1.xenial~20170725171352.96.493eee4     amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                     0.1.13.1.xenial~20170725160546.81.eebfdab    amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64              1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64             1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64             1.8.1.1.xenial~20170725161537.112.9ee4248    amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64             1.8.1.1.xenial~20170725170621.89.2685b0f     amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64               1.8.1.1.xenial~20170725161537.112.9ee4248    amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                        1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                6.6.3.xenial.20170811182512.2704d13          amd64        Kurento core module
ii  kms-elements-6.0                            6.6.3.xenial.20170812234356.9e3fff4          amd64        Kurento elements module
ii  kms-filters-6.0                             6.7.0.xenial~20170813001324.1.0314843        amd64        Kurento filters module
ii  kms-jsonrpc-1.0                             1.2.0.xenial~20170811181902.1.8cee9d8        amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                  1.6.3.xenial.20170725151047.d78deb7          amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                    6.7.0.xenial~20170813003033.1.6ebaa27        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64         1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64        1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                     1.8.1.1.xenial~20170725152356.170.0d6031b    amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                             0.1.13.1.xenial~20170725160546.81.eebfdab    amd64        ICE library (shared library)
```
**Client libraries**
- Language: Java
- Version: 6.6.3

**Browsers tested**
Not related

**System description:**
KMS mounted on Digital Ocean, no NAT, so no need of any other instalation, networking works just fine.

**What steps will reproduce the problem?**
1. Run the [Java Client Integration Test CompositeAudioRecorderTest](https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/test/functional/composite/CompositeAudioRecorderTest.java)
2. Open the output video
3. Contemplate the broken audio
or
1. Run my [test method ](https://gist.github.com/sebastian-greco/aea6a6b8c7147ea6d8e44dca9711f698)
2. Open the output video located at `/var/kurento/test2.webm`
3. Contemplate the broken audio

**What is the expected result?**
Audio from the Composite Hub should be clean and sharp.

**What happens instead?**
Audio is broken, like this:
[VideoExample.webm](https://drive.google.com/file/d/0B81Kw_Wkxl7nWXNsbFdBMHlueGs/view?usp=sharing)

**Does it happen with one of the tutorials?**
There are no tutorials for composite hub. But as already pointed, it does happen with the Java Integration Test.

**Please provide any additional information below.**
This works fine in versions `6.5.0`, `6.6.0` and `6.6.1`.
I haven't been able to install `6.6.2` because of dependency problems while trying to get `deb http://ubuntu.kurento.org/6.6.2 xenial kms6`
(in fact that dependency problem also happens with 6.6.1 but luckily I had and old kurento image with that installation from a few months ago)

**Comment by mariogasparoni** [comment]
I can confirm the audio also works fine in version 6.6.2

Apparently, this is being caused by d25a8cfac429a4da7584ef41290046468c4b5904

**Comment by sebastian-greco** [comment]
I can confirm what @mariogasparoni said. I have compiled the master version without that line and the sound of the composite works fine when mixing audio.
