### ISSUE TITLE
Please change the title of kurento-tutorial-js

### ISSUE THREAD

**Issue by tgabi333** [Kurento/bugtracker#2]
[kurento-tutorial-js](https://github.com/Kurento/kurento-tutorial-js) on github has a false description `kurento-tutorial-java`.

Could you please fix? It may mislead someone.

**Comment by igracia** [comment]
Are you referring to the Readme.md files from each separate tutorial?

**Comment by tgabi333** [comment]
No, i mean this, but it's changed meanwhile, thank you. ![screenshot from 2015-10-14 13 18 48](https://cloud.githubusercontent.com/assets/187022/10482150/3bf5ffc2-7276-11e5-87a8-5d60cca76f36.png)

**Comment by igracia** [comment]
There's also a bug in the [readme files](https://github.com/Kurento/kurento-tutorial-js/blob/master/kurento-chroma/README.md#kurento-chroma) I've just submitted a patch to fix that, too.
