### ISSUE TITLE
RTCPeerConnection cannot be resolved

### ISSUE THREAD

**Issue by ishankgupta95** [Kurento/bugtracker#204]
**if (!pc) {
        pc = new RTCPeerConnection(configuration);
        if (useDataChannels && !dataChannel) {
            var dcId = 'WebRtcPeer-' + self.id;
            var dcOptions = undefined;
            if (dataChannelConfig) {
                dcId = dataChannelConfig.id || dcId;
                dcOptions = dataChannelConfig.options;
            }
            dataChannel = pc.createDataChannel(dcId, dcOptions);
            if (dataChannelConfig) {
                dataChannel.onopen = dataChannelConfig.onopen;
                dataChannel.onclose = dataChannelConfig.onclose;
                dataChannel.onmessage = dataChannelConfig.onmessage;
                dataChannel.onbufferedamountlow = dataChannelConfig.onbufferedamountlow;
                dataChannel.onerror = dataChannelConfig.onerror || noop;
            }
        }
    }**

In the above code, "RTCPeerConnection cannot be resolved" error is only given by mobile browser but the code is working fine for computer browsers.

**Comment by j1elo** [comment]
I'm not sure if this will still apply today. Please comment / reopen if this is still an issue with modern versions of Kurento.
