### ISSUE TITLE
How to recording room video file using kms java api with MCU mode？

### ISSUE THREAD

**Issue by kingkasuo** [Kurento/bugtracker#205]
Hi there,

     Could anyone tell me about how to recording room video file using kms java api with MCU mode？

     Seems there is no such demo code scenarios of mcu. 

     Thanks very much.

**Comment by kingkasuo** [comment]
no one helps?

**Comment by zhangalex** [comment]
Why not take a look at 'kurento-one2one-call-recording' example project? RecorderEndpoint is what you need, I think.

**Comment by kingkasuo** [comment]
thanks~
