### ISSUE TITLE
Unknown symbol from MediaObject.js when transpiling code with Webpack

### ISSUE THREAD

**Issue by musinit** [Kurento/bugtracker#210]
**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

**Client libraries**
- Language: JavaScript
- Version: 6.6.0

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: NOT OK
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

**What steps will reproduce the problem?**
1. Require index.js from kurento-client npm package in some file, let's name it 'test.js'
2. Transpile "test.js" with webpack 3.8.1 to "bundle.js"
3. See unknown symbol in bundle.js after transpiling, error in browser. This symbol is located in file "kurento-client-core/lib/abstracts/MediaObject.js", here what it's look like in browser:
var promise = new Promise(function(resolve, reject)Â {

      function callback2(error, values) {
        resolve(values)
      }

**What is the expected result?**
No such symbol in place of space
**What happens instead?**
See that symbol in place of space
**Does it happen with one of the tutorials?**
Yes
**Please provide any additional information below.**

**Comment by j1elo** [comment]
Assuming this issue was fixed a long time ago, as this hasn't been reported again
