### ISSUE TITLE
Unexpected resolution changes

### ISSUE THREAD

**Issue by nenadalm** [Kurento/bugtracker#212]
**KMS Version**:

6.6.3 via Docker (https://hub.docker.com/r/kurento/kurento-media-server/tags/)

**Client libraries**
- Language: Node.js
- Version: v8.9.1

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: FAIL

**What steps will reproduce the problem?**
Sometimes it happens that video has incorrect resolution. I have camera 1472px wide but stream is sometimes just 1104px wide.

I have the width in media constraints on callee side. Callee has then localVideo, which has 1472px videoWidth, caller has video with 1472px videoWidth, but after a while (1-2 sec), it is 1104px, then after few more secs, it's back to 1472px. This happens quite often. So it looks like problem is in kurento-media-server. It was noticed when `videocrop` filter was turned on (as it should crop the video in half). But it does the same thing without any filter. Just calleeWebRtcEndpoint->callerWebRtcEndpoint. I didn't notice anything related in Kurento logs.

**Expected result**
Video doesn't change resolution.

**Comment by nenadalm** [comment]
Also note that I was able to reproduce it only with 1 of 2 cameras I've tried.

The one I have issues with: https://www.insta360.com/product/insta360-air (1472x768).
The one I couldn't reproduce it with: integrated (1280x720).

**Comment by nenadalm** [comment]
Also If I use higher resolution on affected cam, it stays broken for caller (tried with resolution 2176x1088).

Same thing happens on different pc with the original resolution (1472x736).

**Comment by micaelgallego** [comment]
I think that WebRTC standard is able to change the resolution dynamically to adapt to network conditions. 

Please read this [stackoverflow question](https://stackoverflow.com/questions/30742963/why-does-video-resolution-change-when-streaming-from-android-via-webrtc)

**Comment by nenadalm** [comment]
Thanks. It looks like only way to detect this might be using `onresize` on the `<video>` (https://stackoverflow.com/questions/29708442/is-it-possible-to-catch-the-change-in-resolution-of-streaming-video-of-webrtc)
