### ISSUE TITLE
kurento-media-server, compile error: error: template argument ... involves template parameter(s)

### ISSUE THREAD

**Issue by rossbcan** [Kurento/bugtracker#213]
When compiling kurento-media-server...

Build System: Centos 7, x86_65
Target System: OpenWrt x86_64
GCC Version: toolchain-x86_64_gcc-5.3.0_glibc-2.22
KMS Version: git trunk, within last 2 weeks

If dependency libsigc++ version is less than 2.6.2, file KMS/CmakeLists.txt sets conditional "FIX_SIGC" which is used to define "namespace sigc" template in file "KMS/server/CacheEntry.cpp".

If the template is defined, the compile error (and many others) in title occurs. There is an error in the "namespace sigc" template for libsigc++ versions less than 2.6.2.

Workaround: Use libsigc++-2.6.2 (not tested for newer versions)
Final Fix: Change template code to correctly adapt to all  libsigc++ versions less than 2.6.2, greater than minimum required (pkgconfig) version.

Regards;
Bill

**Comment by j1elo** [comment]
Closed by https://github.com/Kurento/kurento/commit/bb96bbdd1b7c6de2288f5cc39a9f3683dd4fe615
