### ISSUE TITLE
One to many node example not working on iOS

### ISSUE THREAD

**Issue by mayeaux** [Kurento/bugtracker#219]
Hi there, is the one to many video example for Node supposed to work with iOS? It seems to ask to for access to the camera and mic correctly, but then I just see a spinning circle and nothing coming through on the server. Just wondering if it's supported, thanks!

**Comment by micaelgallego** [comment]
We are working on Safari support right now. 

It will be available in the following months.

**Comment by mayeaux** [comment]
Great, thanks for the prompt response you guys have made a great product!

**Comment by mayeaux** [comment]
What about Edge support? Someone just informed me they get a black screen on edge, thanks!

**Comment by micaelgallego** [comment]
Edge will be our next step.
