### ISSUE TITLE
PlayerEndpoint's default RTSP latency really high

### ISSUE THREAD

**Issue by hunternet93** [Kurento/bugtracker#22]
When using PlayerEndpoint with an RTSP source, the auto-created rtspsrc element uses it's default value for the latency property, 2000 ms. This causes a 2-second delay, which is pretty bad for realtime streams. Here's my quick fix: https://gist.github.com/hunternet93/a7b4a791ce8bf2c29ccf

**Comment by igracia** [comment]
@jcaden Could you please review this pull request?

**Comment by jcaden** [comment]
Great patch! Thanks. I'd like more to add an attribute to playerendpoint so latency ca be choose from client side depending on the application, because setting a default 50ms buffer could cause bad behavior when network is not stable.

**Comment by hunternet93** [comment]
That's what I thought'd probably need to happen, my C skills are pretty terrible so I didn't attempt it.

**Comment by igracia** [comment]
@jcaden Should we close this or change the milestone?

**Comment by jcaden** [comment]
There is patch on the way https://github.com/Kurento/kms-elements/pull/3

**Comment by igracia** [comment]
@jcaden Did the patch make it into 6.5.0?

**Comment by jcaden** [comment]
No, sorry.

**Comment by jcaden** [comment]
The functionality is already in the development version will be included in the next release, probably with number 6.6.0

**Comment by douglas-lee** [comment]
hi, @jcaden . i'm using the https://github.com/lulop-k/kurento-rtsp2webrtc, how can I set the latency? is the kurento client js version is too old? cause I have not see any property in it.

**Comment by immingta** [comment]
@douglas-lee 
add the parameter "networkCache" in the pipeline creation for playerEndpoint like
pipeline.create("PlayerEndpoint", {networkCache: 0, uri: address.value}, function(error, player){...
