### ISSUE TITLE
missing debian package dependency (sudo) for kurento-media-server-6.0

### ISSUE THREAD

**Issue by steele** [Kurento/bugtracker#222]
**KMS Version**: 
```
Version: 6.7.0~1.g6ebaa27
Found modules:
        Module: 'core' version '6.6.3'
        Module: 'elements' version '6.6.3'
        Module: 'filters' version '6.7.0~1.g0314843'
```
**Other libraries versions**:
```
ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial~20170725171352.96.493eee4  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial~20170725160546.81.eebfdab amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial~20170725164047.100.3db37b1 amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial~20170725161537.112.9ee4248 amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial~20170725170621.89.2685b0f  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial~20170725161537.112.9ee4248 amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.3.xenial.20170811182512.2704d13       amd64        Kurento core module
ii  kms-elements-6.0                     6.6.3.xenial.20170812234356.9e3fff4       amd64        Kurento elements module
ii  kms-filters-6.0                      6.7.0.xenial~20170813001324.1.0314843     amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.2.0.xenial~20170811181902.1.8cee9d8     amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3.xenial.20170725151047.d78deb7       amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.7.0.xenial~20170813003033.1.6ebaa27     amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial~20170725164047.100.3db37b1 amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial~20170725152356.170.0d6031b amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1.xenial~20170725160546.81.eebfdab amd64        ICE library (shared library)
```
**Client libraries**

N/a

**Browsers tested**

N/a

**System description:**

Ubuntu 16.04 base docker image - basic server installation of Ubuntu Xenial for docker

**What steps will reproduce the problem?**
1. Install the package following the instructions: https://doc-kurento.readthedocs.io/en/latest/installation_guide.html
2. Try to start the server: `service kurento-media-server-6.0 start`

**What is the expected result?**

The server starts normally without errors

**What happens instead?**

>  * Starting Kurento Media Server                                                                                        /etc/init.d/kurento-media-server-6.0: 67: /etc/init.d/kurento-media-server-6.0: sudo: not found
>                                                                                                                  [ OK ]

**Does it happen with one of the tutorials?**

N/a

**Please provide any additional information below.**

There is an assumption that sudo is available on Ubuntu, but it is not a base package and so may not be present on a minimal installation. The debian package meta-data for KMS should enumerate the 'sudo' package as an explicit dependency as it is required for the System V init scripts. (Or, of course, the use of sudo should be removed).

**Comment by j1elo** [comment]
Thank you for letting us know about this small compatibility issue.
Usage of sudo has been removed from the init script; it wasn't essential anyway.
