### ISSUE TITLE
No audio recorded, even when specifying mediaProfile: 'MP4'

### ISSUE THREAD

**Issue by KyleFoleyImajion** [Kurento/bugtracker#225]
**KMS Version**:
Version: 6.7.0-1.g6ebaa27
Found modules:
	Module: 'core' version '6.7.0-21.ge100fbf'
	Module: 'elements' version '6.7.0-27.g1ffdf34'
	Module: 'filters' version '6.7.0-.g4f0ac30'

**Other libraries versions**:
ii  gir1.2-gst-plugins-base-1.5          1.8.1.1.xenial 20170725154709.55.7b19cfd   amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                 1.8.1.1.xenial 20170725152356.170.0d6031b  amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial 20170725171352.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial 20170725160546.81.eebfdab  amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial 20170725164047.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial 20170725154709.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial 20170725161537.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial 20170725170621.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial 20170725161537.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial 20170725154709.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-cmake-utils                      1.5.0.xenial 20170811181647.1.68ec0fc      all          Kurento cmake utils
ii  kms-core-6.0                         6.7.0.xenial 20171219004723.21.e100fbf     amd64        Kurento core module
ii  kms-core-6.0-dev                     6.7.0.xenial 20171219004723.21.e100fbf     amd64        Kurento core module
ii  kms-elements-6.0                     6.7.0.xenial 20171228141917.27.1ffdf34     amd64        Kurento elements module
ii  kms-elements-6.0-dev                 6.7.0.xenial 20171228141917.27.1ffdf34     amd64        Kurento elements module
ii  kms-filters-6.0                      6.7.0.xenial 20171228142219.7.4f0ac30      amd64        Kurento filters module
ii  kms-filters-6.0-dev                  6.7.0.xenial 20171228142219.7.4f0ac30      amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.2.0.xenial 20170811181902.1.8cee9d8      amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                  1.2.0.xenial 20170811181902.1.8cee9d8      amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                       1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsonrpc library
ii  kurento-media-server-6.0             6.7.0.xenial 20170813003033.1.6ebaa27      amd64        Kurento Media Server
ii  kurento-media-server-6.0-dev         6.7.0.xenial 20170813003033.1.6ebaa27      amd64        Kurento media server, development files and tools
ii  kurento-module-creator-4.0           4.0.8.xenial 20170725174309.1.9662c2f      all          Kurento module creator
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial 20170725164047.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial 20170725154709.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev     1.8.1.1.xenial 20170725154709.55.7b19cfd   amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial 20170725152356.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                  1.8.1.1.xenial 20170725152356.170.0d6031b  amd64        GStreamer core development files
ii  libnice-dev                          0.1.13.1.xenial 20170725160546.81.eebfdab  amd64        ICE library (development files)
ii  libnice10:amd64                      0.1.13.1.xenial 20170725160546.81.eebfdab  amd64        ICE library (shared library)

**Client libraries**
- Language:  Node
- Version: 8.9.4

**Browsers tested**
- Chrome: FAIL 63.0.3239.132
- Firefox: FAIL 58.0
- Native: untested

**System description:**
AWS Ubuntu 16.04, STUN/TURN also on a AWS Ubuntu 16.04 instance. Clients are connecting via WSS to signalling server. Vanilla WebRTC being used client-side

**What steps will reproduce the problem?**
`recordParams = {
    uri: 'file:///tmp/s3video/'+conference.conferenceId+'.mp4',
    stopOnEndOfStream: true,
    mediaProfile: 'MP4'
};`

`conference.pipeline.create('RecorderEndpoint', recordParams, (err, recordEndpoint)=>{`...

**What is the expected result?**
Expecting recording to contain audio/video.

**What happens instead?**
Only contains video. If you specify to record 'MP4_AUDIO_ONLY', it records audio just fine. Other participants in the room can hear the 'host' just fine. This issue happened before upgrading to kms-core 6.7.0. I see both audio and video 'FLOWING' to the recording endpoint in the logs

**Does it happen with one of the tutorials?**
Untested

**Please provide any additional information below.**
Everything else works as expected, just no recording audio when video is present. If I have two people in the room and one is recording audio/video and the second is just recording audio, I get the audio only stream perfectly fine in the recording and video only from the first participant. This is what i use to specify what to assign a participant -> `    mediaProfile: (conference.host === fromPeer.guid) ? 'MP4' : 'MP4_AUDIO_ONLY'`

**Comment by KyleFoleyImajion** [comment]
No idea what fixed this, but I upgraded to kurento-media-server-6.0-dev and it's working fine now. If you run into this problem in the future, completely wipe Kurento from your system and make sure you install the very latest. In this case, it was -dev. Message me if you have this problem and I can help you out

**Comment by vijay-online-bub** [comment]
Hey Kyle,

I am having similar issue. When I play the mp4 recorded video in ios devices I don't have any audio. How can I fix this?

**Comment by KyleFoleyImajion** [comment]
Are you using composite hub?

**Comment by vijay-online-bub** [comment]
Nope. Plain old recorder endpoint.

**Comment by KyleFoleyImajion** [comment]
Can you check to make sure that the media is flowing? You should see both audio and video logged for every participant unless otherwise specified when connecting to the endpoint

```
fromPeer.webrtcEndpoint.on('MediaFlowInStateChange', (event)=>{
        if(event.state === 'FLOWING'{
          console.log('Flowing ' + event.mediaType);
        }
});
```

**Comment by vijay-online-bub** [comment]
In chrome it works fine. But in Safari it doesn't play audio.

**Comment by KyleFoleyImajion** [comment]
Oh weird, I haven't run into that issue. I've run into an issue where .webm was not playing audio sometimes, but that's because the browser didn't support .webm. Similar maybe? https://forums.macrumors.com/threads/safari-no-sound-with-html5-video.1539230/
