### ISSUE TITLE
kms development guide disappeared

### ISSUE THREAD

**Issue by xenyou** [Kurento/bugtracker#229]
The link to development guide got dead.

https://github.com/Kurento/doc-kurento

**Comment by xenyou** [comment]
this return 404.

https://github.com/Kurento/doc-kurento/blob/master/static/kms_development_guide.md

**Comment by ruddell** [comment]
Until the readme is updated, you can access it here: http://doc-kurento.readthedocs.io/en/latest/dev/development.html

**Comment by xenyou** [comment]
Thanks.
