### ISSUE TITLE
[bug]CPU 100% and hang up with composite

### ISSUE THREAD

**Issue by xenyou** [Kurento/bugtracker#230]
Using composite makes the machine CPU load 100%.
Maybe it's bug and old 6.5.0 did not reproduce it.

**KMS Version**:

Version: 6.6.2
Found modules:
	Module: 'core' version '6.6.3'
	Module: 'elements' version '6.6.3'
	Module: 'filters' version '6.6.2'

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.3.trusty.20170811193010.2704d13        amd64        Kurento core module
ii  kms-elements-6.0                     6.6.3.trusty.20170811201004.9e3fff4        amd64        Kurento elements module
ii  kms-filters-6.0                      6.6.2.trusty.20170725133434.7b4c9ea        amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.3.trusty.20170725112926.ee575c6        amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3.trusty.20170725122830.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.6.2.trusty.20170725135150.8e7ceee        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: <Node.js>
- Version:6.6.1-dev

**What steps will reproduce the problem?**
1. connect 1:1 with composite (merged videos)

**What is the expected result?**
CPU load is normal (maybe twice of 1:1?)

**What happens instead?**
CPU load is 100%. And videos hang up.

**Does it happen with one of the tutorials?**
kurento-tutorial-node/kurento-one2one-call with a patch.
patch is attached with this issue.

[composite.txt](https://github.com/Kurento/bugtracker/files/1730235/composite.txt)

**Comment by xenyou** [comment]
FYI, normal 1:1 uses 6% CPU in the same machine.

**Comment by xenyou** [comment]
This is very critical for us. Please check it.

**Comment by xenyou** [comment]
Oops, attached patch has hard coded ip address.
Please change it when you test it.

**Comment by xenyou** [comment]
Once this happens, kurento-media-server process can't kill by /etc/init.d/kurento-media-server-6.0 stop. I have to kill -9 to kill the process.

**Comment by xenyou** [comment]
I've also tested this on ubuntu 16.04. But the result is the same.

**Comment by KyleFoleyImajion** [comment]
https://github.com/chapin666/kurento-group-call-node/tree/mcu 

This guy wrote a MCU server that works, check it out. FYI it's not optimized so there are some things in there that can be deleted. Also, It's not necessary to connect endpoint to endpoint (line 65 + 66), you already connect them in with the composite hub ports.

**Comment by KFBIT** [comment]
Hello，I want to know if your question is resolve?I use kurento 6.8.0,I create a Composite and five  hubport,which not stream through,CPU utilization is very high.

**Comment by xenyou** [comment]
close. because l stopped using kurento.
