### ISSUE TITLE
Kurento 6.7.0 Docker image - Segmantation Fault (likely relating to ICE candidates)

### ISSUE THREAD

**Issue by lee-orr** [Kurento/bugtracker#231]
**KMS Version**: 

0:00:00.016800400    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:157:loadModules: Looking for modules, path: /usr/lib/x86_64-linux-gnu/kurento/modules
0:00:00.016986500    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
0:00:00.024716700    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
0:00:00.024785600    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: elements, version: 6.7.0~27.g1ffdf34, date: Dec 28 2017 14:25:38
0:00:00.025423200    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
0:00:00.028722600    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
0:00:00.028812000    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: core, version: 6.7.0~25.g42c657c, date: Jan  9 2018 11:23:07
0:00:00.028872400    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscrowddetectormodule.so
0:00:00.030256600    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscrowddetectormodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscrowddetectormodule.so
0:00:00.030296800    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: crowddetector, version: 6.6.1~4.g8e4fa33, date: Dec 28 2017 14:45:23
0:00:00.030319100    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
0:00:00.037537600    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
0:00:00.037619200    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: filters, version: 6.7.0~7.g4f0ac30, date: Dec 28 2017 14:28:56
0:00:00.037671300    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsplatedetectormodule.so
0:00:00.039255400    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsplatedetectormodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsplatedetectormodule.so
0:00:00.039310000    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: platedetector, version: 6.6.1~4.g5cf056a, date: Dec 28 2017 14:45:52
0:00:00.039360000    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmschromamodule.so
0:00:00.042973200    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmschromamodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmschromamodule.so
0:00:00.043023500    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: chroma, version: 6.6.1~4.g13d4102, date: Dec 28 2017 14:31:42
0:00:00.043058000    37 0x55c6277086a0 DEBUG   KurentoModuleManager ModuleManager.cpp:174:loadModules: Found file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmspointerdetectormodule.so
0:00:00.044593000    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:88:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmspointerdetectormodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmspointerdetectormodule.so
0:00:00.044646500    37 0x55c6277086a0 INFO    KurentoModuleManager ModuleManager.cpp:136:loadModule: Loaded module: pointerdetector, version: 6.6.1~4.g9848fe3, date: Dec 28 2017 14:47:22
Kurento Media Server version: 6.7.0~11.g86109a1
Found modules:
        'chroma' version 6.6.1~4.g13d4102
        'core' version 6.7.0~25.g42c657c
        'crowddetector' version 6.6.1~4.g8e4fa33
        'elements' version 6.7.0~27.g1ffdf34
        'filters' version 6.7.0~7.g4f0ac30
        'platedetector' version 6.6.1~4.g5cf056a
        'pointerdetector' version 6.6.1~4.g9848fe3

**Other libraries versions**:

ii  gstreamer1.5-alsa:amd64              1.8.1..trusty~20170720173912.55.7b19cfd    amd64        GStreamer plugin for ALSA
ii  gstreamer1.5-libav:amd64             1.8.2..trusty~20170720195343.96.493eee4    amd64        libav plugin for GStreamer
ii  gstreamer1.5-libav-dbg:amd64         1.8.2..trusty~20170720195343.96.493eee4    amd64        libav plugin for GStreamer (debug symbols)
ii  gstreamer1.5-nice:amd64              0.1.15.trusty~20170824154559.83.28531a4    amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.trusty~20170811190455.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-bad-dbg:amd64   1.8.1.1.trusty~20170811190455.100.3db37b1  amd64        GStreamer plugins from the "bad" set (debug symbols)
ii  gstreamer1.5-plugins-base:amd64      1.8.1..trusty~20170720173912.55.7b19cfd    amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-base-dbg:amd64  1.8.1..trusty~20170720173912.55.7b19cfd    amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1..trusty~20170720182212.112.9ee4248   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-good-dbg:amd64  1.8.1..trusty~20170720182212.112.9ee4248   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1..trusty~20170720193921.89.2685b0f    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-plugins-ugly-dbg:amd64  1.8.1..trusty~20170720193921.89.2685b0f    amd64        GStreamer plugins from the "ugly" set (debug symbols)
ii  gstreamer1.5-pulseaudio:amd64        1.8.1..trusty~20170720182212.112.9ee4248   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1..trusty~20170720173912.55.7b19cfd    amd64        GStreamer plugins for X11 and Pango
ii  kms-chroma-6.0                       6.6.1.trusty~20171228143112.4.13d4102      amd64        Kurento Chroma Filter
ii  kms-chroma-6.0-dbg                   6.6.1.trusty~20171228143112.4.13d4102      amd64        Kurento Chroma Filter debug symbols
ii  kms-core-6.0                         6.7.0.trusty~20180109112202.25.42c657c     amd64        Kurento core module
ii  kms-core-6.0-dbg                     6.7.0.trusty~20180109112202.25.42c657c     amd64        Kurento core module
ii  kms-crowddetector-6.0                6.6.1.trusty~20171228144430.4.8e4fa33      amd64        Kurento Crowd Detector Filter
ii  kms-crowddetector-6.0-dbg            6.6.1.trusty~20171228144430.4.8e4fa33      amd64        Kurento Crowd Detector Filter debug symbols
ii  kms-elements-6.0                     6.7.0.trusty~20171228142451.27.1ffdf34     amd64        Kurento elements module
ii  kms-elements-6.0-dbg                 6.7.0.trusty~20171228142451.27.1ffdf34     amd64        Kurento elements module
ii  kms-filters-6.0                      6.7.0.trusty~20171228142829.7.4f0ac30      amd64        Kurento filters module
ii  kms-filters-6.0-dbg                  6.7.0.trusty~20171228142829.7.4f0ac30      amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.2.0.trusty~20171115165053.2.5c57a1e      amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dbg                  1.2.0.trusty~20171115165053.2.5c57a1e      amd64        Kurento jsonrpc library
ii  kms-platedetector-6.0                6.6.1.trusty~20171228144518.4.5cf056a      amd64        Kurento Plate Detector Filter
ii  kms-platedetector-6.0-dbg            6.6.1.trusty~20171228144518.4.5cf056a      amd64        Kurento Plate Detector Filter debug symbols
ii  kms-pointerdetector-6.0              6.6.1.trusty~20171228144637.4.9848fe3      amd64        Kurento Pointer Detector Filter
ii  kms-pointerdetector-6.0-dbg          6.6.1.trusty~20171228144637.4.9848fe3      amd64        Kurento Pointer Detector Filter debug symbols
ii  kmsjsoncpp                           1.6.3.trusty.20170725122830.d78deb7        amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dbg                       1.6.3.trusty.20170725122830.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.7.0.trusty~20171115174445.11.86109a1     amd64        Kurento Media Server
ii  kurento-media-server-6.0-dbg         6.7.0.trusty~20171115174445.11.86109a1     amd64        Debugging symbols for Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.trusty~20170811190455.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1..trusty~20170720173912.55.7b19cfd    amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1..trusty~20170720170850.170.0d6031b   amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0-dbg:amd64          1.8.1..trusty~20170720170850.170.0d6031b   amd64        Core GStreamer libraries and elements
ii  libnice-dbg:amd64                    0.1.15.trusty~20170824154559.83.28531a4    amd64        ICE library (debugging symbols)
ii  libnice10:amd64                      0.1.15.trusty~20170824154559.83.28531a4    amd64        ICE library (shared library)

**Client libraries**
- Language: Node.js
- Version: 

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: 64 FAIL
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)
        Kurento in docker image, clients running on the host machine. No STUN or TURN servers

**What steps will reproduce the problem?**
1. Create a pipeline
2. Create a webrtc endpoint
3. Start gathering ice candidates

**What is the expected result?**
All ice candidates are gathered, and connection is successfully established
**What happens instead?**
Kurento server crashes, the following logs appear:
0:06:05.749604500     1 0x7f5b780072d0 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:422:processMessage: Message: {"jsonrpc":"2.0","method":"invoke","params":{"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","operation":"gatherCandidates","sessionId":"a5d4eacb-11cc-471f-a4e9-f548b9f12307"},"id":28}
0:06:05.764086700     1 0x7f5b48004ca0 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:57:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__module__":"kurento","__type__":"IceCandidate","candidate":"candidate:1 1 UDP 2013266431
172.19.0.3 26097 typ host","sdpMLineIndex":0,"sdpMid":"audio"},"source":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","tags":[],"timestamp":"1518815218","type":"OnIceCandidate"},"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}, sessionId: a5d4eacb-11cc-471f-a4e9-f548b9f12307
0:06:05.764258800     1 0x7f5b48004ca0 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:57:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__module__":"kurento","__type__":"IceCandidate","candidate":"candidate:2 1 TCP 1015021823
172.19.0.3 9 typ host tcptype active","sdpMLineIndex":0,"sdpMid":"audio"},"source":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","tags":[],"timestamp":"1518815218","type":"OnIceCandidate"},"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}, sessionId: a5d4eacb-11cc-471f-a4e9-f548b9f12307
0:06:05.796542700     1 0x7f5b48004ca0 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:57:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__module__":"kurento","__type__":"IceCandidate","candidate":"candidate:3 1 TCP 1010827519
172.19.0.3 52932 typ host tcptype passive","sdpMLineIndex":0,"sdpMid":"audio"},"source":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","tags":[],"timestamp":"1518815218","type":"OnIceCandidate"},"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}, sessionId: a5d4eacb-11cc-471f-a4e9-f548b9f12307
0:06:05.846830100     1 0x7f5b48004ca0 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:57:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__module__":"kurento","__type__":"IceCandidate","candidate":"candidate:1 2 UDP 2013266430
172.19.0.3 25354 typ host","sdpMLineIndex":0,"sdpMid":"audio"},"source":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","tags":[],"timestamp":"1518815218","type":"OnIceCandidate"},"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}, sessionId: a5d4eacb-11cc-471f-a4e9-f548b9f12307
0:06:05.871648600     1 0x7f5b48004ca0 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:57:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__module__":"kurento","__type__":"IceCandidate","candidate":"candidate:2 2 TCP 1015021822
172.19.0.3 9 typ host tcptype active","sdpMLineIndex":0,"sdpMid":"audio"},"source":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","tags":[],"timestamp":"1518815219","type":"OnIceCandidate"},"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}, sessionId: a5d4eacb-11cc-471f-a4e9-f548b9f12307
0:06:05.873484400     1 0x7f5b48004ca0 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:57:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__module__":"kurento","__type__":"IceCandidate","candidate":"candidate:3 2 TCP 1010827518
172.19.0.3 35338 typ host tcptype passive","sdpMLineIndex":0,"sdpMid":"audio"},"source":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","tags":[],"timestamp":"1518815219","type":"OnIceCandidate"},"object":"756b7503-8995-4021-b124-a38f0e932289_kurento.MediaPipeline/41b8f608-2e2c-40ea-925b-1a0df6fbed17_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}, sessionId: a5d4eacb-11cc-471f-a4e9-f548b9f12307
0:06:05.877007800     1 0x7f5b780072d0 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:424:processMessage: Response: {"id":28,"jsonrpc":"2.0","result":{"sessionId":"a5d4eacb-11cc-471f-a4e9-f548b9f12307","value":null}}

Segmentation fault (thread 140030941054720, pid 1)
Stack trace:

**Does it happen with one of the tutorials?**
I haven't tried it with the tutorials

**Please provide any additional information below.**
My best guess is that it crashes when the last ice candidate has been gathered... but  I haven't got a clue why.

**Comment by virtualfunction** [comment]
I'm getting something similar with the STUN / ICE process. Not happening with 6.6.2

```
signaller_1            | [Mon Feb 26 2018 04:23:05 GMT+0000 (UTC)] Connection viewer_1: {"type":"viewer_response","response":"accepted","sdp_answer":"v=0\r\no=- 3728607785 3728607785 IN IP4 0.0.0.0\r\ns=Kurento Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=msid-semantic: WMS\r\na=group:BUNDLE audio\r\nm=audio 1 UDP/TLS/RTP/SAVPF 111 0\r\na=mid:audio\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:0 PCMU/8000\r\na=setup:active\r\na=sendonly\r\na=rtcp-mux\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ssrc:4290616449 cname:user171269979@host-fe0411b0\r\na=ice-ufrag:1hOP\r\na=ice-pwd:qUv4PbVkJ/P9pMqLwm0DVl\r\na=fingerprint:sha-256 94:27:0E:E6:E8:23:85:65:3D:A1:49:CD:40:79:64:91:74:CC:7E:FB:45:8D:94:CB:FA:5A:D1:D8:FF:A1:1F:04\r\n"}
kms_1                  | 0:00:22.733846903     1 0x7f70fc001780 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:422:processMessage: Message: {"jsonrpc":"2.0","method":"invoke","params":{"object":"4efde862-7dc8-47ee-b026-31dbf9effaa4_kurento.MediaPipeline/622a864b-e5a8-4704-a98b-236470fbfac5_kurento.WebRtcEndpoint","operation":"gatherCandidates","sessionId":"c56e40d6-0fe0-41e3-852f-f13e3f700d65"},"id":21}
kms_1                  | Segmentation fault (thread 140123478349568, pid 1)
kms_1                  | Stack trace:
kms_1                  | [__GI___pthread_mutex_lock]
kms_1                  | nptl/pthread_mutex_lock.c:66
kms_1                  | [gnutls_alert_get]
kms_1                  | /usr/lib/x86_64-linux-gnu/libgnutls.so.28:0x4140C
kms_1                  | [gnutls_openpgp_set_recv_key_function]
kms_1                  | /usr/lib/x86_64-linux-gnu/libgnutls.so.28:0xD1B07
kms_1                  | [stun_agent_init_request]
kms_1                  | /opt/kurento/stun/stunagent.c:388
kms_1                  | [stun_usage_bind_create]
kms_1                  | /opt/kurento/stun/usages/bind.c:94
kms_1                  | [priv_discovery_tick_unlocked]
kms_1                  | /opt/kurento/agent/discovery.c:1041
kms_1                  | [discovery_schedule]
kms_1                  | /opt/kurento/agent/discovery.c:1226
kms_1                  | [nice_agent_gather_candidates]
kms_1                  | /opt/kurento/agent/agent.c:3083
kms_1                  | [kms_ice_nice_agent_start_gathering_candidates]
kms_1                  | /opt/kms-elements/src/gst-plugins/webrtcendpoint/kmsiceniceagent.c:430
kms_1                  | [kms_webrtc_session_gather_candidates]
kms_1                  | /opt/kms-elements/src/gst-plugins/webrtcendpoint/kmswebrtcsession.c:804
kms_1                  | [__kms_webrtc_marshal_BOOLEAN__VOID]
kms_1                  | /opt/kms-elements/obj-x86_64-linux-gnu/src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.c:87 (discriminator 3)
kms_1                  | [closure_invoke_notifiers]
kms_1                  | /build/glib2.0-ajuDY6/glib2.0-2.46.1/./gobject/gclosure.c:290
kms_1                  | [accumulate]
kms_1                  | /build/glib2.0-ajuDY6/glib2.0-2.46.1/./gobject/gsignal.c:3133
kms_1                  | [g_signal_emit_valist]
kms_1                  | /build/glib2.0-ajuDY6/glib2.0-2.46.1/./gobject/gsignal.c:3395
kms_1                  | [g_signal_emit_by_name]
kms_1                  | /build/glib2.0-ajuDY6/glib2.0-2.46.1/./gobject/gsignal.c:3479
kms_1                  | [kms_webrtc_endpoint_gather_candidates]
kms_1                  | /opt/kms-elements/src/gst-plugins/webrtcendpoint/kmswebrtcendpoint.c:426
```

**Comment by zhangalex** [comment]
Try older version:
`docker run --net host --restart=always -v /home/pat/configs/WebRtcEndpoint.conf.ini:/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini -v /home/pat/data/files:/home/pat/data/files -p 8888:8888 -d kurento/kurento-media-server:6.6.3-1`

**Comment by mariogasparoni** [comment]
This also happened for me on trusty when using Kurento from dev repos, which installs libnice10 (0.1.15) as default. In my use case, downgrading it to libnice 0.1.13 solved it.

`sudo apt-get install libnice10=0.1.13.1~20160930090742.81.geebfdab.trusty`

**Comment by j1elo** [comment]
Closing this: Docker images should be working well now.
