### ISSUE TITLE
libSSL crashes on mirrored packets

### ISSUE THREAD

**Issue by j1elo** [Kurento/bugtracker#242]
Report: https://groups.google.com/d/topic/kurento/AJdjdJvFmyg/discussion

libSSL breaks if a client mirrors the packets it receives back to the server. In practice, this can happen with clients connecting from some countries which might have severe restrictions to Internet connectivity, such as some gulf countries (Oman, Saudi Arabia, Emirates). Clients connecting from those countries sometimes send back packets right as they originated from KMS, and libSSL breaks.

Huge thanks to [Tom van der Geer](https://github.com/tvandergeer), who provided a [reproducible test](https://github.com/tvandergeer/dtls-handshaker) which aided in studying and solving the issue.

Segmentation faults due to this issue have this shape:

```
Segmentation fault
Stack trace:
[SSLv3_client_method]
/lib/x86_64-linux-gnu/libssl.so.1.0.0:0x23D3E
[SSL_check_chain]
/lib/x86_64-linux-gnu/libssl.so.1.0.0:0x34307
0xCBA2 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
0xECEC at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
0x61C1 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
0x644A at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E065
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x75DEE
0x9550 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstdtls.so
```

**Analysis**: A custom build of libSSL was provided in the past for users of Ubuntu 14.04 (Trusty), due to some problems that the official version had. As of today, this version of the library is outdated, while the official version has been receiving updates and bug fixes. Current version of libSSL in official Ubuntu repositories didn't crash during our tests. This issue does not affect Ubuntu 16.04 (Xenial).

**Solution**: We don't have resources to maintain a fork of libSSL, so the proposed solution is to remove it from Kurento repos and fall back to using the one provided with Ubuntu.

Progress:

- [x] kms-elements: dependency removed with Kurento/kms-elements@9266baa747f9b53854ce3361113a78ca84d3eb56
- [x] kurento-media-server: dependency removed with Kurento/kurento-media-server@77379b3a21fcbb138f8edbe0797be10496f955fc
- [x] gst-plugins-bad: ~build depends on libssl-dev (>= 1.0.2); runtime depends on libssl1.0.0 (>= 1.0.2)~ dependency removed with https://github.com/Kurento/gst-plugins-bad/commit/87b14488625e962b7295919969f25a1971051024.
- [x] libsrtp: ~build depends on libssl-dev (>= 1.0.2); runtime depends on libssl1.0.0 (>= 1.0.**1**)~ dependency removed with https://github.com/Kurento/libsrtp/commit/7e44cf103c9a92325f0aab7ad22ce0d29c50c3d3.

These dependencies need to be removed and the packages tested (both build and execution).

**Comment by LeonanCarvalho** [comment]
There is any workaround for it ?

**Comment by j1elo** [comment]
We ended up moving all packages to use the system's default SSL version
