### ISSUE TITLE
h264 high CPU usage

### ISSUE THREAD

**Issue by zhangalex** [Kurento/bugtracker#243]
I notice that if set h264 as default video codec, the cpu usage is very high. Our scenario is using mobile app to do a one2one video call with chrome. 

we are using kms 6.7.0

**Comment by zhangalex** [comment]
It should be that android still sending vp8 video.

**Comment by githubbla** [comment]
Same issue - h264 high cpu, no transcoding (no vp8 in config) on 4cpu dedicated server with 8gb ram! stream 12 x streams rtsp connected with pipeline to 1 webrtc - after some time high cpu.
<img width="1014" alt="Screen Shot 2020-01-28 at 22 22 19" src="https://user-images.githubusercontent.com/12095960/73302071-b156e180-421c-11ea-9b56-12aa0545c2a2.png">
