### ISSUE TITLE
KMS has very poor video quality when do one2one chat.

### ISSUE THREAD

**Issue by zhangalex** [Kurento/bugtracker#248]
When I'm testing APPRTC on https://appr.tc with Android app, it has a very good video quality. But I built a local KMS server 6.6, the video from the remote has very poor quality. After did some research I found there is limit on bandwidth, after set up following methods,

				callerWebRtcEndpoint.SetMaxVideoSendBandwidth(0)
				callerWebRtcEndpoint.SetMaxVideoRecvBandwidth(0)
				callerWebRtcEndpoint.SetMaxAudioRecvBandwidth(0)
				callerWebRtcEndpoint.SetMaxOutputBitrate(0)

It has better video quality. However it still has bad quality at the beginning of video compares to solution without KMS.

**Comment by micaelgallego** [comment]
Why have you closes this issue?

**Comment by zhangalex** [comment]
@micaelgallego  I found that most of the reason is come from WEBRTC internal design, the video resolution/frame-rate/bitrate will drop depends on CPU/network/picture complexity.  But the bad thing is that if the resolution drop it will be very hard to grow up even if the network condition is very good. 

SO, the solution will be increase MinVideoSendBandwidth to higher value, and then change the logic of  webrtc source code to make a better algorithm. 

This is what we do for now, do you have any suggestion?

**Comment by zhangalex** [comment]
I found there are a lot of people who using Android native WebRTC encounter this problem, but never has solution.
