### ISSUE TITLE
[kms 6.3.1-DEV] Poor audio when playing webm files

### ISSUE THREAD

**Issue by igracia** [Kurento/bugtracker#25]
We've made some tests playing WEBM format files, and the audio is poor for both local and http served ffiles. This doesn't happen in MP4 files, and @dfernandezlop reports that this has been happening for quite some time, but went undetected.

**Comment by igracia** [comment]
@jcaden  I'm assigning this to you for triage

**Comment by dfernandezlop** [comment]
This bug was fixed in https://github.com/Kurento/kms-core/commit/0a2c08ea353d7b594b17a78a040b0ee1498d5c9f

Closing this issue.
