### ISSUE TITLE
kurento-recorder example not working on chrome

### ISSUE THREAD

**Issue by carbonrider** [Kurento/bugtracker#251]
**KMS Version**:

Kurento Media Server version: 6.7.1
Found modules:
'chroma' version 6.7.1~7.g8cb7bc0
        
'core' version 6.7.1

'elements' version 6.7.1

'filters' version 6.7.1

'pointerdetector' version 6.7.1~6.g5ed9fea

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial~20170725171352.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial~20170725160546.81.eebfdab  amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial~20170725170621.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-chroma                           6.7.1.xenial~20180321190324.7.8cb7bc0      amd64        Kurento Chroma filter
ii  kms-core                             6.7.1.xenial.20180321183643.47e0370        amd64        Kurento Core module
ii  kms-elements                         6.7.1.xenial.20180321184406.5aaf4a0        amd64        Kurento Elements module
ii  kms-filters                          6.7.1.xenial.20180321185049.7f2d045        amd64        Kurento Filters module
ii  kms-jsonrpc                          6.7.1.xenial~20180321183209.1.637bf2a      amd64        Kurento JSON-RPC library
ii  kms-pointerdetector                  6.7.1.xenial~20180321193558.6.5ed9fea      amd64        Kurento Pointer Detector filter
ii  kmsjsoncpp                           1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.7.1.xenial.20180321185711.dd49a2c        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial~20170725152356.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1.xenial~20170725160546.81.eebfdab  amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from openh264

**Client libraries**
- Language: JavaScript
- Version: master branch from git

**Browsers tested**
- Chrome: FAIL - 66
- Firefox: NA
- Native: NA

**System description:**
Its a default installation, there is no other server installed.

**What steps will reproduce the problem?**
1. Install Kurento Media Server as specified in the installation document.
2. Configure tutorials as specified in [Kurento Recording Tutorial](http://doc-kurento.readthedocs.io/en/stable/tutorials/js/tutorial-recorder.html). Skip the step of git checkout 6.7.1, as there is no branch with that number. Continue on the master branch.
3. Once all the steps mentioned in the tutorial are complete, open browser and start recording.

**What is the expected result?**
The video should get recorded in /tmp folder as configured in the JS file.

**What happens instead?**
The video doesn't get recorded at all. There is no file in /tmp folder. In addition, the stop button doesn't stop the video.

**Does it happen with one of the tutorials?**
It works with branch 6.6.1 of [https://github.com/Kurento/kurento-tutorial-js](https://github.com/Kurento/kurento-tutorial-js) but not with master branch

**Please provide any additional information below.**
After JavaScript debugging, it seems there is no callback received on following line of [js/index.js](https://github.com/Kurento/kurento-tutorial-js/blob/master/kurento-recorder/js/index.js) of tutorial example.

`client.connect(webRtc, webRtc, recorder, function(error) {`

**Comment by RealArtemiy** [comment]
Same issue
Chrome 70 version
Firefox 62 version

**Comment by ikallali** [comment]
you have to remove the second "webRtc" parameter...

`client.connect(webRtc, recorder, function(error) {`
