### ISSUE TITLE
kurento-loopback-stats demo lantency unit

### ISSUE THREAD

**Issue by ryanjfdeng** [Kurento/bugtracker#252]
**KMS Version**:

Kurento Media Server version: 6.7.1
Found modules:
	'core' version 6.7.1
	'elements' version 6.7.1
	'filters' version 6.7.1

**Other libraries versions**:

ii  gstreamer0.10-tools                        0.10.36-1.5ubuntu1                           amd64        Tools for use with GStreamer
ii  gstreamer1.0-nice:amd64                    0.1.13-0ubuntu2                              amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64                   1.8.2.1.xenial~20170725171352.96.493eee4     amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                    0.1.13.1.xenial~20170725160546.81.eebfdab    amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64             1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64            1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64            1.8.1.1.xenial~20170725161537.112.9ee4248    amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64            1.8.1.1.xenial~20170725170621.89.2685b0f     amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64              1.8.1.1.xenial~20170725161537.112.9ee4248    amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                       1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer plugins for X11 and Pango
ii  kms-core                                   6.7.1.xenial.20180321183643.47e0370          amd64        Kurento Core module
ii  kms-elements                               6.7.1.xenial.20180321184406.5aaf4a0          amd64        Kurento Elements module
ii  kms-filters                                6.7.1.xenial.20180321185049.7f2d045          amd64        Kurento Filters module
ii  kms-jsonrpc                                6.7.1.xenial~20180321183209.1.637bf2a        amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                                 1.6.3.xenial.20170725151047.d78deb7          amd64        Kurento jsoncpp library
ii  kurento-media-server                       6.7.1.xenial.20180321185711.dd49a2c          amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64        1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64       1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer libraries from the "base" set
ii  libgstreamer0.10-0:amd64                   0.10.36-1.5ubuntu1                           amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0:amd64                    1.8.1.1.xenial~20170725152356.170.0d6031b    amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                            0.1.13.1.xenial~20170725160546.81.eebfdab    amd64        ICE library (shared library)
ii  libreoffice-avmedia-backend-gstreamer      1:5.1.6~rc2-0ubuntu1~xenial3                 amd64        GStreamer backend for LibreOffice
ii  openh264-gst-plugins-bad-1.5:amd64         1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer plugins from openh264

**Client libraries**
- Language: JavaScript
- Version:

**Browsers tested**
- Chrome:

**What steps will reproduce the problem?**
1. Maybe there are bugs in the kurento-loopback-stats demo. In index.js 206 lines:
 document.getElementById('e2eLatency').innerHTML = stats.videoE2ELatency / 1000000 + " seconds";
2.Doc http://doc-kurento.readthedocs.io/en/stable/features/statistics.html says videoE2ELatency: End-to-end video latency measured in nano seconds. So the code should be ：
 document.getElementById('e2eLatency').innerHTML = stats.videoE2ELatency / 1000000000 + " seconds";
or
  document.getElementById('e2eLatency').innerHTML = stats.videoE2ELatency / 1000000 + "ms";

**Comment by j1elo** [comment]
https://github.com/Kurento/kurento-tutorial-js/commit/26ee06fa44072544164f419149a2fffd1637e71b
