### ISSUE TITLE
what is MEDIA_OBJECT_EVENT_NOT_SUPPORTED meaning?

### ISSUE THREAD

**Issue by kingkasuo** [Kurento/bugtracker#254]
Simple kurento-hello-world demo can not see echo video ?

**Log Below:**
_2018-06-06 18:31:09.128 ERROR 90498 --- [nio-8443-exec-5] o.k.t.helloworld.HelloWorldHandler       : [Handler::handleTextMessage] Exception: org.kurento.client.internal.server.KurentoServerException: Event not found (Code:40106, Type:null, Data: {"type":"MEDIA_OBJECT_EVENT_NOT_SUPPORTED"}), sessionId: 4_

**Comment by micaelgallego** [comment]
Please update Kurento Media Server to latest version.

Un saludo.

Micael Gallego
ElasTest Project Technical Coordinator - http://elastest.io
Profesor en la Escuela Técnica Superior de Ingeniería Informática URJC
