### ISSUE TITLE
Incorrect log output

### ISSUE THREAD

**Issue by 136060150** [Kurento/bugtracker#257]
**KMS Version**:
Kurento Media Server version: 6.7.1
Found modules:
'core' version 6.7.1
'elements' version 6.7.1
'filters' version 6.7.1

**Other libraries versions**:

**Please provide any additional information below.**

module: kms-elements
file:kmsiceniceagent.c
lines:358

```
static void
kms_ice_nice_agent_get_local_credentials (KmsIceBaseAgent * self,
    const char *stream_id, gchar ** ufrag, gchar ** pwd)
{
  KmsIceNiceAgent *nice_agent = KMS_ICE_NICE_AGENT (self);
  guint id = atoi (stream_id);

  GST_DEBUG_OBJECT (self, "Set local credentials, stream_id: %d", id);

  nice_agent_get_local_credentials (nice_agent->priv->agent, id, ufrag, pwd);
}
```

 `GST_DEBUG_OBJECT (self, "Set local credentials, stream_id: %d", id); `

Replace with 

 `GST_DEBUG_OBJECT (self, "Get local credentials, stream_id: %d", id); `

**Comment by j1elo** [comment]
Noted, will include in next push
