### ISSUE TITLE
Latency of remote stream loop back with IPC/RTSP/RTMP.

### ISSUE THREAD

**Issue by yangboz** [Kurento/bugtracker#26]
Hi, all:

First off, thanks for this great work! 

And I have walk through all of the tutorials, from hello-world to custom module and element metadata filter testing, function works well, but with time delay and poor performance  while remote stream playing with IPC/RTSP/RTMP.

I just wonder does I missing somewhere configuration, or does the JSON IDL hurts the performance,  or does the KMS transcoding lower performance, or could be use Thrift IDL, or MQTT messaging service to enhance existed web web socketing and JSON parsing functionality?

Thanks,
Yangbo

**Comment by igracia** [comment]
The issue with latency in video has nothing to do with JSON or Thrift, as that would be used for signalling. Have you detected cases where the latency is ok? I mean, I suppose the tutorials have no latency, right?

**Comment by yangboz** [comment]
The latency is happened in detected cases, I wonder to find the root cause, or some thing I missed to avoid those latency, any suggestion?

**Comment by igracia** [comment]
Not really. Check in a controlled environment, with one of the tutorials, and note down the conditions when the delay happens.

**Comment by igracia** [comment]
@yangboz Any news about this? If there is no update, I'm closing the issue.
