### ISSUE TITLE
None of the samples except loopback is working

### ISSUE THREAD

**Issue by neilyoung** [Kurento/bugtracker#264]
**KMS Version**:

Kurento Media Server version: 6.7.1
Found modules:
	'chroma' version 6.7.1~7.g8cb7bc0
	'core' version 6.7.1
	'elements' version 6.7.1
	'filters' version 6.7.1

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial~20170725171352.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial~20170725160546.81.eebfdab  amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial~20170725170621.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-chroma                           6.7.1.xenial~20180321190324.7.8cb7bc0      amd64        Kurento Chroma filter
ii  kms-core                             6.7.1.xenial.20180321183643.47e0370        amd64        Kurento Core module
ii  kms-elements                         6.7.1.xenial.20180321184406.5aaf4a0        amd64        Kurento Elements module
ii  kms-filters                          6.7.1.xenial.20180321185049.7f2d045        amd64        Kurento Filters module
ii  kms-jsonrpc                          6.7.1.xenial~20180321183209.1.637bf2a      amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.7.1.xenial.20180321185711.dd49a2c        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial~20170725152356.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1.xenial~20170725160546.81.eebfdab  amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from openh264

**Client libraries**
- Language: JavaScript
- Version: 6.7.2

**Browsers tested**
FAIL: Chrome
FAIL: Firefox

**System description:**
	AWS stack, created from the template you provide

**What steps will reproduce the problem?**
1. Configure the "kurento-magic-mirror/js/index.js" to use the AWS instance
2. Run the sample
3.

**What is the expected result?**
Would like to see Mario's hat on my head

**What happens instead?**
Spinning wheel in the right window

**Does it happen with one of the tutorials?**
With all others too, except loopback

**Please provide any additional information below.**

Maybe this makes the diff: After SDP negotiation I get this trace in KMS server log:

2018-06-25 09:26:30,040458 8738 [0x00007ff8affae700] warning dtlssrtpdemux             gstdtlssrtpdemux.c:137 sink_chain() <dtls-srtp-demux>  received invalid buffer: 1

**Comment by neilyoung** [comment]
Additional information: kurento-pointerdetector refuses to "bower install"

bower kurento-module-pointerdetector#master          EINVRES Request to https://bower.herokuapp.com/packages/kurento-module-pointerdetector failed with 502

**Comment by neilyoung** [comment]
Any info here?

**Comment by ruddell** [comment]
You need to upgrade your `bower` version, or specify `"registry": "https://registry.bower.io"` in your `.bowercc` file.  See https://stackoverflow.com/a/51020318/3737815

**Comment by neilyoung** [comment]
@ruddell Thanks, but this is not the main problem :) IMHO the samples are still not working, or has it been fixed in between? Got no notice...

**Comment by neilyoung** [comment]
@ruddell You are right. I tried that (the bower fix) and it worked. Will try the second fix later and report. Thanks so far

**Comment by j1elo** [comment]
Closing: all this is probably fixed now.
