### ISSUE TITLE
files.kurento.org missing media used by Java - Send DataChannel tutorial 

### ISSUE THREAD

**Issue by fivebats** [Kurento/bugtracker#266]
**KMS Version**:

N/A

**Other libraries versions**:

N/A

**Client libraries**

N/A

**Browsers tested**

N/A

**System description:**

This is a problem with your file server. It affects some of the tutorial code. So the server should be fixed or the tutorial code should reference different media.

**What steps will reproduce the problem?**
1. Run the Java - Send DataChannel tutorial against any kurento server.
2. Start the playback.

**What is the expected result?**

Video should appear and data should show up in the data channel GUI.

**What happens instead?**

Nothing plays.

**Does it happen with one of the tutorials?**

Yes. This *is* one of the tutorials.

**Please provide any additional information below.**

The tutorial code attempts to play http://files.kurento.org/video/filter/barcodes.webm and the server returns a 404. Browsing the server makes me think it is missing its files.

**Comment by micaelgallego** [comment]
We should change reference to files.kurento.io to files.openvidu.io.

Thanks for reporting.

Regards.
