### ISSUE TITLE
Automatically release resources if two clients closed.

### ISSUE THREAD

**Issue by zhangalex** [Kurento/bugtracker#271]
Does KMS have the ability to automatically destroy/release the pipeline/endpoint/recorder if two KMS WebSocket connections disconnected?

**Comment by zhangalex** [comment]
I found that RTP recorder does not release the resource if client crash and don't get a chance to invoke release method.

**Comment by micaelgallego** [comment]
Resources are released after 4min.

**Comment by zhangalex** [comment]
Thanks, can I configure to a smaller value? For example, 1 min.
