### ISSUE TITLE
AMR/8000 codec support. Error: Removing not supported codec 'AMR/8000'

### ISSUE THREAD

**Issue by zhangalex** [Kurento/bugtracker#274]
In KMS 6.6.3-1, I'm using RTP feature to display RTSP stream on the web.  But the log says that AMR/8000 is not supported,

`WebRtcEndpointImpl.cpp:96:remove_not_supported_codecs_from_array:<kmswebrtcendpoint69> Removing not supported codec 'AMR/8000'`

Is there anyway to make KMS support this?

**Comment by zhangalex** [comment]
@micaelgallego  Do you have any idea on this? Thanks in advance.

**Comment by zhangalex** [comment]
install the plugin to fix?

**Comment by smarteertech** [comment]
@zhangalex Did you find any solution?

**Comment by j1elo** [comment]
Seems that the list of supported codecs for WebRTC is hardcoded [here](https://github.com/Kurento/kms-elements/blob/3c0ec65d65795371c68455b0bb7c6f2784dd4b7d/src/server/implementation/objects/WebRtcEndpointImpl.cpp#L62), and it doesn't include AMR.

This makes me wonder why the AMR codec is mentioned by default in the sample config file [here](https://github.com/Kurento/kms-core/blob/92b4e5750a23da508d852a75e25156c4197065ca/src/server/config/SdpEndpoint.conf.json#L18). Maybe that should be removed, as it seems that AMR isn't really implemented in the server.

**Comment by opg7371** [comment]
Is the support for AMR codec now included in Kurento?

**Comment by opg7371** [comment]
In this link it is written, that kurento supports AMR

https://www.kurento.org/kurento-media-element-toolbox

**Comment by j1elo** [comment]
Best thing you can do is to try with the RtpEndpoint and check... AMR is not enabled for WebRTC but I think it might work for RTP.

**Comment by opg7371** [comment]
Actually our main priority is for AMR-WB/16000. Can you the same for the AMR-WB/16000
