### ISSUE TITLE
If users have different set of devices (ie. UserA (Cam/Mic) - UserB (Mic)) data is correctly decoded by UserB endpoint, User A is unable to get audios

### ISSUE THREAD

**Issue by JanuszP** [Kurento/bugtracker#28]
[Dockerfile.txt](https://github.com/Kurento/bugtracker/files/121481/Dockerfile.txt)
Hello,
  
  Recently I've encountered a problem when users have different set of devices available. For example let's have:

UserA - camera + microphone
UserB - microphone

When connection is made UserB is able to see and hear UserA but UserA doesn't hear anything from UserB. When debuging, in chrome://webrtc-internals one can see that data is passed to UserA.

To see by yourself this problem please follow steps described in http://doc-kurento.readthedocs.org/en/stable/tutorials/java/tutorial-one2one.html but use my fork 
 https://github.com/JanuszP/kurento-tutorial-java/tree/differentDevices (branch differentDevices):

1. Get the code:
git clone https://github.com/JanuszP/kurento-tutorial-java.git
cd kurento-tutorial-java/kurento-one2one-call
git checkout differentDevices
mvn compile exec:java

2. Access https://localhost:8443 in two tabs  (accept the unknown certificate) - let's name them tabA and tabB
3. In tabA register (ie as UserA)
4. In tabB register (ie as UserB) and ender UserA as peer, don't press enter
5a. Click on "Call audio only"  - you'll start to receive audio from UserA, but UserA won't hear anything from UserB
5b. Click on "Call audio only - receive video" - you'll start to receive audio and video from UserA but User A won't hear anything from UserB

In my oppinion this is a bug as one can't expect that all users will have the same set of devices available and if that's not the case then there is no way of contacting UserA. I'd expect that parties share as much as they can, so in configuration mentioned above UserA can hear UserB, UserB can see and hear everything.

My OS: Ubuntu 15.10
Tested kurento versions (running in docker image, Dockerfile attached): 

Version: 6.3.3
Found modules:
	Module: 'core' version '6.3.1'
	Module: 'elements' version '6.3.1'
	Module: 'filters' version '6.3.0'

And 

Version: 6.3.4~2.g7386d4a
Found modules:
	Module: 'core' version '6.3.2~19.g21d51f9'
	Module: 'elements' version '6.3.2~17.ge44014a'
	Module: 'filters' version '6.3.1~1.gb3f6a20'

Browser:  Chrome 45.0.2454.101

Best Regards,
  Janusz

**Comment by dfernandezlop** [comment]
Hi JanuszP,

I think that your application has a problem with this bug in chrome https://code.google.com/p/chromium/issues/detail?id=403710

If you negotiate your peer as receive video and audio, it is not going to show any media if it doesn't receive both media. I can see this in the A client log:

constraints: {"mandatory":{"OfferToReceiveAudio":true,"OfferToReceiveVideo":true},"optional":[{"DtlsSrtpKeyAgreement":true}]}

It means that client A is waiting for video and audio, so if it only receives audio, it never plays the audio.

Regards.
David.

**Comment by JanuszP** [comment]
Hi dfernandezlop, 
  
  You might be right and the problem is on my side, yet I'm not sure. I've speent couple of days trying to figure out where the problem is yet I couldn't find anything that was in my reach in reasonable time. I had to focus on other tasks yet I'll test this more deeply and let you know what I'll find out. Things that I have checked (yet maybe I was clumsy doing tests and there was something wrong with my setup):

UserA - camera + microphone
UserB - microphone

1. Audio data reaches UserA (can be seen on charts in chrome://webrtc-internals ) yet it's not played - so your diagnose is probably right

2. Recording Endpoint doesn't work out of the box for UserB, I have to inform it separately what is available to tell it to record only Audio. 

3. I've tried adjusting "OfferToReceiveAudio/Video" appropriately to what available (by exchanging additional messages between UserA/UserB) yet the result was the same - as stated, I was under time pressure so I might not got this right. Eventually I'll compose something that would show it.  

4. We have tested Janus WebRtc Gateway and it worked correctly (yet clients negotiate offer/answer with gateway directly so maybe that's the reason?).

Best Regards,
  Janusz

**Comment by dfernandezlop** [comment]
Hi JanuszP,

I'm going to try  to answer to your questions:

2. You can look for traces like these in your KMS log:
Media Flowing OUT in pad default with type audio
Media Flowing IN in pad default with type audio
This traces could you a clue about if webrtc on side B is putting media in the pipeline and if the recorder is receiving media.

3. If you have a code, I could take a look to this situation.
4. I don't know how Janus works and how does the negotiations. I'm sorry.

Regards.

**Comment by dfernandezlop** [comment]
Any update? If there isn't updates in a couple of days, I will close the thread.

**Comment by dfernandezlop** [comment]
No updates. I'm closing the thread.
