### ISSUE TITLE
kms-core: Few headers not found

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#29]
kms-core/src/server/implementation/objects/MediaObjectImpl.hpp:5:27: fatal error: MediaObject.hpp: No such file or directory

**Comment by kirushyk** [comment]
Included with "quotes". No such file in same directory. Same for `#include "Tag.hpp"`

**Comment by kirushyk** [comment]
(i am trying to cross-compile kms to Windows)

**Comment by kirushyk** [comment]
Oh, as I understood, this file should be generated.

**Comment by kirushyk** [comment]
As I understood, I should use `kurento-module-creator` to generate this files, correct?

**Comment by dfernandezlop** [comment]
Hi kirushyk,

You are right, these files are auto-generated by kurento-module-creator and it is executed in the cmake process.

Regards.
David.

**Comment by igracia** [comment]
@kirushyk did you solve this already?

**Comment by kirushyk** [comment]
@igracia @dfernandezlop : Yes, thank you.
Can you please point me to place where CMake runs kurento-module-creator for particular .json files and how CMake makes kurento-module-creator understand where to put C++ output?
