### ISSUE TITLE
Kurento tutorials not working on Windows Firefox

### ISSUE THREAD

**Issue by derick31** [Kurento/bugtracker#291]
I am currently running the one to one call tutorial on a local environment. The KMS server is running on a virtual box. When testing on Windows Chrome. The users are able to see each other during the call. But when tested on Windows Firefox. The users cannot see each other and ICE server failed error is produced. I also tested it on Ubuntu Firefox and it is also working.

It seems that Firefox tries to use a turn/stun server even if it is on a local network. Is there any configuration that needs to be done to make it run on Firefox?

**Comment by neilyoung** [comment]
Out of curiosity: Is it related to this problem? 
https://github.com/andyet/SimpleWebRTC/issues/414

**Comment by derick31** [comment]
@neilyoung  Problem occurs on Firefox-Chrome and Firefox-Firefox. Firefox shouldn`t be using any TURN server when the connection is just local right? Thank you for the reference

**Comment by neilyoung** [comment]
@derick31 It doesn't unless otherwise instructed. Could you please check the setting `media.peerconnection.ice.relay.only` in `about:config`? Should be false.

**Comment by derick31** [comment]
@neilyoung yes, it is in false. Is there any problem with firefox when we use a virtual box for KMS server?

**Comment by neilyoung** [comment]
Not to my knowledge. I don't have any problem with this

**Comment by neilyoung** [comment]
But I remember to have had some problems with the JS sample code as well. Please check here https://github.com/Kurento/bugtracker/issues/264

**Comment by derick31** [comment]
I tried on an Amazon instance of kurento as well. In one to one call. Users are able to see each other. But after a while, in about:webrtc, the ICE State of the Candidates are cancelled

**Comment by derick31** [comment]
Issue no longer occurs. There was a problem with the Virtual Box where the KMS server is. I instead used a KMS server in a Ubuntu OS PC.
