### ISSUE TITLE
401 with TURN server

### ISSUE THREAD

**Issue by neilyoung** [Kurento/bugtracker#294]
Even though there is a valid TURN configuration, the TURN Allocate Request is made w/o password, which in turn provokes a 401 from the TURN server. Subsequent requests don't carry the password either.

I have followed the code of KMS up to the point, where the configuration parameters are passed to a library function (and I suppose, it is libnice) called nice_agent_set_relay_info

This happens in https://github.com/Kurento/kms-elements/blob/master/src/gst-plugins/webrtcendpoint/kmsiceniceagent.c

All my traces show me, that the full information is provided at this point:

```
GST_INFO_OBJECT (self, "kms_ice_nice_agent_add_relay_server: %s %s", server_info.username, server_info.password);

  nice_agent_set_relay_info (nice_agent->priv->agent,
      id,
      NICE_COMPONENT_TYPE_RTP,
      server_info.server_ip,
      server_info.server_port,
      server_info.username, server_info.password, type);
  nice_agent_set_relay_info (nice_agent->priv->agent,
      id,
      NICE_COMPONENT_TYPE_RTCP,
      server_info.server_ip,
      server_info.server_port,
      server_info.username, server_info.password, type);

```

which leads to a correct (here anonymised) trace in KMS:

```
2018-08-16T20:18:26,553635 9410 0x00007f45c0d52700    info kmsiceniceagent           kmsiceniceagent.c:406 kms_ice_nice_agent_add_relay_server() <KmsIceNiceAgent@0x7f45a0024160>  kms_ice_nice_agent_add_relay_server: username password
However, what appears at network level is this (anonymized)

    Length: 92
    Checksum: 0xedca [unverified]
    [Checksum Status: Unverified]
    [Stream index: 3]
Session Traversal Utilities for NAT
    [Duplicated original message in: 277]
    [Response In: 331]
    Message Type: 0x0003 (Allocate Request)
    Message Length: 64
    Message Cookie: 2112a442
    Message Transaction ID: 11befb311ffd76ad7c1c36d9
    Attributes
        SOFTWARE
            Attribute Type: SOFTWARE (0x8022)
                1... .... .... .... = Attribute Type Comprehension: Optional (0x1)
                .0.. .... .... .... = Attribute Type Assignment: IETF Review (0x0)
            Attribute Length: 16
            Software: libnice 0.1.13.1
        REQUESTED-TRANSPORT: UDP
            Attribute Type: REQUESTED-TRANSPORT (0x0019)
                0... .... .... .... = Attribute Type Comprehension: Required (0x0)
                .0.. .... .... .... = Attribute Type Assignment: IETF Review (0x0)
            Attribute Length: 4
            Transport: UDP (0x11)
            Reserved: 000000
        USERNAME: username
            Attribute Type: USERNAME (0x0006)
                0... .... .... .... = Attribute Type Comprehension: Required (0x0)
                .0.. .... .... .... = Attribute Type Assignment: IETF Review (0x0)
            Attribute Length: 31
            Username: username
            Padding: 1
```

I suppose that the tasks of dealing with STUN and TURN are taken by libnice, so could you please try to reproduce?

**Comment by neilyoung** [comment]
Any progress in this matter? Any additonal info required? Right now all people behind symmetric NATs are unreachable. And these are astonishing many (e.g. all the LTE guys)

**Comment by neilyoung** [comment]
@micaelgallego Are you using it with or without authentication? Please note: I'm not using a COTURN server in my domain, I'm using the NUMB TURN server you recommend.

**Comment by micaelgallego** [comment]
We are using COTURN with authentication in default OpenVidu installation.

**Comment by neilyoung** [comment]
Well, strange, really... Is your COTURN publicly available for a single shot test?

**Comment by micaelgallego** [comment]
Yes... it is available... but I dont remember the credentials right now.

Install an OpenVidu stack on AWS (there is a CloudFormation for that) and make any test you want.

**Comment by micaelgallego** [comment]
https://openvidu.io/docs/deployment/deploying-demos-aws/

**Comment by neilyoung** [comment]
@micaelgallego Thanks, but as far as I can see, there is only a password configuration for the TURN server, no info about IP and probably port

**Comment by neilyoung** [comment]
Sorry, closed accidently

**Comment by micaelgallego** [comment]
TURN server is installed in the same machine as KMS and OpenVidu Server.

**Comment by neilyoung** [comment]
OK, I have now also installed a COTURN server locally and everything works. For the first time I now also see the MESSAGE_INTEGRETY attribute, which is formed from the NONCE in the 401 challenge, the username, realm and password. I haven't seen this before with NUMB

```
 Key = MD5(Username || ":" || Realm || ":" || password)
 Hash = HMAC-SHA1(Key, Text)
```

https://msdn.microsoft.com/en-us/library/dd949398(v=office.12).aspx

I was following these tutorials while installing and configuring COTURN:

https://doc-kurento.readthedocs.io/en/stable/user/faq.html
http://builds.kurento.org/release/stable/docs/faq.html

Everything works as expected

**Comment by KyleFoleyImajion** [comment]
Having the exact same issue, but even installing the CoTURN locally does not solve the problem. Vanilla P2P calls work fine using our EC2 CoTURN server. The trickle ice tester works perfectly. Whenever Kurento tries to connect, about 90% of the packets are 401 unauthorized. TURN server is fully open to the world. I'll provide some stats below:

-All instances are EC2 Ubuntu 16.04.
-TURN server is its own EC2 instance. 
-TURN details in WebRTCEndpoint config file are verified correct
-`turnserver -v` shows P2P calls work fine, but Kurento is sending packets with no username or password
-Occasionally Kurento will send a valid packet.
-Happens when building Kurento from source, and on 6.7.2, 6.7.1. Haven't tested anything prior

I can attach some TURN or Kurento logs if requested.

**Comment by KyleFoleyImajion** [comment]
I can provide the TURN config as well
