### ISSUE TITLE
Not able to get multiple WebRTC streams from different Kurento Media Servers to a single Browser

### ISSUE THREAD

**Issue by tsonghong** [Kurento/bugtracker#3]
I'm having a very odd issue trying to get a single Browser (
latest Chrome and  latest Firefox)
to receive WebRTC video from multiple Kurento Media Servers
(observed both in 6.1.1 and 6.0.1 as I have skipped 6.1.0).

It appears for a given browser page, I can only get media displayed
for the first Kurento Media Server that goes toward it.

For example, if I had:

KMS1 with WebRTC stream A and WebRTC stream  B
and
KMS2 with stream X

If my browser page views A first, then it can also view B
when I add B.
However, it won't be able to see stream X when I try to add X.

THen if I remove the disconnect from the streams A and B,
then try to connect to X, then I would be able to see X.
But then trying to connect back to A and B, I don't see media
for those.  In this example, I have a 2 vs. 1, but it appears any number for those
two are applicable.

Now, the really interesting part is that this behavior is true for both
Kurento H.264 on Ubuntu and Mac OS (Firefox or Chrome) .
However, if I use VP8 (Chrome) on Kurento, I see that this issue doesn't
exist for Mac OS client (but does exist for latest Ubuntu client).

Is there any explanation you can think of for this behavior?

Analyzing the working SDP vs. non-working SDP (remote and local),
I don't see any big difference.  And the byte counts show 0
from about:webrtc for the test webcams that generate the data.

--- 

This is mainly a copy and paste from my post in kurento groups.  Sorry I didn't have time to embeillish it but over time I may come back if I find more time to gather more info.  Thanks.

**Comment by igracia** [comment]
Thanks for reporting this. It'll probably take some time for us to get round to this, as it is a corner case. We'll keep this open, and update here.

**Comment by tgabi333** [comment]
I saw a strange behavior like this when connecting ice servers with multiple streams. It was some kind of network limitations to ice servers, the connection just hung out, even ssh connection for the same server hung out.

Are you sure that three streams from the same source is working?

**Comment by tsonghong** [comment]
In my setups, I didn't use any turn servers/ice servers, just stun servers.  What I do notice when running "nload" to see the traffic outgoing from the latter Kurento server stream is that there appears to be a brief burst of network outgoing before it settles back to previous level.  But still I don't see a single frame displayed.  Now, when I perform the same action with the order of the two Kurento servers swapped, it's still always the latter Kurento server that I'm not able to view the data from.  So, I don't think the issue is particular to a specific box.

I think knowing the answer to this may help quicker: Have you guys ever succeeded in having a single browser tab have two windows open where Window#1 is streaming from KurentoServer A, and Window#2 is streaming from Kurento Server B?  If you have succeeded or not, then I think that would be a big hint if it's my configuration.

**Comment by tsonghong** [comment]
And yes, I'm able to successfully from a single Kurento server see multiple streams.  For example, I'll just hook up 3 cameras all feed Kurento Server A, and I'm able to see all 3 cameras fine from Kurento Server A on a single browser tab.

**Comment by dfernandezlop** [comment]
Hi,

I have tested two videos in the same browser tab (Chrome 46.0.2490.80 (64-bit))  and everything works fine. I'm using VP8. My configurations are:

- KMS A in host machine (Ubuntu 14.04).
Version: 6.1.2~1.g18ab837
Found modules:
        Module: 'core' version '6.1.3~32.g30d3f45'
        Module: 'elements' version '6.1.2~22.g5c261e9'
        Module: 'filters' version '6.1.2~2.gafec4f4'

- KMS B in virtual machine (Ubuntu 14.04).
Found modules:
        Module: 'core' version '6.1.3~26.g4dee71d'
        Module: 'elements' version '6.1.2~21.g21f6b13'
        Module: 'filters' version '6.1.2~2.gafec4f4'

My test uses java client but I'm not able to reproduce your error. Can you see any error in the browser console or the media server logs?

Anyway, for your tests, Chrome doesn't support H264 in webrtc. That test can be done only in Firefox.

Regards.
David.

**Comment by tsonghong** [comment]
HI David, thanks for that.  I don't get any noticeable error message.

When you do your test, is your testing client a Mac OS ?

I noticed that if I had the combo of Mac OS client + VP8 + Chrome, then I
didn't see the issue.

But if I had Ubuntu client + VP8 + Chrome, then I did see the issue.

Henry


On Thu, Nov 5, 2015 at 11:50 PM, David Fernández López <
notifications@github.com> wrote:

> Hi,
>
> I have tested two videos in the same browser tab (Chrome 46.0.2490.80
> (64-bit)) and everything works fine. I'm using VP8. My configurations are:
>
>    -
>
>    KMS A in host machine (Ubuntu 14.04).
>    Version: 6.1.2~1.g18ab837
>    Found modules:
>    Module: 'core' version '6.1.3~32.g30d3f45'
>    Module: 'elements' version '6.1.2~22.g5c261e9'
>    Module: 'filters' version '6.1.2~2.gafec4f4'
>    -
>
>    KMS B in virtual machine (Ubuntu 14.04).
>    Found modules:
>    Module: 'core' version '6.1.3~26.g4dee71d'
>    Module: 'elements' version '6.1.2~21.g21f6b13'
>    Module: 'filters' version '6.1.2~2.gafec4f4'
>
> My test uses java client but I'm not able to reproduce your error. Can you
> see any error in the browser console or the media server logs?
>
> Anyway, for your tests, Chrome doesn't support H264 in webrtc. That test
> can be done only in Firefox.
>
> Regards.
> David.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kurento/bugtracker/issues/3#issuecomment-154099694>.
>



-- 
*We do everything against time in search of a complete life.*

**Comment by dfernandezlop** [comment]
Hi Henry,

Client was Chrome 46.0.2490.80 (64-bit)  in Ubuntu. Maybe you have different versions of Chrome in MacOs and Ubuntu?

**Comment by tsonghong** [comment]
Hi David,

I think maybe my Chrome versions may have been slightly different at that time.  I would need to reverify.
But if you don't mind, since your setup is already there and ready,
is it possible you can do me a favor and force H.264 on your Ubuntu client and use Firefox and see if you can get the issue?  Mainly, because my own use case is H.264 + Firefox as opposed to VP8

If you want to follow how exactly I did this:

On both your KMS Ubuntu  boxes A and B,

install H.264 using the openh264:

$ sudo apt-get install openh264-gst-plugins-bad-1.5
$ sudo apt-get install gstreamer1.5-plugins

Then remove VP8 from Kurento by

a)  commenting out:

a=rtpmap:97 VP8/90000

in this file:

/etc/kurento/sdp_pattern.txt

and

b) commenting out these lines

    {
      "name" : "VP8/90000"
    },


from this file:

/etc/kurento/modules/kurento/SdpEndpoint.conf.json

---

Then restart Kurento on both boxes to pick up the change:

 sudo service kurento-media-server-6.0 restart


Then generate two H.264 streams - 1 from KMS A and another from KMS B to a Firefox browser.

If you can see both in a single firefox tab, then it has to be my side for sure.

Again, thanks!

Henry

**Comment by dfernandezlop** [comment]
Hi Henry,

I have tested with VP8 in Firefox and it doesn't work. I get errors like this in KMS log:

WARN          dtlsconnection gstdtlsconnection.c:721:openssl_poll:<GstDtlsConnection@0x7f7f30006520> Unknown SSL error: 6, ret: 0

It seems that Firefox has a weird behaviour with SSL keys, we will try to investigate it.

Thanks for the report.

**Comment by tsonghong** [comment]
Hi David, many thx for that.  Because I'd like to deploy a service using multiple kurentos with Firefox as the client, do you know what the realistic chance of this possibly getting solved or what timeframe is realistic?   Henry

**Comment by mishamistral** [comment]
Hello, my scenario is different, but with a similar behavior.

I have:

clientA --> Kurento1 <-- clientB -->Kurento2

so clientA communicates with clientB trough Kurento1. For some reasons (PlumberEndpoint I miss you so much !!), clientB needs to record his stream on Kurento2, so it needs to be connected to two different Kurento servers 

Well:

if clientB starts recording to Kurento2 AFTER the connection to Kurento1, the resulting file is empty, no network traffic and so no stream;
if clientB starts recording to Kurento2 BEFORE the connection to Kurento1, the stream to Kurento1 doesn't start;
if clientB uses only one Kurento (1 or 2 is the same) for both streaming to clientA and recording, all seems to work fine.

About Kurento:
Os: Ubuntu 14.04.3
Version: 6.1.1
Found modules:
        Module: 'core' version '6.1.2'
        Module: 'elements' version '6.1.1'
        Module: 'filters' version '6.1.1'

        Available factories:
        AlphaBlending
        Composite
        Dispatcher
        DispatcherOneToMany
        FaceOverlayFilter
        GStreamerFilter
        HttpPostEndpoint
        HubPort
        ImageOverlayFilter
        MediaPipeline
        Mixer
        PassThrough
        PlayerEndpoint
        RecorderEndpoint
        RtpEndpoint
        WebRtcEndpoint
        ZBarFilter

I tested on Chrome 46.0.2490.80 and Firefox 42.0 on Windows 7 and Ubuntu Linux 14.04

Thank you

**Comment by igracia** [comment]
@mishamistral Before going any further, could you please check with the latest development versions? There are some [known incompatibilities](https://groups.google.com/forum/#!searchin/kurento/chrome$2046/kurento/TC7JuK3GZ14/MUXXMHUOCgAJ) between KMS and Chrome 46.

**Comment by mishamistral** [comment]
Thank you for your reply. I'll try with the development version, but I have the same problem using Firefox 42.

**Comment by igracia** [comment]
@mishamistral Just the same, otherwise debugging can be fruitless.

**Comment by mishamistral** [comment]
Hi Ivan,

I tried with the following version:

Version: 6.1.2~4.g3c371d0
Found modules:
        Module: 'core' version '6.1.3~41.g3d7be7b'
        Module: 'elements' version '6.1.2~35.gc88c519'
        Module: 'filters' version '6.1.2~3.gf1efe25'

Os: Ubuntu 14.04.03

and Firefox 42 on Windows 7; the result was the same than before: no connection to the second server after a connection to a first Kurento server.
I also tried with two different connections from two different tabs, and the behavior is the same.

Thank you

**Comment by igracia** [comment]
Ok, thanks for trying that.

@dfernandezlop Could you have a look at this report too, please?

**Comment by dfernandezlop** [comment]
@tsonghong Sorry, but I can't offer you a timeframe to solve the problem. We will try to find a solution, but it is not in our near roadmap.

@mishamistral Hi, we need more information to evaluate your problem. The perfect situation will be that you can provide us a  test application to check the problem. If it is no possible, at least we need to know exactly your pipeline and your network configuration.

**Comment by mishamistral** [comment]
Thank you for your support. You can reproduce the problem, using the kurento helloworld tutorial. I modified the code to use two different kurento servers:
```javascript
var toSecondKurento = false;

var argv = minimist(process.argv.slice(2), {
    default: {
        as_uri: 'http://localhost:8080/',
        ws_uri1: 'ws://192.168.1.150:8888/kurento',
        ws_uri2: 'ws://192.168.1.150:8889/kurento'
    }
});

...

function getKurentoClient(callback) {
    if(toSecondKurento){
        toSecondKurento = !toSecondKurento;
        console.log('Connecting to ' + argv.ws_uri1);
        if (kurentoClient1 !== null) {
            return callback(null, kurentoClient1);
        }

        kurento(argv.ws_uri, function(error, _kurentoClient) {
            if (error) {
                console.log("Could not find media server at address " + argv.ws_uri1);
                return callback("Could not find media server at address" + argv.ws_uri1
                    + ". Exiting with error " + error);
            }

            kurentoClient1 = _kurentoClient;
            callback(null, kurentoClient1);
        });
    } else{
        toSecondKurento = !toSecondKurento;
        console.log('Connecting to ' + argv.ws_uri2);
        if (kurentoClient2 !== null) {
            return callback(null, kurentoClient2);
        }
        kurento(argv.ws_uri2, function(error, _kurentoClient) {
            if (error) {
                console.log("Could not find media server at address " + argv.ws_uri2);
                return callback("Could not find media server at address" + argv.ws_uri2
                    + ". Exiting with error " + error);
            }

            kurentoClient2 = _kurentoClient;
            callback(null, kurentoClient2);
        });
    }
}
```
When you open the application in the first firefox tab. all works fine; if you open another instance in a second tab (so using the second server), this instance doesn't work; another instance in a third tab will works fine, because it will connect to the first kurento server, and so on..
The Kurento is installed in a virtual machine bridged to the host:
host ip addr.: 192.168.1.240
vm ip addr: 192.168.1.150
and I tested with two instances listening on different ports (8888, 8889). Anyway I tested also with two Kurentos installed in two different machines, with the same result.

Thank you

**Comment by jcaden** [comment]
In the case of your test, the problem is that you are connecting to two servers that have different dtls certificates and the same IP address. This situation could be fixed using the same certificate but it is something that we are not supporting right now.

**Comment by mishamistral** [comment]
I had the same problem using two different servers with two different IP addresses. If you want, I can retest the hello world scenario using two different servers.

**Comment by jcaden** [comment]
Yes please, re-test using servers in different IP addresses. It will be great if you could also test using chrome.

Thank you.

**Comment by mishamistral** [comment]
I tested the modified Hello World with two servers with different IP addresses with these results on a Windows 7 machine:
Firefox 42 doesn't work;
Chrome 46.0.2490.80 works fine.
After that I modified the application, merging all in a single page:
```javascript
function start(server) {
    if(server === 1){
        var options = {
            localVideo: videoInput1,
            remoteVideo: videoOutput1,
            onicecandidate : onIceCandidate1
        };
        webRtcPeer1 = kurentoUtils.WebRtcPeer.WebRtcPeerSendrecv(options, function(error) {
            if(error) return onError(error);
            this.generateOffer(onOffer1);
        });
        showSpinner(videoInput1, videoOutput1);
    } else {
        var options = {
            localVideo: videoInput2,
            remoteVideo: videoOutput2,
            videoStream: webRtcPeer1.getRemoteStream(),
            onicecandidate : onIceCandidate2
        };
        webRtcPeer2 = kurentoUtils.WebRtcPeer.WebRtcPeerSendrecv(options, function(error) {
            if(error) return onError(error);
            this.generateOffer(onOffer2);
        });
        showSpinner(videoInput2, videoOutput2);
    }
	console.log('Creating WebRtcPeer and generating local sdp offer ...');
}
```
As before, it works on Chrome only.
Finally, I added a RecorderEndpoint in the two pipelines:

```javascript
function createMediaElements(pipeline, ws, callback) {
    pipeline.create('WebRtcEndpoint', function(error, webRtcEndpoint) {
        var ts = Math.floor(new Date().getTime()/1000);
        var uri = 'file:///tmp/test_' + ts + '.webm';
        if (error) {
            return callback(error);
        }
        pipeline.create('RecorderEndpoint',{uri: uri},function(error, recorderEndpoint) {
            if (error) {
                return callback(error);
            }
            return callback(null, webRtcEndpoint, recorderEndpoint);
        })
    });
}

function connectMediaElements(webRtcEndpoint, recorderEndpoint, callback) {
    webRtcEndpoint.connect(webRtcEndpoint, function(error) {
        if (error) {
            return callback(error);
        }
        webRtcEndpoint.connect(recorderEndpoint, function(error) {
            if (error) {
                console.error(error);
                return callback(error);
            }
            recorderEndpoint.record(function(error){
                if(error){
                    console.error(error);
                    return callback(error);
                }
            });
            return callback(null);
        });
    });
}
```
On Chrome, it records only in the first connected server, but in the second it creates an empty file. It' s worth to note that, when I try to record on the second server, I can see the loopback video.

Thank you

**Comment by dfernandezlop** [comment]
@mishamistral Could you share all your code? Because if I use your snippets there is a lot of not defined elements. To check your problem, I need the complete code.

Thanks.

**Comment by mishamistral** [comment]
@dfernandezlop , sorry for my late reply. In the following, you can see the code of the server.js, (helloworld tutorial) modified to use two different servers, as in the scenario described before.

```javascript
/*
 * (C) Copyright 2014-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var path = require('path');
var url = require('url');
var cookieParser = require('cookie-parser')
var express = require('express');
var session = require('express-session')
var minimist = require('minimist');
var ws = require('ws');
var kurento = require('kurento-client');

var argv = minimist(process.argv.slice(2), {
    default: {
        as_uri: 'http://localhost:8080/',
        ws_uri1: 'ws://192.168.1.150:8888/kurento',
        ws_uri2: 'ws://192.168.1.151:8888/kurento'
    }
});

var app = express();

/*
 * Management of sessions
 */
app.use(cookieParser());

var sessionHandler = session({
    secret : 'none',
    rolling : true,
    resave : true,
    saveUninitialized : true
});

app.use(sessionHandler);

/*
 * Definition of global variables.
 */
var sessions = {};
var candidatesQueue = {};
var kurentoClient1 = null;
var kurentoClient2 = null;

/*
 * Server startup
 */
var asUrl = url.parse(argv.as_uri);
var port = asUrl.port;
var server = app.listen(port, function() {
    console.log('Kurento Tutorial started');
    console.log('Open ' + url.format(asUrl) + ' with a WebRTC capable browser');
});

var wss = new ws.Server({
    server : server,
    path : '/helloworld'
});

/*
 * Management of WebSocket messages
 */
wss.on('connection', function(ws) {
    var sessionId = null;
    var request = ws.upgradeReq;
    var response = {
        writeHead : {}
    };

    sessionHandler(request, response, function(err) {
        sessionId = request.session.id;
        console.log('Connection received with sessionId ' + sessionId);
    });

    ws.on('error', function(error) {
        console.log('Connection ' + sessionId + ' error');
        stop(sessionId);
    });

    ws.on('close', function() {
        console.log('Connection ' + sessionId + ' closed');
        stop(sessionId);
    });

    ws.on('message', function(_message) {
        var message = JSON.parse(_message);
        //console.log('Connection ' + sessionId + ' received message ', message);

        switch (message.id) {
        case 'start':
            sessionId = request.session.id;
            start(message.server, sessionId, ws, message.sdpOffer, function(error, sdpAnswer) {
                if (error) {
                    return ws.send(JSON.stringify({
                        id : 'error',
                        message : error
                    }));
                }
                ws.send(JSON.stringify({
                    id : 'startResponse',
                    sdpAnswer : sdpAnswer,
                    server: message.server
                }));
            });
            break;

        case 'stop':
            stop(sessionId);
            break;

        case 'onIceCandidate':
            onIceCandidate(sessionId, message.candidate);
            break;

        default:
            ws.send(JSON.stringify({
                id : 'error',
                message : 'Invalid message ' + message
            }));
            break;
        }

    });
});

/*
 * Definition of functions
 */

// Recover kurentoClient for the first time.
function getKurentoClient(server, callback) {
    if(server === 1){
        console.log('Connecting to ' + argv.ws_uri1);
        if (kurentoClient1 !== null) {
            return callback(null, kurentoClient1);
        }

        kurento(argv.ws_uri1, function(error, _kurentoClient) {
            if (error) {
                console.log("Could not find media server at address " + argv.ws_uri1);
                return callback("Could not find media server at address" + argv.ws_uri1
                    + ". Exiting with error " + error);
            }

            kurentoClient1 = _kurentoClient;
            callback(null, kurentoClient1);
        });
    } else{
        console.log('Connecting to ' + argv.ws_uri2);
        if (kurentoClient2 !== null) {
            return callback(null, kurentoClient2);
        }
        kurento(argv.ws_uri2, function(error, _kurentoClient) {
            if (error) {
                console.log("Could not find media server at address " + argv.ws_uri2);
                return callback("Could not find media server at address" + argv.ws_uri2
                    + ". Exiting with error " + error);
            }

            kurentoClient2 = _kurentoClient;
            callback(null, kurentoClient2, server);
        });
    }
}

function start(server, sessionId, ws, sdpOffer, callback) {
    if (!sessionId) {
        return callback('Cannot use undefined sessionId');
    }

    getKurentoClient(server, function(error, kurentoClient) {
        if (error) {
            return callback(error);
        }

        kurentoClient.create('MediaPipeline', function(error, pipeline) {
            if (error) {
                return callback(error);
            }

            createMediaElements(pipeline, ws, function(error, webRtcEndpoint, recorderEndpoint) {
                if (error) {
                    pipeline.release();
                    return callback(error);
                }

                if (candidatesQueue[sessionId]) {
                    while(candidatesQueue[sessionId].length) {
                        var candidate = candidatesQueue[sessionId].shift();
                        webRtcEndpoint.addIceCandidate(candidate);
                    }
                }

                connectMediaElements(webRtcEndpoint,recorderEndpoint,function(error) {
                    if (error) {
                        pipeline.release();
                        return callback(error);
                    }

                    webRtcEndpoint.on('OnIceCandidate', function(event) {
                        var candidate = kurento.register.complexTypes.IceCandidate(event.candidate);
                        ws.send(JSON.stringify({
                            id : 'iceCandidate',
                            candidate : candidate,
                            server: server
                        }));
                    });

                    webRtcEndpoint.processOffer(sdpOffer, function(error, sdpAnswer) {
                        if (error) {
                            pipeline.release();
                            return callback(error);
                        }

                        sessions[sessionId] = {
                            'pipeline' : pipeline,
                            'webRtcEndpoint' : webRtcEndpoint
                        }
                        return callback(null, sdpAnswer);
                    });

                    webRtcEndpoint.gatherCandidates(function(error) {
                        if (error) {
                            return callback(error);
                        }
                    });
                });
            });
        });
    });
}

function createMediaElements(pipeline, ws, callback) {
    pipeline.create('WebRtcEndpoint', function(error, webRtcEndpoint) {
        var ts = Math.floor(new Date().getTime()/1000);
        var uri = 'file:///tmp/test_' + ts + '.webm';
        if (error) {
            return callback(error);
        }
        pipeline.create('RecorderEndpoint',{uri: uri},function(error, recorderEndpoint) {
            if (error) {
                return callback(error);
            }
            return callback(null, webRtcEndpoint, recorderEndpoint);
        })
    });
}

function connectMediaElements(webRtcEndpoint, recorderEndpoint, callback) {
    webRtcEndpoint.connect(webRtcEndpoint, function(error) {
        if (error) {
            return callback(error);
        }
        webRtcEndpoint.connect(recorderEndpoint, function(error) {
            if (error) {
                console.error(error);
                return callback(error);
            }
            recorderEndpoint.record(function(error){
                if(error){
                    console.error(error);
                    return callback(error);
                }
            });
            return callback(null);
        });
    });
}

function stop(sessionId) {
    if (sessions[sessionId]) {
        var pipeline = sessions[sessionId].pipeline;
        console.info('Releasing pipeline');
        pipeline.release();

        delete sessions[sessionId];
        delete candidatesQueue[sessionId];
    }
}

function onIceCandidate(sessionId, _candidate) {
    var candidate = kurento.register.complexTypes.IceCandidate(_candidate);

    if (sessions[sessionId]) {
        console.info('Sending candidate');
        var webRtcEndpoint = sessions[sessionId].webRtcEndpoint;
        webRtcEndpoint.addIceCandidate(candidate);
    }
    else {
        console.info('Queueing candidate');
        if (!candidatesQueue[sessionId]) {
            candidatesQueue[sessionId] = [];
        }
        candidatesQueue[sessionId].push(candidate);
    }
}

app.use(express.static(path.join(__dirname, 'static')));
```

**Comment by dfernandezlop** [comment]
Hi @mishamistral,

Thanks for your code but it seems that you also have changed things in html file. Please, attach all your modified files, I can't do changes to adjust the demo to your situation.

Best.

**Comment by mishamistral** [comment]
Here it is,

thank you

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="expires" content="0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="img/kurento.png" type="image/png" />

    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/demo-console/index.css">
    <link rel="stylesheet" href="bower_components/ekko-lightbox/dist/ekko-lightbox.min.css">
    <link rel="stylesheet" href="css/kurento.css">

    <script src="bower_components/adapter.js/adapter.js"></script>
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="bower_components/demo-console/index.js"></script>
    <script src="bower_components/ekko-lightbox/dist/ekko-lightbox.min.js"></script>

    <script src="bower_components/kurento-utils/js/kurento-utils.js"></script>

    <script src="js/index.js"></script>
    <title>Kurento Tutorial 1: Hello World</title>
  </head>
  <body>

    <header>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>
            <a class="navbar-brand" href=".">Kurento Tutorial</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="https://github.com/Kurento/kurento-tutorial-node/tree/master/kurento-hello-world">
                  <span class="glyphicon glyphicon-file"></span> Source Code</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="page-header">
        <h1>Tutorial 1: Hello World (WebRTC in loopback)</h1>
        <p>
          This application shows a <i>WebRtcEndpoint</i> connected to itself
          (loopback). Take a look to the <a href="img/pipeline.png"
            data-toggle="lightbox" data-title="Hello World Media Pipeline"
            data-footer="WebRtcEnpoint in loopback">Media Pipeline</a>. To run
          this demo follow these steps:
        </p>
        <ol>
          <li>Open this page with a browser compliant with WebRTC (Chrome, Firefox).</li>
          <li>Click on <i>Start</i> button.</li>
          <li>Grant the access to the camera and microphone. After the SDP negotiation the loopback should start.</li>
          <li>Click on <i>Stop</i> to finish the communication.</li>
        </ol>
      </div>
      <div class="row">
        <div class="col-md-5">
          <h3>Local stream</h3>
          <video id="videoInput1" autoplay width="480px" height="360px" poster="img/webrtc.png"></video>
        </div>
        <div class="col-md-2">
          <a id="start1" href="#" class="btn btn-success">
            <span class="glyphicon glyphicon-play"></span> Start</a>
            <br/>
            <br/>
            <a id="stop1" href="#" class="btn btn-danger">
              <span class="glyphicon glyphicon-stop"></span> Stop</a>
        </div>
        <div class="col-md-5">
          <h3>Remote stream</h3>
          <video id="videoOutput1" autoplay width="480px" height="360px" poster="img/webrtc.png"></video>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          <h3>Local stream</h3>
          <video id="videoInput2" autoplay width="480px" height="360px" poster="img/webrtc.png"></video>
        </div>
        <div class="col-md-2">
          <a id="start2" href="#" class="btn btn-success">
            <span class="glyphicon glyphicon-play"></span> Start</a>
          <br/>
          <br/>
          <a id="stop2" href="#" class="btn btn-danger">
            <span class="glyphicon glyphicon-stop"></span> Stop</a>
        </div>
        <div class="col-md-5">
          <h3>Remote stream</h3>
          <video id="videoOutput2" autoplay width="480px" height="360px" poster="img/webrtc.png"></video>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <label class="control-label" for="console">Console</label><br><br>
          <div id="console" class="democonsole">
            <ul></ul>
          </div>
        </div>
      </div>
    </div>

    <footer>
      <div class="foot-fixed-bottom">
        <div class="container text-center">
          <hr/>
          <div class="row">&copy; 2014-2015 Kurento</div>
          <div class="row">
            <div class="col-md-4">
              <a href="http://www.urjc.es">
                <img src="img/urjc.gif" alt="Universidad Rey Juan Carlos" height="50px"/>
              </a>
            </div>
            <div class="col-md-4">
              <a href="http://www.kurento.org">
                <img src="img/kurento.png" alt="Kurento" height="50px"/>
              </a>
            </div>
            <div class="col-md-4">
              <a href="http://www.naevatec.com">
                <img src="img/naevatec.png" alt="Naevatec" height="50px"/>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>
```

**Comment by tsonghong** [comment]
Hi Kurento team, were you able to reproduce this issue?  If not, would having a working example based on one of the Kurento tutorials help accelerate a solution for this?  Even now I'm still able to get this issue with latest Kurento.  Thanks!

**Comment by dfernandezlop** [comment]
Hi @mishamistral,

Sorry for the delay, we have a lot of work now. I have been able to get the error with your demo. It seems the same case reported at the beginning of the thread.

This problem is caused because Firefox doesn't support use different pem certificates in the same tab. 

The solution would be configure the same pem in both KMS but right now this feature is not supported.

Sorry for the troubles.
David.

**Comment by tsonghong** [comment]
Thx, can this be on the kurento roadmap for solving?  Basically, we will
have situations where it will be hard to make sure all the source video
(which can be allocated globally for a single user) can reach the same user
through the same kurento server.  We have some global customers who can
have subgroups located globally.  And therefore scaling has become a
nightmare when having to deal with this.

Thx.

**Comment by jcaden** [comment]
Sorry, but currently this is something that is not in our short-term roadmap.

**Comment by tsonghong** [comment]
Hi David and Jcaden,

can you elaborate on:

"The solution would be configure the same pem in both KMS but right now this feature is not supported."

Is this something we can do ourselves or requires a code change in Kurento?  What file would we need to configure?

Thanks!

Henry

**Comment by jcaden** [comment]
This means that it is not implemented.

Sorry for the trouble.

**Comment by tsonghong** [comment]
Ok, and if you can give us a pointer, would you say we are on the right track
if we modified the gst-plugins-bad library by making the PEM string the same
across all kurento media servers?

For example, if we made the gst_dtls_certificate_set_property() 
return the same result that is mentioned in this file:

https://github.com/kittee/gst-plugins-bad/blob/e1dda890a76ccc02f0746c3399a0a25ffb2c6b29/ext/dtls/gstdtlscertificate.c#L61

Is this the right idea?

Thanks.

Henry

**Comment by jcaden** [comment]
Not really, I'd use the "pem" property available in the element.

It's not a good idea to modify the default behavior of a library that works just to fit your needs because you will find problems later, in this case security problems.

**Comment by mikeg0** [comment]
We've been able to replicate this issue too.  And we have been able to replicate this using the AWS elasticRTC Kurento product that is in beta.  If you have a load balanced array of KMS servers with multiple streams sending from different servers, FF will only render the first stream.  However, this load balanced architecture works fine in Chrome.

Is this expected behavior in regards to the webRTC spec?  If not, should we open a bugzilla issue with FF?

**Comment by tsonghong** [comment]
Wow, after trying the pemcertificate feature in 6.4.1, looks like this issue is solved!  If that was the intention of that feature, well, Kurento team, you have made my day!   Thank you!

**Comment by dfernandezlop** [comment]
It's great to hear that :)

**Comment by mikeg0** [comment]
I can confirm this fix too.  Great work!

**Comment by Lisitskiy** [comment]
@mikeg0, @tsonghong 
Hello.
 I have a same problem with last dev version. Can you tell me, what  pemcertificate feature has sloved it?
- My clients connecting to app using wss, 
- Node app connecting  to  nginx load balanser -> KMS using ws

Thanks

**Comment by rayj00** [comment]
tsonghong  I see you are able to successfully from a single Kurento server see multiple streams.
I am having problems trying to get 3 seperate video streams on the same page.
I wonder if you could share the main code to do this?  Thanks.

**Comment by chandra967** [comment]
i have a problem with kurento server the issue is 
Hello, my scenario is different, but with a similar behavior.

I have:

clientA --> Kurento1 <-- clientB -->Kurento2

so clientA communicates with clientB trough Kurento1. For some reasons (PlumberEndpoint I miss you so much !!), clientB needs to record his stream on Kurento2, so it needs to be connected to two different Kurento servers

Well:

if clientB starts recording to Kurento2 AFTER the connection to Kurento1, the resulting file is empty, no network traffic and so no stream;
if clientB starts recording to Kurento2 BEFORE the connection to Kurento1, the stream to Kurento1 doesn't start;
if clientB uses only one Kurento (1 or 2 is the same) for both streaming to clientA and recording, all seems to work fine.

please need to take 2 kurento application server in 2 containers and 2 media server in 2 containers 

About Kurento:
