### ISSUE TITLE
Kurento Media Server fails to start on IPv4 only machines

### ISSUE THREAD

**Issue by JoseGoncalves** [Kurento/bugtracker#301]
**KMS Version**:

Kurento Media Server version: 6.8.0
Found modules:
	'core' version 6.8.0
	'elements' version 6.8.0
	'filters' version 6.8.0

**System description:**
KMS is located in a VM running Ubuntu 16.04.5 without IPv6 support, i.e., in /etc/default/grub I've added the following line: `GRUB_CMDLINE_LINUX="ipv6.disable=1"`

**What steps will reproduce the problem?**
Started KMS with command:
`sudo /usr/bin/kurento-media-server --gst-debug-level=3 --gst-debug=Kurento*:4,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4 --logs-path=/var/log/kurento-media-server`

**What is the expected result?**
KMS starts

**What happens instead?**
KMS aborts with the following error reported:
`error KurentoWebSocketTransport WebSocketTransport.cpp:130 WebSocketTransport()  Error starting listen for websocket transport on port 8080: Underlying Transport Error`

**Comment by JoseGoncalves** [comment]
I solved my problem by applying the following patch:
```patch
diff --git a/server/transport/websocket/websocketpp/transport/asio/endpoint.hpp b/server/transport/websocket/websocketpp/transport/asio/endpoint.hpp
index 28780a8..cf2a599 100644
--- a/server/transport/websocket/websocketpp/transport/asio/endpoint.hpp
+++ b/server/transport/websocket/websocketpp/transport/asio/endpoint.hpp
@@ -527,7 +527,7 @@ public:
    */
   void listen (uint16_t port, lib::error_code &ec)
   {
-    listen (lib::asio::ip::tcp::v6(), port, ec);
+    listen (lib::asio::ip::tcp::v4(), port, ec);
   }
 
   /// Set up endpoint for listening on a port
@@ -544,7 +544,7 @@ public:
    */
   void listen (uint16_t port)
   {
-    listen (lib::asio::ip::tcp::v6(), port);
+    listen (lib::asio::ip::tcp::v4(), port);
   }
 
   /// Set up endpoint for listening on a host and service (exception free)
```
Nevertheless, this forces IPv4 usage.
Not knowing the networking API used in Kurento I ask, is there a better way to setup this endpoints, in order it works both in machines with and without IPv6 support?

**Comment by j1elo** [comment]
Added a new setting parameter `ipv6`, which is enabled by default, and you can use in case disabling IPv6 support is needed: https://github.com/Kurento/kurento-media-server/commit/6cb18953c2ca3ddae94484caa98f10d585b9d13d

Test with latest [nightly build](https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html#kurento-media-server) and please give some feedback to know if this change is enough and works well.

This probably also fixes the issue in https://github.com/Kurento/bugtracker/issues/290

**Comment by JoseGoncalves** [comment]
I've tested, and while the standard socket starts listening, the secure one does not.
I get the following error:

```
2019-04-10T14:47:38,496961 7723 0x00007f11c888c280 warning KurentoWebSocketTransport WebSocketTransport.cpp:226 WebSocketTransport()  Secure websocket server not enabled: Error listening on port8443
```
My kurento.conf.json file is set like this:
```
{
  "mediaServer": {
    "resources": {
        "//": "Resources usage limit for raising an exception when an object creation is attempted",
        "//exceptionLimit": "0.8",
        "//": "Resources usage limit for restarting the server when no objects are alive",
        "//killLimit": "0.7",
        "//": "Garbage collector period in seconds",
        "garbageCollectorPeriod": 240,
        "//": "Whether to disable the RPC request cache, for memory constrained environments",
        "disableRequestCache": false
    },
    "net": {
      "websocket": {
        "ipv6": false,
        "port": 8080,
        "secure": {
            "port": 8443,
            "certificate": "fullchain_privkey.pem",
            "password": ""
        },
        "//registrar": {
            "//address": "ws://localhost:9090",
            "//localAddress": "localhost"
        },
        "//": "Maximum queue length of pending connections (see sysctl tcp_max_syn_backlog)",
        "//": "Default SOMAXCONN (128)",
        "//connqueue": 128,
        "path": "kurento",
        "threads": 10
      }
    }
  }
}
```

**Comment by j1elo** [comment]
It makes sense, I forgot to add the conditional check for the case of the secure socket...
https://github.com/Kurento/kurento-media-server/commit/3ee14ad78cb5aac7588904ae2217842241400411 should fix it, will be available in nightly repos in 1hr or so

**Comment by JoseGoncalves** [comment]
I've recompiled and found that now it's OK. Thanks!
