### ISSUE TITLE
Kurento in docker none of the samples except hello-world is working 

### ISSUE THREAD

**Issue by hendroid** [Kurento/bugtracker#306]
KMS Version:
Version: 6.7.0~1.g6ebaa27
Found modules:
        Module: 'chroma' version '6.6.1~3.g6df8f1d'
        Module: 'core' version '6.6.3'
        Module: 'crowddetector' version '6.6.1~3.geed9c9d'
        Module: 'elements' version '6.6.3'
        Module: 'filters' version '6.7.0~1.g0314843'
        Module: 'pointerdetector' version '6.6.1~3.gcf066f4'

Other libraries versions:
dpkg -l | egrep -i "kurento|gst.*1.5|nice"

ii  gir1.2-gst-plugins-base-1.5          1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                 1.8.1.1.xenial~20170725152356.170.0d6031b amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial~20170725171352.96.493eee4  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial~20170725160546.81.eebfdab amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial~20170725164047.100.3db37b1 amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial~20170725161537.112.9ee4248 amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial~20170725170621.89.2685b0f  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial~20170725161537.112.9ee4248 amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer plugins for X11 and Pango
ii  kms-chroma-6.0                       6.6.1.xenial~20170813010231.3.6df8f1d     amd64        Kurento Chroma Filter
ii  kms-chroma-6.0-dev                   6.6.1.xenial~20170813010231.3.6df8f1d     amd64        Kurento Chroma Filter development files
ii  kms-cmake-utils                      1.5.0.xenial~20170811181647.1.68ec0fc     all          Kurento cmake utils
ii  kms-core-6.0                         6.6.3.xenial.20170811182512.2704d13       amd64        Kurento core module
ii  kms-core-6.0-dev                     6.6.3.xenial.20170811182512.2704d13       amd64        Kurento core module
ii  kms-crowddetector-6.0                6.6.1.xenial~20170813012447.3.eed9c9d     amd64        Kurento Crowd Detector Filter
ii  kms-elements-6.0                     6.6.3.xenial.20170812234356.9e3fff4       amd64        Kurento elements module
ii  kms-elements-6.0-dev                 6.6.3.xenial.20170812234356.9e3fff4       amd64        Kurento elements module
ii  kms-filters-6.0                      6.7.0.xenial~20170813001324.1.0314843     amd64        Kurento filters module
ii  kms-filters-6.0-dev                  6.7.0.xenial~20170813001324.1.0314843     amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.2.0.xenial~20170811181902.1.8cee9d8     amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                  1.2.0.xenial~20170811181902.1.8cee9d8     amd64        Kurento jsonrpc library
ii  kms-pointerdetector-6.0              6.6.1.xenial~20170726110048.3.cf066f4     amd64        Kurento Pointer Detector Filter
ii  kmsjsoncpp                           1.6.3.xenial.20170725151047.d78deb7       amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                       1.6.3.xenial.20170725151047.d78deb7       amd64        Kurento jsonrpc library
ii  kurento-media-server-6.0             6.7.0.xenial~20170813003033.1.6ebaa27     amd64        Kurento Media Server
ii  kurento-module-creator-4.0           4.0.8.xenial~20170725174309.1.9662c2f     all          Kurento module creator
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial~20170725164047.100.3db37b1 amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev     1.8.1.1.xenial~20170725154709.55.7b19cfd  amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial~20170725152356.170.0d6031b amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                  1.8.1.1.xenial~20170725152356.170.0d6031b amd64        GStreamer core development files
ii  libnice-dev                          0.1.13.1.xenial~20170725160546.81.eebfdab amd64        ICE library (development files)
ii  libnice10:amd64                      0.1.13.1.xenial~20170725160546.81.eebfdab amd64        ICE library (shared library)

Client libraries (Fedora 27):
node -v
v8.12.0

Browsers tested
 FAIL: Chrome
 FAIL: Firefox

System description (Red Hat Enterprise Linux Server release 7.4 (Maipo)):
Docker Version:
docker-1.13.1-75.git8633870.el7_5.x86_64
Docker Image source:
https://github.com/Kurento/kurento-docker/tree/master/docker

What steps will reproduce the problem?
1. as described here: https://github.com/Kurento/kurento-docker/tree/master/docker
2. Run the sample https://doc-kurento.readthedocs.io/en/stable/tutorials/node/tutorial-magicmirror.html

What is the expected result?
Would like to see Mario's hat on my head

What happens instead?
Same as hello-world sample. I see both streams but no filters.
After few seconds/ minutes the remote stream freezes. 

Does it happen with one of the tutorials?
With all others too.

**Comment by hendroid** [comment]
docker logs kurento -f

---schnipp---
0:01:04.313642904     1 0x7f60f80a2270 DEBUG   KurentoWebSocketEventHandler WebSocketEventHandler.cpp:54:sendEvent: Sending event: {"jsonrpc":"2.0","method":"onEvent","params":{"value":{"data":{"candidate":{"__mo
dule__":"kurento","__type__":"IceCandidate","candidate":"candidate:6 2 TCP 1015022078 172.17.0.2 36045 typ host tcptype passive","sdpMLineIndex":1,"sdpMid":"video"},"source":"d31f811f-0d9e-421d-9a8c-395e13485523_
kurento.MediaPipeline/4699c242-7a14-4563-a094-d372cc0456c8_kurento.WebRtcEndpoint","tags":[],"timestamp":"1540970986","type":"OnIceCandidate"},"object":"d31f811f-0d9e-421d-9a8c-395e13485523_kurento.MediaPipeline/
4699c242-7a14-4563-a094-d372cc0456c8_kurento.WebRtcEndpoint","type":"OnIceCandidate"}}}                                                                                                                             
 -> a0010ed9-72e2-4376-a62c-0ab4c1a108cc                                                                                                                                                                            
0:01:04.344757074     1 0x7f60f8040e30 DEBUG   KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:295:newSelectedPairFull:<kmswebrtcendpoint0> New pair selected stream_id: 1, component_id: 1, local candidate: candi
date:4 1 UDP 2013266431 172.17.0.2 59070 typ host, remote candidate: candidate:2839917044 1 UDP 2122194687 10.254.204.34 43083 typ host                                                                            
0:01:05.370533051     1 0x7f6098001ad0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:447:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type audio                      
0:01:05.391637652     1 0x7f609001b190 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:492:mediaFlowInStateChange:<kmsfilterelement0> Media Flowing IN in pad default with type audio                         
0:01:05.392977518     1 0x7f609001b190 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:447:mediaFlowOutStateChange:<kmsfilterelement0> Media Flowing OUT in pad default with type audio                       
0:01:05.408310800     1 0x7f6084002ad0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:492:mediaFlowInStateChange:<kmswebrtcendpoint0> Media Flowing IN in pad default with type audio                        
0:01:05.422148415     1 0x7f60a0011800 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:447:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type video                      
0:01:05.631202912     1 0x7f608003ca80 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:492:mediaFlowInStateChange:<kmsfilterelement0> Media Flowing IN in pad default with type video                         
0:01:05.758467799     1 0x7f61040af630 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:447:mediaFlowOutStateChange:<kmsfilterelement0> Media Flowing OUT in pad default with type video                       
0:01:05.819019294     1 0x7f60c8016680 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:492:mediaFlowInStateChange:<kmswebrtcendpoint0> Media Flowing IN in pad default with type video                        
** (kurento-media-server:1): CRITICAL **: gst_video_frame_map_id: assertion 'info->width <= meta->width' failed                                                                                                    
** (kurento-media-server:1): CRITICAL **: gst_video_frame_map_id: assertion 'info->width <= meta->width' failed                                                                                                    
** (kurento-media-server:1): CRITICAL **: gst_video_frame_map_id: assertion 'info->width <= meta->width' failed              
---schnapp---

**Comment by j1elo** [comment]
Closing this: Docker images should be working well now.
