### ISSUE TITLE
Unable to install old versions / Binary distribution not available

### ISSUE THREAD

**Issue by mfornasa** [Kurento/bugtracker#31]
I need to install an old version (6.2.0) because latest version does not support TURN, and we need it. It appears that the ubuntu package repo does not contain old binary versions.
This is **very** annoying because:
* Does not allow to downgrade
* Does not allow to replicate a working 6.2.0 install on another server

I tried to build the old version from source, but I'm having issues, which are out of scope here. Anyway, you should provide old versions. 

If you don't want to let them in the repo, please provide them in an archival form. Anyway, standard deb practice is to leave old version in the repo, in order to not break `apt` on existing installations.

**Comment by jcaden** [comment]
If you are going to downgrade because of TURN, previous versions do not
support it correctly. When a turn candidate is used kms will break. Why do
you think you need TURN? Is your kms behind an address dependant NAT or a
firewall?

**Comment by jcaden** [comment]
The issue about not cointaining old versions is caused by reprepro, that deletes old versions when you upload a new one.

**Comment by mfornasa** [comment]
Not sure about the TURN issue. We have a standard AWS setup (with their NAT and firewall), and 6.3.3 does not work for us, while 6.2.0 works. Any hint?

About the binary distribution, I want to point out that deleting old versions is **preventing any production-grade usage**. Ubuntu packages disappearing does not allow me to have a reproducible environment.

**Comment by jcaden** [comment]
if you open udp ports that kms is using it should work on aws. This is something we are testing every day.

We will try to fix the problem with the packages, but we do not have much time for this right now.

**Comment by pritambarhate** [comment]
It will be great, if there is documentation where all the files added by Kurento installation are listed. This way one can backup all those files before upgrading Kurento. 

I am also in a situation where a server has older version which works with the code deployed. However the same codebase doesn't seem to work with the latest version. So before upgrading to the latest version, it would be good to backup current installation.

**Comment by igracia** [comment]
I think that the best practice in that case is to have a staging
environment, when you can make all the appropriate tests before rolling the
new version. That would really be the best thing to do. That way, if your
software does not go well with the new version, there's nothing to roll
back.

**Comment by javierlopezfernandez** [comment]
Support for installation of older versions is available since 6.4.0. You'll need to add following repository URL:

deb http://ubuntu.kurento.org/6.4.0 trusty kms6
deb http://ubuntu.kurento.org/6.5.0 trusty kms6
...

In order to install stable you'll want to use:

deb http://ubuntu.kurento.org trusty kms6

**Comment by naveenp-egnaroinc** [comment]
Hi, I tried using the URL  deb http://ubuntu.kurento.org/6.6.1 trusty kms6 to get an older version.

I get 

W: Failed to fetch http://ubuntu.kurento.org/6.6.1/dists/trusty/kms6/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ubuntu.kurento.org/6.6.1/dists/trusty/kms6/binary-i386/Packages  404  Not Found

Please help
