### ISSUE TITLE
Share Resource

### ISSUE THREAD

**Issue by 823639792** [Kurento/bugtracker#316]
**KMS Version**: 6.8.1

**Client libraries**
- Language:  JavaScript

I found that the same rtsp address is accessed at the same time, and the CPU usage is multiplied, such as one 8% and two 16%. Can multiple resources be shared when multiple clients access an rtsp address at the same time?

**Comment by micaelgallego** [comment]
Can you elaborate a bit more your use case? 

If you need to connect several browsers to the same RTSP resource, you will need only a PlayerEndpoint with two WebRtcEndpoints connected to it.

**Comment by 823639792** [comment]
1, clone https://github.com/lulop-k/kurento-rtsp2webrtc
2, open kurento service
3, open http-server
4, chrome open a tab, open rtsp: rtsp://192.168.10.241/mp4Test.mkv, cpu occupies 6%; then open a new tab, open rtsp://192.168.10.241/mp4Test.mkv, cpu occupied 12%

So kurento-rtsp2webrtc to modify where to share rtsp, as long as the same rtsp address, cpu resources do not increase
