### ISSUE TITLE
kurento-client-js Cannot assign to read only property 'toJSON' of object '[object Object]' error

### ISSUE THREAD

**Issue by ethand91** [Kurento/bugtracker#317]
**KMS Version**:
6.8.1

**Client libraries**
Language: Node.js
kurento-client:  6.8.0
Node: 8.12.0
Typescript: 3.0.1

**What is the expected result?**
For the Node.js application to initialize

**What happens instead?**
TypeError: Cannot assign to read only property 'toJSON' of object '[object Object]'
Node.js application fails to start

**Does it happen with one of the tutorials?**
No

**Please provide any additional information below.**
My node application is based on TypeScript. 
I am also using mongoose version: 5.3.15

The console output also shows that the error is coming from: 
/node_modules/mongoose/lib/error/validation.js:74:34

However if I download the kurento-client-js repository and comment out the below line in lib/index.js my application starts up without the toJSON error occuring.

lib/index.js
require('error-tojson');

Are there any issues with commenting out the above line?

**Comment by j1elo** [comment]
Should be fixed by changed from
* https://github.com/Kurento/kurento-client-js/pull/9
* https://github.com/Kurento/kurento-client-js/pull/10
* https://github.com/Kurento/kurento-client-js/pull/12
