### ISSUE TITLE
Remote stream not shown in browser KMS running on the docker

### ISSUE THREAD

**Issue by konglinghai123** [Kurento/bugtracker#319]
the issues like this
![image](https://user-images.githubusercontent.com/12596758/49845527-0447bc80-fe02-11e8-89e2-b19428cd386b.png)

the firefox webrtc debug show
![image](https://user-images.githubusercontent.com/12596758/49845580-3d802c80-fe02-11e8-87a8-2bad4dc63e6f.png)

![image](https://user-images.githubusercontent.com/12596758/49845771-0f4f1c80-fe03-11e8-88ea-7d793bbbb89c.png)

test the stun server 
![image](https://user-images.githubusercontent.com/12596758/49845692-b8494780-fe02-11e8-87b5-1f9040cd6eef.png)

The kms（docker） is running on public IP，I run the 'kurento-hello-world' on my company network.
 And connect the kms websokcet(ws://xxx.xxx.xxx.xxx:8888/kurento)
what's the problem?

**Comment by micaelgallego** [comment]
Where is located the browser you are trying to connect to KMS? Are you using STUN?

**Comment by konglinghai123** [comment]
yes, I use browser to connect to KMS and STUN. I  modifiy the kurento-hello-world index.js is work well.
like this.
![image](https://user-images.githubusercontent.com/12596758/49857006-57366980-fe2c-11e8-88d8-86fe7a1e1e79.png)
```
  var icesevers = {"iceServers":[

      {urls:"stun:139.198.123.138:3478"},
      {
          urls: ["turn:139.198.123.138:3478"],
          username: "kerento",
          credential: "kerento"
      }
      ]
  }
  var options = {
    localVideo: uiLocalVideo,
    remoteVideo: uiRemoteVideo,
    mediaConstraints: { audio: true, video: true },
    onicecandidate: (candidate) => sendMessage({
      id: 'ADD_ICE_CANDIDATE',
      candidate: candidate,
    }),
      configuration: icesevers
  };

```
But I have new issues , the one2onecall is not work well.
like this
![image](https://user-images.githubusercontent.com/12596758/49857104-9fee2280-fe2c-11e8-9f75-94050713cd4b.png)
what's worng?
