### ISSUE TITLE
[Question] how does the kms handle the high concurrency ?

### ISSUE THREAD

**Issue by thincal** [Kurento/bugtracker#32]
In the production environment, how to handle thousands of people accessing the kms at the same time ? Is there any solution to set up a distributed kms service ? many thanks.

**Comment by thincal** [comment]
During studying the Kurento docs, there is one Kurento design principle:

**Distribution of Media and Application Services**
Kurento Media Server and applications can be collo-cated, scalated or distributed among different machines.
A single application can invoke the services of more than one Kurento Media Server. The opposite also applies, that is, a Kurento Media Server can attend the requests of more than one application.

There are two cases about the high concurrency:
1. setting up a new conference
the signal server might can distribute the request to different kms, so that the signal server should manage all the kms info, if yes is this function already existing in signal server ?

2. joining in the existing conference 
if the work load of the responsible kms instance is too high to server other joining request, what will do ? so is that possible to distribute one conference to many kms instance ? since the media content and the session state should be shared and managed among those kms instances. Is that possible ?

Many thanks for your any suggestions or ideas :)

**Comment by thincal** [comment]
@jacdea @igracia could help with this problem ? It is really appreciated for any info / insights. Thanks.

**Comment by jcaden** [comment]
Hi,

Please, do not use the bugtracker for questions, use mailing list instead: https://groups.google.com/forum/#!forum/kurento

About the scaling, kurento itself does not have any solution for that, but there is an initiative that deals with autoscaling using the same APIs as Kurento does. It's called ElasticRTC the beta program is now in progress, if you need further information you can connect info@kurento.org

**Comment by thincal** [comment]
@jcaden thanks for your info, but the cluster support should be also an important feature for KMS, and I didn't see any related info documented. Anyway I will go to the Google groups for further help, thanks
