### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 823639792** [Kurento/bugtracker#324]
@micaelgallego 
Kurento Media Server version: 6.9.0
Found modules:
	'core' version 6.9.0
	'elements' version 6.9.0
	'filters' version 6.9.0

- Language:   Node.js
- Version: 8.14.0

**System description:**
	ubuntu16.04

**What steps will reproduce the problem?**
 Follow "Local Installation" https://doc-kurento.readthedocs.io/en/6.9.0/user/installation.html steps install and run service.
but the the service not run.
If  I run "/usr/bin/kurento-media-server", the console output:

Segmentation fault (thread 140349513139968, pid 9905)
Stack trace:
[__rawmemchr]
sysdeps/x86_64/rawmemchr.S:37
[_IO_str_init_static_internal]
/build/glibc-Cl5G7W/glibc-2.23/libio/strops.c:41
[__GI___isoc99_vsscanf]
/build/glibc-Cl5G7W/glibc-2.23/stdio-common/isoc99_vsscanf.c:43
[__isoc99_sscanf]
/build/glibc-Cl5G7W/glibc-2.23/stdio-common/isoc99_sscanf.c:35
0xC3FF at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstrtsp.so
[g_object_set_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x178F8
[g_object_set]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x17FCC
[kms_player_endpoint_get_type]
/usr/lib/x86_64-linux-gnu/gstreamer-1.5/libkmselementsplugins.so:0x9BA2
[g_cclosure_marshal_VOID__OBJECTv]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x130A7
[g_closure_invoke]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x101D4
[g_signal_emit_valist]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2A9A6
[g_signal_emit]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x2B08F
[gst_memory_new_wrapped]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x32655
[gst_bin_add]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x36800
0x1CDB8 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstplayback.so
[gst_element_change_state]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x5924E

**Comment by eric-jswang** [comment]
I had the same issue. Would you kindly let me know the solution to close this issue ? Thanks.

**Comment by 823639792** [comment]
@eric-jswang   https://github.com/Kurento/bugtracker/issues/325

**Comment by eric-jswang** [comment]
OK. I see this (https://github.com/Kurento/bugtracker/issues/343#issuecomment-459301168).
Thanks !
