### ISSUE TITLE
Unable to locate package kurento-media-server

### ISSUE THREAD

**Issue by RRJCNL3** [Kurento/bugtracker#327]
**KMS Version**: 6.90

**Please provide any additional information below.**
I tried to do a local installation of Kurento Media Server in a Ubuntu 16.04 Desktop and Server using the updated instructions in https://doc-kurento.readthedocs.io/en/stable/user/installation.html

First error encountered was when getting the keys but I was able to resolve this by changing
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83` to
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5AFA7A83`

However, running 
`sudo apt-get install kurento-media-server`
returns an `Unable to locate package kurento-media-server`

I was able to install kurento without problems last October so I am thinking that this has something to do with the update.

**Comment by phongnguyen192** [comment]
@RRJCNL3 I have the same issues and how to fix it ?

**Comment by RRJCNL3** [comment]
Hi, Which specific problem are you experiencing?

**Comment by phongnguyen192** [comment]
I am facing below error for command:
sudo apt-get install kurento-media-server
The last command results in these error messages:
E: Unable to locate package kurento-media-server

**Comment by RRJCNL3** [comment]
Were you successful in adding the keys? How about doing a sudo apt-get update?
Can you specify the machine where you are installing kms?
