### ISSUE TITLE
pass extra parameter from java client to kms

### ISSUE THREAD

**Issue by gyh007** [Kurento/bugtracker#330]
**KMS Version**:6.7.0

**Client libraries**
- Language: Java
- Version: kurento-client 6.7.1

Hi, 
i have a question, i want to pass some extra parameter from java client to kms, i found there the builder sush as Compositer.builder can pass two properties to c++ when it is created, one is constructorParams, one is properties, but the ServerMethods.cpp in kurento-media-server ignore the properties one just use constructorParams, why? what is the recommended way to pass extra parameter from java client to kms? thanks!

**Comment by micaelgallego** [comment]
You can pass extra parameters to KMS... but these parameters will be ignored by KMS. I mean... you can implement a custom KMS module or fork KMS project to include your one logic... but, by default, KMS will ignore any unknown property.

**Comment by MasterShi** [comment]
@gyh007 How do you cope with  this problem at last?
