### ISSUE TITLE
[SHOULD] Repo description, topics and URL Link

### ISSUE THREAD

**Issue by jason-fox** [Kurento/bugtracker#335]
Please click the edit button at the head of the [Kurento repo](https://github.com/Kurento/kurento-media-server) and amend the description link and topics as shown (or similar):

### Description:

> Media Server responsible for media transmission, processing, loading and recording.

### Link

> https://fiware-sth-comet.rtfd.io

### Topics

`fiware`, `kurento`, `media-server`

**Comment by j1elo** [comment]
Repo description, topics and link have been updated
Note the provided link is probably mistaken; the official project home page has been used.
