### ISSUE TITLE
[MUST] Docs do not use Chapter CSS

### ISSUE THREAD

**Issue by jason-fox** [Kurento/bugtracker#341]
Within the FIWARE [Docs Repo](https://github.com/Kurento/doc-fiware-readthedocs) a line has been added to display the text using chapter appropriate CSS:

https://github.com/Kurento/doc-fiware-readthedocs/blob/5ab1fd4ceb758c93c134d3c9666ddb2c18ffdb4e/conf.py#L193

This is not displayed on the existing `https://kurento.rtfd.io` site. My assumption is that this is because the ReadtheDocs project has been configured to display the latest **stable** release and  according to the RTD [Project setup](https://readthedocs.org/projects/kurento/) - there has been no version release since 6.6.0

Note that `https://kurento.readthedocs.io/en/latest/` - returns 404

Please do the following:

* Within the GitHub repo create releases for 6.8.0, 6.8.1 and 6.9.0
* Amend the RTD [config](https://readthedocs.org/projects/kurento/versions/) if necessary to generate `latest` documentation as well - i.e. ensure the **built** checkbox next to `latest` is checked

* MUST requirement from the TSC

**Comment by gtunon** [comment]
[FIWARE]
We are working in a full FIWARE documentation rework for new repositories and this issue will be addressed in this rework.

**Comment by jason-fox** [comment]
stale
