### ISSUE TITLE
kurento play rtsp stream trouble  

### ISSUE THREAD

**Issue by daiseita** [Kurento/bugtracker#343]
i use the sample  code  https://github.com/lulop-k/kurento-rtsp2webrtc   
try to  play IP Cam rtsp stream on the web page  but,  samething wrong happened  
the log show 'reconnect to server' constatly .   i chage  2,3 rtsp source to try  and  the result is same.

does anyone can tell me how to fix this problem ?  or   did i do somethine wrong?

**KMS Version**:
6.9.0

**Client libraries**
- Language:  JavaScript
- Version:

**Browsers tested**
- Chrome:

**System description:**
	KMS  

**What steps will reproduce the problem?**
1.  i build kurento media server 6.9.0    on  ubutu 16.0.4  with no stun 
2.  i build sample code https://github.com/lulop-k/kurento-rtsp2webrtc on same machine
3.  i try to run the sample code 
4.  i put in rtsp url   like rtsp://192.168.168.24:554/h264   and  start
5.  client can not connect to kurento websocket server  
6.  log show to message 'reconnect to server' constantly
7.  i check  kurento server   , evertime i try to play rtps stream   the websocket is shut down 

**What is the expected result?**
play a  IP Cam rtsp stream on  the web page
**What happens instead?**
log show to message 'reconnect to server' constantly

**Please provide any additional information below.**
i try to play a  mjpeg stream on  this sample code  and  it  can work

**Comment by rura6502** [comment]
@823639792 in 6.9.1-20181221, I met another error this. could you please help me?

```
0:08:35.414865361     1 0x7f351c2864a0 WARN            uridecodebin gsturidecodebin.c:939:unknown_type_cb:<uridecodebin1> warning: No decoder available for type 'application/x-rtp, media=(string)application, payload=(int)98, clock-rate=(int)90000, encoding-name=(string)VND.ONVIF.METADATA, a-recvonly=(string)"", ssrc=(uint)3938144230, clock-base=(uint)2268877219, seqnum-base=(uint)1, npt-start=(guint64)0, play-speed=(double)1, play-scale=(double)1'.
0:08:35.414944520     1 0x7f351c2864a0 WARN                 default descriptions.c:1221:gst_pb_utils_get_codec_description: No description available for media type: application/x-rtp
0:08:35.414949850     1 0x562e77839cc0 WARN          playerendpoint kmsplayerendpoint.c:1335:process_bus_message:<kmsplayerendpoint1> Error code 6: 'No decoder available for type 'application/x-rtp, media=(string)application, payload=(int)98, clock-rate=(int)90000, encoding-name=(string)VND.ONVIF.METADATA, a-recvonly=(string)"", ssrc=(uint)3938144230, clock-base=(uint)2268877219, seqnum-base=(uint)1, npt-start=(guint64)0, play-speed=(double)1, play-scale=(double)1'.', element: uridecodebin1, parent: internalpipeline
0:08:35.414968078     1 0x7f351c2864a0 WARN               decodebin gstdecodebin2.c:4565:gst_decode_bin_expose:<decodebin4> error: no suitable plugins found:
Missing decoder: application/x-rtp (application/x-rtp, media=(string)application, payload=(int)98, clock-rate=(int)90000, encoding-name=(string)VND.ONVIF.METADATA, a-recvonly=(string)"", ssrc=(uint)3938144230, clock-base=(uint)2268877219, seqnum-base=(uint)1, npt-start=(guint64)0, play-speed=(double)1, play-scale=(double)1)

0:08:35.414981495     1 0x562e77839cc0 WARN          playerendpoint kmsplayerendpoint.c:1338:process_bus_message:<kmsplayerendpoint1> Debugging info: gsturidecodebin.c(939): unknown_type_cb (): /GstPipeline:internalpipeline/GstURIDecodeBin:uridecodebin1
0:08:35.415472087     1 0x7f3530002680 WARN                 basesrc gstbasesrc.c:2948:gst_base_src_loop:<udpsrc13> error: Internal data flow error.
0:08:35.415493829     1 0x7f3530002680 WARN                 basesrc gstbasesrc.c:2948:gst_base_src_loop:<udpsrc13> error: streaming task paused, reason not-linked (-1)
0:08:35.518630037     1 0x7f35b4004900 INFO          webrtcendpoint kmswebrtcendpoint.c:439:kms_webrtc_endpoint_add_ice_candidate:<kmswebrtcendpoint1> Add ICE candidate 'candidate:562403431 1 udp 1685921535 119.65.194.26 28535 typ srflx raddr 192.168.11.35 rport 50350 generation 0 ufrag 5TqI network-id 3' for session 'kmswebrtcendpoint1-sess0'
```

**Comment by justinchoi97** [comment]
Hi I am having exact same issue trying to ingest RTSP using lulop-k's repo.
PlayerEndPoint can ingest http fine - however when inputting any RTSP url, it appears to kill KMS and therefore has to restart it. 
I have checked that the URL is valid by checking it with both VLC and gstreamer (Both plays the streams fine). 
I am running Kurento on a local machine so no docker. My kurento version is 6.9.0. 
Any help would be appreciated  thanks

**Comment by rura6502** [comment]
@justinchoi97 I solved this problem. This problem was solved in 6.9.1 version, but it just is in pre-release version or 6.9.1 docker. but if you use docker, have to set the coturn. you can see the pre-release install document in the official site. good luck.

**Comment by lc2a** [comment]
@rura6502 ,
I got below error when play rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov with PlayerEndPoint & WebRtcEndpoint (lulop-k's repo)

user@kurento:~$ dpkg-query -l kurento-media-server | awk '$1 == "ii" { print $3; exit }'
**6.9.1-1kurento1.16.04**~20190214125843.gbp46086b


`user@kurento:~$ tail -f /var/log/kurento-media-server/errors.log


2019-02-19T16:37:32+00:00 -- New execution
Segmentation fault (thread 139680112539392, pid 425)
Stack trace:
[__rawmemchr]
sysdeps/x86_64/rawmemchr.S:37
[_IO_str_init_static_internal]
/build/glibc-Cl5G7W/glibc-2.23/libio/strops.c:41
[__GI___isoc99_vsscanf]
/build/glibc-Cl5G7W/glibc-2.23/stdio-common/isoc99_vsscanf.c:43
[__isoc99_sscanf]
/build/glibc-Cl5G7W/glibc-2.23/stdio-common/isoc99_sscanf.c:35
[gst_rtspsrc_set_property]
/opt/kurento/gst/rtsp/gstrtspsrc.c:1102
[object_set_property]
/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gobject.c:1423
[g_object_set]
/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gobject.c:2275
[kms_player_endpoint_uridecodebin_element_added]
/opt/kurento/src/gst-plugins/kmsplayerendpoint.c:1293
[g_cclosure_marshal_VOID__OBJECTv]
/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gmarshal.c:2105 (discriminator 4)
[closure_invoke_notifiers]
/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gclosure.c:290
[g_signal_emit_valist]
/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gsignal.c:3294
[g_signal_emit]
/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gsignal.c:3443
[gst_bin_add_func]
/opt/kurento/gst/gstbin.c:1298
[gst_bin_add]
/opt/kurento/gst/gstbin.c:1374
[setup_source]
/opt/kurento/gst/playback/gsturidecodebin.c:2220
[gst_element_change_state]
/opt/kurento/gst/gstelement.c:2648
`

Kindly advise. Thanks

**Comment by j1elo** [comment]
Please reopen if this still happens with Kurento >= 6.15.0
