### ISSUE TITLE
Unable to locate package kurento-media-server

### ISSUE THREAD

**Issue by lendvair** [Kurento/bugtracker#348]
I've followed the these installation guides:

https://openvidu.io/docs/deployment/deploying-ubuntu/
https://doc-kurento.readthedocs.io/en/stable/user/installation.html#local-installation

But the result is always the same: **E: Unable to locate package kurento-media-server**

As you can see on the screenshot, the apt-get update command also fails due the connectivity problems.

![virtualbox_ubuntu 16 04 5 lts desktop_14_02_2019_09_20_33](https://user-images.githubusercontent.com/3914496/52773129-850d7980-303a-11e9-9f8b-929f6a705172.png)

**Comment by madsinamsterdam** [comment]
Have the same issue on ubuntu 18.04.4.

**Comment by j1elo** [comment]
_Works For Me_ (™)

The installation works for a clean, empty system, so it must be something wrong on your side:

```
# Starts a clean in-place Docker container
docker run --rm -i ubuntu:18.04 /bin/bash <<'EOL'

apt-get update && apt-get install --no-install-recommends --yes \
    gnupg

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83

echo "deb [arch=amd64] http://ubuntu.openvidu.io/6.13.0 bionic kms6" \
    | tee /etc/apt/sources.list.d/kurento.list

apt-get update && apt-get install --no-install-recommends --yes \
    kurento-media-server


echo "Kurento Media Server installed successfully! version check:"
kurento-media-server --version

EOL
# In-place Docker container commands end here
```
