### ISSUE TITLE
KMS 6.4.1~1.g3ffe480, kurento-repository 6.3.1-SNAPSHOT, Ubuntu Server 14.04 LTS -- Can’t seek recorded video from kurento repository

### ISSUE THREAD

**Issue by hdlopesrocha** [Kurento/bugtracker#35]
Hi! 
I can't seek recorded videos through player.setPosition(...), player.getVideoInfo().getIsSeekable() always returns false.

Those are my dependencies:
libraryDependencies += "org.kurento" % "kurento-java" % "6.3.0"
libraryDependencies += "org.kurento" % "kurento-client" % "6.3.0"
libraryDependencies += "org.kurento" % "kurento-repository-client" % "6.3.0"

Thanks ;-)

**Comment by dfernandezlop** [comment]
Hi,

Could you tell me please:

- What version of KMS are you using.
- What video are you using.
- Have you tried with other video.
- Could you share your video to check this behaviour?

Thanks.
David.

**Comment by hdlopesrocha** [comment]
I am using WebM and playing it with PlayerEndpoint directly from Kurento-Repostory (MongoDB).
The video was recorded by RecorderEndpoint, I am recording parts of 10 seconds and all of them have this issue.

[videos.zip](https://github.com/Kurento/bugtracker/files/149594/videos.zip)

**Comment by dfernandezlop** [comment]
Hi,

The files recorded using the RecorderEndpoint through http are not seekables. The problem is that we record the video while it arrives to the recorder and when the video ends we can't write the headers at the begining of the file so the file is not seekable.

Sorry for the troubles.
Best regards.
David.

**Comment by hdlopesrocha** [comment]
Ok, it makes sense.
It could be interesting to have an option on the recorder to upload the recorded file on end, so it could be seekable.

**Comment by dfernandezlop** [comment]
Ok, we will try to offer a solution for this situation.

I'm going to close the thread.
