### ISSUE TITLE
cannot make webrtc call in Chrome Dev Version 74.0.3729.22 

### ISSUE THREAD

**Issue by huaxinjiayou** [Kurento/bugtracker#355]
change to dtls 1.2？

https://groups.google.com/forum/#!searchin/discuss-webrtc/removing$20tls$201.0$2C$20tls$201.1$20and$20dtls$201.0$20support$20from$20webrtc%7Csort:date/discuss-webrtc/OhMcXQOA_wE/vaWApOE4AwAJ

**Comment by xenyou** [comment]
any information?

chrome M74 will be available soon.
If kurento can not handle this, all systems kurento is used will be dead.

**Comment by alexlapa** [comment]
@xenyou ,

Its getting fixed [5e920718](https://github.com/Kurento/gst-plugins-bad/commit/5e920718bb5e6a056c6b4b4c6a19e32d0f9436aa)

**Comment by j1elo** [comment]
DTLS 1.2 becomes mandatory starting from Chrome 74. Yesterday, all required changes to Kurento were done, so you should be able to test it with the latest nightly build: https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html#kurento-media-server

You can also test with nightly Docker builds: https://hub.docker.com/r/kurento/kurento-media-server-dev

**Comment by xenyou** [comment]
I've installed nightly build and new gstreamer1.5-plugins-bad packge.
Now M74 works fine.

**Comment by j1elo** [comment]
Fixed by Kurento/gst-plugins-bad@5e920718bb5e6a056c6b4b4c6a19e32d0f9436aa
