### ISSUE TITLE
Upgrade WebSocket libraries

### ISSUE THREAD

**Issue by j1elo** [Kurento/bugtracker#356]
- [X] Java: `io.netty` libraries.

- [ ] Javascript: `websocket-stream` used by KurentoForks/reconnect-ws (https://groups.google.com/d/topic/kurento/AvUgqLd5_Nc/discussion)

- [x] C++: `websocketpp` library in Kurento Media Server: remove custom fork (in-place source code at path [kurento-media-server/server/transport/websocket/websocketpp](https://github.com/Kurento/kurento-media-server/tree/58698a86e3c23beac6cdf44e248267d0d6645c3c/server/transport/websocket/websocketpp)), instead use system package `libwebsocketpp-dev`.
  DONE in commit https://github.com/Kurento/kurento-media-server/commit/f39f530c6812889b40689c104aced37060261dac

**Comment by agonza1** [comment]
It seems to be related with this: 
https://github.com/progre/reconnect-ws/pull/1
and
https://github.com/Kurento/kurento-jsonrpc-js/pull/1

**Comment by JoseGoncalves** [comment]
Upgrading `websocket-stream` to v3.3.3 works for me and removes the vulnerabilities reported by `npm` with the old `ws` version that is currently pulled.

Tried to upgrade to latest `websocket-stream` (v5.5.0) with no success.
See my comments in https://github.com/KurentoForks/reconnect-ws/pull/2.

**Comment by j1elo** [comment]
Related: https://github.com/Kurento/bugtracker/issues/373

**Comment by j1elo** [comment]
Using https://github.com/Kurento/bugtracker/issues/439 to track this.
