### ISSUE TITLE
KMS 6.4.1~1.g3ffe480, Ubuntu Server 14.04 LTS -- ZBarFilter's strange behaviour with 2 simultaneous QRCodes

### ISSUE THREAD

**Issue by hdlopesrocha** [Kurento/bugtracker#36]
When showing 2 QR Codes at the same time, ZBarFilter's EventListener<CodeFoundEvent>().onEvent() is called multiple times per second, they seem fighting each other.

BTW, I don't know if I have a bug, but ZBarFilter stops detecting QRCodes after a while (+/- 1 minute)

**Comment by jcaden** [comment]
ZbarFilter right now tries to send all qr codes it finds in a frame. If the same qr is detecting no events are raised for some time, but if there are more than one, they are reported all the time. It's the way it works (probably not the best one).

If it stops working is because the library we are using is not detecting any code. We are not maintaining the detection, just propagating its events. Please reports the bugs you find there to gstreamer.

**Comment by hdlopesrocha** [comment]
I saw the source of kms-filters, apparently I didn't found anything wrong.
Meanwhile I had this error on kurento-media-server:
`Segmentation fault (thread 140294790989568, pid 1992)
Stack trace:
[g_type_check_instance_is_fundamentally_a]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x3488D
[g_object_ref]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x14A1E
[g_weak_ref_get]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0:0x1A5B5
[check_if_flow_media]
/usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.6:0x1B885
[gst_structure_fixate]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x99E44
[g_test_get_filename]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x70965
[start_thread]
/build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312 (discriminator 2)
[clone]
sysdeps/unix/sysv/linux/x86_64/clone.S:113
`

**Comment by dfernandezlop** [comment]
This trace is a known bug , we are trying to fix it but is not related with the topic, you can open another one. 

I'm going to close the bug because we don't control the GStreamer filter zbar.

**Comment by dserrada** [comment]
Sorry but: What's the known bug associated with the trace? I'm looking for it but i couldn't find it.

**Comment by jcaden** [comment]
@dserrada  The previous version of kurento media server had a buggy implementation of flow in and flow out events. This is already fixed on 6.5.0. The trace present in [this comment](https://github.com/Kurento/bugtracker/issues/36#issuecomment-190474314) is related to this bug.

**Comment by dserrada** [comment]
Ok.

I'm using Version: 6.4.1~5. and I'm seeing this trace from time to time, with the associated server crash. Is related to any element o test case I can avoid?

**Comment by jcaden** [comment]
You should update, there is no way to workaround it.
