### ISSUE TITLE
KMS 6.7.1 crash with "SIGABRT"

### ISSUE THREAD

**Issue by zjhui2015** [Kurento/bugtracker#369]
**KMS Version**:6.7.1

**Ubuntu Version**:16.04

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial~20170725171352.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1.xenial~20170725160546.81.eebfdab  amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial~20170725170621.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-core                             6.7.1.xenial.20180321183643.47e0370        amd64        Kurento Core module
ii  kms-elements                         6.7.1.xenial.20180321184406.5aaf4a0        amd64        Kurento Elements module
ii  kms-filters                          6.7.1.xenial.20180321185049.7f2d045        amd64        Kurento Filters module
ii  kms-jsonrpc                          6.7.1.xenial~20180321183209.1.637bf2a      amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.7.1.xenial.20180321185711.dd49a2c        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial~20170725152356.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1.xenial~20170725160546.81.eebfdab  amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from openh264

**Client libraries**

- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:

**Browsers tested**

Add OK or FAIL, along with the version, after browsers where you have tested
this issue:

- Chrome:

**System description:**

Please describe your setup (where is KMS located, where are the clients,
whether you are using STUN/TURN, etc.)

**What steps will reproduce the problem?**

kms crash

warning: .dynamic section for "/lib64/ld-linux-x86-64.so.2" is not at the expected address (wrong library or version mismatch?)
warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libnice.so.10" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/kurento-media-server -DFOREGROUND'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1122b92428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f104b494700 (LWP 3499))]
(gdb) bt
#0  0x00007f1122b92428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f1122b9402a in __GI_abort () at abort.c:89
#2  0x000000000051a552 in Debug::DeathHandler::SignalHandler(int, void*, void*) ()
#3  <signal handler called>
#4  0x00007f1123e87d69 in sigc::internal::signal_emit1<void, kurento::ElementDisconnected, sigc::nil>::emit(sigc::internal::signal_impl*, kurento::ElementDisconnected const&) ()
   from /usr/lib/x86_64-linux-gnu/libkmscoreimpl.so.6
#5  0x00007f1123e7f76f in kurento::MediaElementImpl::mediaFlowInStateChange(int, char*, KmsElementPadType) () from /usr/lib/x86_64-linux-gnu/libkmscoreimpl.so.6
#6  0x00007f1123e76989 in ?? () from /usr/lib/x86_64-linux-gnu/libkmscoreimpl.so.6
#7  0x00007f112416bfa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f112417dfc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f1124186d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f112418708f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f1121af6554 in ?? () from /usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.6
#12 0x00007f112441b29b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#13 0x00007f112247a904 in g_hook_list_marshal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f1124419afb in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#15 0x00007f112441d98b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#16 0x00007f1124425533 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#17 0x00007f112440e5e3 in gst_proxy_pad_chain_default () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#18 0x00007f112441d5cf in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#19 0x00007f1124425533 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#20 0x00007f112440e5e3 in gst_proxy_pad_chain_default () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#21 0x00007f112441d5cf in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#22 0x00007f1124425533 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#23 0x00007f1110ab5e1e in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstcoreelements.so
#24 0x00007f112444fc5b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0
#25 0x00007f11224b155e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f11224b0bc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f1124f916ba in start_thread (arg=0x7f104b494700) at pthread_create.c:333
#28 0x00007f1122c6441d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**What is the expected result?**

**What happens instead?**

**Does it happen with one of the tutorials?**

**Please provide any additional information below**

**Comment by j1elo** [comment]
Probably closed this in Kurento/kms-core#19, re-open if the issue still happens.
