### ISSUE TITLE
kurento-client-js dependency issue

### ISSUE THREAD

**Issue by tgabi333** [Kurento/bugtracker#37]
`dockerode` should be a devDependency.

**Comment by dfernandezlop** [comment]
Hi,

@rbenitez Could you take a look to this?

**Comment by rbenitez** [comment]
Yes, I agree. It's fixed in this [commit](https://github.com/Kurento/kurento-client-js/commit/fe7f4df65989d11f5b85f7aae3d8a4a19ad0d3a6)
