### ISSUE TITLE
Datachannel not opening in Firefox, stuck in connecting state

### ISSUE THREAD

**Issue by carlaAL** [Kurento/bugtracker#370]
**KMS Version**:

Kurento Media Server version: 6.9.0
Found modules:
	'core' version 6.9.0
	'elements' version 6.9.0
	'filters' version 6.9.0

**Ubuntu Version**

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64                    1.8.2.1.xenial~20181023163456.96.493eee4     amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                     0.1.15-1kurento2                             amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64              1.8.1.1.xenial~20181023161445.100.3db37b1    amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64             1.8.1.1.xenial~20181023154838.55.7b19cfd     amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64             1.8.1.1.xenial~20181023160032.112.9ee4248    amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64             1.8.1.1.xenial~20181023162927.89.2685b0f     amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64               1.8.1.1.xenial~20181023160032.112.9ee4248    amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                        1.8.1.1.xenial~20181023154838.55.7b19cfd     amd64        GStreamer plugins for X11 and Pango
ii  kms-core                                    6.9.0-0kurento1.16.04                       amd64        Kurento Core module
ii  kms-datachannelexample                      6.7.1.xenial~20181210204015.9.9c2cf6a        amd64        Kurento WebRTC DataChannel example
ii  kms-elements                                6.9.0-0kurento1.16.04                       amd64        Kurento Elements module
ii  kms-filters                                 6.9.0-0kurento1.16.04                       amd64        Kurento Filters module
ii  kms-jsonrpc                                 6.9.0.xenial.20181210195903.71b45ec          amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                                  1.6.3.xenial.20181023152331.d78deb7          amd64        Kurento jsoncpp library
ii  kurento-media-server                        6.9.0-0kurento1.16.04                       amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64         1.8.1.1.xenial~20181023161445.100.3db37b1    amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64        1.8.1.1.xenial~20181023154838.55.7b19cfd     amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                     1.8.1.1.xenial~20181023153550.170.0d6031b    amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                             0.1.15-1kurento2                             amd64        ICE library (shared library)
ii  libreoffice-avmedia-backend-gstreamer       1:5.1.6~rc2-0ubuntu1~xenial6                 amd64        GStreamer backend for LibreOffice
ii  openh264-gst-plugins-bad-1.5:amd64          1.8.1.1.xenial~20181023161445.100.3db37b1    amd64        GStreamer plugins from openh264

**Client libraries**

- Language:  Node.js and JavaScript
- Version: Nodejs v8.12.0

**Browsers tested**

Add OK or FAIL, along with the version, after browsers where you have tested
this issue:

- Chrome: OK
- Firefox: 66-63 FAIL- datachannel state connecting
- Safari: OK

**System description:**
My KMS is in an Ubuntu 16.04 in another computer in the same network as my client. I am running my client in windows 10. The STUN/Turn servers are located and accesible from a debian server I configured.

**What steps will reproduce the problem?**

1. I log in in my application and call the user
2. Once the call is accepted I can see and hear the other point (no matter the browser)
3. Datachannel is still stuck in connecting state in Firefox

**What is the expected result?**
Datachannel opens and messages can be send

**What happens instead?**
Datachannel is never opened in Firefox though the peer connection is established and connected

**Does it happen with one of the tutorials?**
Javacript's Datachannel demo does not open the datachannel in Firefox either.

**Please provide any additional information below**
Code from my nodejs
```
  room.pipeline.create('WebRtcEndpoint', {useDataChannels: true}, (error, webRtc) => {
      webRtc.on('DataChannelOpen', function () {
                console.log("--------------Data channel opened.--------------");
      });
 });

```
From my javascript:

```
   pc = new RTCPeerConnection(pc_config);
  dataChannel = pc.createDataChannel('send', {reliable: false});
  dataChannel.binaryType = 'arraybuffer';
  dataChannel.onerror = function (error) {
                      console.log(error);
                    };
  dataChannel.onmessage = function (event) {
                        console.log(event);
                    };
  dataChannel.onclose = function () {
                        console.log('close data');
                    };
  dataChannel.onopen = function () {
                        console.log('OPEN');
                    };
  pc.ondatachannel = e => {
                console.log('ondatachannel')
            }
```

**Comment by carlaAL** [comment]
While debugging I found that the iceComponentState changes to FAILED in Firefox but I do not know how to see the reason

**Comment by fivebats** [comment]
@carlaAL : I have a similar issue, and note that it began on Firefox version 63. What version of Firefox are you using? I would be interested to see if your problem goes away on FF 62 or earlier.

**Comment by carlaAL** [comment]
@fivebats I have just tried it on FF 62 and it works, in FF 66 and 65 it does not...

**Comment by carlaAL** [comment]
Are there any news on this matter? I want to be able to communicate through datachannels instead of websockets once connected

**Comment by j1elo** [comment]
> @fivebats I have just tried it on FF 62 and it works, in FF 66 and 65 it does not...
> From what I have read I think it is related to the SDP format, in version 63 they've changed from:
> 
> ```
> m=application 63743 DTLS/SCTP 5000
> a=sctpmap:5000 webrtc-datachannel 256
> ```
> 
> to:
> `m=application 54111 UDP/DTLS/SCTP webrtc-datachannel a=sctp-port:5000`
> 
> maybe KMS is not taking this into account

This is exactly the issue. We've received multiple reports from other users and the change in SDP syntax seems to be the cause for this problem.

The SDP syntax changed in Firefox and will soon change in Chrome too; for that reason Kurento is not able to process it correctly. We are aware of this issue and will try to fix it as soon as possible, hopefully it can be solved for the next release (no release date yet, though)

Other reports:
* [Datachannel stuck in 'connecting' state](https://groups.google.com/d/topic/kurento/imvNipCJxe0/discussion)
* [RTCDataChannel getting stuck in 'connecting' state in Firefox](https://groups.google.com/d/topic/kurento/iaDn1eV4Ix0/discussion)

Refs:
* [PSA: Changes in SDP syntax for SCTP media sections](https://groups.google.com/d/topic/discuss-webrtc/L1FepJuNXOs/discussion)

**Comment by j1elo** [comment]
Please check out the fix branch `fix-datachannel-sdp` and give some feedback to let us know if the problem is solved.

You can try it out either with `apt-get install`, using this repository line (Ubuntu Xenial only):
```
deb http://ubuntu.openvidu.io/fix-datachannel-sdp xenial kms6
```

or with the experimental Docker image (https://hub.docker.com/r/kurento/kurento-media-server-exp):
```
kurento/kurento-media-server-exp:fix-datachannel-sdp
```

**Comment by fivebats** [comment]
This fix works for me. I used the experimental Docker image and Firefox nightly 70.0a1 (2019-07-16).
