### ISSUE TITLE
Communication problem between KMS server and JavaScript based client

### ISSUE THREAD

**Issue by daminichopra** [Kurento/bugtracker#371]
we are working on kurento for streaming. We have successfully installed KMS server by source.
For testing while we are running the kurento client based on JavaScript (hello-world), facing an issue of communication between client and server.
We are able to get local stream on web broswer via webcam but for remote stream it shows an connectivity error with ws://localhost:8888/kurento please refer below image for the same.
![kurento](https://user-images.githubusercontent.com/35693908/57020382-b9aacd80-6c46-11e9-9783-8b95cb039ea6.png)

**Comment by j1elo** [comment]
This has happened recently to other user, solution was to configure Secure WebSocket (**WSS://**) in Kurento Media Server: https://groups.google.com/d/topic/kurento/5rsnYLn1y48/discussion

**Comment by micaelgallego** [comment]
Also consider using OpenVidu Platform (https://openvidu.io) to add WebRTC to web and mobile applications. It is based on Kurento and it is easier to use.

**Comment by daminichopra** [comment]
Thanks.
I have installed it through docker latest and it works on firefox 66.0.4 version only on mobile(android) but not on google chrome 73+ version Is there any limitation to use kurento not on google chrome.
Also, is there any document in which it is explained how streaming coming from any file,network,camera is feed in KMS and can use in other application that we want to register or any endpoints by which we can fed data from KMS to our application.

**Comment by j1elo** [comment]
> Also, is there any document in which it is explained how streaming coming from any file,network,camera is feed in KMS and can use in other application that we want to register or any endpoints by which we can fed data from KMS to our application.

I'd say try the PlayerEndpoint which has support for files, network cameras (RTP, RTSP), etc. But **this** would be a good question to ask in the community mailing list, so please do so. Here in the bugtracker, we'll focus only on the issue described in the title and first post.

Please make sure you run everything in localhost, I would also suggest that you start by running locally if you have Ubuntu Xenial or Bionic, so you can discard it's a problem with Docker ports. Lastly, have a look at browser console messages, and also at KMS logging messages, to see if there are any warnings / errors that can give more information...

**Comment by j1elo** [comment]
Closing because it's not (proved to be) a bug in Kurento
