### ISSUE TITLE
kurento-client ws package vulnerability

### ISSUE THREAD

**Issue by agonza1** [Kurento/bugtracker#373]
**KMS Version**:
```
Kurento Media Server version: 6.10.0
Found modules:
        'core' version 6.10.0
        'elements' version 6.10.0
        'filters' version 6.10.0
```

**Ubuntu Version**

Ubuntu 16.04

**Client libraries**

- Repo: https://github.com/Kurento/kurento-client-js
- Language: Node.js
- Version: 6.10.0 (latest)

**What steps will reproduce the problem?**

1. npm install kurento-client
2. npm audit
3. Result: found 3 vulnerabilities (1 low, 2 high)

**What is the expected result?**
0 vulnerabilities

**What happens instead?**
found 3 vulnerabilities (1 low, 2 high)

Level | Vulnerability
-- | --
High | Denial of Service
High | DoS due to excessively large websocket message
Low | Remote Memory Disclosure

 Package:  ws
 Patched in:  >= 1.0.1

**Does it happen with one of the tutorials?**
Yes, all

**Comment by agonza1** [comment]
Seems to work fine with the following changes. It needs to merge:
https://github.com/Kurento/kurento-jsonrpc-js/pull/1
and
https://github.com/progre/reconnect-ws/pull/1

So we might need to additionally update the reconnect-ws and kurento-jsonrpc-js modules in the package.json

**Comment by RobotnickIsrael** [comment]
There us another problem with the way it's packed.

Since reconnect-ws, qunit-cli and qunit-reporter-junit are going to github, 
it makes kurento-client not installable on computers connected to an idependent artifactory and not to the internet (and therfore no connection to github).
Can you please not use forks as these?

**Comment by N-Olbert** [comment]
@j1elo Are there any updates on this? I haven't investigated the vulnerabilities, but since two are marked as "high", the current situation does not seem ideal.

**Comment by koendhondt** [comment]
Hi, any progress on this? This issue appears to be open for more than 3.5 years now.

**Comment by j1elo** [comment]
Using https://github.com/Kurento/bugtracker/issues/439 to track this.
