### ISSUE TITLE
I can't save data streaming when deploy to server

### ISSUE THREAD

**Issue by caodat** [Kurento/bugtracker#375]
I can't save data streaming to server when using different network for live streaming.
It work for Local and LAN network
Kurento infomation:
- Kurento media server: 6.7.1
- Ubuntu server 16.04
I get some message error:
```
Pipeline error encountered: UNEXPECTED_PIPELINE_ERROR: Could not open file "/root/Documents/kurento-video/2/3/video-20190523.073415.webm" for writing. (gstfilesink.c(438): gst_file_sink_open_file (): /GstPipeline:pipeline29/GstFileSink:filesink16:
system error: Permission denied)(errCode=6)

Pipeline error encountered: UNEXPECTED_PIPELINE_ERROR: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. (gstbasesink.c(5244): gst_base_sink_change_state (): /GstPipeline:pipeline29/GstFileSink:filesink16:
Failed to start)(errCode=4)
```
Please help me!
Thanks!

**Comment by j1elo** [comment]
The error message tells it all to you:
```
Could not open file "/root/Documents/kurento-video/2/3/video-20190523.073415.webm" for writing.
system error: Permission denied
```

Permission denied to write that file. Kurento doesn't have permissions, or the file is in a read-only filesystem. In any case, it's a system config issue, not a bug in Kurento.

**Comment by caodat** [comment]
Thank you.I find problem. Set permission resolve my issue

**Comment by yasareni1** [comment]
How did u checked permission for this issue. please explain the process which you followed

**Comment by caodat** [comment]
On my server: Location /root/directory => Not working
Change location /home/directory => Working

**Comment by fearchannel** [comment]
Ok so what permission did u set?

**Comment by j1elo** [comment]
Note if you run Kurento by hand (`/usr/bin/kurento-media-server`), it runs with your user:

```
ps u "$(pgrep -f kurento-media-server)"
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
juan   4803  0.0  0.1 386820 23632 ?        Sl   20:16   0:00 /usr/bin/kurento-media-server
```

but if you run it with the system scripts (`sudo service kurento-media-server start`, or with systemctl), then it runs with the user `kurento`:

```
ps u "$(pgrep -f kurento-media-server)"
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
kurento   4803  0.0  0.1 386820 23632 ?        Sl   20:16   0:00 /usr/bin/kurento-media-server
```

so, you must ensure that the correct user has access to the destination dir. For example, the user `kurento` will NOT have write access to your user's /home/username/ folder, by default. It won't have write permissions for anything under /root/, either. You need to create a dir that is owned by the correct user, the one that is running KMS; of other solution would be to `chmod 777 /any/target/dir/` and then that target dir will be writable by all users of the system.
