### ISSUE TITLE
Memory Usage High 

### ISSUE THREAD

**Issue by garg-geek** [Kurento/bugtracker#376]
- We are using kurento 6.9 On Ubuntu Xenial. 
- Our use case is very simple. There is only one publisher and one listener. 
- I noticed that memory used by kurento keeps increasing when publisher count increase but when publisher count decreases then memory usage does not decrease(it decrease only by .5% in some cases). I can see this issue when publisher count is 30 and reduce the publisher count to 0.
- I have done this activity many times and every time result is same. Somehow kurento is not able to claim the memory. 
- I disconnected my web socket connection(through which i created endpoint and pipelines) and after 4-5 min i see log that garbage collector running but after this also memory usage does not decrease. Can you help me identify the reason.

**Comment by cnliusen** [comment]
I am using kurento 6.10. I met the same problem. The memory is increasing slowly

**Comment by cnliusen** [comment]
This can also be reproduced with the `One to many video call` example project.

1. Open two pages, one as presenter and one as viewer
2. Let the presenter broadcast video to the viewer for 30s and then stop both the presenter and the viewer.
3. Repeat 1 and 2 for 10 times.

When I stop the presenter and the viewer, I can see only some of the memory is freed.

For my own project, there are many users so the memory increase is obvious.

I also want to mentioned that I have disabled VP8 encoding. I don't know if this is related. I haven't got a chance to test it.

**Comment by cnliusen** [comment]
I have done another test using the official [Hello World example](https://doc-kurento.readthedocs.io/en/6.10.0/tutorials/js/tutorial-helloworld.html). I modify `index.js` by adding a function `test` and invoke it when window loaded. So when I run the server and open the page, the page will:

1. stream for 5 seconds
2. stop streaming for 5 seconds
3. repeats 1 and 2 forever

```js
window.onload = function()
{
  ...
  test();
}

function test() {
  uiStart();
  setTimeout(() => {
    uiStop();
    setTimeout(() => {
      test()
    }, 5 * 1000);
  }, 5 * 1000);
}
```

I opened 23 pages and plotted the memory:

<img width="1577" alt="Screen Shot 2019-05-30 at 3 17 40 PM" src="https://user-images.githubusercontent.com/1041742/58669094-ec9cbb80-82ef-11e9-89ff-2ba816078128.png">

**Comment by j1elo** [comment]
How exactly is the memory usage measured? What command-line command would be equivalent to the measurement system you use?

**Comment by cnliusen** [comment]
The memory usage in the graph above was measured by `collecd` with its `memory` plugin. It can also be measured by run the following script periodically:

```bash
#!/bin/bash

process_name=kurento-media-server

pid=$(pidof $process_name)

# exit if kms is not running
if [[ -z $pid ]]; then
    exit 0
fi

memory_mb=$(ps -o rss $pid | tail -1 |  grep -v grep | awk '{printf $1/1024}')

# store the log
echo $(date +%s),$memory_mb >> /tmp/kms.log
```

I named this script `kmslog.sh` and run it with `crontab`:

```crontab
* * * * * /home/ubuntu/kmslog.sh 
```

So the script is called every one mintues. This gives the same result as `collectd`.  Here is a sample output. Each line is a unix timestamp followed by the memory usage in MB. This log was generated when I opened 8 test pages.

```log
1559580181,21.3672
1559580241,21.3672
1559580301,44.418
1559580361,50.6719
1559580421,57.0977
1559580481,61.6562
1559580541,65.1719
1559580601,69.3398
1559580661,72.3984
1559580721,76.9023
1559580781,78.8125
1559580841,82.7383
1559580901,84.5664
1559580961,88.1406
```

**Comment by skgith1** [comment]
Also having issues with memory on latest version of Kurento and Ubuntu 18.

Had the same problem using 6.6.0 on Ubuntu 16.

Also, another issues causing Kurento to stop working is high thread usage similar to memory it does not seems to close all threads when a broadcast stops or a viewer disconnects.

```
sudo service kurento-media-server status
....
Tasks: 3845 (limit: 4915)
```

**Comment by j1elo** [comment]
Possibly related to https://github.com/Kurento/bugtracker/issues/85

**Comment by cnliusen** [comment]
Any updates? I have tested this with KMS 6.12. This issue still exists.

**Comment by cnliusen** [comment]
I did the above test again. I used 8 pages. The memory increasing is much slower than before, however still some memory leaking.

<img width="734" alt="Screen Shot 2019-11-18 at 1 38 59 PM" src="https://user-images.githubusercontent.com/1041742/69096342-131ef200-0a09-11ea-94b3-4b82845c899c.png">

**Comment by j1elo** [comment]
Hi, we fixed several memory leaks in Kurento for 6.12, until we couldn't find any more leaks with Valgrind. Memory does still slowly increase, so I'm inclined to think this is not a memory leak issue any more (as Valgrind reports 0 leaks found), but instead a Kernel memory fragmentation issue.

Note that to detect *actual* memory leaks, [neither top nor ps are the right tool for the job; Valgrind is](https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#memory-usage-grows-too-high). In essence, measuring RSS only shows that the memory is not going back to the Kernel, but [that is a misleading indicator](https://stackoverflow.com/a/6005353) and doesn't imply that the process is actually losing memory.

We are experimenting with different implementations of memory allocators, such as [jemalloc](http://jemalloc.net/) or [tcmalloc](http://goog-perftools.sourceforge.net/doc/tcmalloc.html), which could be set up for the specific use case, and maybe provide better behavior regarding the memory allocation patterns of GStreamer (which represents 90% of the memory usage from Kurento)

**Comment by j1elo** [comment]
Actually, could you try running Kurento with jemalloc? We have had better memory behavior with that one, so maybe you can confirm that it works better in your use case. If you don't know how, I can provide further instructions to do so.

**Comment by skgith1** [comment]
I notice the same, memory builds up much much slower on 6.12 which is better (I resolved the task limit issue by setting DefaultTasksMax=infinity)

Unfortunately there seems to be a similar problem with kurento-client on node.js the memory will build infinitely and will only go down if the socket connection (from node to the media server) is severed. Never noticed this before.

**Comment by hdev72** [comment]
i have this problem in kurento client in node js
here is my logs:
kurento memory leak: pipelines count: 1    UsedMemory: 271468  
kurento memory leak: pipelines count: 1    UsedMemory: 273876 
kurento memory leak: pipelines count: 0    UsedMemory: 278136 
kurento memory leak: pipelines count: 1    UsedMemory: 278136   
kurento memory leak: pipelines count: 1    UsedMemory: 282540 
kurento memory leak: pipelines count: 1    UsedMemory: 283784 
kurento memory leak: pipelines count: 0    UsedMemory: 285612 
kurento memory leak: pipelines count: 0    UsedMemory: 286952 
kurento memory leak: pipelines count: 0    UsedMemory: 287656 
kurento memory leak: pipelines count: 0    UsedMemory: 287696  
kurento memory leak: pipelines count: 2    UsedMemory: 287748 Sessions: 748
kurento memory leak: pipelines count: 2    UsedMemory: 287796 Sessions: 746

sudo service kurento-media-server stop
sudo service kurento-media-server start

kurento memory leak: pipelines count: 0    UsedMemory: 23424 Sessions: 4


I think the memory leak problem is due to the accumulation of sessions, but now i dont know how can i remove unused sessions without restart server
