### ISSUE TITLE
Issue in RTP receiver tutorial - mvn -U clean spring-boot:run -Dkms.url=ws://localhost:8888/kurento

### ISSUE THREAD

**Issue by MinesNicaicai** [Kurento/bugtracker#378]
**KMS Version**:

6.10.0

**Ubuntu Version**

Ubuntu 18.04.2 LTS

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64                   1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                    0.1.15-1kurento3.18.04                          amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64             1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64            1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64            1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64            1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64              1.8.1-1kurento2.18.04                           amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                       1.8.1-1kurento1.18.04                           amd64        GStreamer plugins for X11 and Pango
ii  kms-core                                   6.10.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-elements                               6.10.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-filters                                6.10.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-jsonrpc                                6.10.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                                 1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kurento-media-server                       6.11.0-0kurento1.18.04~20190528094645.gbp738f49 amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64        1.8.1-1kurento2.18.04                           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64       1.8.1-1kurento1.18.04                           amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                    1.8.1-1kurento1.18.04                           amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                            0.1.15-1kurento3.18.04                          amd64        ICE library (shared library)
ii  libusrsctp                                 0.9.2-1kurento1.18.04                           amd64        sctp-refimpl library
ii  openh264                                   1.4.0-1kurento1.18.04                           amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64         1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                     0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins

**Client libraries**

- Language: <Java>
- Version: 11.0.3

**What steps will reproduce the problem?**

I followed the instructions of the Kurento tutorial
https://doc-kurento.readthedocs.io/en/stable/tutorials/java/tutorial-rtp-receiver.html
and got the problem while launching the spring-boot on my server

mvn -U clean spring-boot:run -Dkms.url=ws://localhost:8888/kurento

Information on the console:

Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) on project kurento-rtp-receiver: An exception occurred while running. null: InvocationTargetException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.HttpEncodingAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.http.encoding-org.springframework.boot.autoconfigure.web.HttpEncodingProperties': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException: javax.xml.bind.ValidationException -> [Help 1]

**Comment by micaelgallego** [comment]
You need Java 8
