### ISSUE TITLE
KMS 6.4.0 No audio  in Firefox (Windows)  

### ISSUE THREAD

**Issue by ClassOnLive** [Kurento/bugtracker#38]
After migrating to KMS 6.4 I have identified a problem in Firefox 44
In the onetomany tutorial, if presenter uses Chrome and the viewer Firefox, the viewer doesn't receive audio.
Other scenarios works perfectly

Chrome--->Chrome OK
Firefox--->Chrome OK
Firefox--->Firefox OK
**Chrome--->Firefox KO**

I have tested under Windows

Regards

**Comment by jcaden** [comment]
Hi,

We have checked that this problem also is present in MacOS, but not in Linux.

From our testing it seems something related to kurento-utils or firefox itself and the way that it interacts with the OS to play the sounds. This are the reasons why we think this:

* If you check the audio icon on the firefox tab it reports that is playing audio
* If you try two times, the next time the audio is OK (at least in the tests we have performed), it seems like firefox has problems to connect to the device that plays the audio in the system.

Can you confirm that trying back in firefox without restarting the browser (using a different tab but keeping the first one open) works?

**Comment by ClassOnLive** [comment]
Yes, you are right.
When I open the second tab, audio works.

So now? How can we handle this?



*Sergio Puertas*
CEO/CTO en ClassOnLive
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=http%3A%2F%2Fwww.classonlive.com%2F&si=5703881506422784&pi=272d5e56-ee86-4e48-8cfa-212e31b2ac52>
+34 620 60 20 85
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fwww.classonlive.com%2F&si=5703881506422784&pi=272d5e56-ee86-4e48-8cfa-212e31b2ac52>
<https://www.facebook.com/classonlive?ref=hl>
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Ftwitter.com%2Fclassonlive&si=5703881506422784&pi=272d5e56-ee86-4e48-8cfa-212e31b2ac52>

<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fclassonlive&si=5703881506422784&pi=272d5e56-ee86-4e48-8cfa-212e31b2ac52>

<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fplus.google.com%2F%2BClassonliveES&si=5703881506422784&pi=272d5e56-ee86-4e48-8cfa-212e31b2ac52>



2016-03-01 10:45 GMT+01:00 José Antonio Santos Cadenas <
notifications@github.com>:

**Comment by jcaden** [comment]
We can report it to Firefox and also try to figure out if kurento-utils is doing something that is causing the problem. 

Can you report it to Firefox, please?

**Comment by ClassOnLive** [comment]
I have report to Mozilla but I think Mozilla is not the problem.

I have tested with opentok https://opentokrtc.com/  and it works in Firefox.
Maybe the problem is in kurento-utils



*Sergio Puertas*
CEO/CTO en ClassOnLive
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=http%3A%2F%2Fwww.classonlive.com%2F&si=5703881506422784&pi=f3d3a277-539c-4cf1-e27e-eb9689eaf314>
+34 620 60 20 85
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fwww.classonlive.com%2F&si=5703881506422784&pi=f3d3a277-539c-4cf1-e27e-eb9689eaf314>
<https://www.facebook.com/classonlive?ref=hl>
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Ftwitter.com%2Fclassonlive&si=5703881506422784&pi=f3d3a277-539c-4cf1-e27e-eb9689eaf314>

<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fclassonlive&si=5703881506422784&pi=f3d3a277-539c-4cf1-e27e-eb9689eaf314>

<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fplus.google.com%2F%2BClassonliveES&si=5703881506422784&pi=f3d3a277-539c-4cf1-e27e-eb9689eaf314>



2016-03-01 11:00 GMT+01:00 José Antonio Santos Cadenas <
notifications@github.com>:

**Comment by ClassOnLive** [comment]
This is the bug reported in Mozilla.
https://bugzilla.mozilla.org/show_bug.cgi?id=1252400

I have tested is apprtc and it works, so the problem have to be  in Kurento
side.
The problem  appreared in 6.3.3.



*Sergio Puertas*
CEO/CTO en ClassOnLive
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=http%3A%2F%2Fwww.classonlive.com%2F&si=5703881506422784&pi=a7d8ef79-65a1-4b4f-8ad9-bbbccb8210d3>
+34 620 60 20 85
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fwww.classonlive.com%2F&si=5703881506422784&pi=a7d8ef79-65a1-4b4f-8ad9-bbbccb8210d3>
<https://www.facebook.com/classonlive?ref=hl>
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Ftwitter.com%2Fclassonlive&si=5703881506422784&pi=a7d8ef79-65a1-4b4f-8ad9-bbbccb8210d3>

<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fclassonlive&si=5703881506422784&pi=a7d8ef79-65a1-4b4f-8ad9-bbbccb8210d3>

<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8pTv1sVRs3fx3LyGy-W8p-VB856dT_df4sR6z-02?t=https%3A%2F%2Fplus.google.com%2F%2BClassonliveES&si=5703881506422784&pi=a7d8ef79-65a1-4b4f-8ad9-bbbccb8210d3>



2016-03-01 13:55 GMT+01:00 Sergio Puertas de ClassOnLive <
sergio.puertas@classonlive.com>:

**Comment by mparis** [comment]
It is working in Firefox 45, so the Firefox team has closed the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1252400
