### ISSUE TITLE
Chrome77 can't run

### ISSUE THREAD

**Issue by 823639792** [Kurento/bugtracker#381]
**KMS Version**: 6.9.0

**Ubuntu Version** 16.04

After upgrading to chrome77 version, the video of kurento media server could not be viewed. After debugging, the local ip was hidden. Only modified the flag [chrome://flags/#enable-webrtc-hide-local-ips-with-mdns] can viewed the video, I don't know if you have modified the kurento media server code to support the latest chrome?
Sorry for my poor English.

**Comment by j1elo** [comment]
Not a bug. Support for mDNS is not yet done. Chrome 77 is only Canary release, we use canary to guide required features of KMS but won't promise support until it gets to beta or stable.

**Comment by 823639792** [comment]
I just tested the official version of chrome75 and can't run it.

**Comment by 823639792** [comment]
I updated kms to 6.12. There is still a problem with rtsp playback.
```
Cannot parse remote candidate: 'candidate:2161638322 1 udp 2113937151 6bad9582-19ca-4846-b9c4-db02f13f2471.local 54314 typ host generation 0 ufrag mnVn network-cost 999'
Adding remote candidate to ICE Agent: Agent failed, stream_id: '1'
...
gst_rtsp_connection_connect_with_response: failed to connect: Could not connect to 192.168.2.45: Connection refused
```
Target RTSP url(rtsp://guest:uin123456@192.168.2.45:554/h264/ch1/main/av_stream) can be connected via vlc.
```
Kurento Media Server version: 6.12.1~1.ga130787
Found modules:
	'core' version 6.12.1~1.gb345e36
	'elements' version 6.12.1~1.gf19f0b2
	'filters' version 6.12.1~1.gbbef4af
```

**Comment by gharia** [comment]
@j1elo you added a fix for mDNS issue:
https://github.com/Kurento/kms-elements/commit/789d25b5152ba33eb4fe917ffac5e4d6a1e80a3d
I am not an expert in this but it looks like the relevant issue in `libnice`, https://gitlab.freedesktop.org/libnice/libnice/issues/68, is still open. Are these two connected (the fix you applied and `libnice` issue)?

**Comment by j1elo** [comment]
@gharia the feature in Kurento is written by following the very similar solution that @lminiero added to Janus [here](https://github.com/meetecho/janus-gateway/blob/803bd80a6498a52a669581a32690b4d1f02f8c60/sdp.c#L637). It should just make a special case for hostnames that end with "`.local`", and try to resolve them. To continue with this issue, please see my comment: https://github.com/Kurento/bugtracker/issues/405#issuecomment-544932824

**Comment by j1elo** [comment]
@823639792

> ```
> gst_rtsp_connection_connect_with_response: failed to connect: Could not connect to 192.168.2.45: Connection refused
> ```
> 
> Target RTSP url(rtsp://guest:uin123456@192.168.2.45:554/h264/ch1/main/av_stream) can be connected via vlc.
> 

Seems that Gst is trying to connect to *192.168.2.45* but then it gets a *Connection refused*. I doubt this has anything to do with how mDNS or any other ICE candidates are handled.
