### ISSUE TITLE
Information needed on Kurento/kurento-fiware-java project

### ISSUE THREAD

**Issue by MarkoMarkani** [Kurento/bugtracker#389]
Sorry to bother you here,but I have one question.How can I get a URL of the stream,as well as a IP address of my camera.My goal is to send that data to the Fiware ,but all I can send is hard coded data. How can I access and send to the Fiware dynamic data from my request?This is a code from CameraController class in  Kurento/kurento-fiware-java project.

        `@RequestMapping(value = { "/camera/new" }, method = { RequestMethod.POST })
         @ResponseBody
         public String NewCamera(HttpServletRequest req) {
	     String response = "{\"result\": __RESULT__}";

	
	   try {
	  final OrionConnectorConfiguration orionConnectorConfiguration = new 
          OrionConnectorConfiguration();

	  CamPublisher cp = new CamPublisher(orionConnectorConfiguration);

	  Camera cam = new Camera();

	  cam.setId("CameraDefault_" + System.currentTimeMillis());

	  cam.setName("Kurento-plate-detector Camera");

	  cam.setType("plate-detector");

	  // check if Dates are set.
	  cam.setCreationDate(format.format(System.currentTimeMillis()));
	  cam.setUpdateDate(cam.getCreationDate());
	  cam.setState("NEW");

	  // TODO ips will be updated on ICE negotiation

	  Gson gson = new Gson();
	  String jsonInString = gson.toJson(cam);
	  log.debug("CAM:{}", jsonInString);

	  cp.publish(cam);

	  response = response.replace("__RESULT__", "\"OK\"," + "\"device\":" + jsonInString);

	  } catch (Throwable t) {
	  response = response.replace("__RESULT__", "error");
	  }
	return response;
         }`

**Comment by j1elo** [comment]
Not a bug.
