### ISSUE TITLE
kurento-magic-mirror not work

### ISSUE THREAD

**Issue by xujialiang** [Kurento/bugtracker#390]
**KMS Version**:6.11 docker

Paste output of `kurento-media-server -v` in the machine where KMS is running

**Ubuntu Version**

Paste output of `lsb_release -a` in the machine where KMS is running

**Other libraries versions**:

Paste output of executing `dpkg -l | grep -Pi 'kurento|gst.*1.5|nice'` in the
machine where KMS is running

**Client libraries**

- Language: Node.js
- Version: 6.11

**Browsers tested**

Add OK or FAIL, along with the version, after browsers where you have tested
this issue:

- Chrome: FAIL
- Firefox: FAIL
- Safari: FAIL
- Native library: FAIL

**System description:**

Please describe your setup (where is KMS located, where are the clients,
whether you are using STUN/TURN, etc.)

**What steps will reproduce the problem?**

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Does it happen with one of the tutorials?**

**Please provide any additional information below**

**Comment by j1elo** [comment]
Seems to work fine with current version
