### ISSUE TITLE
webjars/webrtc-adapter/release/adapter.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by aenriquezgentile** [Kurento/bugtracker#391]
**kurento-utils Version**: 6.11.1

**Browsers tested**
- Chrome: FAIL
- Firefox: FAIL

**System description:**

This error occurs for angular 2+ projects with kurento-utils v6.11.1.
![image](https://user-images.githubusercontent.com/16226587/62014924-68df3e00-b17d-11e9-9378-10a936272a6e.png)

**What steps will reproduce the problem?**

1. import kurent-utils in an angular component
2. load the page which loads the component
3. check browser console

**Does it happen with one of the tutorials?**
Yes, it happens with https://github.com/Kurento/kurento-tutorial-js.git tutorial.
If you check the browser console when loading the tutorial you will see:
_Failed to load resource: the server responded with a status of 404 (Not Found)_

**Please provide any additional information below**
Commit which caused this bug (line 75): https://github.com/Kurento/kurento-utils-js/commit/0d9785f677423aa4efa9b379162f78e0e21029b3#diff-3751ca3918476070cf093b7868be7afc

**Comment by meefik** [comment]
In found it in the code https://github.com/Kurento/kurento-utils-js/blob/master/lib/WebRtcPeer.js#L71-L82

**Comment by JoseGoncalves** [comment]
Found a similar issue using Kurento in a Vue.js app.
kurento-utils v6.11.1 is importing webrtc-adapter from a Java specific path.
My workaround, to be able to use kurento-utils in a npm environment is [this](https://github.com/JoseGoncalves/kurento-utils-js/commit/d47f4c268747997bd5abe4aa4ed8514ebb9e1691) .

**Comment by j1elo** [comment]
Probably solved with this commit: https://github.com/Kurento/kurento-utils-js/commit/523370e082681b610b1d22232f678b7fd8783dd9

Please let us know if it improves the issue

**Comment by JoseGoncalves** [comment]
Yes, it solves. I've tested in my apps (were I import webrtc-adapter) and it works fine.

**Comment by j1elo** [comment]
Interesting. Can you confirm that for the same exact test, if you use normal Kurento build (not experimental), the error happens? I want to be 100% sure that only difference is the change in Kurento, not other external change such as different test conditions, different system, etc

**Comment by aenriquezgentile** [comment]
> Probably solved with this commit: [Kurento/kurento-utils-js@523370e](https://github.com/Kurento/kurento-utils-js/commit/523370e082681b610b1d22232f678b7fd8783dd9)
> 
> Please let us know if it improves the issue

Yes, this commit solves the issue. Don't know if it will break something for IE but I don't think so.
Thank you.
