### ISSUE TITLE
Kurento Loopback with recording using generators not working on Firefox 68+ for Linux and Mac 

### ISSUE THREAD

**Issue by brili** [Kurento/bugtracker#395]
as reported on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1572952 the firefox team suggests it is a kurento bug

**KMS Version**: 

`Kurento Media Server version: 6.11.0`

Found modules:

	'core' version 6.11.0
	'elements' version 6.11.0
	'filters' version 6.11.0

**Ubuntu Version**

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial 

**Other libraries versions**:

ii  gir1.2-gstreamer-0.10                       0.10.36-1.5ubuntu1                         amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64                    1.8.1-1kurento1.16.04                      amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                     0.1.15-1kurento3.16.04                     amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64              1.8.1-1kurento3.16.04                      amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64             1.8.1-1kurento1.16.04                      amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64             1.8.1-1kurento2.16.04                      amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64             1.8.1-1kurento1.16.04                      amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64               1.8.1-1kurento2.16.04                      amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                        1.8.1-1kurento1.16.04                      amd64        GStreamer plugins for X11 and Pango
ii  kms-core                                    6.11.0-0kurento1.16.04                     amd64        Kurento Core module
ii  kms-elements                                6.11.0-0kurento1.16.04                     amd64        Kurento Elements module
ii  kms-filters                                 6.11.0-0kurento1.16.04                     amd64        Kurento Filters module
ii  kms-jsonrpc                                 6.11.0-0kurento1.16.04                     amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                                  1.6.3-1kurento1.16.04                      amd64        Kurento jsoncpp library
ii  kurento-media-server                        6.11.0-0kurento1.16.04                     amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64         1.8.1-1kurento3.16.04                      amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64        1.8.1-1kurento1.16.04                      amd64        GStreamer libraries from the "base" set
ii  libgstreamer0.10-0:amd64                    0.10.36-1.5ubuntu1                         amd64        Core GStreamer libraries and elements
ii  libgstreamer0.10-dev                        0.10.36-1.5ubuntu1                         amd64        GStreamer core development files
ii  libgstreamer1.5-0:amd64                     1.8.1-1kurento1.16.04                      amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                             0.1.15-1kurento3.16.04                     amd64        ICE library (shared library)
ii  libusrsctp                                  0.9.2-1kurento1.16.04                      amd64        sctp-refimpl library
ii  openh264                                    1.4.0-1kurento1.16.04                      amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64          1.8.1-1kurento3.16.04                      amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                      0.10.0-1kurento1.16.04                     amd64        OpenWebRTC specific GStreamer plugins

**Client libraries**

JavaScript https://github.com/Kurento/kurento-tutorial-js
- Version: 6.11

**Browsers tested**

Add OK or FAIL, along with the version, after browsers where you have tested
this issue:

- Chrome: OK
- Firefox 68+: Windows (OK), **but fails on MacOS, Linux**
- Firefox < 68: OK
- Safari: OK
- Native library:

**System description:**

Please describe your setup (where is KMS located, where are the clients,
whether you are using STUN/TURN, etc.)

**What steps will reproduce the problem?**

1. https://houselannister.vyou.ch on Linux or Mac
2. Press start and the video should show

**What is the expected result?**

**What happens instead?**

Console output on page says:

Error: Error adding candidate
Error: Error adding candidate
TypeError: arguments.unshift is not a function

Video does not appear on remote stream.

**Does it happen with one of the tutorials?**
Yes the testing is done on the kurento-hello-world-recorder-generator

**Please provide any additional information below**

The firefox team says on https://bugzilla.mozilla.org/show_bug.cgi?id=1572952

Kurento should not be treating this as a fatal error anyway. We're signaling additional information in a manner it doesn't support yet, that it could be ignoring. Kurento needs to update their code. I suppose if this continues to be a problem, we can disable these new onicecandidate events until the implementation community catches up.

**Comment by micaelgallego** [comment]
Tutorials where KMS is controlled directly from browser are not a good starting point to implement a production application. Also, KurentoClient library is a bit outdated and doesn't work very well with generators and async/await.
