### ISSUE TITLE
Task limit reached causes kurento to crash

### ISSUE THREAD

**Issue by skgith1** [Kurento/bugtracker#398]
**KMS Version**:
Kurento Media Server version: 6.11.0
Found modules:
        'core' version 6.11.0
        'elements' version 6.11.0
        'filters' version 6.11.0
        'thatoverlay' version 0.0.1-dev

**Ubuntu Version**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Other libraries versions**:
ii  gir1.2-gst-plugins-base-1.5           1.8.1-1kurento1.18.04                          amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                  1.8.1-1kurento1.18.04                          amd64        Description: GObject introspection data for the GStreamer library
ii  gir1.2-nice-0.1:amd64                 0.1.15-1kurento3.18.04                         amd64        ICE library (GObject introspection)
ii  gstreamer1.5-libav:amd64              1.8.1-1kurento1.18.04                          amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64               0.1.15-1kurento3.18.04                         amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64        1.8.1-1kurento3.18.04                          amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64       1.8.1-1kurento1.18.04                          amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64       1.8.1-1kurento2.18.04                          amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64       1.8.1-1kurento1.18.04                          amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64         1.8.1-1kurento2.18.04                          amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                  1.8.1-1kurento1.18.04                          amd64        GStreamer plugins for X11 and Pango
ii  kms-cmake-utils                       6.11.0-0kurento1.18.04                         all          Kurento CMake utils
ii  kms-core                              6.11.0-0kurento1.18.04                         amd64        Kurento Core module
ii  kms-core-dev                          6.11.0-0kurento1.18.04                         amd64        Kurento Core module
ii  kms-elements                          6.11.0-0kurento1.18.04                         amd64        Kurento Elements module
ii  kms-elements-dev                      6.11.0-0kurento1.18.04                         amd64        Kurento Elements module
ii  kms-filters                           6.11.0-0kurento1.18.04                         amd64        Kurento Filters module
ii  kms-filters-dev                       6.11.0-0kurento1.18.04                         amd64        Kurento Filters module
ii  kms-jsonrpc                           6.11.0-0kurento1.18.04                         amd64        Kurento JSON-RPC library
ii  kms-jsonrpc-dev                       6.11.0-0kurento1.18.04                         amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                            1.6.3-1kurento1.18.04                          amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                        1.6.3-1kurento1.18.04                          amd64        Kurento jsonrpc library
ii  kurento-media-server                  6.11.0-0kurento1.18.04                         amd64        Kurento Media Server
ii  kurento-media-server-dev              6.11.0-0kurento1.18.04                         amd64        Kurento Media Server
ii  kurento-module-creator                6.11.0-0kurento1.18.04                         all          Kurento Module Creator
ii  libgstreamer-plugins-bad1.5-0:amd64   1.8.1-1kurento3.18.04                          amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64  1.8.1-1kurento1.18.04                          amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev      1.8.1-1kurento1.18.04                          amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64               1.8.1-1kurento1.18.04                          amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                   1.8.1-1kurento1.18.04                          amd64        GStreamer core development files
ii  libnice-dev                           0.1.15-1kurento3.18.04                         amd64        ICE library (development files)
ii  libnice10:amd64                       0.1.15-1kurento3.18.04                         amd64        ICE library (shared library)
ii  libusrsctp                            0.9.2-1kurento1.18.04                          amd64        sctp-refimpl library
ii  openh264                              1.8.0-0kurento1.18.04~20190610114102.gbpe251c8 amd64        OpenH264 Video Codec provided by Cisco Systems, Inc.
ii  openh264-gst-plugins-bad-1.5:amd64    1.8.1-1kurento3.18.04                          amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                0.10.0-1kurento1.18.04                         amd64        OpenWebRTC specific GStreamer plugins

**Client libraries**
- Language: Node.js   JavaScript
- Version: node.js 10.16.1  kurento-utils.js 6.11.0

**What steps will reproduce the problem?**

1. Start kurento
2. Connect many presenters to many viewers, add remove presenters and viewers over time

**What is the expected result?**
Kurento should remain within the Maximum Task Limit

**What happens instead?**
Over time kurento will exceed/use the entire task limit and crash, this can happen after several days but sometimes within a much shorter period of time such as a day or two.

Right before crash:
![kurento 2](https://user-images.githubusercontent.com/37164141/63907405-4e50ec80-c9e9-11e9-88b2-b09c89b516ae.JPG)

After crash:
![kurento 1](https://user-images.githubusercontent.com/37164141/63907471-9a039600-c9e9-11e9-8194-b1a585036fb4.JPG)

**Comment by venteamicasa** [comment]
Is there any news about this issue?

**Comment by j1elo** [comment]
Kurento received multiple stability and crash fixes through versions 6.11 to 6.15, so please test with latest version and reopen if this still happens
