### ISSUE TITLE
WebRTC compatiblity

### ISSUE THREAD

**Issue by sm2017** [Kurento/bugtracker#399]
I am using kurento 6.11.0 , Is is compatible with WebRTC M75?
Can I have a compatibility chart?

**Comment by micaelgallego** [comment]
It should be. If it is not compatible, please fill an issue

**Comment by j1elo** [comment]
Unsurprisingly, this is a **bug** tracker. The question forum is located here: https://groups.google.com/forum/#!forum/kurento
