### ISSUE TITLE
adapter.js dependency broken in tutorial-js

### ISSUE THREAD

**Issue by markkimsal** [Kurento/bugtracker#40]
webrtc/adapter has decided to stop publishing a built adapter.js file.  The bower dependency has a loose requirement of "*", but should be restricted to something like 0.2.9 for adapter.js until that project can publish a built adapter.js file or the tutorials come up with instructions to build it.

https://github.com/webrtc/adapter/issues/206

kurento-tutorial-js/kurento-recorder/bower.json

```
  "dependencies": { 
    "adapter.js": "*",
    "bootstrap": "~3.3.0",
    "ekko-lightbox": "~3.3.0",
    "demo-console": "1.5.1",
    "kurento-client": "6.2.0",
    "kurento-utils": "6.2.0"
  } 

```

**Comment by jcaden** [comment]
@rbenitez  can you please check this?

**Comment by rbenitez** [comment]
Hi @markkimsal, we sent an email in the kurento public list about this problem the last week. We are going to wait some days more. If they don't fix the problem, we will change the version in the tutorials.

Sorry for inconvenience.

Regards

**Comment by kirushyk** [comment]
Hello, have same problem.
Using 0.2.x now.

**Comment by rbenitez** [comment]
We are using  "adapter.js": "v0.2.9"  in bower.json. Please, check it.

Regards

**Comment by markkimsal** [comment]
https://github.com/Kurento/kurento-tutorial-js/blob/master/kurento-recorder/bower.json

**Comment by rbenitez** [comment]
@markkimsal like I told you, we are going to wait some days more. If they don't fix the problem, we will change the version in the tutorials but we haven't done yet. During this weekend, we will change the adapter.js version and will type v0.2.9..

**Comment by dfernandezlop** [comment]
This issue has been resolved. I'm closing the bug.
