### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by xenyou** [Kurento/bugtracker#400]
It seems that chrome recently add mDNS support.

plz read this.
https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/

In some case, chrome gather mDNS private IPs like xxx-yyy-zzz.local.
If KMS receives those Ips, KMS says 'Error adding candidate'.

**Comment by xenyou** [comment]
thx!!

**Comment by 823639792** [comment]
Is this modification included in the 6.11.1 release?
When I use nightly build 6.11.1, has some errors :

21:04:09.456156385     1 0x7fa5dc003a00 WARN         kmsiceniceagent kmsiceniceagent.c:451:kms_ice_nice_agent_add_ice_candidate:<KmsIceNiceAgent@0x7fa580133c60> Cannot parse remote candidate: 'candidate:2161638322 1 udp 2113937151 069bb0ac-42e6-4259-92d0-3a915e127d46.local 65515 typ host generation 0 ufrag 1THI network-cost 999'

21:04:09.456165015     1 0x7fa5dc003a00 ERROR       kmswebrtcsession kmswebrtcsession.c:449:kms_webrtc_session_agent_add_ice_candidate:<kmswebrtcsession19> Adding remote candidate to ICE Agent: Agent failed, stream_id: '1'

**Comment by j1elo** [comment]
Hi, this is not yet shipped; it will be with Kurento 6.12, to be released in the next days / next week (we are trying to fix #393 before)

**Comment by aashirwadgupta** [comment]
Hi Team, 
We await the release 6.12 as a major functionality of our application is dependent on parsing mDNS candidates. 
Can you please suggest any probable timeline or date so that we can keep our clients aware. 
Thanks in advance :)

**Comment by j1elo** [comment]
Probable date: this week :-)

**Comment by j1elo** [comment]
Kurento 6.12 has just been released right now, you can check out the release notes and install it:
https://doc-kurento.readthedocs.io/en/6.12.0/project/relnotes/v6_12_0.html

**Comment by aashirwadgupta** [comment]
Thanks a lot team, you guys are awesome
