### ISSUE TITLE
npm install for kurento-tutorial-node displays error messages

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#41]
I have something like for any particular tutorial:

`gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cyril/Developer/kurento-tutorial-node/kurento-chroma/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
`

Subsequent `npm install` calls shows no error.

**Comment by dfernandezlop** [comment]
Hi  @kirushyk,

I have executed npm install on kurento-tutorial-node/kurento-chroma like you and everything seems to work fine.

Could you give more information?

Best.

**Comment by spongessuck** [comment]
I found that it gets this error because the version of `bufferutil` used by one of the libraries is incompatible with newer versions of NodeJS. Installing with whatever NPM version comes with NodeJS v0.12 didn't show this error for me.

**Comment by dfernandezlop** [comment]
Thanks @spongessuck.

@rbenitez could you take a look to this?

**Comment by rbenitez** [comment]
I have seen that ws library has this dependency. We are using 0.7.2 version for ws library, so we have to think about update to 1.0.1 version. We will do tests with this version on node 4.2.1

**Comment by rbenitez** [comment]
Hi @kirushyk, 

We have fixed this problem with this [commit](https://github.com/Kurento/kurento-tutorial-node/commit/32cd7f30d3a5497801485f49a2065d104a6f0c84)

Please update the tutorials and try again.

**Comment by kirushyk** [comment]
Good :-)
