### ISSUE TITLE
hello-world tutorial using docker KMS can't get stream

### ISSUE THREAD

**Issue by mgyong** [Kurento/bugtracker#410]
Kurento Media Server version: 6.12.0
Description:	Ubuntu 16.04.6 LTS

Running KMS using docker container. The hello world example is also running in the same container
 docker run -d --name kms -p 8888:8888 -p 8443:8443     kurento/kurento-media-server:latest

config below
{
    "mediaServer": {
        "resources": {
            "\/\/exceptionLimit": "0.8",
            "\/\/killLimit": "0.7",
            "garbageCollectorPeriod": "240",
            "\/\/": "Whether to disable the RPC request cache, for memory constrained environments",
            "disableRequestCache": "false"
        },
        "net": {
            "websocket": {
                "\/\/ipv6": "false",
                "port": "8888",
                "\/\/secure": {
                    "\/\/port": "8433",
                    "\/\/certificate": "\/kurento-tutorial-js\/kurento-hello-world\/keys\/server.pem",
                    "\/\/password": ""
                },
                "\/\/registrar": {
                    "\/\/address": "ws:\/\/localhost:9090",
                    "\/\/localAddress": "localhost"
                },
                "\/\/": "Default SOMAXCONN (128)",
                "\/\/connqueue": "128",
                "path": "kurento",
                "threads": "10"
            }
        }
    },
    "configPath": "\/etc\/kurento",
    "modules": {
        "kurento": {
            "PlayerEndpoint": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "UriEndpoint": {
                "defaultPath": "file:\/\/\/var\/lib\/kurento\/",
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "BaseRtpEndpoint": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "WebRtcEndpoint": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "MediaElement": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "HttpEndpoint": {
                "serverAddress": "localhost",
                "port": "9091",
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "SdpEndpoint": {
                "numAudioMedias": "1",
                "numVideoMedias": "1",
                "audioCodecs": [
                    {
                        "name": "opus\/48000\/2",
                        "\/\/": "Next is an example about how a codec can be configured.",
                        "\/\/": "WARNING: Usage of properties is not yet supported",
                        "\/\/properties": {
                            "\/\/maxcodedaudiobandwidth": "16000",
                            "\/\/maxaveragebitrate": "20000",
                            "\/\/stereo": "1",
                            "\/\/useinbandfec": "1",
                            "\/\/usedtx": "0"
                        }
                    },
                    {
                        "name": "PCMU\/8000"
                    },
                    {
                        "name": "AMR\/8000"
                    }
                ],
                "videoCodecs": [
                    {
                        "name": "VP8\/90000"
                    },
                    {
                        "name": "H264\/90000"
                    }
                ],
                "configPath": "\/etc\/kurento\/modules\/kurento"
            }
        }
    }
}

**Client libraries**
javascript hello_world tutorial example

**Browsers tested**
- Chrome:

hello world tutorial index.js
var args = getopts(location.search,
{
  default:
  {
    ws_uri: 'wss://' + location.hostname + ':8888/kurento',
    ice_servers: undefined
  }
});

**What is the expected result?**
I am expecting the remote stream to be working but the hello world javascript example is unable to connect to KMS

<img width="1336" alt="Screen Shot 2019-11-10 at 4 39 18 PM" src="https://user-images.githubusercontent.com/2178001/68554074-c882f180-03da-11ea-8b91-17d058c4c1cb.png">

**Comment by j1elo** [comment]
It's possible that recent changes in browser **autoplay** policies have broken some of the Kurento tutorials... have a look at the browser console to see if there is any error. Also, kurento-utils-js uses "onaddstream" which is a deprecated RTCPeerConnection method, so maybe it has stopped working on the tutorials. That's the two possible causes I can think of right now.

**Comment by mgyong** [comment]
<img width="1600" alt="Screen Shot 2019-11-14 at 12 14 54 AM" src="https://user-images.githubusercontent.com/2178001/68838627-dd2de680-0673-11ea-9937-e3b8aacc0e34.png">
I am now running the hello world javascript node js server example on the host computer instead of in the docker container. 
In browser console i am getting 
[localhost-1573719519085.log](https://github.com/Kurento/bugtracker/files/3845342/localhost-1573719519085.log)
index.js:70 Use freeice
kurento-client.js:27044 WebSocket connection to 'wss://127.0.0.1:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
ws @ kurento-client.js:27044
WebsocketStream @ kurento-client.js:26934
WebsocketStream @ kurento-client.js:26917
(anonymous) @ kurento-client.js:25158
attempt @ kurento-client.js:25062
emitter.connect.emitter.listen @ kurento-client.js:25131
connect @ kurento-client.js:916
KurentoClient @ kurento-client.js:1045
KurentoClient @ kurento-client.js:197
onOffer @ index.js:102
(anonymous) @ kurento-utils.js:358
index.js:70 reconnect to server 0 100 undefined
kurento-client.js:27044 WebSocket connection to 'wss://127.0.0.1:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
ws @ kurento-client.js:27044
WebsocketStream @ kurento-client.js:26934
WebsocketStream @ kurento-client.js:26917
(anonymous) @ kurento-client.js:25158
attempt @ kurento-client.js:25062
emitTwo @ kurento-client.js:4927
emit @ kurento-client.js:4998
Backoff.onBackoff_ @ kurento-client.js:2236
index.js:70 reconnect to server 1 100 undefined
kurento-client.js:27044 WebSocket connection to 'wss://127.0.0.1:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
ws @ kurento-client.js:27044
WebsocketStream @ kurento-client.js:26934
WebsocketStream @ kurento-client.js:26917
(anonymous) @ kurento-client.js:25158
attempt @ kurento-client.js:25062
emitTwo @ kurento-client.js:4927
emit @ kurento-client.js:4998
Backoff.onBackoff_ @ kurento-client.js:2236
index.js:70 reconnect to server 2 200 undefined
kurento-client.js:27044 WebSocket connection to 'wss://127.0.0.1:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
ws @ kurento-client.js:27044
WebsocketStream @ kurento-client.js:26934
WebsocketStream @ kurento-client.js:26917
(anonymous) @ kurento-client.js:25158
attempt @ kurento-client.js:25062
emitTwo @ kurento-client.js:4927
emit @ kurento-client.js:4998
Backoff.onBackoff_ @ kurento-client.js:2236
index.js:70 reconnect to server 3 300 undefined
kurento-client.js:27044 WebSocket connection to 'wss://127.0.0.1:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
ws @ kurento-client.js:27044
WebsocketStream @ kurento-client.js:26934
WebsocketStream @ kurento-client.js:26917
(anonymous) @ kurento-client.js:25158
attempt @ kurento-client.js:25062
emitTwo @ kurento-client.js:4927
emit @ kurento-client.js:4998
Backoff.onBackoff_ @ kurento-client.js:2236
index.js:70 reconnect to server 4 500 undefined

**Comment by rjmunro** [comment]
I found that I needed to use the URL `https://127.0.0.1:8443/index.html?ws_uri=ws://127.0.0.1:8888/kurento` to tell the demo to use the websocket server at port 8888, when the site was on port 8443, and to use the `ws:` not `wss:` protocol.

**Comment by j1elo** [comment]
I have rewritten some parts of the documentation, that needed a good review to clarify and provide better instructions:

* [The js tutorial instructions](https://doc-kurento.readthedocs.io/en/latest/tutorials/js/tutorial-helloworld.html)
* [Configure JavaScript applications to use HTTPS](https://doc-kurento.readthedocs.io/en/latest/features/security.html#features-security-js-https) section
* [Securing Kurento Media Server](https://doc-kurento.readthedocs.io/en/latest/features/security.html#features-security-kms-wss) section

These should now correctly explain how to launch the browser-JS tutorials with default KMS settings (i.e. with `ws://` instead or `wss://`)
