### ISSUE TITLE
Client Node server crashing whenever a new user gets connected as viewer

### ISSUE THREAD

**Issue by devWaleed** [Kurento/bugtracker#417]
**KMS Version**:

Kurento 6.10.0

**Ubuntu Version**
18.04

I am running Ubuntu in VM. My Node.js server is inside VM on Ubuntu, my KMS is on Ubuntu, I have bound my VM to work with my host laptop which has Windows. I have also mapped my modem to a domain which i purchased, ssl is configured. So whenever i open my domain/url, it is able to connect to my Node server inside VM on Ubuntu.

**What steps will reproduce the problem?**

I am opening a tab on windows laptop in Chrome. I click on presenter and my stream gets started. I see some logs on console in Node server which verifies i am connected.

Now on other laptop, i can open tutorial basic page, but as soon as i click viewer button, my Node server crashes and says:

presenter.pipeline.create('WebRtcEndpoint', ...)

Cannot read property create of null which means pipeline here is null. I have added some console.logs to verify that pipeline is null.

**Does it happen with one of the tutorials?**

I am trying to replicate one to many example

**Comment by j1elo** [comment]
6.10 has a crotial ceash issue that got resolved in 6.12. Update asap to avoid solved errors and bugs.

Now for this issue, this seems to be a logic error in the Node application code. Check that the presenter.pipeline variable is correctly storing the previously created pipeline, and try to see at what point it stops containing it

**Comment by devWaleed** [comment]
@j1elo presenter.pipeline value is set inside kurento() function which is a constructor of 'kurento-client' package. This function is called but its callback is never invoked.

**Comment by j1elo** [comment]
You can also use promises and async/await style with kurento-client-js (not with kurento-utils-js in the browser, though).

Maybe this example helps:
https://github.com/Kurento/mediasoup-demos/blob/master/mediasoup-kurento-filter/server.js#L384

**Comment by j1elo** [comment]
If you still cannot make it work, please share some code that shows how you are creating and using the Kurento pipeline and showing the issue

**Comment by devWaleed** [comment]
Unable to setup their demo. Some npm install issue. I have created an issue here: https://github.com/versatica/mediasoup-demo/issues/69

**Comment by ibc** [comment]
> @j1elo Unable to setup their demo. Some npm install issue. I have created an issue here: [versatica/mediasoup-demo#69](https://github.com/versatica/mediasoup-demo/issues/69)

I don't think @j1elo told you to install the mediasoup-demo...

**Comment by j1elo** [comment]
Indeed. That was _just some example code_ of how to avoid the callback-based JS style, showing that you can use the newer async/await style with kurento-client-js (but not with kurento-utils-js yet)

@devWaleed this seems to be a bug in your application code. Nothing we can do here. If you find that there is definitely abug **in Kurento**, feel free to share a test code sample that shows the bug, and reopen this issue.
