### ISSUE TITLE
kms-elements dev package dependencies

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#42]
As I understood (maybe I am wrong?), `kms-elements-6.0-dev` Ubuntu package should be dependent from `openwebrtc-gst-plugins-dev` and `libsoup2.4-dev`, because to build something with kms-elements we need to link against that libs.

**Comment by jcaden** [comment]
You don't need this dependencies as you only need libraries to link, but not its headers.

**Comment by kirushyk** [comment]
Okay, thats true.
However, to build `kms-elements-6.0-dev` from source, you still need that packages.

**Comment by jcaden** [comment]
Yes, that is why they are build dependencies.
