### ISSUE TITLE
kurento-media-server 6.11.0 depend libraries version of gstreamer / gst-plugins-bad / gst-plugins-good / gst-plugins-base / gst-plugins-ugly?

### ISSUE THREAD

**Issue by sshsun1990** [Kurento/bugtracker#422]
**KMS Version**:

Kurento Media Server version: 6.11.0
Found modules:
	'core' version 6.11.0
	'elements' version 6.11.0
	'filters' version 6.11.0

**Ubuntu Version**

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Please provide any additional information below**
kurento-media-server 6.11.0 depend libraries version of gstreamer / gst-plugins-bad / gst-plugins-good / gst-plugins-base / gst-plugins-ugly?

**Comment by j1elo** [comment]
So, what is the **bug** in Kurento?

6.13 is released as of today, please [clean up your system](https://doc-kurento.readthedocs.io/en/6.13.0/dev/dev_guide.html#clean-up-your-system) (be careful!) and try installing it from scratch:
https://doc-kurento.readthedocs.io/en/6.13.0/user/installation.html

**Comment by sshsun1990** [comment]
Maybe the bug is not in kurento, it's in gst-plugins-good or gstreamer. 
Because I found a core stack is compositor.c:562, and the same time kurento recv signal SIGABRT. But many stack is not print. So I want to know the version of gstreamer and other depend libraries. I know, I can refer offical document install debug libraries, but I want to see source code.
Perhaps, you can tell me 6.13 depend libraries, I can upgrade my kurento service.

**Comment by j1elo** [comment]
Kurento uses a fork of GStreamer 1.8.1, with some manually applied patches over time.

In your case, compositor.c:562 would be here:
https://github.com/Kurento/gst-plugins-bad/blob/master/gst/compositor/compositor.c#L562

**Comment by j1elo** [comment]
For these cases it's useful to run the program with debugger (GDB) or memory analyzer (Valgrind).

If you download the source code and build your own Kurento, we have a run script that makes it very easy.

Just run this to debug:

```
cd kms-omni-build
bin/kms-build-run.sh --gdb
```

this for [Valgrind](https://valgrind.org/):

```
cd kms-omni-build
bin/kms-build-run.sh --valgrind-memcheck
```

this for [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer):

```
cd kms-omni-build
bin/kms-build-run.sh --address-sanitizer
```

For more info on building from source code: [Building from sources](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#building-from-sources)

**Comment by sshsun1990** [comment]
Now I fork the GStreamer and gst-plugins-good source code from Kurento respository, but I can't found the branch 1.8.1 of GStreamer or another gst-plugins-bad. Maybe is it gstreamer1.8 branch?

![image](https://user-images.githubusercontent.com/54736945/71362048-de85f380-25cf-11ea-8cda-d41188334a62.png)

Yes, it is as you say, I will do debug and check memory.

**Comment by j1elo** [comment]
No, it's just the **master** branch. We're working to get rid of this fork, and use official Ubuntu packages in Ubuntu 18.04, but for now were using this fork.

**Comment by sshsun1990** [comment]
OK, thanks. I got it.
