### ISSUE TITLE
Target Bitrate between Kurento Instances

### ISSUE THREAD

**Issue by mneundorfer** [Kurento/bugtracker#428]
I am wondering how it is possible to make use of bandwidth estimation (BWE) when having a connection between two Kurento instances via `WebRtcEndpoint`s.

**KMS Version**:

```
0:00:00.018994930    42 0x5591e5229ea0 INFO    KurentoModuleManager ModuleManager.cpp:90:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
0:00:00.019083808    42 0x5591e5229ea0 INFO    KurentoModuleManager ModuleManager.cpp:137:loadModule: Loaded module: core, version: 6.13.0, date: Dec 17 2019 13:17:31
0:00:00.027920695    42 0x5591e5229ea0 INFO    KurentoModuleManager ModuleManager.cpp:90:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
0:00:00.028033602    42 0x5591e5229ea0 INFO    KurentoModuleManager ModuleManager.cpp:137:loadModule: Loaded module: elements, version: 6.13.0, date: Dec 17 2019 13:26:02
0:00:00.029396612    42 0x5591e5229ea0 INFO    KurentoModuleManager ModuleManager.cpp:90:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
0:00:00.029468178    42 0x5591e5229ea0 INFO    KurentoModuleManager ModuleManager.cpp:137:loadModule: Loaded module: filters, version: 6.13.0, date: Dec 17 2019 13:35:00
Kurento Media Server version: 6.13.0
Found modules:
	'core' version 6.13.0
	'elements' version 6.13.0
	'filters' version 6.13.0
```

**Ubuntu Version**

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Other libraries versions**:

```
ii  gstreamer1.5-libav:amd64             1.8.1-1kurento1.16.04                    amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.15-1kurento3.16.04                   amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1-1kurento4.16.04                    amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1-1kurento2.16.04                    amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1-1kurento3.16.04                    amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1-1kurento1.16.04                    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1-1kurento3.16.04                    amd64        GStreamer plugin for PulseAudio
ii  kms-core                             6.13.0-0kurento1.16.04                   amd64        Kurento Core module
ii  kms-elements                         6.13.0-0kurento1.16.04                   amd64        Kurento Elements module
ii  kms-filters                          6.13.0-0kurento1.16.04                   amd64        Kurento Filters module
ii  kms-jsonrpc                          6.13.0-0kurento1.16.04                   amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3-1kurento1.16.04                    amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.13.0-0kurento1.16.04                   amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1-1kurento4.16.04                    amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1-1kurento2.16.04                    amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1-1kurento2.16.04                    amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.15-1kurento3.16.04                   amd64        ICE library (shared library)
ii  libsrtp0:amd64                       1.6.0-0kurento1.16.04                    amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                           0.9.2-1kurento1.16.04                    amd64        sctp-refimpl library
ii  openh264                             1.4.0-1kurento1.16.04                    amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1-1kurento4.16.04                    amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins               0.10.0-1kurento1.16.04                   amd64        OpenWebRTC specific GStreamer plugins
```

**System description:**

Please describe your setup (where is KMS located, where are the clients,
whether you are using STUN/TURN, etc.)

**What steps will reproduce the problem?**

I have a setup here which looks like this:

```
Camera -> (PlayerEndpoint) Kurento1 (WebRtcEndpoint) -> (WebRtcEndpoint) Kurento2 (WebRtcEndpoint) -> (WebRtcPeer) Browser
```

**What is the expected result?**

When having a slow connection between `Kurento1` and `Kurento2`, the bandwidth estimation kicks in and the resolution of the stream is adapted accordingly

**What happens instead?**

The resolution is not adapted, the stream freezes. Also it seems there are no `RTCP` packets containing REMB information sent from `Kurento2` to `Kurento1`.  The `kms_enc_tree_bin_set_target_bitrate ` in `kmsenctreebin.c` never seems to be triggered.

Is this actually supposed to work? If not, do you by any chance have suggestions on how to make this work?

Thanks for your support!

**Comment by j1elo** [comment]
Hi,

please edit your [debug log level](https://doc-kurento.readthedocs.io/en/latest/features/logging.html#logging-levels-and-components) to add these categories:

```
kmsremb:5,kmsutils:5,basertpendpoint:5,enctreebin:5"
```

to have more details about what is going on with the REMB calculations between Kurento instances.

Note that the congestion controll will only affect the video bitrate, not its resolution. The dynamic resolution adaptation is a Chrome thing, other browsers like Firefox don't do it, and probably other implementations don't do it either. But you should definitely see some adaptation in REMB bitrate between WebRTC endpoints.

Also have a look as SDP Offer and SDP Answers that are exchanged in all legs of your setup, to ensure that REMB (`a=rtcp-fb:N goog-remb`) is actually enabled everywhere

**Comment by mneundorfer** [comment]
Thanks for your feedback, @j1elo!

As far as I understand, some encoders (e.g. `vp8enc`) indeed [adapt the resolution](https://github.com/Kurento/kms-core/blob/c171bbd969fef575a188613c74ba5652010ffe18/src/gst-plugins/commons/kmsenctreebin.c#L150) based on the `target_bitrate`. At least this is what I thought I already observed in the "simple" setup `Kurento -> Browser`...?

Concentrating on the log output generated with the log levels you proposed helped me to track down the underlying issue. The following seems to have happened:

1. In general, you are completely right - in the default configuration, Kurento indeed does send/receive REMB information
2. When Kurento is forced to work with `H264` instead of `VP8` (which is my setup here - my clumsy way of forcing `H264` is to just remove the `VP8` configuration in the `SdpEndpoint.conf.json` file), no `REMB` logs can be found. Nevertheless, your hint with the log levels helped me to find that the line
```
kmsbasertpendpoint.c:1118:kms_base_rtp_endpoint_start_transport_send:<kmswebrtcendpoint0> Media 'video' has REMB
``` 
was missing - which is caused by the fact that the SDPs do not contain the `goog-remb` line anymore. 
I found that it is only missing in my particular setup. When having the simple `Browser -> Kurento` setup, everything works just fine.

---

On a side note, I am wondering why we seem to receive `REMB` packets at all: I did some Wireshark tracing to get to the bottom of that, and what I observed is the following:

Sender report from `Kurento1` to `Kurento2`:

![grafik](https://user-images.githubusercontent.com/4457940/73050313-b2d08480-3e7f-11ea-959c-c77cd900164e.png)

Receiver report from `Kurento2` to `Kurento1`:

![grafik](https://user-images.githubusercontent.com/4457940/73050306-a64c2c00-3e7f-11ea-936a-d0050c49a8ab.png)

Sender report from `Kurento2` to `Browser`:

![grafik](https://user-images.githubusercontent.com/4457940/73050270-8f0d3e80-3e7f-11ea-8f75-2c42ce1ceb36.png)

Receiver report from `Browser` to `Kurento2`:

![grafik](https://user-images.githubusercontent.com/4457940/73050249-7bfa6e80-3e7f-11ea-9105-e61c5dfe4da1.png)

I noticed that there are no `REMB` packages (`RTCP` packet type [`206`](https://tools.ietf.org/html/draft-alvestrand-rmcat-remb-00)) transmitted at all. Is there something I am missing about how `REMB` works? I am really curious about how the bitrate estimation currently travels over the network, as I seem to be unable to find it :-) ...

Also, does Kurento support alternatives such as `transport-cc`?

**Comment by mneundorfer** [comment]
I have a few additional observations under bandwidth limitations, that might be interesting

(For limiting bandwidth, I use the [`slow-network`](https://github.com/Kurento/slow-network) utility)

**`Kurento -> Browser`**
The estimations when bandwidth is limited are very stable and in general, the bitrate adaptations are working fine

**`Kurento -> Kurento`**
The estimations seems to be very volatile when bandwidth is limited. During the whole test, to which I [attached logs](https://gist.github.com/mneundorfer/71d219c2b14a7f28b577321c860377b2), the network was limited via `./slow -i eno1 -r 600`. An example is starting in line `2157`: The estimation starts at `30000`, then directly jumps to `196749`, back to `30000` and some other lower values until reaching `205237` (line `3048`).
In general, it seems that the bitrate estimation grows way to fast, resulting in a very laggy stream (if any)

**Comment by j1elo** [comment]
> As far as I understand, some encoders (e.g. `vp8enc`) indeed [adapt the resolution](https://github.com/Kurento/kms-core/blob/c171bbd969fef575a188613c74ba5652010ffe18/src/gst-plugins/commons/kmsenctreebin.c#L150) based on the `target_bitrate`.

That's not really what is happening there. The `resize-allowed` parameter in VP8 only has an effect internally to the codec itself, with an observable reduction in transmitted bits/s but (in principle) no observable change in resolution "from outside". Have a look at [7. Temporal and Spatial Resampling](https://www.webmproject.org/docs/encoder-parameters/#7-temporal-and-spatial-resampling): this setting allows the encoder to downscale the video in times where the internal encoding buffer runs low on data, then I guess this downscaling information is sent in-band in form of metadata frames, and finally _the decoder upscales the video back to its original resolution_. That's what I meant with "from outside": the apparent decoded resolution is the same as the original resolution the video had during encoding.

Also, Kurento does not integrate in any way the reception of REMB messages (with bandwidth estimation data), and the rescaling feature of the encoder.

The actual numerical implementation of REMB is a bit of a black box, written by people who now aren't part of the Kurento project any more :-) so it might have some issues and fine tunings to do, but it would also require a good amount of knowledge that we currently don't have. Also I think it would be more effective to start thinking on newer mechanisms such as `transport-cc` (which Kurento doesn't include yet).

**Comment by mneundorfer** [comment]
Thanks a lot for those insights!! I am wondering what I observed then :-) must have been adaptations due to CPU bottlenecks I guess...

I see. That's not great news - I will try to dig at least a little into this, maybe I can give you some feedback in case I stumble across something interesting...
