### ISSUE TITLE
Node Tutorial one to Many has no loading the remote server Stream Spinner moving endless

### ISSUE THREAD

**Issue by parveen-oodles** [Kurento/bugtracker#43]
Hello , I am new to using Kurrento required in project , but as i clone the tutorial given on git hub for Kurento and following the instruction for one2Many call . First of all there is broken packages fro adapter.js as i successfully resolved them but after that there is an issue i.e my webcam is running well and i am able to see my side stream but not able to see the remote stream there is spinner moving endless.

And also there are two error as i see on console of my chrome i.e:-

1)Failed to parse SessionDescription. m=audio 0 UDP/TLS/RTP/SAVPF Expects at least 4 fields.
2)Uncaught (in promise) Failed to parse SessionDescription. m=audio 0 UDP/TLS/RTP/SAVPF Expects at least 4 fields.

Please help me to out from this situation .
Any help would be appreciated.
Thanks

**Comment by igracia** [comment]
What client are you using? Have you tried different clients?

It would be nice to know the KMS version, and the commit of the tutorial that you are using.

**Comment by tsonghong** [comment]
I beleive it's possible to get that message "Failed to parse SessionDescription. m=video 0 RTP/SAVPF Expects at least 4 fields." if you disbaled VP8 on Kurento and then tried to view the results on the Chrome browser where the sending device video is in H.264 format.  Chrome doesn't support H264 at the moment, but Kurento can transcode from H264 to VP8 for you to work on Chrome.

**Comment by dfernandezlop** [comment]
Hi @parveen-oodles,

Any updates?

**Comment by parveen-oodles** [comment]
Hello all , thanks for your response but i was not able to successfully running any of the kurento examples , i resloved all the errors but in last there was not any error but the **remote side stream is not loaded**. I also gives the details of KMS version kurento file config etc on **stackoverflow community** and also got reply from santoscadenas as well. 

But finally i setup the same on a diff ubuntu machine and upgrade dist and also install **openjdk7** and after that i hit command-:  **sudo apt-get install libglib2.0-0 ** and finally install** kurento 6-0** and than i see that everything working fine on that machine but after that my skype and some other apps are not working so as i resloved those dependency issues but again i was stuck with same remote stream not loaded issue. So finally i remove everything from that machine and than run kurento only than it's working fine for me. I don't know where is the actual issue but finally it works for me but i want that you people please help me to f**inding out where is the exact issue**.

Sorry for the late reply from my side
and thanks again for your quick response.

**Comment by dfernandezlop** [comment]
Ok. As Jose is helping you in stackoverflow [1], I'm going to close this thread, we can't duplicate the info and the effort.

Regards.

[1] http://stackoverflow.com/questions/35915585/node-tutorial-one-to-many-has-no-loading-the-remote-server-stream-spinner-moving
