### ISSUE TITLE
PlayerEndpoint reduces video frame rate by 50% when setPosition is called on a video file containing b-frames

### ISSUE THREAD

**Issue by okwasi** [Kurento/bugtracker#438]
When I call setPosition on a PlayerEndpoint serving a .mp4 file that contains H264 b-frames, I observe that the video frame rate perceived by the client is halved. This issue does not happen when the .mp4 file contains only H264 i-frames and p-frames.

Pick a .mp4 file that contains H264 b-frames. Let's assume the file has frames encoded at 25 fps.

Set up the PlayerEndpoint with the .mp4 file:
```
MediaPipeline pipeline = kurentoClient.createMediaPipeline();
PlayerEndpoint playerEndpoint = new PlayerEndpoint
    .Builder(pipeline, FILE_PATH)
    .useEncodedMedia()
    .build();
```

Start the pipeline and observe that the file is played back at 25 fps (as expected). Then do the following:
```
playerEndpoint.setPosition(playerEndpoint.getPosition() + 10000);
```

Observe that the forward seek is successful, but that the file is played back at ~12 fps, which is ~50% of the original fps.

The expectation is that the file should continue to be played back at 25 fps.

__NOTE:__ The above issue does not occur with .mp4 files that have no H264 b-frames. Files that contain only i-frames and p-frames are fine.

I poked a little bit by calling the `useEncodedMedia()` on the PlayerEndpoint builder. In the scenario where I had a .mp4 file with b-frames, I noticed the following type of error logs:

My hunch is that the playback frame rate reduced by the fraction of encoded frames in the .mp4 file that are b-frames.

```
0:09:21.795760900     1 0x55de9bf850a0 ERROR         playerendpoint kmsplayerendpoint.c:540:process_sample:<appsink6> Non incremental original PTS (last original PTS: 0:00:05.880875000, original PTS: 0:00:05.839166666, is preroll: 0). Not pushing
0:09:21.878599800     1 0x55de9bf850a0 ERROR         playerendpoint kmsplayerendpoint.c:540:process_sample:<appsink6> Non incremental original PTS (last original PTS: 0:00:06.006000000, original PTS: 0:00:05.922583333, is preroll: 0). Not pushing
```

**Kurento Media Server**
- Kurento version: 6.13.0
- Server OS: Docker on macOS
- Installation method: docker pull kurento/kurento-media-server:latest && docker run -it --rm --name kms -p 8888:8888 kurento/kurento-media-server:latest

**Application Server**
- Language: Java
- Client version: 6.13.0

**End-user clients**
- Device: Mac
- OS: MacOS Catalina
- Browser: Chrome
- Version: 79.0.3945.130

```
$kurento-media-server -v
0:00:00.017134600    50 0x55ed451f9e90 INFO    KurentoModuleManager ModuleManager.cpp:90:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
0:00:00.017213700    50 0x55ed451f9e90 INFO    KurentoModuleManager ModuleManager.cpp:137:loadModule: Loaded module: elements, version: 6.13.0, date: Dec 17 2019 13:26:02
0:00:00.017690700    50 0x55ed451f9e90 INFO    KurentoModuleManager ModuleManager.cpp:90:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
0:00:00.017743100    50 0x55ed451f9e90 INFO    KurentoModuleManager ModuleManager.cpp:137:loadModule: Loaded module: core, version: 6.13.0, date: Dec 17 2019 13:17:31
0:00:00.019006400    50 0x55ed451f9e90 INFO    KurentoModuleManager ModuleManager.cpp:90:loadModule: Load file: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so, module name: /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
0:00:00.019064600    50 0x55ed451f9e90 INFO    KurentoModuleManager ModuleManager.cpp:137:loadModule: Loaded module: filters, version: 6.13.0, date: Dec 17 2019 13:35:00
Kurento Media Server version: 6.13.0
Found modules:
	'core' version 6.13.0
	'elements' version 6.13.0
	'filters' version 6.13.0

$dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
ii  gstreamer1.5-libav:amd64             1.8.1-1kurento1.16.04                    amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.15-1kurento3.16.04                   amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1-1kurento4.16.04                    amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1-1kurento2.16.04                    amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1-1kurento3.16.04                    amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1-1kurento1.16.04                    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1-1kurento3.16.04                    amd64        GStreamer plugin for PulseAudio
ii  kms-core                             6.13.0-0kurento1.16.04                   amd64        Kurento Core module
ii  kms-elements                         6.13.0-0kurento1.16.04                   amd64        Kurento Elements module
ii  kms-filters                          6.13.0-0kurento1.16.04                   amd64        Kurento Filters module
ii  kms-jsonrpc                          6.13.0-0kurento1.16.04                   amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3-1kurento1.16.04                    amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.13.0-0kurento1.16.04                   amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1-1kurento4.16.04                    amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1-1kurento2.16.04                    amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1-1kurento2.16.04                    amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.15-1kurento3.16.04                   amd64        ICE library (shared library)
ii  libsrtp0:amd64                       1.6.0-0kurento1.16.04                    amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                           0.9.2-1kurento1.16.04                    amd64        sctp-refimpl library
ii  openh264                             1.4.0-1kurento1.16.04                    amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1-1kurento4.16.04                    amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins               0.10.0-1kurento1.16.04                   amd64        OpenWebRTC specific GStreamer plugins
```

**Comment by j1elo** [comment]
That looks like a very strange decoding issue... in principle, this should be the OpenH264 codec which is handled by GStreamer. I don't really see a reason in Kurento code that would have an effect in such an internal process.

Could you please try again with the newer experimental images based on Ubuntu 18.04 and GStreamer 1.14? More recent version of all dependencies probably means improved decoding and fixed bugs:

https://groups.google.com/d/msg/kurento/VFNHvJHSxUQ/M0RYUUPQAQAJ

**Comment by okwasi** [comment]
Thanks for the response @j1elo. I failed to mention that I'd also tried the experimental images for Kurento 7 and got the same results. Just to be sure, I went back and used the experimental images again. The issue is still there.

The issue on line 540 of https://github.com/Kurento/kms-elements/blob/master/src/gst-plugins/kmsplayerendpoint.c makes me believe that the boolean condition doesn't take into account the way in which B-frames are encoded, where the previous and next frames are required to decode the current frame.

**Comment by j1elo** [comment]
Maybe you can just comment out [this line](https://github.com/Kurento/kms-elements/blob/d58731dd53e38b74d553d30d66627d984ca6e9c8/src/gst-plugins/kmsplayerendpoint.c#L541) so the error will be printed, but the rest of the function code will still be run. That would let us know if this check is bogus or not, if the results are better.

We want to make easy for devs to change Kurento code and test, so doing this is well documented. You can clone all source code and [build from sources](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#build-from-sources).

Or, if you don't feel comfortable installing all dependencies and running KMS from sources, it's also possible that you only work with kms-elements (where PlayerEndpoint lives): clone it, change the suggested line, and [rebuild a new Deb package](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#kurento-buildpackage-docker-image). Then install it (`dpkg -i PackageFile.deb`) and restart KMS to test the changes.

**Comment by okwasi** [comment]
Thanks for the hints Juan. I'll try my hands at one of these and let you know what I find. Most likely in the next week or so.

**Comment by okwasi** [comment]
@j1elo Sorry for the long delay. I created a custom build of the kms-elements package with the commented out line like you suggested, and I still see the issue with dropped frames.

Is there anything else you'd recommend?

**Comment by RobotnickIsrael** [comment]
I noticed that playerendpoint in general has issues with b frames.
Meaning I use many cameras connecting to my playerendpoints, and i always need to play with my GOP. In somecameras only IP works, changing to IBP or IBBP kills it.
Since than I always look for this option in cameras but not all of them have it - and anyway it shouldnt be a problem.

**Comment by okwasi** [comment]
@RobotnickIsrael thanks for corroborating my findings. In a way, I can see why the problem would occur for WebRTC streaming, given the eager nature in which packets (i.e. frames) need to be sent without much buffering. I wonder if GStreamer can be tweaked to accommodate streaming files with b-frames.

**Comment by slabajo** [comment]
It turns out that the low frame rate condition was caused because the seek event included a trickmode flag. That flag caused any libav decoder to enter a mode AVDISCARD_NONREF that makes the decoder to skip all non reference frames, including B frames, so resulting in low framerate. The nature of the seek feature in playerendpoint does not need any trick flag, so it seems perfectly safe skipping it.
