### ISSUE TITLE
语音识别

### ISSUE THREAD

**Issue by yangjunjie52** [Kurento/bugtracker#444]
Hello, kurento is a very good project, I read the related documents, but I want to extract audio and video when real-time audio and video are turned on, and perform audio recognition of audio and video, like the subtitle effect during live broadcast. . But I ca n’t get started at the moment, for guidance

**Comment by j1elo** [comment]
We use this bugtracker exclusively for talking about bugs in Kurento code.

You can follow the [Kurento documentation](https://doc-kurento.readthedocs.io/en/latest/), which includes tutorials, development guides and lots of info. There is also an open-source [community forum](https://groups.google.com/forum/#!forum/kurento) that you can use to ask about how to use Kurento.

Lastly, if you need help from us for solving issues or consultancy services, we offer [commercial support](https://doc-kurento.readthedocs.io/en/latest/user/support.html#support-commercial)
