### ISSUE TITLE
Running ShowDataCannel project error

### ISSUE THREAD

**Issue by yangjunjie52** [Kurento/bugtracker#445]
ERROR   KurentoModuleManager ModuleManager.cpp:212:getFactory: Factory KmsShowData not found: map::at

**Comment by j1elo** [comment]
Sorry, the package `kms-datachannelexample` is not available to install until we end the migration to Ubuntu 18.04; meanwhile, you can checkout the code of that example module here: 
kms-datachannelexample

**Comment by j1elo** [comment]
https://github.com/Kurento/kms-datachannelexample

**Comment by yangjunjie52** [comment]
How to use it?
