### ISSUE TITLE
ShowDataChannel Demo  Can't demonstrate normally

### ISSUE THREAD

**Issue by yangjunjie52** [Kurento/bugtracker#447]
> 0:24:00.067888635     1 0x7fb278002090 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:993:### **disconnect**: Disconnecting e70214c1-d9bb-47e2-a239-97740bad794f_kurento.MediaPipeline/5fcfe8fb-5154-4386-a330-aeacb0737192_kurento.WebRtcEndpoint - e70214c1-d9bb-47e2-a239-97740bad794f_kurento.MediaPipeline/cda0aff2-bcfb-4818-bbb2-515b1f7a1a13_datachannelexample.KmsShowData params AUDIO default default

The above is the background error run docker
The front page cannot send data, I wrote the send data to death, and there is no change in the video

**Comment by j1elo** [comment]
Hi,

the module `kms-datachannelexample` which is needed for this tutorial was disabled, but I've now reviewed it and enabled.

Using the [nightly local install](https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html#local-installation), follow the instructions of the [Show DataChannel tutorial](https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-show-datachannel.html), and now the package `kms-datachannelexample` can be also installed, so the tutorial should work.
