### ISSUE TITLE
KMS 6.4.0 with turn (transport=tcp) crash if we turn off the turn

### ISSUE THREAD

**Issue by ClassOnLive** [Kurento/bugtracker#45]
We have KMS 6.4 and a Turn server in different machines.
If we make a call and the streams go through the turn server, if we suddenly turn off the turn server, KMS process crash and we have to reboot it.
Steps to reproduce:
Cut UDP traffic in Server where is hosted KMS
Stablish a call and be sure that streams travel through the turn server via TCP. 
During the call, switch off the turn
Allow UDP traffic again in the server
Try to make again the call

**Comment by dfernandezlop** [comment]
Hi,

I have detected the problem. It is a bug in libnice. We are going to try to find a solution.

Thanks.
David.

**Comment by dfernandezlop** [comment]
Hi again,

We have opened a bug in libnice [1], but we don't have any answer yet.

Sorry for troubles.

[1] https://phabricator.freedesktop.org/T7352

**Comment by jcaden** [comment]
It seems that the latest libnice version (master branch) fixes this issue, but TURN UDP stopped working. We are trying to fix everything before closing this issue.

**Comment by igracia** [comment]
@jcaden Did this ever get solved?

**Comment by chevonc** [comment]
Any updates on this guys? Started hitting this recently as well using `transport=tcp`

**Comment by j1elo** [comment]
Closing this: Kurento 6.14 is currently using libnice 0.1.17 which has received a ton of fixes and improvements.
