### ISSUE TITLE
Kurento Media Server can not support iceRestart ?

### ISSUE THREAD

**Issue by sshsun1990** [Kurento/bugtracker#452]
KMS Team have plan support iceRestart?

**Comment by j1elo** [comment]
No, and it's not in the short term roadmap.
For other questions about Kurento please use the [community forum](https://groups.google.com/forum/#!forum/kurento)

Closing this, as it is not a bug.

**Comment by hdev72** [comment]
> No, and it's not in the short term roadmap. For other questions about Kurento please use the [community forum](https://groups.google.com/forum/#!forum/kurento)
> 
> Closing this, as it is not a bug.

hello dear admin,
 i think its a bug because when user has unstable network we need to reconnect , now when kurento doesn't has this feature how can we reconnect user to room normally? we should restart all process of offer answers between all participants?
