### ISSUE TITLE
Installation failed due to missing GPG key

### ISSUE THREAD

**Issue by Smasherr** [Kurento/bugtracker#453]
```
16:27:02 + tee /etc/apt/sources.list.d/kurento.list
16:27:02 
16:27:02 + 
16:27:02 echo deb http://ubuntu.kurento.org xenial kms6
16:27:02 
16:27:02 deb http://ubuntu.kurento.org xenial kms6
16:27:02 + wget http://ubuntu.kurento.org/kurento.gpg.key -O -
16:27:02 + apt-key add -
16:27:02 
16:27:02 --2020-03-26 15:27:02--  http://ubuntu.kurento.org/kurento.gpg.key
16:27:02 
16:27:02 Resolving ubuntu.kurento.org (ubuntu.kurento.org)... 
16:27:02 52.218.110.76
16:27:02 Connecting to ubuntu.kurento.org (ubuntu.kurento.org)|52.218.110.76|:80... 
16:27:02 connected.
16:27:02 
16:27:02 HTTP request sent, awaiting response... 
16:27:02 404 Not Found
16:27:02 2020-03-26 15:27:02 ERROR 404: Not Found.
16:27:02 
16:27:02 
16:27:03 gpg: no valid OpenPGP data found.
```

**Comment by j1elo** [comment]
What instructions are you following?

**Comment by Smasherr** [comment]
Ah, pardon me, I forgot to attach the link to the documentation:
https://doc-kurento.readthedocs.io/en/6.6.2/installation_guide.html

**Comment by j1elo** [comment]
Closing as not-a-bug

> Ah, pardon me, I forgot to attach the link to the documentation:
> https://doc-kurento.readthedocs.io/en/6.6.2/installation_guide.html

Just curious, how did you get to that page? through a Google search, maybe?
Version 6.6.2 is from July 2017 so it's pretty old...

You can get to the latest version (6.13.0) here: https://doc-kurento.readthedocs.io/en/latest/

**Comment by Smasherr** [comment]
>through a Google search, maybe?
Yes, exactly. In our company in my role as DevOps, I stumbled upon an old build of a docker image, which includes Kurento. I tried to build it, saw that 404 error occur and googled "kurento gpg key"

> You can get to the latest version (6.13.0) here: https://doc-kurento.readthedocs.io/en/latest/
Thank you very much for your assistance!
