### ISSUE TITLE
Can't change Max open files value in Kurento

### ISSUE THREAD

**Issue by longlnk** [Kurento/bugtracker#454]
Hi everyone,

I found an error during the change process /proc/sys/fs/file-max but Max open files not that.

Example:
I change /proc/sys/fs/file-max: 5,000,000
But Max Open Files: 100,000 (DAEMON_MAX_FILES="$(( ($(cat /proc/sys/fs/file-max) * 50) / 100 ))")
![image](https://user-images.githubusercontent.com/15074179/78703880-2d645880-7935-11ea-966d-a809119c1952.png)

Log Kurento:
![image](https://user-images.githubusercontent.com/15074179/78704003-656b9b80-7935-11ea-89e2-561840aff9c1.png)

Please help me.

**Comment by avssav** [comment]
Hi, 
It maybe connect with /proc/sys/fs/nr_open. nr_open limits file-max in my Ubuntu 16.04

**Comment by longlnk** [comment]
> Hi,
> It maybe connect with /proc/sys/fs/nr_open. nr_open limits file-max in my Ubuntu 16.04

I changed it in /etc/systemd/system/default.target.wants/kurento-media-server.service
It worked.

**Comment by j1elo** [comment]
Is this a bug in the settings files of Kurento Media Server?

**Comment by longlnk** [comment]
> Is this a bug in the settings files of Kurento Media Server?

Yes, I fixed.
