### ISSUE TITLE
Feature : Allow separate certificate chain and private key files

### ISSUE THREAD

**Issue by TFleury** [Kurento/bugtracker#459]
I tried to use certificate files issued by Letsencrypt, but I was unable to use them as is.

In `kurento.conf.json` there is a single param for certificate file : "mediaServer.net.websocket.secure.certificate"

Could it be possible to have distinct parameters for certificate and private key files ?

If it can save time to someone else, the workaround is to concat `privatekey.pem` and `cert.pem` in a single file.

**Comment by j1elo** [comment]
This handles the file to [SSL_CTX_use_certificate_chain_file](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_certificate_chain_file.html) and the reason to use a compound file is being able to load a whole certificate chain: from the server certificate, including any intermediate CA, and ending with a root CA.

Once this is done, just also adding the key to the same file is a matter of convenience.

What I agree is that it could be better documented. I'll add some comments in the file itself, so it becomes immediately apparent how it should be used.
