### ISSUE TITLE
Kurento crashes on vp8enc invalid parameter

### ISSUE THREAD

**Issue by Absor** [Kurento/bugtracker#46]
Kurento constantly crashes on this error:

```
2016-03-14 21:43:54,690903 26443 [0x00007fce82a718c0]   error KurentoMediaPipelineImpl  MediaPipelineImpl.cpp:26 busMessage()  Error on bus: error message: 0x7fce64067310, time 99:99:99.999999999, seq-num 36607, element 'vp8enc0', GstMessageError, gerror=(GError)NULL, debug=(string)"gstvpxenc.c\(1904\):\ gst_vpx_enc_handle_frame\ \(\):\ /GstPipeline:pipeline0/KmsHubPort:kmshubport0/KmsAgnosticBin2:kmsagnosticbin2-5/KmsEncTreeBin:kmsenctreebin0/GstVP8Enc:vp8enc0:\012invalid\ parameter";
2016-03-14 21:43:54,691199 26443 [0x00007fce82a718c0]   error KurentoMediaElementImpl   MediaElementImpl.cpp:256 _media_element_impl_bus_message()  MediaElement error: error message: 0x7fce64067310, time 99:99:99.999999999, seq-num 36607, element 'vp8enc0', GstMessageError, gerror=(GError)NULL, debug=(string)"gstvpxenc.c\(1904\):\ gst_vpx_enc_handle_frame\ \(\):\ /GstPipeline:pipeline0/KmsHubPort:kmshubport0/KmsAgnosticBin2:kmsagnosticbin2-5/KmsEncTreeBin:kmsenctreebin0/GstVP8Enc:vp8enc0:\012invalid\ parameter";
```

The pipeline is this:

RtpEndpoint -> (HubPort ->) OneToMany -> (HubPort ->) WebRtcEndpoint

I'm sending a h264 video and I guess there is a problem with the encoding to VP8.

This is the error log:

```
Segmentation fault (thread 140523436189440, pid 26443)
Stack trace:
0xAD89 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstvpx.so
0x666B at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstvpx.so
0x8E18 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstvpx.so
[gst_video_encoder_get_type]
/usr/lib/x86_64-linux-gnu/libgstvideo-1.5.so.0:0x419FB
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E4F7
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x7649E
[gst_base_transform_get_type]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x36500
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E4F7
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x7649E
[gst_base_transform_get_type]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x36500
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E4F7
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x7649E
[gst_base_transform_get_type]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x36500
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E4F7
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x7649E
0x3CAF9 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstcoreelements.so
```

**Comment by dfernandezlop** [comment]
Hi,

Could you tell me what KMS and GStreamer versions are you using?

Regards.

**Comment by Absor** [comment]
This is the dpkg output of kurento and gstreamer:

```
ii  kurento-media-server-6.0             6.4.0.trusty                               amd64        Kurento Media Server
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160224182850.34.g1d2c0c1.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.7.1.1~20160224182649.23.g036c2d2.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad1.5-0:amd64  1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.7.1.1~20160225111550.199.gba35ee7.trusty amd64        Core GStreamer libraries and elements
```

**Comment by igracia** [comment]
@Absor Is this still happening?

**Comment by jcaden** [comment]
It seems is still happening https://groups.google.com/forum/#!topic/kurento/f7u2PhSraok

@Absor could you describe the rtp source that you are using? Most probably the cause of the problem is in that source.

**Comment by Absor** [comment]
In this case I am using another Kurento as the source. The other Kurento pipeline is RtpEndpoint -> HubPort -> DispatcherOneToMany -> HubPort -> RtpEndpoint (output). Then the receiving RtpEndpoint is on the other Kurento.

Sorry for re-posting on the forums, I had forgotten this bug and the tracker you were using.

**Comment by Absor** [comment]
Seems to be an error with vp8enc again, but another error message this time. I haven't seen the original error message after upgrading Kurento version.

**Comment by Absor** [comment]
The original rtp source (to the other instance, that seems to have no problems) is ffmpeg if this helps/matters.

**Comment by jcaden** [comment]
Yes, it matters, there could be some problem with the formats. How are you exactly using ffmpeg to send media?

**Comment by Absor** [comment]
The source format is h264, ffmpeg says it is:

    Stream #0:0(und): Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 23.98 fps, 90k tbn, 23.98 tbc (default)

I still transcode it in the tests using ffmpeg (no copy option, but vcodec libx264):

    ffmpeg -re -i video.mp4 -an -vcodec libx264 -preset ultrafast -tune zerolatency -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ZDJ4Ump3N0xtRTg0V0k4OWJNaXpKRFl3ejZ0QVJW srtp://<KURENTO_IP_HERE>:<PORT>

The secure rtp key is randomized every time.

**Comment by Absor** [comment]
ffmpeg SDP

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Trailer
t=0 0
a=tool:libavformat 57.25.100
m=video 51290 RTP/AVP 96
c=IN IP4 <KURENTO_IP>
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ZDJ4Ump3N0xtRTg0V0k4OWJNaXpKRFl3ejZ0QVJW
```

RtpEndpoint is negotiated with:

```
v=0
o=- 0 0 IN IP4 0.0.0.0
s=-
t=0 0
m=video 1 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ZDJ4Ump3N0xtRTg0V0k4OWJNaXpKRFl3ejZ0QVJW
```

**Comment by jcaden** [comment]
Thank you!
Does is fail independently to the video.mp4 choose or is just with a specific one? Could it be shared?

**Comment by Absor** [comment]
I will try to isolate the problem better and get a repeatable case, will keep you updated.

**Comment by jcaden** [comment]
Cool, thanks.

**Comment by rbenitez** [comment]
Hi, 

we have a test for this problem [here](https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/test/functional/agnostic/AgnosticRtpEndpointToWebRtcWithFfmpegTest.java). With this test we have the same problem and we get sometimes a segmentation fault in the kms.

**Comment by Absor** [comment]
Any ideas on why? Is it ffmpeg output? I was not able to reproduce this after the day I got these errors, seems very random.

**Comment by jcaden** [comment]
It seems that ffmpeg is using a h264 profile (or at least NAL units) that is not supported by gstreamer, but I need further investigation.

This log entry gave me the clue:

    rtph264depay0:NAL unit type 26 not supported yet

**Comment by jcaden** [comment]
@rbenitez @Absor Can you confirm if media is transmitted from ffmpeg to KMS using UDP and not TCP?

**Comment by Absor** [comment]
I will check, I also explained my setup more related to another issue I have here if it is any help, SDP with another profile in use there too: https://groups.google.com/forum/#!topic/kurento/7ck5JTx9r2o

**Comment by Absor** [comment]
ffmpeg is sending using UDP.

**Comment by sancane** [comment]
Hi there!

The problem here is that you are sending encoded video to an RTPEndpoint that is not configured to use SDES, so all that errors in encoders are the result of trying to interpret the encoded media flow as if it wasn't encrypted.

Furthermore, I detected several issues in your example. First of all, as defined in RFC4568, SRTP security descriptions MUST only be used with the SRTP transport  (e.g., "RTP/SAVP" or "RTP/SAVPF") , I suggest you using SAVPF to enable support for feedback messages which help you to recover from packet losses quickly. So you should change your SDP for the next one:

v=0
o=- 0 0 IN IP4 0.0.0.0
s=-
t=0 0
m=video 1 RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ZDJ4Ump3N0xtRTg0V0k4OWJNaXpKRFl3ejZ0QVJW

Another problem here is regarding the RTPEndpoint configuration, you must create it providing support for AES_CM_128_HMAC_SHA1_80 encryption so you are using that encryption suite. In orde to do that, make sure you are creating your endpoint in this way:

Java Code:
RtpEndpoint rtpEp = new RtpEndpoint.Builder(mp).build();
SDES sdes = new SDES();
sdes.setCrypto(CryptoSuite.AES_128_CM_HMAC_SHA1_80);
RtpEndpoint rtpEp = new RtpEndpoint.Builder(mp).withCrypto(sdes).build();

Javascript Code:
var opt1 = {
  crypto: SDES({
    crypto : "AES_128_CM_HMAC_SHA1_32"
  })
 };
 pipeline.create("RtpEndpoint", opt1, function(error, rtpEp1){...});

Making above changes your code should work nicely.
Regards

**Comment by Absor** [comment]
I was using rtp/savpf, that sdp was a bad copy paste. I also configure the crypto in the endpoint. The video stream has worked and these problems came randomly.

What seems to have fixed the problems now was updating to ubuntu 16.04 and using your packages for it. Maybe something to do with newer libraries?

**Comment by sancane** [comment]
quite probable
