### ISSUE TITLE
WorkerPool 100% CPU lock when releasing multiple Endpoints

### ISSUE THREAD

**Issue by j1elo** [Kurento/bugtracker#462]
## Prerequisites

* [X] I have read the SUPPORT document
  

* [X] I have checked the Troubleshooting Guide
  

* [X] I have tested with the latest version of Kurento
  

## Issue description
When multiple MediaObjects (i.e. all derived classes such as WebRtcEndpoint or RtpEndpoint) are **released at the same time**, CPU usage will temporarily raise to 100% (because the release method is very CPU intensive). This, in turn, will cause an explosion of new threads from the WorkerPool class, because of deficiencies in how this class is implemented.

The WorkerPool class (kms-core/src/server/implementation/WorkerPool.cpp) maintains a thread pool that will service two methods from MediaSet:

* When a MediaSet wants to unref a MediaObject in `MediaSet::unref()` ([code](https://github.com/Kurento/kms-core/blob/1ca1c73e3a2c7002c0e45a9e506b5ada80158f84/src/server/implementation/MediaSet.cpp#L444))
* When a MediaSet wants to actually delete a MediaObject in `MediaSet::releasePointer()` ([code](https://github.com/Kurento/kms-core/blob/1ca1c73e3a2c7002c0e45a9e506b5ada80158f84/src/server/implementation/MediaSet.cpp#L480))

WorkerPool logic is flawed because with 100% CPU, its "health check" routine will trigger, adding one new thread to the pool ([code](https://github.com/Kurento/kms-core/blob/098714c746c64e3ccca2a7c29e6ba553c078da1a/src/server/implementation/WorkerPool.cpp#L160)), and will log the following warning message:

```
warning KurentoWorkerPool  WorkerPool.cpp:155 operator()()  Worker threads locked. Spawning a new one.
```

This is related to the fact that `MediaSet::unref()` and `MediaSet::releasePointer()` seem to take an unreasonable time to run, but that's a different issue.

## Context
Issue has been noticed during performance testing, a test with 15 simultaneous users was using around 35% CPU, but at the end of the test when all WebRtcEndpoints got released at the same time, the CPU got locked at 100% for more than 10 minutes.

## How to reproduce?
Create a many-to-many room with multiple WebRtcEndpoints and then try to release all of them at the same time.

## Expected & current behavior
CPU might need to stay at 100% for a while during Endpoint release, but it should end up recovering back to 0% after some reasonable time.

## (Optional) Possible solution
Avoid spawning infinite threads in the WorkerPool class.

**Comment by j1elo** [comment]
A rewrite of the WorkerPool class is being done in the branch `workerpool-rewrite` of `kms-core`, here:
https://github.com/Kurento/kms-core/tree/workerpool-rewrite

The WorkerPool class is rewritten to limit the number of threads to the number of CPU cores. This prevents the "thread explosion" issue. Of course, this doesn't change the fact that `MediaSet::unref()` and `MediaSet::releasePointer()` seem to suffer from a LOT of lock contention, so releasing multiple WebRtcEndpoints at the same time will still use a lot of CPU for a period of time that can vary between some seconds and a couple minutes.

**Comment by j1elo** [comment]
Looks like we have two issues here:

* 100% CPU usage for several minutes, when lots of Endpoints have to be disconnected at the same time.
* High lock contention rate on the mutexes that protect the ConnectionData structs (which store the information about a connection between two MediaElements).

Our most important issue is actually the 100% CPU usage, not the lock contention. After some profiling with Valgrind's Callgrind I've discovered that the issue comes from a lot of ineffective lookup operations which pass GstPad names around, leaving other modules to again search element pads by name.

I'm working on a change that would instead store the GstPad itself as a cache, and use it directly instead of having to look for it multiple times. These lookups were "nothing" with small scenarios, but when presented with thousands of MediaElement connections, all these start to sum up and cause a lot of seemingly unnecessary CPU usage.

**Comment by j1elo** [comment]
New branch published, now can be tested:
* For apt-get installs: use repo `deb [arch=amd64] http://ubuntu.openvidu.io/workerpool-rewrite xenial kms6` (with either `xenial` or `bionic`).
* For Docker: `docker pull kurento/kurento-media-server-exp:workerpool-rewrite`

**Comment by j1elo** [comment]
This is a graph of CPU% usage during a load test. The test went up to 12 participants. The moment the test ends (4:24:30) all 12 participants leave at the same time, and the thread lock bug is triggered, with CPU staying at 100%:
![image](https://user-images.githubusercontent.com/1824582/82876796-a3e70500-9f39-11ea-8a51-b7eeec7034d5.png)

With the fix proposed in https://github.com/Kurento/kms-core/tree/workerpool-rewrite, the test ends (4:44:30) and CPU comes back to idle levels:
![image](https://user-images.githubusercontent.com/1824582/82877204-3091c300-9f3a-11ea-8b8a-d58fad27a356.png)

**Comment by prlanzarin** [comment]
Did some testing as well. 
Scenario: 30 participants with video, full star topology, 8 vCPU E5-2630 box, 8GB RAM.
Join time is spaced ~5s. Leave time is scheduled in batches of 5 participants every minute (kind of a friendly scenario). Could reproduce the lock with current master (see graph `Before`). Couldn't reproduce with `workerpool-rewrite` (see graph `after`).

Looks good, great job.

**Before**
![30x30, dynamic profiles_ cpu (before)](https://user-images.githubusercontent.com/4529051/83281264-355ead00-a1ae-11ea-8a04-dc70887ba22d.png)
**After**
![30x30_ dynamic profiles, cpu (after)](https://user-images.githubusercontent.com/4529051/83281297-414a6f00-a1ae-11ea-91f1-ea31a62648ad.png)

**Comment by j1elo** [comment]
The `workerpool-rewrite` branch with the fix can be tested with either *apt-get* installation or Docker images:

* For **apt-get**, the [Local Installation](https://doc-kurento.readthedocs.io/en/latest/user/installation.html#local-installation) instructions are the same, but the Apt repository is this one:

  Ubuntu 16.04 (Xenial):
  ```
  deb [arch=amd64] http://ubuntu.openvidu.io/workerpool-rewrite xenial kms6
  ```

  Ubuntu 18.04 (Bionic):
  ```
  deb [arch=amd64] http://ubuntu.openvidu.io/workerpool-rewrite bionic kms6
  ```

* For **Docker**, use this [experimental image](https://hub.docker.com/r/kurento/kurento-media-server-exp):

  ```
  docker pull kurento/kurento-media-server-exp:workerpool-rewrite

  docker run [...] kurento/kurento-media-server-exp:workerpool-rewrite
  ```
