### ISSUE TITLE
not able start a openvidu kms server

### ISSUE THREAD

**Issue by pradeepmdk** [Kurento/bugtracker#464]
0x7f585c008a70 ERROR   KurentoUriEndpointImpl UriEndpointImpl.cpp:179:stop:<kmsrecorderendpoint0> Error: Already in state stop

here my config:

docker run -p 4443:4443  --rm --name openvidu -e OPENVIDU_PUBLICURL=https://192.168.43.111:4443  -e OPENVIDU_SECRET=MY_SECRET -e OPENVIDU_RECORDING=true  -e OPENVIDU_RECORDING_PATH=~/Documents/media -v ~/Documents/media:/media   -v /var/run/docker.sock:/var/run/docker.sock  openvidu/openvidu-server-kms

**Comment by micaelgallego** [comment]
Use openvidu forum https://openvidu.discourse.group
