### ISSUE TITLE
Docker failed to run container of kurento image on aarch64

### ISSUE THREAD

**Issue by noddy09** [Kurento/bugtracker#466]
I tried to run kurento's docker container by command:
`docker run --name kms -d -p 8333:8888 kurento/kurento-media-server`
This gave me docker container id as output, but when I tried to see logs of same container by command:
` docker logs -f kms`
This returns: `standard_init_linux.go:211: exec user process caused "exec format error" `

**Comment by j1elo** [comment]
Well it Works For Me (tm)

```
$ docker pull kurento/kurento-media-server:latest
latest: Pulling from kurento/kurento-media-server
Digest: sha256:5a9155798bf959292ce95c2421565e50148cc6a68fc382157447332daa349ce4
Status: Image is up to date for kurento/kurento-media-server:latest
docker.io/kurento/kurento-media-server:latest

$ docker run --name kms -d -p 8333:8888 kurento/kurento-media-server:latest
3179026c01656063bfd5ea91814fa3c44ffee5fdc60cedfa7facb6c7e5ba04b1

$ docker logs -f kms
(...)
[Docker entrypoint] Start Kurento Media Server, UID: 0
(...)
```

The issue template is there for a reason, not to get deleted and ignored as you did. Especially the section about your environment, what OS, what Docker version, how to reproduce the issue.

**Comment by luofang** [comment]
I have the same questions when i run the KMS on my docker. don't know what happend.
Hardware: Raspberry Pi
OS: ubuntu 18.04 LTS. (or debian baster 10) not worked both.
Docker version: 19.13.9.

**Comment by j1elo** [comment]
`exec user process caused "exec format error"` means "_you are trying to run a container made for other architecture_".

The `kurento/kurento-media-server` images are built for x86_64 architecture. You will need to run the container on a system that has the x86_64 architecture.

**Comment by j1elo** [comment]
Similar issues:
* [docker image error: standard_init_linux.go:211: exec user process caused “exec format error”](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4558)
* [standard_init_linux.go:211: exec user process caused "exec format error"](https://github.com/pypa/manylinux/issues/410)

**Comment by noddy09** [comment]
> The issue template is there for a reason, not to get deleted and ignored as you did. Especially the section about your environment, what OS, what Docker version, how to reproduce the issue.

Firstly, Sorry for this. I hit /issues/new/ and i landed directly here and skipped those docs mistakly.
and again sorry for late response, i just came back to home from epidemic recovery.



> The `kurento/kurento-media-server` images are built for x86_64 architecture. You will need to run the container on a system that has the x86_64 architecture.

As I got to know [this](https://github.com/Kurento/kurento-media-server/pull/10/commits) , arch64 is supported by kurento. So I thought same PR merged with docker images also, isn't it?
Here are my environment details:
OS: Ubuntu 20.04 (Linux 5.4.0-1009-aws #9-Ubuntu aarch64 GNU/Linux )
Docker version: 19.03.8, build afacb8b7f0

**Comment by j1elo** [comment]
Hi, that PR only added a small change in a 3rd-party library, so it can be compiled from sources in aarch64 systems. It didn't change anything about the build process of Docker images.

Our [Kurento Docker images](https://hub.docker.com/r/kurento/kurento-media-server) are generated with the files from [kurento-docker](https://github.com/Kurento/kurento-docker/tree/master/kurento-media-server), you can have a look and see that they are based on the official Ubuntu images, which I guess are only compatible with x86_64 architectures. The images are actually just installing packages from the Apt repository, which contains binaries built, again, on the ubuntu:16.04 Docker image.

We don't have resources or people that can maintain builds on other architectures, so for different than x86_64 you'll have to [build from sources](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#build-from-sources).

**Comment by noddy09** [comment]
> I hit /issues/new/ and i landed directly here and skipped those docs mistakly.

Thanks for making corrections in readme.md

> We don't have resources or people that can maintain builds on other architectures, so for different than x86_64 you'll have to build from sources.

I will try to build deb for aarch64 also. Thank you for guidance.

**Comment by storkinsj** [comment]
Hey folks, FYI I saw an answer on stackexchange recently that seemed to nail this redherring error message. In their case, and in my case, the problem was that the execute permission was not set on the execution target. You may want to chmod+x to the execution target in your Dockerfile/Docker build and try again.
