### ISSUE TITLE
OpenSSL 1.0.2 is out of support

### ISSUE THREAD

**Issue by dasJ** [Kurento/bugtracker#467]
Title says it all. From the OpenSSL website:

> 
> With regards to current and future releases the OpenSSL project has adopted the following policy:
> 
> -    The next version of OpenSSL will be 3.0.0.
> -    Version 1.1.1 will be supported until 2023-09-11 (LTS).
> -    Version 1.0.2 is no longer supported. Extended support for 1.0.2 to gain access to security fixes for that version is available.
> -    Versions 1.1.0, 1.0.1, 1.0.0 and 0.9.8 are no longer supported.

If you're thinking "hey, there's extended support":

> 
> Premium Level Support
> 
> US$50,000 annually
> 
>     A support contract designed to meet the needs of Enterprise customers
>     Includes extended support for the immediately previous LTS release beyond the public EOL date for that release 

Currently, building the current Kurento (6.13.0) with a newer OpenSSL version results in:
```
[ 22%] Building CXX object server/transport/websocket/CMakeFiles/websocketTransport.dir/WebSocketRegistrar.cpp.o
In file included from /build/source/server/transport/websocket/websocketpp/config/asio.hpp:33,
                 from /build/source/server/transport/websocket/WebSocketRegistrar.hpp:26,
                 from /build/source/server/transport/websocket/WebSocketRegistrar.cpp:18:
/build/source/server/transport/websocket/websocketpp/transport/asio/security/tls.hpp: In member function 'std::error_code websocketpp::transport::asio::tls_socket::connection::translate_ec(ErrorCodeType)':
/build/source/server/transport/websocket/websocketpp/transport/asio/security/tls.hpp:386:43: error: 'SSL_R_SHORT_READ' was not declared in this scope; did you mean 'SSL_F_SSL_READ'?
  386 |       if (ERR_GET_REASON (ec.value() ) == SSL_R_SHORT_READ) {
      |                                           ^~~~~~~~~~~~~~~~
      |                                           SSL_F_SSL_READ
```
…  and more errors following

**Comment by j1elo** [comment]
Related to / Duplicate of https://github.com/Kurento/bugtracker/issues/356
See https://github.com/Kurento/kurento-media-server/pull/15 comments for some background info.
