### ISSUE TITLE
Error to with RecorderEnpoint and WebRTCEndpoint codec H264 et OPUS

### ISSUE THREAD

**Issue by bodyscape** [Kurento/bugtracker#469]
Tested with Kurento master branch and 6.13.0

i have this log :

0:01:03.018754420  4100 0x7f9f14001f70 INFO             agnosticbin kmsagnosticbin.c:774:kms_agnostic_bin2_link_pad:<kmsagnosticbin2-0> Upstream provided caps: ANY
0:01:03.018886621  4100 0x7f9f14001f70 INFO             agnosticbin kmsagnosticbin.c:783:kms_agnostic_bin2_link_pad:<kmsagnosticbin2-0> Downstream wanted caps: EMPTY
0:01:03.019082823  4100 0x7f9f14001f70 ERROR       recorderendpoint kmsrecorderendpoint.c:1641:kms_recorder_endpoint_query_accept_caps:<kmsrecorderendpoint0> Incompatbile caps audio/x-aac
0:01:03.019101124  4100 0x7f9f14001f70 ERROR            agnosticbin kmsagnosticbin.c:397:proxy_src_pad_query_function:<src_0:proxypad33> Caps not accepted: accept-caps query: 0x7f9f00058a30, GstQueryAcceptCaps, caps=(GstCaps)"audio/x-opus\,\ rate\=\(int\)48000\,\ channels\=\(int\)2\,\ channel-mapping-family\=\(int\)0\,\ stream-count\=\(int\)1\,\ coupled-count\=\(int\)1\,\ streamheader\=\(buffer\)\<\ 4f707573486561640102000080bb0000000000\,\ 4f707573546167731f0000004753747265616d657220656e636f64656420766f72626973636f6d6d656e740000000001\ \>", result=(boolean)false;

**Comment by j1elo** [comment]
`Incompatbile caps audio/x-aac` tells me that the audio is not OPUS but AAC...

**Comment by bodyscape** [comment]
Hi, the source audio is OPUS from webrtc and the recorderEnpoint is set to MKV. In KVM is H264 and AAC. It's suppose to make the transcoding, right? not crash
