### ISSUE TITLE
Kurento 6.4.1 crashes when configuring the WebRtcEndpoint.conf.ini pemCertificate

### ISSUE THREAD

**Issue by tsonghong** [Kurento/bugtracker#47]
When we configure a pem certificate to /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini,
we see that kurento crashes after exchanging SDPs with a WebRtc application.

We are using  Version: 6.4.1 Kurento (daily build)
[PEMcrashing_gdbcoredump.txt](https://github.com/Kurento/bugtracker/files/173560/PEMcrashing_gdbcoredump.txt)
[PEMcrashing_kurentomedialog.txt](https://github.com/Kurento/bugtracker/files/173561/PEMcrashing_kurentomedialog.txt)

ubuntu@kurento1:/etc/kurento/modules/kurento$ cat WebRtcEndpoint.conf.ini

stunServerAddress=<cut>
stunServerPort=19302

pemCertificate=<cut>.pem

We verified that if we undo the configuration, then kurento won't crash.

The exact versions of the binaries are:

ubuntu@kurento1:/var/log/kurento-media-server$ dpkg --list | grep kurento
ii  kurento-media-server-6.0               6.4.1~20160310095912.4.g9a56711.trusty     amd64        Kurento Media Server
ii  kurento-module-creator-4.0             4.0.5~20160210214321.3.g76ca25d.trusty     all          Kurento module creator
ubuntu@kurento1:/var/log/kurento-media-server$ dpkg --list | grep kms
ii  kms-cmake-utils                        1.3.1~20160225151921.1.gb4fa868.trusty     all          Kurento cmake utils
ii  kms-core-6.0                           6.4.1~20160314161458.20.g7ba2f64.trusty    amd64        Kurento core module
ii  kms-core-6.0-dev                       6.4.1~20160314161458.20.g7ba2f64.trusty    amd64        Kurento core module
ii  kms-elements-6.0                       6.4.1~20160314164110.25.g3982eb5.trusty    amd64        Kurento elements module
ii  kms-elements-6.0-dev                   6.4.1~20160314164110.25.g3982eb5.trusty    amd64        Kurento elements module
ii  kms-filters-6.0                        6.4.1~20160314170258.3.g06e2b4f.trusty     amd64        Kurento filters module
ii  kms-filters-6.0-dev                    6.4.1~20160314170258.3.g06e2b4f.trusty     amd64        Kurento filters module
ii  kms-jsonrpc-1.0                        1.1.1~20160210175344.2.gf8e5185.trusty     amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                    1.1.1~20160210175344.2.gf8e5185.trusty     amd64        Kurento jsonrpc library
ii  kmsjsoncpp                             1.6.3~20160224182314.38.g263929e.trusty    amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                         1.6.3~20160224182314.38.g263929e.trusty    amd64        Kurento jsonrpc library
ubuntu@kurento1:/var/log/kurento-media-server$ 

Above attached files are:

1) The gdp core dump stack trace

2) The kurento logs that occur during the crash for exactly one stream attempt

Other info:

1) We are doing H.264 (not VP8) only

2) Our kurento servers are running on Ubuntu 14.04

3) The pem file we are using contains all certificates including root

**Comment by dfernandezlop** [comment]
Hi  @tsonghong,

It seems that your certificate doesn't contain the private key.

Please, try with a certificate generated with the commands below:
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes
cat key.pem cert.pem > certificate.pem

Regards.

**Comment by tsonghong** [comment]
Thanks for the quick reply, seems to work!
