### ISSUE TITLE
Kuernto with 6.12.1 version is not working in IE 11

### ISSUE THREAD

**Issue by sudhi001** [Kurento/bugtracker#474]
Kurento latest release version is not working in IE 11, I have tested with kurento Java demo application. None of the demo application is not working with IE.  Working good in All other browsers. Please Support ASAP
![Capture](https://user-images.githubusercontent.com/7729914/82176131-7d025080-98f3-11ea-91b8-14d9cf9d87ae.PNG)

**Comment by j1elo** [comment]
Not a bug: IE11 doesn't have direct support for WebRTC, so we don't support it either.

The Pull Request Kurento/kurento-utils-js#25 added code in kurento-utils-js for a (paid?) private plugin from Temasys, that seems to add WebRTC capabilities to IE>=9. The PR was accepted, but **we don't give support for it**. For more details check out the Temasys plugin, or contact the user that did the PR.
