### ISSUE TITLE
Javascript - recorder tutorial not working on firefox or chrome .

### ISSUE THREAD

**Issue by GEETAMJ** [Kurento/bugtracker#475]
## Prerequisites

* [] I have read the SUPPORT document
  

* [] I have checked the Troubleshooting Guide
  

* [] I have tested with the latest version of Kurento
  

## Issue description

Kurento recorder tutorial only shows local stream and not the remote stream , fails with the following message running endlessly . :-
App console->>
onClick
Use freeice
Offer...
reconnect to server 0 100 undefined
reconnect to server 1 100 undefined
reconnect to server 2 200 undefined
reconnect to server 3 300 undefined

Browser console ->>
kurento-client.js:27362 WebSocket connection to 'ws://localhost:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
## How to reproduce?

Just follow https://doc-kurento.readthedocs.io/en/6.12.0/tutorials/js/tutorial-recorder.html

### INFO about Kurento Media Server

* Kurento version:  
* Server OS:        
* Installation method:
    
  - [] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:                 
* Kurento Client version:   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment]
This is fixed in latest code; use the newer instructions: https://doc-kurento.readthedocs.io/en/latest/tutorials/js/tutorial-recorder.html
