### ISSUE TITLE
Cant install Kurento-media-server on Ubuntu 18.04(bionic)

### ISSUE THREAD

**Issue by GEETAMJ** [Kurento/bugtracker#476]
## Prerequisites

* [] I have read the SUPPORT document
  

* [] I have checked the Troubleshooting Guide
  

* [] I have tested with the latest version of Kurento
  

## Issue description

Cant install kurento-media-server on my Ubuntu 18.04 due to unmet dependencies:-

The following packages have unmet dependencies:
 kurento-media-server : Depends: kms-core (>= 6.7.0) but it is not going to be installed
                        Depends: libboost-log1.65.1 but it is not installable
                        Depends: libboost-program-options1.65.1 but it is not installable
                        Depends: libboost-thread1.65.1 but it is not installable
                        Depends: gstreamer1.5-plugins-bad but it is not going to be installed
                        Depends: gstreamer1.5-plugins-good but it is not going to be installed
                        Depends: gstreamer1.5-plugins-ugly but it is not going to be installed
                        Depends: kms-elements (>= 6.7.0) but it is not going to be installed
                        Depends: kms-filters (>= 6.7.0) but it is not going to be installed

## How to reproduce?

I followed the official docs for installation ,
https://doc-kurento.readthedocs.io/en/6.13.2/user/installation.html#installation-local

### INFO about Kurento Media Server

* Kurento version:  
* Server OS:        
* Installation method:
    
  - [] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:                 
* Kurento Client version:   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment]
It works with a clean Ubuntu 18.04. Proof:

```
# Starts a clean in-place Docker container
docker run --rm -i ubuntu:18.04 /bin/bash <<'DOCKERCOMMANDS'

apt-get update
apt-get install --no-install-recommends --yes \
    gnupg
    
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83

source /etc/upstream-release/lsb-release 2>/dev/null || source /etc/lsb-release

echo "deb [arch=amd64] http://ubuntu.openvidu.io/6.13.2 $DISTRIB_CODENAME kms6" \
    >/etc/apt/sources.list.d/kurento.list

apt-get update
apt-get install --no-install-recommends --yes \
    kurento-media-server

echo "Done! KMS version:"
kurento-media-server --version

DOCKERCOMMANDS
# In-place Docker container commands end here
```

**Comment by j1elo** [comment]
Please reopen this issue if you are able to reproduce the installation issue in a clean environment with default settings. Preferably a Docker container, which is the perfect way to avoid the "Works For Me" situations.

**Comment by bASEstr** [comment]
For anyone that is having this issue, you **must** fully install ubuntu for kurento media server to be installable.
You cannot install kurento media server when using the OS directly from the ISO (aka "try ubuntu" method).
