### ISSUE TITLE
Embedded device video not displayed on FF w/o manual WebRtcEndpoint reconnect (Kurento 6.3+)

### ISSUE THREAD

**Issue by tsonghong** [Kurento/bugtracker#48]
Hello Kurento team:

We have embedded linux devices (similar to raspberry pi) running OpenWebRTC
that were able to stream H.264 video to Firefox prefectly fine with Kurento 6.2.

But after we upgraded Kurento to 6.3+ (including the 6.4.1 daily build),
we noticed that the embedded device video would not display on Firefox unless we
issued a reconnect (i.e. disconnect() and connect()) between 
the embedded device and the Firefox Browsers' WebRtcEndpoints.

On the other hand, using webcams from our notebooks (including the Macbooks) as the video source
 would still work fine before and after the Kurento 6.3+ upgrade.

To try to figure out the discrepency between our embedded device vs. the notebook webcams,
we then compiled a openh264 plugin with debug log enabled for Kurento 6.2 and 6.4.
We found that in the case of the embedded device, 
Kurento 6.4 did not send out SPS/PPS to the Firefox until we did the disconnect() and connect().
For Kurento 6.2, we could see the SPS/PPS right before IDR frame after SEI frame.
Also, we noticed that in Kurento 6.4, the SPS/PPS frames were only at the beginning of each chunk of multiple nals
possibly indicating that Kurento is manipulating the SPS/PPS. One guess was that perhaps Kurento caches it first
and only starts to prepend it after the disconnect()/connect().

So, to reword this:

Our setup is an embedded device conected to browser through kms via two webrtc links [embedded device —> kms —> browser].
In kms6.2.0, it seems every sps/pps sent from embedded device will reach the browser in the original nal packet order.
However, in 6.3, the SPSs/PPSs are only seen on the browser side after a kms disconnect() and connect().
This perhaps caused decoding issue on the browser side.
So, that left us wondering if the kms pipeline is manipulating the SPS/PPS. 

Some other key observations:

1) This issue is reproducible 100% of the time with our embedded devices, and not randomly happening.

2) During the period where Firefox doesn't display the video of the embedded device,
we can confirm that if we were to run "about:webrtc" on Firefox, we were indeed able
to see reported video packets including a constantly changing fps incoming.
Plus, when we ran a network traffic monitor, we could confirm 100 to 250+ kpbs of increased
network traffic going into the Firefox browser.
So, there was no doubt video data was reaching Firefox during the moments of no displayed video.

3) This issue would not happen if another WebRTC video session was already running
through the browser.  In other words, if there was at least one other WebRTC video session
from a remote source (could be webcam and doesn't have to be embedded device nor the same embedded device),
then any embedded device video session after that one will be displayed fine on Firefox (no need to disconnect() and connect()
to see the video).

4) We also observed the Kurento logs and found no error messages during the no video.
Attached below are the full logs,
but in summary we noticed a difference in the "Media Flow*" messages when comparing webcam vs. embedded device:

```
----------------------------------------------------------------
webcam:

1) WEBCAM connects to Kurento with WebRTC:

0:00:18.982057608  3784 0x7f982800ec50 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:430:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type video
0:00:18.996005744  3784 0x7f982800ed40 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:430:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type audio

2) WEBCAM Endpoint connects to the USER(Firefox) Endpoint and Video displays fine:

0:01:38.138247554  3784 0x7f982802c320 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type audio
0:01:38.458053067  3784 0x7f982802bf70 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type video

3) WEBCAM Endpoint disconnects the USER(Firefox) Endpoint:

0:04:08.134167388  3784 0x7f98480540a0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:480:mediaFlowInStateChange:<kmswebrtcendpoint1> Media NOT Flowing IN in pad default with type audio
0:04:08.135677836  3784 0x7f98480540a0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:480:mediaFlowInStateChange:<kmswebrtcendpoint1> Media NOT Flowing IN in pad default with type video

4) WEBCAM Endpoint reconnects the USER(Firefox) Endpoint:

0:04:55.882380378  3784 0x7f982c112370 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type audio
0:04:56.060663859  3784 0x7f982c0ee1e0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type video
```

```
embedded device:

1) EmbeddedDevice connects to Kurento with WebRTC:

0:00:27.283718292  3631 0x7f9ed0002b70 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:430:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type audio
0:00:33.190223866  3631 0x7f9ed8002540 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:430:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type video

2) EmbeddedDevice Endpoint connects to the USER(Firefox) Endpoint and Video doesn't display on Firefox:

0:06:00.137348698  3631 0x7f9eec053f20 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type audio
0:06:04.929399109  3631 0x7f9eec0540f0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type video

3) EmbeddedDevice Endpoint disconnects the USER(Firefox) Endpoint:

0:06:42.109000358  3631 0x7f9ed0002b20 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:480:mediaFlowInStateChange:<kmswebrtcendpoint1> Media NOT Flowing IN in pad default with type audio
0:06:42.109520868  3631 0x7f9ed0002b20 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:480:mediaFlowInStateChange:<kmswebrtcendpoint1> Media NOT Flowing IN in pad default with type video
0:06:43.167749173  3631 0x7f9ed0002b20 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:434:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media NOT Flowing OUT in pad default with type video

4) EmbeddedDevice Endpoint reconnects the USER(Firefox) Endpoint and Video does display on Firefox:
0:07:02.613650456  3631 0x7f9ee4083ca0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type audio
0:07:02.810242711  3631 0x7f9ed8002540 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:430:mediaFlowOutStateChange:<kmswebrtcendpoint0> Media Flowing OUT in pad default with type video
0:07:08.475622697  3631 0x7f9ee40838f0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:476:mediaFlowInStateChange:<kmswebrtcendpoint1> Media Flowing IN in pad default with type video
```

5) We also thought perhaps the issue related to the SDP descrepancy between the SDP offer of the Firefox webcam vs.
embedded device.  And here is the SDP reported in the Kurento 6.4 logs for both of those
(in case you guys can spot a key mandatory difference):

 ```
webcam SDP offer:

"v=0\r\n
o=mozilla...THIS_IS_SDPARTA-43.0 7596407556004302705 0 IN IP4 0.0.0.0\r\n
s=-\r\n
t=0 0\r\n
a=fingerprint:sha-256 D6:D0:EC:FF:C4:9C:19:2D:0E:6A:2B:B0:C5:D4:F7:14:A5:3C:29:F5:A3:E6:51:65:E1:92:CB:92:28:D2:A0:6E\r\n
a=group:BUNDLE sdparta_0 sdparta_1\r\n
a=ice-options:trickle\r\n
a=msid-semantic:WMS *\r\n

m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8\r\n
c=IN IP4 0.0.0.0\r\n
a=sendonly\r\n
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\n
a=ice-pwd:8c5a5e5c610c50650f4c8acd31ac4589\r\n
a=ice-ufrag:5d8eda04\r\n
a=mid:sdparta_0\r\n
a=msid:{43e195e6-b5fb-4658-bb01-7560fb8aae80} {e54bcc97-0ac2-4ac0-81d8-4102d805305c}\r\n
a=rtcp-mux\r\n
a=rtpmap:109 opus/48000/2\r\n
a=rtpmap:9 G722/8000/1\r\n
a=rtpmap:0 PCMU/8000\r\n
a=rtpmap:8 PCMA/8000\r\n
a=setup:actpass\r\n
a=ssrc:2397072748 cname:{e445d9ae-609a-41f3-9b5b-e05460621b2f}\r\n

m=video 9 UDP/TLS/RTP/SAVPF 120 126 97\r\n
c=IN IP4 0.0.0.0\r\n
a=sendonly\r\n
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\n
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1\r\n
a=ice-pwd:8c5a5e5c610c50650f4c8acd31ac4589\r\n
a=ice-ufrag:5d8eda04\r\n
a=mid:sdparta_1\r\n
a=msid:{43e195e6-b5fb-4658-bb01-7560fb8aae80} {d9bff552-bf9d-45a4-9825-9227b49b4426}\r\n
a=rtcp-fb:120 nack\r\n
a=rtcp-fb:120 nack pli\r\n
a=rtcp-fb:120 ccm fir\r\n
a=rtcp-fb:126 nack\r\n
a=rtcp-fb:126 nack pli\r\n
a=rtcp-fb:126 ccm fir\r\n
a=rtcp-fb:97 nack\r\n
a=rtcp-fb:97 nack pli\r\n
a=rtcp-fb:97 ccm fir\r\n
a=rtcp-mux\r\n
a=rtpmap:120 VP8/90000\r\n
a=rtpmap:126 H264/90000\r\n
a=rtpmap:97 H264/90000\r\n
a=setup:actpass\r\n
a=ssrc:1705482647 cname:{e445d9ae-609a-41f3-9b5b-e05460621b2f}\r\n
```

```
Embedded Device SDP offer:

"v=0\r\n
o=- 1457885336085230300 1 IN IP4 127.0.0.1\r\n
s=-\r\n
t=0 0\r\n

m=audio 9 UDP/TLS/RTP/SAVPF 0\r\n
c=IN IP4 0.0.0.0\r\n
a=rtcp-mux\r\n
a=sendrecv\r\n
a=rtpmap:0 PCMU/8000\r\n
a=ice-ufrag:fzMJ\r\n
a=ice-pwd:Z+keesWgM1K3N8ZiNb4wsI\r\n
a=fingerprint:sha-256 E7:C8:CA:E4:51:CE:D0:6B:BD:95:01:1A:02:84:59:6C:92:63:BA:BF:A0:FD:1C:6D:83:C5:AC:3F:DB:9A:B3:7F\r\n
a=setup:active\r\n

m=video 9 UDP/TLS/RTP/SAVPF 126\r\n
c=IN IP4 0.0.0.0\r\n
a=rtcp-mux\r\n
a=sendrecv\r\n
a=rtpmap:126 H264/90000\r\n
a=fmtp:126 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\n
a=rtcp-fb:126 nack pli\r\n
a=rtcp-fb:126 ccm fir\r\n
a=ice-ufrag:Zu4u\r\n
a=ice-pwd:z5Cb74v4zzWtYBxIJk7efw\r\n
a=fingerprint:sha-256 E7:C8:CA:E4:51:CE:D0:6B:BD:95:01:1A:02:84:59:6C:92:63:BA:BF:A0:FD:1C:6D:83:C5:AC:3F:DB:9A:B3:7F\r\n
a=setup:active\r\n"
```

Kurento full logs:

[kurentologs_embedded.txt](https://github.com/Kurento/bugtracker/files/174623/kurentologs_embedded.txt)
[kurentologs_webcam.txt](https://github.com/Kurento/bugtracker/files/174624/kurentologs_webcam.txt)

**Comment by tsonghong** [comment]
Just a quick update:

One of our team members said that the issue is related to how 
Kurento interacts with the gstreamer1.5-plugins-good library.

Because he said that with this version installed:

gstreamer1.5-plugins-good:amd64      1.7.0.1~20151125150841.141.g0708286.trusty

He didn't have the issue even with Kurento 6.2 and 6.3 and presumably 6.4.

However, he said when he upgraded to:

gstreamer1.5-plugins-good:amd64      1.7.1.1~20160224182713.65.ge5dc864.trusty

then he had the issue for both 6.2 and 6.3 and 6.4.

Also, he said that if Kurento transcoded the incoming H264 to VP8 (i.e. VP8 going to FF browser),
the issue was never present (regardless of what version gstreamer1.5-plugins-good was).

So, it apperas to be how Kurento and gstreamer good plugin interacts when dealing with H264.

**Comment by tsonghong** [comment]
By the way, we beleive the issue is related to the "config-interval" parameter in the rtp gst library as mentioned:

https://github.com/Kurento/gst-plugins-good/commit/453a618a9dc0ee6b35532f8b6c1d526300e17c54

Because based on that description, the SPS/PPS are disabled by default.  So, if you can show me how to configure the "-1 = send with every IDR frame"within kurento package and if we verify it works, then I think we can close this issue.

Thanks!

Henry

**Comment by jcaden** [comment]
@tsonghong  This property is currently set to send a SPS/PPS package every second. I think that it will be enough.

**Comment by tsonghong** [comment]
In the master branch, I see the DEFAULT_CONFIG_INTERVAL set to 0 which based on the comments says disable sending SPS/PPS.  If it were every second, I would think DEFAULT_CONFIG_INTERVAL would be 1.  Am I missing something?

I'm referring to:
https://github.com/Kurento/gst-plugins-good/blob/master/gst/rtp/gstrtph264pay.c#L71

**Comment by igracia** [comment]
@tsonghong Is this still happening in 6.5.0?

**Comment by dfernandezlop** [comment]
I'm going to close the bug because there isn't new information since two months ago.
