### ISSUE TITLE
Call started but not able to see caller video

### ISSUE THREAD

**Issue by vivekgupta8983** [Kurento/bugtracker#483]
## Prerequisites

* [] I have read the SUPPORT document
  

* [] I have checked the Troubleshooting Guide
  

* [] I have tested with the latest version of Kurento
  

### INFO about Kurento Media Server

* Kurento version:  
* Server OS:        
* Installation method:
    
  - [] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:                 
* Kurento Client version:   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment]
Please use the [Kurento Public Mailing List](https://groups.google.com/forum/#!forum/kurento) for questions about how to configure Kurento. Other users will probably be able to help you.

I'm closing this because it is not about a bug.
