### ISSUE TITLE
DAEMON_MAX_FILES is evaluted to 0 on ubuntu 20.04

### ISSUE THREAD

**Issue by uwesimon** [Kurento/bugtracker#488]
in 
  /etc/default/kurento-media-server 
the setting
DAEMON_MAX_FILES="$(( ($(cat /proc/sys/fs/file-max) * 50) / 100 ))"
evaluated to 0

Reason:
cat /proc/sys/fs/file-max
returns
9223372036854775807

so the * 50 produces an 64bit overrun.

This causes broken pipe and other errors during startup and kurento-media-server is not starting.
No messages in logfile because file could not be opened.

Better use
DAEMON_MAX_FILES="$(( $(cat /proc/sys/fs/file-max)  / 2 ))"

**Comment by j1elo** [comment]
I wonder why the original author of that line (https://github.com/Kurento/kurento-media-server/commit/4502b2a55b0c9a5d2b5e554f7d7f9e9d9a86b8be) decided to use such a convoluted method to divide by 2.
