### ISSUE TITLE
Unable to get stream in WAN network.

### ISSUE THREAD

**Issue by ajayDhomase46** [Kurento/bugtracker#489]
Operating system (Ubuntu 16.04, 18.04, etc.) --> Ubuntu 18.04
Installation method (apt-get, Docker, AWS, build from sources) --> apt-get
Kurento version --> 6.13.2

I’m having trouble with “kurento-group-call” application, when clients use the application in the LAN network it works fine. But unable to get video stream when clients connected from the WAN network. I have followed the Installation Guide for the Kurento media server. 
Below is my configured kurento server:

{
    "mediaServer": {
        "resources": {
            "\/\/exceptionLimit": "0.8",
            "\/\/killLimit": "0.7",
            "garbageCollectorPeriod": "240",
            "\/\/": "Default: false",
            "disableRequestCache": "false"
        },
        "net": {
            "websocket": {
                "\/\/ipv6": "false",
                "port": "8888",
                "secure": {
                    "port": "8433",
                    "\/\/certificate": "cert+key.pem",
                    "\/\/": "Password for the private key, if one was set when the key was created",
                    "\/\/password": ""
                },
                "\/\/registrar": {
                    "\/\/address": "ws:\/\/localhost:9090",
                    "\/\/localAddress": "localhost"
                },
                "\/\/": "Default: SOMAXCONN (128)",
                "\/\/connqueue": "128",
                "path": "kurento",
                "threads": "10"
            }
        }
    },
    "configPath": "\/etc\/kurento",
    "modules": {
        "kurento": {
            "BaseRtpEndpoint": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "PlayerEndpoint": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "HttpEndpoint": {
                "serverAddress": "localhost",
                "port": "9091",
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "WebRtcEndpoint": {
                "externalAddress": "xx.xx.xx.xx",
                "stunServerAddress": "xx.xx.xx.xx",
                "stunServerPort": "3478",
                "turnURL": "kurento:kurento@xx.xx.xx.xx:3478?transport=udp",
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "MediaElement": {
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "SdpEndpoint": {
                "numAudioMedias": “1”,
                "numVideoMedias": “1”,
                "audioCodecs": [
                    {
                        "name": "opus\/48000\/2",
                        "\/\/": "Next is an example about how a codec can be configured.",
                        "\/\/": "WARNING: Usage of properties is not yet supported",
                        "\/\/properties": {
                            "\/\/maxcodedaudiobandwidth": "16000",
                            "\/\/maxaveragebitrate": "20000",
                            "\/\/stereo": "1",
                            "\/\/useinbandfec": "1",
                            "\/\/usedtx": "0"
                        }
                    },
                    {
                        "name": "PCMU\/8000"
                    },
                    {
                        "name": "AMR\/8000"
                    }
                ],
                "videoCodecs": [
                    {
                        "name": "VP8\/90000"
                    },
                    {
                        "name": "H264\/90000"
                    }
                ],
                "configPath": "\/etc\/kurento\/modules\/kurento"
            },
            "UriEndpoint": {
                "defaultPath": "file:\/\/\/var\/lib\/kurento\/",
                "configPath": "\/etc\/kurento\/modules\/kurento"
            }
        }
    }
}
-------------------------------------------
and turnserver.conf is as follows:

external-ip=xx.xx.xx.xx
listening-port=3478
min-port=49152
max-port=65535
verbose
fingerprint
lt-cred-mech
realm=kurento.org
user=kurento:kurento
log-file=/var/log/turnserver/turnserver.log
simple-log

-------------------------------------------------------
I have opened below ports on AWS server:

TCP: 3478,8443,8888,443,5349
UDP: 3478,443,49152-65535

Any help would be appreciated!!

**Comment by j1elo** [comment]
Please use the [Kurento Public Mailing List](https://groups.google.com/forum/#!forum/kurento) for questions about how to configure Kurento. Other users will probably be able to help you.

I'm closing this because it is not about a bug.
