### ISSUE TITLE
MediaPipeline' not found (Code:40101, Type:null, Data: {"type":"MEDIA_OBJECT_NOT_FOUND"})

### ISSUE THREAD

**Issue by lizige** [Kurento/bugtracker#498]
KMS version is 6.14.0

## Issue description

RomManager create conference system,  start one instance of my conference app , is ok.
start two instance ,create webrtcenpoint  report this error  
MediaPipeline' not found (Code:40101, Type:null, Data: {"type":"MEDIA_OBJECT_NOT_FOUND"})

**Comment by j1elo** [comment]
Each instance of KMS must contain its own Pipeline, you cannot reference the pipeline from instance 1 to be used by WebRtcEndpoint for instance 2.

Think of MediaPipeline == Room. If you use 2 rooms, then you need 2 Pipelines.

**Comment by j1elo** [comment]
Closing for lack of feedback. Possibly not a bug, just an application error.
