### ISSUE TITLE
Lacking important page in docs

### ISSUE THREAD

**Issue by gustawdaniel** [Kurento/bugtracker#503]
I am on page:

https://doc-kurento.readthedocs.io/en/stable/tutorials/java/tutorial-recorder.html

I can see

This tutorial has been configured to use https. Follow the `instructions` to secure your application.

I can click on `instructions` link.

I am redirected to

https://doc-kurento.readthedocs.io/features/security.html#configure-java-applications-to-use-https

I see

```

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```

I should see instructions about https, no 404 page.

**Comment by gustawdaniel** [comment]
Probably this is correct link:

https://doc-kurento.readthedocs.io/en/stable/features/security.html#features-security-java-https

but I am not sure.

**Comment by j1elo** [comment]
Thanks for reporting!

**Comment by j1elo** [comment]
Fixed links will be available in the nightly builds of the docs, here:

https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-recorder.html
