### ISSUE TITLE
find a bug in kms-plugin-sample

### ISSUE THREAD

**Issue by anti-destiny** [Kurento/bugtracker#506]
## Issue description
When I run the sample of gstreamer plugin, a segment fault occured. I found a few modification of the code can fix this problem.
```
  if (filter_type == KMS_SAMPLE_FILTER_TYPE_EDGES) {
    GST_DEBUG ( "Calculating edges");
    
    // +++ here!!! before invoke canny function, convert the frame into grayscale image first.
    cv::Mat gray;  
    cvtColor((*sample_filter->priv->cv_image), gray, COLOR_BGR2GRAY);

    Canny (gray, output_image,
            edge_threshold, 255);
  } else if (filter_type == KMS_SAMPLE_FILTER_TYPE_GREY) {
    GST_DEBUG ( "Calculating black&white image");
    cvtColor ( (*sample_filter->priv->cv_image), output_image, COLOR_BGR2GRAY );
  }
```
As you can see in the code, I convert the input frame into gray before feed it into the Canny algorithm, and it removes the error. 
However, I'm not sure I handled this problem in a right way. Whatever, I hope this will help you to improve kurento.

**Comment by j1elo** [comment]
Hi, could you please make a Pull Request? I'll gladly merge it, thanks!

**Comment by anti-destiny** [comment]
I made a pull request at [here](https://github.com/Kurento/kms-plugin-sample/pull/1). Please check it.
