### ISSUE TITLE
Recording file got corrupted when socket disconnects

### ISSUE THREAD

**Issue by ershubhamgupta1** [Kurento/bugtracker#514]
## Prerequisites

* [] I have read the SUPPORT document
  

* [] I have checked the Troubleshooting Guide
  

* [] I have tested with the latest version of Kurento
  

### INFO about Kurento Media Server

* Kurento version:  
* Server OS:        
* Installation method:
    
  - [] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:                 
* Kurento Client version:   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment]
Invalid issue report: no information provided.
MP4 is a BAD format for recording and we probably will remove it in the future. Best is WEBM, it is robust against crashes and socket disconnections.
