### ISSUE TITLE
AWS Cloud Formation template - where to set VPC details

### ISSUE THREAD

**Issue by grimace** [Kurento/bugtracker#517]
I have failed many times to set up Kurento Media Server using the AWS Cloud Formation Template.  I have VPC, but it's not clear to me where I set the VPC in the template wizard process.  Is there a way to clarify that?

**Comment by j1elo** [comment]
The Kurento CF template is written to deploy **on the default VPC** (see the [Amazon Virtual Private Cloud](https://docs.aws.amazon.com/vpc/) docs). There is no VPC selector defined in this template, so you won't see a choice for it during the AWS CF wizard. If you need more flexibility than what this template offers, you have two options:

   A. Manually create an EC2 instance, assigning all the resources as needed, and then using the other installation methods to set Kurento Media Server up on it: [Docker image](https://doc-kurento.readthedocs.io/en/latest/user/installation.html#docker-image), [Local Installation](https://doc-kurento.readthedocs.io/en/latest/user/installation.html#local-installation).

   B. Download the current CF (https://s3-eu-west-1.amazonaws.com/aws.kurento.org/KMS-Coturn-cfn-6.14.0.yaml), and edit it to create your own custom version with everything you need from it.
