### ISSUE TITLE
Control plane authentication

### ISSUE THREAD

**Issue by makkarpov** [Kurento/bugtracker#518]
Technically, this is not a bug, but rather a feature request. But seeing that there are other issues labeled 'enhancement', I suppose that it's still right place to write about it.

## Issue description

The problem is that it looks like there is no way to authenticate websocket control connections, apart from firewall and reverse proxy-based ones. At least I found none in configs and docs. Even with reverse proxy ways (e.g. I can configure nginx to check auth) there is a problem that Kurento always binds to 0.0.0.0, and it seems that there is no corresponding config option to make it bind to localhost. So anyone can connect to server instance and use it for their own needs, consuming server resources.

I see configuration option for websocket path, so it can be used assuming Kurento will reject incorrect paths. But I think that usage of this option is rather a dirty hack than authentication solution (e.g. passing tokens as URLs is generally bad idea and I don't think that it was originally intended as authentication feature).

## Proposed solution

Something as simple as shared secret or mutual TLS (client certs) would be sufficient and should be rather easy to implement.

**Comment by j1elo** [comment]
Relevant docs: https://doc-kurento.readthedocs.io/en/latest/features/security.html#signaling-plane-authorization

However it's correct that Kurento should provide a way to specify a binding address other than `0.0.0.0` ("any").

**Comment by makkarpov** [comment]
mTLS should be also useful and it should be already implemented by OpenSSL/other crypto lib, so it also should be as simple as adding bunch of config params.

**Comment by j1elo** [comment]
Could you please point to some documentation or tutorial resource that I can read to learn more about mTLS? I haven't implemented it in the past so it's a bit of an unknown area for me

**Comment by makkarpov** [comment]
Since you are using Boost ASIO (and I haven't used it before :) I suppose that these API calls should be sufficient:

https://www.boost.org/doc/libs/1_58_0/doc/html/boost_asio/reference/ssl__context/set_verify_mode.html
https://www.boost.org/doc/libs/1_58_0/doc/html/boost_asio/reference/ssl__context/load_verify_file.html

I used [this](https://stackoverflow.com/a/25347389/1848172) StackOverflow answer as a reference. First function will enforce verification (so, first config param on whether that verification is needed) and second function will specify trusted certification authorities (second config param with path to file)
