### ISSUE TITLE
Recorder uses MP3 instead of AAC for MP4 format

### ISSUE THREAD

**Issue by j1elo** [Kurento/bugtracker#519]
## Prerequisites

* [x] I have read the SUPPORT document
  

* [x] I have checked the Troubleshooting Guide
  

* [x] I have tested with the latest version of Kurento
  

## Issue description

RecorderEndpoint will use MP3 ([here](https://github.com/Kurento/kms-core/blob/1c21e0b1e0dd95c4e5220c2ad6019dba5da1a912/src/gst-plugins/commons/kmsrecordingprofile.c#L103)) instead of AAC, when the selected format is MP4.

The most commonly accepted audio codec for MP4 containers is AAC, so the choice of encoding audio to MP3 seems a bit weird, and it causes incompatibility issues. To be specific, Safari (and apparently also IE) will only decode AAC audio from MP4 files.

Related:
* Pull Request [Kurento/kms-core#11](https://github.com/Kurento/kms-core/pull/11) (*changed mp4 audio codec to mpegversion 4*), which changes the audio encoder from MP3 to AAC for the MP4 format.
* Forum: [RecorderEndpoint: Can we record MP4 video with AAC audio codec?](https://groups.google.com/d/topic/kurento/iCaNUnPFZ7c/discussion) where the former authors of Kurento state that they prefer leaving the encoder to MP3, because of CPU usage concerns.
* [This comment](https://github.com/Kurento/bugtracker/issues/225#issuecomment-369030434) on another issue, which describes the situation.

## Context

The files that get written by RecorderEndpoint can later be played back directly by browsers. This is very helpful because these files can be, for example, stored in an HTTP server, thus providing a direct URL would make the browser to play it. However this won't work with Safari if the audio codec is MP3.

## How to reproduce?

1. Use RecorderEndpoint with the MP4 format, recording both audio and video.
2. Cleanly end the recording.
3. Drag the resulting file onto a Chrome browser window. See how it plays both video and audio back.
4. Drag the resulting file onto a Safari browser window. See how it plays the video back, but there is no audio.

## (Optional) Possible solution

Accept Pull Request [Kurento/kms-core#11](https://github.com/Kurento/kms-core/pull/11) (*changed mp4 audio codec to mpegversion 4*)

### INFO about Kurento Media Server

* Kurento version: all (tested with 6.14.0)
* Server OS:        

### INFO about end-user clients

* Device(s): Macbook
* OS(es): MacOS 10.13.6
* Browser(s): Safari 13.1

**Comment by j1elo** [comment]
My only concern regarding this is that changing the RecorderEndpoint from storing MP3 to AAC might be considered a breaking change, so we probably should schedule this change for Kurento 7.0.

On the other hand we could consider this behavior a bug, thus it could be shipped as a bugfix release.

It all depends on whether this change might break already existing applications out there, which might have been written to expect MP3 audio, and thus might suddenly break after updating KMS and starting to get unexpected AAC audio.

**Comment by j1elo** [comment]
A good workaround for this issue: post-process the recordings to change the audio codec to AAC.

Run this command:

```
$ ffmpeg -i Recording.mp4 -c:v copy -c:a aac Recording_AAC.mp4
```

**Comment by Napoleon-Black** [comment]
It will be nice to have some options to select the audio format for the MP4 container. Because for now, we should compile our own versions of KMS to change the audio format.

**Comment by j1elo** [comment]
Closed by merging https://github.com/Kurento/kms-core/pull/11 into the branch for Kurento 7.0
