### ISSUE TITLE
Documentation about externalAddress

### ISSUE THREAD

**Issue by lonesomewalker** [Kurento/bugtracker#522]
## Prerequisites

* [X] I have read the SUPPORT document

* [X] I have checked the Troubleshooting Guide

* [X] I have tested with the latest version of Kurento

## Issue description
Documentation says:
WebRTC: Add externalAddress to WebRtcEndpoint config & client API.

Allows to specify an external IP address, so Kurento doesn’t need to auto-discover it during WebRTC initialization. This saves time, and also removes the need for configuring external STUN or TURN servers.

## Context
Does this mean: ONE ip address or more?
Can it be one IPv4 and one IPv6?
Can it be several ip addresses? 

## (Optional) Possible solution
this description is a bit vague :-)

**Comment by prlanzarin** [comment]
@lonesomewalker  Chiming in:

> Does this mean: ONE ip address or more?
Can it be one IPv4 and one IPv6?
Can it be several ip addresses?

It's just one right now. Doesn't support dual stacking, so it's IPv4 only or IPv6 only.
Same goes for the networkInterfaces configuration: due to how libnice currently works, `networkInterfaces` will only get IPv4 addresses from the selected interface.

**Comment by lonesomewalker** [comment]
Well this is a big issue then, since we live in 2020 where IPv6-only internet access exists :-|
Also this leads to several issues with dual-stack implementations -> timeout :-(

**Comment by prlanzarin** [comment]
Recommended approach for dual stack scenarios is setting neither of them. Leave it up to Kurento to do a full gathering. If your server is behind NAT, configure a STUN server on it.

If you want to mildly speed up the connection establishment while doing a full gathering, you might just filter out server-side candidates that you know are useless after they got out of Kurento.

I've been meaning to look at the networkInterfaces and make it dual stack for a long time now and contribute it back to KMS, but just haven't got the time for it yet.

**Comment by lonesomewalker** [comment]
@prlanzarin we already had mail contact.
Still waiting for response (maybe in spam folder...) :P

**Comment by j1elo** [comment]
This was done to scratch an itch in OpenVidu, so it's normal that not all and every situation was covered. The code was released in case anyone might also benefit, and I also wrote public docs, but other than that, our stance is "use it only if it happens to fit your needs and you know what you're doing".

PRs are always welcome, though!

**Comment by lonesomewalker** [comment]
Well, actually we need somebody who is willing to get this running dual-stack (IPv4 AND IPv6)
Paid.  :-)

**Comment by prlanzarin** [comment]
@j1elo @lonesomewalker I'm taking a look into this (and also the networkInterfaces option) for BigBlueButton's build of KMS. Once I'm confident it's stable enough, I'll open a PR for upstream KMS.
