### ISSUE TITLE
Issue in RTP receiver tutorial    the port of   KMS listens for Video RTP is change

### ISSUE THREAD

**Issue by honggesmile** [Kurento/bugtracker#523]
Prerequisites
[V] I have read the SUPPORT document, kurento blogs and mailing groups
[V] I have checked the Troubleshooting Guide

KMS Version:

6.13.0

Ubuntu Version

Ubuntu 16.04.2 LTS

exmaple: rtp receiver :https://doc-kurento.readthedocs.io/en/stable/tutorials/java/tutorial-rtp-receiver.html
Every time the application is restarted, the audio and video ports monitored by kms will change.
for example ,KMS connection info shows as :
**SDP negotiation finished
* KMS listens for Audio RTP at port: 51566
* KMS listens for Video RTP at port: 53104
* KMS expects Audio SSRC from sender: 445566
* KMS expects Video SSRC from sender: 112233
* KMS local IP address: 172.16.0.11
* KMS will discover remote IP and port to send RTCP**

When i click stop　then chick start,KMS connection info shows as :
**SDP negotiation finished
* KMS listens for Audio RTP at port: 61400
* KMS listens for Video RTP at port: 52894
* KMS expects Audio SSRC from sender: 445566
* KMS expects Video SSRC from sender: 112233
* KMS local IP address: 172.16.0.11
* KMS will discover remote IP and port to send RTCP**

When sending rtp stream with ffmpeg, you need to specify the port. 
`ffmpeg -re -i /dev/video0 -c:v libx264 -tune zerolatency -payload_type 103 -r 20 -an -f rtp rtp://106.53.95.37:56408 > test.sdp`
Can the port monitored by kms be fixed? I have tried to modify the 　
`#min-port=49152 
#max-port=65535`
in the configuration file /etc/turnserver.conf
But it doesn't work (the program cannot run after modification), what should I do, thank you

**Comment by j1elo** [comment]
The port varies for each execution by design. This is how it must work for WebRTC, and the RTP implementation of Kurento is derived from its WebRTC module.

You can reduce the range of ports by changing `minPort` and `maxPort` in the file `/etc/kurento/.../BaseRtpEndpoint.conf.ini`
