### ISSUE TITLE
Failure to build if `kurento-media-server-dev` package unavailable

### ISSUE THREAD

**Issue by dcmartin** [Kurento/bugtracker#524]
## Prerequisites

* [X] I have read the SUPPORT document
  

* [X] I have checked the Troubleshooting Guide
  

* [X] I have tested with the latest version of Kurento
  

## Issue description

The build from source instructions require the installation of `kurento-media-server-dev` package using `apt`; however, this package is not available on non-AMD64 platforms.  I am unable to utilize the build script provided due to a lack of CMAKE modules required, notably "KurentosHelpers" although that repository appears to be part of the OmniBuild configuration.

## Context

Attempting to build KMS for AARCH64 platform (and ARMV7)

## How to reproduce?

To reproduce follow the build from source instructions on AARCH64 or ARMV7 Ubuntu 18 environment.

### INFO about Kurento Media Server

* Kurento version:  master branch of kms-omni-build
* Server OS:       Ubuntu 18.04
* Installation method:
    
  - [] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [X] Built from sources
    

### INFO about your Application Server

* Language:                 
* Kurento Client version:   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
-- CMake project: kms-jsonrpc
If KurentoHelpers is not found, you need to install 'kms-cmake-utils' from the Kurento repository
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "FindKurentoHelpers.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KurentoHelpers", but CMake did not find one.

  Could not find a package configuration file provided by "KurentoHelpers"
  with any of the following names:

    KurentoHelpersConfig.cmake
    kurentohelpers-config.cmake

  Add the installation prefix of "KurentoHelpers" to CMAKE_PREFIX_PATH or set
  "KurentoHelpers_DIR" to a directory containing one of the above files.  If
  "KurentoHelpers" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/dcmartin/GIT/kms-omni-build/kms-jsonrpc/CMakeFiles/CMakeOutput.log".

```

**Comment by j1elo** [comment]
This is the complete list of repositories that must be built top build Kurento Media Server:

https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#code-repositories

All of these are built, one by one, by our CI servers, which then are all organized under the `kurento-media-server-dev` but that's purely for convenience.

**Comment by j1elo** [comment]
There have been several issues and forum posts about building for the Raspberry Pi (ARM), so I'm collecting all together in here: https://github.com/orgs/Kurento/projects/7

**Comment by j1elo** [comment]
Since then, docs have been more careful with the use case of bootstraping a Kurento dev environment from scratch. I'm closing this as it's not an actual bug.
