### ISSUE TITLE
kurento-rtsp2webrtc second browser receives only inter-frame differences

### ISSUE THREAD

**Issue by wojtkowiak** [Kurento/bugtracker#54]
Hello,

firstly thanks for a great open source project!

I am not sure is that an issue or maybe I am not using your api the right way.

I have a rtsp stream from a camera. The camera is a dome type, but most of the time it does not move. The background is still as it films an empty (no persons in it) room. If I will open the example on one computer everything is fine. But when two or more clients are viewing the webrtc stream, it seems that it only cares about sending keyframes to the first one, while the other ones are receiving only the inter-frame differences.
I have recorded the issue so you can see what am I talking about. Is there a way of forcing the keyframe to be send at a certain interval, or at least at the webrtc call start (the moment when another client connects to the stream through webrtc).
Or maybe this is not intended to be used this way?

https://www.youtube.com/watch?v=XTLehkOSGL4

On the recorded movie you can see the camera stream in VLC and Chrome with the rtsp2webrtc example (I have just added another frontend and buttons to steer the camera). I have another browser opened on an another computer and it was connected as the first client. You can see that from the start it only receives the frame differences. Later even it has received the keyframe it has troubles with detecting when a new keyframe should be send because when I move the camera the interval at which the keyframe is sent is very low (this can be seen in the second part of the movie). 

Any hints on that? When it comes to server settings I just installed kurento thorught apt-get on ubuntu 14.04. Do you need additional info?

**Comment by dfernandezlop** [comment]
Hi,

Your problem doesn't seems to be a Kurento related problem. Although there are hundreds of viewers, Kurento only reads one time the stream for your camera  (probably if you disconnect the vlc, you won't have problems with the video). There is no way to request a keyframe from the Kurento API.

Maybe the problem could be related with your camera or with your bandwidth. Have you tried to connect two differents clients to the camera? For example, vlc and gstreamer.

Regards.
David.

**Comment by dfernandezlop** [comment]
Any update?

**Comment by wojtkowiak** [comment]
Hey,
thanks for your time.

I have tried vlc and ffplay at the same time and there seems to be no such issue.

https://www.youtube.com/watch?v=Iofl9yr5IMk
Here I am starting just w ffplay. Then I am staring kurento and connecting two clients. After that I add vlc. In this test the keyframe was updated a little bit sooner than the last time. On ffplay and vlc there is no issue.

https://www.youtube.com/watch?v=9uT8fw0v7xw
In the second test I have left two clients connected for 5 minutes to check if they will finally receive the keyframe if I will not move the camera. They did not. I added vlc at that moment to check, but it received the proper video. 
I have also restarted one of the client which you can see in this video and I was expecting to get the same video as is still present on the second client, but you can see that it only got the diffs. So to my reasoning if kurento itself would receive a broken video from the camera then at least whenever I join new clients they should receive the video as it is seen on other clients, right?

Is there anything with the API or configuration I could play with to try to improve the situation?

**Comment by dfernandezlop** [comment]
Hi,

There is a main difference between using vlc and Kurento. Kurento is transcoding the flow from h264 to vp8. Probably KMS is loosing a keyframe and it doesn't received anymore so it is not able to transcode in the correct way.

I have never seen this error with other IP cams. Maybe you can configure your cam to emit keyframes each n seconds.

Regards.

**Comment by wojtkowiak** [comment]
Hey,

I am closing this. Indeed with other cameras I did not have any problems :smile:
Thanks for your time and awesome project!
