### ISSUE TITLE
RTMP contribution for RecorderEndpoint

### ISSUE THREAD

**Issue by j1elo** [Kurento/bugtracker#541]
## Prerequisites

* [x] I agree to fill this issue template.
* [x] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

An interesting contribution was made in the Kurento forums, to add RTMP support for the RecorderEndpoint. It allows the Endpoint to record FLV format, which then can be read on the fly by an RTMP server:

https://groups.google.com/d/msg/kurento/_1jO6ugsAO4/Yen1ug25AwAJ

This issue is just a replacement for a proper Pull Request in kms-core and kms-elements.

Work related to this contribution:

* [ ] Review the code of the patches to verify it does as expected and has overall acceptable code quality.
* [ ] Merge with master and resolve conflicts.
* [ ] Test the functionality and verify that it does work as intended.
* [ ] Write unit tests that complement the already existing recording formats.
* [ ] Write documentation together with the already existing recording formats.

Patch files from the forum are attached also to this issue:
[patch-rtmp.zip](https://github.com/Kurento/bugtracker/files/5440286/patch-rtmp.zip)

**Comment by alex1712** [comment]
This are the PR's resulting from that conversation:
https://github.com/Kurento/kms-core/pull/24
https://github.com/Kurento/kms-elements/pull/30

**Comment by neilyoung** [comment]
Confirming PRs to work (if that matters) :)

**Comment by neilyoung** [comment]
Thanks!
