### ISSUE TITLE
Kurento crash when I replace libgstreamer-1.5.so.0.801.0 library

### ISSUE THREAD

**Issue by sshsun1990** [Kurento/bugtracker#543]
## Prerequisites

* [] I agree to fill this issue template.
* [] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

I building gstreamer from git source [**https://github.com/Kurento/gstreamer.git** (master branch)], then replace the library **/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0.801.0**. **But I found kurento-media-server (version 6.11.0 / 6.12.0) crash**.

errors.log
(kurento-media-server:16484): GStreamer-CRITICAL **: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed

### INFO about Kurento Media Server

* Kurento version:  6.11.0
* Server OS:  Ubuntu 16.04 (Xenial)
* Installation method:
  - [] [Built from sources]

[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### INFO about your Application Server

* Programming Language:  kurento-java client
* Kurento Client version:   6.11.0

### INFO about end-user clients

* Device(s):    Android

### Run these commands

export GST_DEBUG="3,Kurento*:5,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4,agnosticbin:4,gst*:4,kmsremb:3"
nohup kurento-media-server/server/kurento-media-server \
    --modules-path=. \
    --modules-config-path=./config \
    --conf-file=./config/kurento.conf.json \
    --gst-plugin-path=. --logs-path=/var/log/kms_dev --log-file-size=100 --number-log-files=10 2>&1 1>/dev/null &

**Comment by j1elo** [comment]
what are you trying to achieve?

**Comment by sshsun1990** [comment]
I want to add some debug info log. But, I only building from git source and replace, kurento-media-server crash.

**Comment by j1elo** [comment]
You should probably run with GDB and see where it crashes.

But a better method to replace the GStreamer library is to [build your own DEB package](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#create-deb-packages) and install it over the one from Kurento.

For example the easiest is with the Docker image:

```
docker run --rm \
    --mount type=bind,src="$PWD",dst=/hostdir \
    kurento/kurento-buildpackage:xenial \
        --install-kurento 6.11.0 \
        --apt-add-repo
```

then

```
sudo dpkg -i libgstreamer1.5-0_*.deb
```

**Comment by sshsun1990** [comment]
Ok, thanks. I will retry do it.

**Comment by sshsun1990** [comment]
Hello, How can I build my own DEB package for gstreamer? I can not find description and document in Kurento and Gstreamer offical website.

**Comment by j1elo** [comment]
My previous comment contained a link. Click on it.

**Comment by j1elo** [comment]
But instead of the example kms-core, use any of the several Gstreamer repos we have, for exaple https://github.com/Kurento/gstreamer

**Comment by j1elo** [comment]
Closing this because I don't see any bug in Kurento
