### ISSUE TITLE
Dispatcher(one to many)

### ISSUE THREAD

**Issue by huseyindoru** [Kurento/bugtracker#556]
## Prerequisites

* [X] I agree to fill this issue template.
* [X] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description
When I use dispatcher(one to many) there is a delay in audio and video data.
This does not happen when I connect end-to-end webrtc endpoints.

## Context

We aim to connect with more users in the media server.

## Expected & current behavior

judder and video drop frame should be reduced

### INFO about Kurento Media Server

* Kurento version:  6.14
* Server OS:          Ubuntu 16.04 (Xenial),
* Installation method:
    
  - [x] [apt-get]
  - [] [Docker]
  - [] [AWS CloudFormation]
  - [] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### INFO about your Application Server

* Programming Language:   browser JavaScript
* Kurento Client version:     6.14.0

### INFO about end-user clients

* Device(s):    Android
* OS(es):        etc.
* Browser(s):   Chrome 80

### Run these commands

```
cat /etc/lsb-release
```

```
kurento-media-server --version
```

```
dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment]
Yes, the Dispatcher has some unbalanced overhead. Can you replace the Dispatches with Passthrough? I believe the Passthrough is equally valid for a scenario of 1-to-many.

**Comment by huseyindoru** [comment]
> Yes, the Dispatcher has some unbalanced overhead. Can you replace the Dispatches with Passthrough? I believe the Passthrough is equally valid for a scenario of 1-to-many.

webrtc endpoints also support 1 to more connections. but CPU usage is very high so we used dispatcher. How to use passthrough cpu? webrtc 12-core pc in 13-person room uses 33% cpu. dispatcher is using 17% in the same room

**Comment by huseyindoru** [comment]
> Yes, the Dispatcher has some unbalanced overhead. Can you replace the Dispatches with Passthrough? I believe the Passthrough is equally valid for a scenario of 1-to-many.

Thanks for your reply.
We noticed that the CPU usage is high in one to many connections of webrtc endpoints. that's why we used dispatcher. How to use pass cpu? Webrtc 12-core computer in a 13-person room uses 33% cpu. dispatcher uses 17% in the same room

**Comment by micaelgallego** [comment]
Hello @huseyindoru, can you elaborate a bit more your comment? 

Dispatcher allow you to select which input is connected to the Dispatcher output. An example of this behavior can be seen in the test: https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/test/functional/dispatcher/DispatcherWebRtcTest.java

Similar behavior can be obtained if you connect an input WebRtcEndpoint A to an output WebRtcEndpoint B. If you connect a new input WebRtcEndpoint C to the WebRtcEndpoint B, then B will sent to user the C media. 

Have you make performance testing comparing these two scenarios (with the same behavior) and you found more CPU load in the pure WebRtcEndpoints than using a Dispatcher?

Can you describe exactly what test you have done and the obtained results?

Regards

**Comment by huseyindoru** [comment]
> Merhaba @huseyindoru , yorumunuzu biraz daha detaylandırır mısınız?
> 
> Dağıtıcı, Dağıtıcı çıkışına hangi girişin bağlanacağını seçmenize izin verir. Bu davranışın bir örneği testte görülebilir: [https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/ test / function / dispatcher / DispatcherWebRtcTest.java](https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/test/functional/dispatcher/DispatcherWebRtcTest.java)
> 
> Bir WebRtcEndpoint A girişini bir WebRtcEndpoint B çıkışına bağlarsanız benzer davranış elde edilebilir. WebRtcEndpoint B'ye yeni bir WebRtcEndpoint C girişi bağlarsanız, B, kullanıcıya C ortamını gönderir.
> 
> Bu iki senaryoyu karşılaştırarak performans testi yaptınız mı (aynı davranışla) ve saf WebRtcEndpoints'te Dağıtıcı kullanmaktan daha fazla CPU yükü buldunuz mu?
> 
> Yaptığınız testi ve elde ettiğiniz sonuçları tam olarak açıklayabilir misiniz?
> 
> Saygılarımızla

hello @micaelgallego 
We tested two scenarios as follows
There are 13 different users in a room.

**scenario 1** 
the user sends a stream over a WebRtc and receives a stream over 12 different WebRtc Endpoints.The links here are directly via WebRtc End.
To explain, there are users A B C D E F G H I J K L M in the room
User A sends streams with A0 WebRtcEnd, 
 AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL, AM WebRtcEnd recevier streams
B0.conenct(Ab)
C0.connect(Ac).
33% CPU utilization in this scenario

**scenario 2**
Each user in the room creates a dispenser (one to many). and transfers stream from there
in this case the CPU usage is 17% but there are stuttering in the sound and images.

Example Code (scenario 2)
  send my stream =>
 this.MyEndPoint.pipeline.create("DispatcherOneToMany", (error, dispatcher) => {
	if (!error) {
		this.MyEndPoint.dispatcher = dispatcher;
		this.MyEndPoint.dispatcher.createHubPort((error, _hubPort) => {
			if (!error) {
				this.MyEndPoint.dispatcherhubPort = _hubPort;
				this.MyEndPoint.mediaServerWebRtc.connect(this.MyEndPoint.dispatcherhubPort);
				this.MyEndPoint.dispatcher.setSource(this.MyEndPoint.dispatcherhubPort);
				this.MyEndPoint.IsConnect = true;
			}
		});
	}});

	to receive streams (each user has a different Target Dispatcher)=> 
	TargetDispatcher.createHubPort((error, _hubPort) => {
						if (!error) {
							Target.hubPort = _hubPort;
							Target.hubPort.connect(Target.mediaServerWebRtc);
							}
                        }

**Comment by huseyindoru** [comment]
We stopped using the dispatcher(one to many). It creates delays in sound and video. And it doesn't exhibit stable CPU usage.
