### ISSUE TITLE
Transcode

### ISSUE THREAD

**Issue by huseyindoru** [Kurento/bugtracker#557]
## Prerequisites

* [x] I agree to fill this issue template.
* [x] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

Hello, I am making a one-to-one connection with webrtc endpoint via kurento media server.
However, as the number of connections increases, the use of cpu increases.

media server is configured to use only h264. cpu usage is increasing despite
Does kurento media server transcode (decode - encode) while sending h264 end point h264 end point video?  If it is, how can I close it?

This is how I configure my media server

SdpEndpoint.conf.json
"videoCodecs" : [
    {
      "name" : "H264/90000"
    }
]

## Context

Creating sfu based virtual rooms

### INFO about Kurento Media Server

* Kurento version:  6.14.0
* Server OS:           Ubuntu 16.04 (Xenial
* Installation method:
    
  - [x] [apt-get]
  - [] [Docker]
  - [] [AWS CloudFormation]
  - [] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### INFO about your Application Server

* Programming Language:   browser JavaScript
* Kurento Client version:      6.14.0

### INFO about end-user clients

* Device(s):    
* OS(es):        Windows 10
* Browser(s):  Chrome 80

### Run these commands

```
cat /etc/lsb-release
```

```
kurento-media-server --version
```

```
dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment]
No bug description provided. Probably a configuration or application issue.
