### ISSUE TITLE
might be a successful build on raspberry pi arm v7 64bit 

### ISSUE THREAD

**Issue by chetanbnaik** [Kurento/bugtracker#56]
Dear All,

This post wants to talk about 3 things:
--> the build procedure that I followed.
--> possible error in kms-elements build on ARM architecture?
--> python binding like any other plugin of gstreamer?

I have somehow managed to build the kms-elements on my raspberry pi 2 model b. It took lots of efforts and stackoverflow, to compile it successfully. I am yet to try out the installation.

But at the end of building the kms-elements, when I try to do "gst-inspect-1.5 webrtcednpoint", I get the following error:
```
(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gst-inspect-1.5:27954): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gst-inspect-1.5:27954): GStreamer-CRITICAL **: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed
```
and then the usual information is displayed.

These errors are not shown for any of the other kms-elements. For eg. gst-inspect-1.5 httpendpoint works nicely.

My original aim was to have build kms from source, and also have the python bindings for the kms-elements
The step-by-step procedure used here is:

First, lets install all the needed dependencies.

`sudo apt-get install git build-essential cmake pkg-config automake autoconf flex bison python-pip python-dev libffi-dev libboost-all-dev libssl-dev libtool gettext libfam-dev maven gobject-introspection python-cairo-dev gnome-common`

Installation of GLib 2.46, needed for "libnice"
```
→ wget http://ftp.gnome.org/pub/gnome/sources/glib/2.46/glib-2.46.2.tar.xz

tar xvf glib-2.46.2.tar.xz

cd glib-2.46.2

./autogen.sh

./configure

make

sudo make install
```

Installation of pygobject
```
sudo apt-get install libgirepository1.0-dev libcairo2-dev
→ wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.18/pygobject-3.18.2.tar.xz
tar xvf pygobject-3.18.2.tar.xz
./autogen.sh --prefix=/usr/local --with-python=python
make
make install
```

KMS-cmake-utils

```
git clone https://github.com/Kurento/kms-cmake-utils

cd kms-cmake-utils

mkdir build

cd build

cmake ..

sudo make install
```

------------------------------------

git clone https://github.com/Kurento/kurento-module-creator
```
cd kurento-module-creator

git checkout v3.0.10


sudo apt-get install maven

mvn package

sudo cp ./target/kurento-module-creator-3.0.10.jar ./target/kurento-module-creator-jar-with-dependencies.jar /usr/local/bin

sudo cp ./target/classes/FindKurentoModuleCreator.cmake /usr/local/share/cmake-3.0/Modules/

vi ./scripts/kurento-module-creator → change

sudo cp ./scripts/kurento-module-creator /usr/local/bin

```

------------------------------------
```
git clone https://github.com/Kurento/jsoncpp

cd jsoncpp

mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -G "Unix Makefiles" ../..

sudo make install
```

------------------------------------
```
git clone https://github.com/Kurento/kms-jsonrpc

cd kms-jsonrpc

mkdir build

cd build

cmake -DCMAKE_MODULE_PATH=/usr/local/share/cmake-3.0/Modules/ ..

sudo make install
```

------------------------------------
```
git clone https://github.com/Kurento/gstreamer.git

cd gstreamer

./autogen.sh

./configure

make

sudo make install
```

------------------------------------
```
sudo apt-get install libasound2-dev libvorbis-dev libvisual-0.4-dev libogg-dev libtheora-dev libpango1.0-dev libvpx-dev

git clone https://github.com/Kurento/gst-plugins-base.git

cd gst-plugins-base

./autogen.sh

./configure

make

sudo make install
```

Now, the actual KMS-CORE

------------------------------------
```
sudo apt-get install libsigc++-2.0-dev libglibmm-2.4-dev uuid-dev

git clone https://github.com/Kurento/kms-core

cd kms-core

mkdir build

cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_PATH=/usr/local/share/cmake-3.0/Modules ..
```

but this is where a warning is thrown and I have to modify line 99 in
```
vi ../src/gst-plugins/kmsaudiomixer.c

  GST_LOG_OBJECT (pad, "Modifing latency query. New latency %lld",

   100       LATENCY * GST_MSECOND);
```

the warning is something like: "error: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘long long int’ "

the compilation fails again due to a similar warning, and I have to modify line 104.

vi ../src/server/implementation/MediaSet.cpp
```
104     GST_INFO ("Destroying %d pipelines that are already alive", pipes.size() );
```

after this, the compilation is successful.

sudo make install

------------------------------------
```
git clone https://github.com/sctplab/usrsctp

cd usrsctp

./bootstrap

./configure

make

sudo make install
```

------------------------------------
```
git clone https://github.com/Kurento/openwebrtc-gst-plugins

cd openwebrtc-gst-plugins

mkdir build

./autogen

./configure

make

sudo make install
```

------------------------------------
```
sudo apt-get install libgupnp-1.0-dev gir1.2-gupnp-1.0 libgupnp-igd-1.0-dev gir1.2-gupnpigd-1.0


git clone https://github.com/Kurento/libnice

sudo apt-get install gtk-doc-tools

cd libnice

vi configure.ac → change the [ LIBNICE_RELEASE=”yes” ]

./autogen.sh

./configure

make

sudo make install
```

------------------------------------
```
git clone https://github.com/Kurento/kms-elements

cd kms-elements

/src/gst-plugins/kmscompositemixer.c:299:3: error: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘long long int’ [-Werror=format=]

 GST_LOG_OBJECT (pad, "Modifing latency query. New latency %ld",

mkdir build

cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_PATH=/usr/local/share/cmake-3.0/Modules ..

sudo make install
```

------------------------------------
```
→ Install gst-python from https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.7.1.tar.xz

vi configure “ Change am__api_version = 1.14 and GST_

./configure --prefix=/usr/local --with-pygi-overrides-dir=/usr/local/lib/python2.7/site-packages/gi/overrides

make

make install
```

After this, I was expecting to have a successful build, but gst-inspect-1.5 on webrtcendpoint throws few wanrings and errors. Should this be expected? I can find this out only when I try it using it in an application. Has anybody else experience similar problems?

**Comment by chetanbnaik** [comment]
Hello All,

I would like to announce that the above method is correct, if one wants to build kurento kms-elements on Raspberry Pi. 

The gst-inspect-1.5 was throwing the error because the gstreamer cache was not updated.

My next step is to use kms-elements, and make RPi work as a standalone webrtc native client able to communication with any other browser or native client

**Comment by igracia** [comment]
Cool! Thanks for the feedback, and for the effort on doing that. Please do post your progress, as it will help other user compile KMS in different environments.

**Comment by gianpi90** [comment]
How do you resolve the issue?
I follow this guide, but the errors still remain.
When I delete cache I have also the error:

`** (gst-plugin-scanner:6304): CRITICAL **: can't find gi.repository.Gst`

I have installed gir1.2-gst but this doesn't fix the issue.
I have installed the server also, and it fails due to this error.

**Comment by chetanbnaik** [comment]
which glib version you have in LD_LIBRARY_PATH while compiling libnice? 
I started the installation on a fresh sd card, as there can be conflicts with raspbian versions of various dependencies.

**Comment by gianpi90** [comment]
ok I resolved these errors installing gst-libav gst-plugins-good ugly bad and their dependencies, but I have a wrong behaviour of the server, I have to rebuild kms packages?

**Comment by chetanbnaik** [comment]
I would suggest don't install gstreamer plugins from the repository using apt-get. Build those available from Kurento repository.

**Comment by gianpi90** [comment]
I have compiled them from kurento source repository.

**Comment by f6qpQNBA3p** [comment]
Hello, how to start KMS after gst-python ?

**Comment by neilyoung** [comment]
I was seemingly able to compile the entire stuff on an RPI 3A+ and could even launch kurento-media-server, but then it fails, because `Error: Cannot create gstreamer element: webrtcendpoint``

Whole story here (in case somebody finds the bug):

https://gist.github.com/neilyoung/1f54a80f1c5183d1762fc2ece0bce532
