### ISSUE TITLE
Can't build from sources using Docker kurento-buildpackage

### ISSUE THREAD

**Issue by shubidubapp** [Kurento/bugtracker#560]
## Prerequisites

* [X] I agree to fill this issue template.
* [X] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description
Can not build and get a release for Ubuntu from `kms-elements` using docker image `kurento/kurento-buildpackage`.
I could get a build about one moth ago using `docker run --rm --mount type=bind,src="$PWD",dst=/hostdir kurento/kurento-buildpackage:bionic --install-kurento 6.13.0 --apt-add-repo --allow-dirty`. Now the build starts and a few minutes later I find it stuck. No matter how I run it I can't get a build. I have tried using it on different computers, running ubuntu, I have tried to use it with `kurento/kurento-buildpackage:xenial` instead of `kurento/kurento-buildpackage:bionic` which showed more progress (this time it got stuck at doing tests) I have tried to get a build from unedited `kms-elements` no changes.

```
cd /build/obj-x86_64-linux-gnu/tests/server && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_rtp_endpoint.dir/link.txt --verbose=1
/usr/bin/c++  -g -O2 -fdebug-prefix-map=/build=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++14 -Wall -pthread -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/obj-x86_64-linux-gnu=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-old-style-cast -Wno-error=date-time -DHAVE_CONFIG_H  -Wl,-Bsymbolic-functions -Wl,-z,relro -pie -rdynamic CMakeFiles/test_rtp_endpoint.dir/rtpEndpoint.cpp.o  -o test_rtp_endpoint -Wl,-rpath,/build/obj-x86_64-linux-gnu/src/server:/build/obj-x86_64-linux-gnu/src/gst-plugins/webrtcendpoint ../../src/server/libkmselementsimpl.so.6.13.0 -lkmscoreimpl -lkmsgstcommons -lgstreamer-1.5 -lgobject-2.0 -lglib-2.0 -lgstsdp-1.5 -lglib-2.0 -ljsonrpc -lkmsjsoncpp -lsigc-2.0 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0 -lboost_unit_test_framework -lboost_filesystem -lboost_system -lkmsgstcommons -lgstreamer-1.5 -lgobject-2.0 -lglib-2.0 -lgstsdp-1.5 -lglib-2.0 -ljsonrpc -lkmsjsoncpp -lsigc-2.0 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0 -lboost_unit_test_framework -lboost_filesystem -lboost_system ../../src/server/implementation/HttpServer/libkmshttpep.a -lsoup-2.4 -luuid ../../src/gst-plugins/webrtcendpoint/libkmswebrtcendpointlib.so.6.13.0 ../../src/gst-plugins/webrtcendpoint/libwebrtcdataproto.so.6.13.0 -lgstapp-1.5 -lgstsctp-1.5 -lgstbase-1.5 -lgstpbutils-1.5 -lnice -lgio-2.0 -lssl -lcrypto ../../src/server/libkmselementsinterface.a -lkmscoreimpl -lgstsdp-1.5 -ljsonrpc -lkmsjsoncpp -lboost_unit_test_framework -lboost_filesystem -lboost_system -lgstsdp-1.5 -ljsonrpc -lkmsjsoncpp -lboost_unit_test_framework -lboost_filesystem -lboost_system -lglibmm-2.4 -lsigc-2.0 -lkmsgstcommons -lgstreamer-1.5 -lgobject-2.0 -lglib-2.0 -lgstreamer-1.5 -lgobject-2.0 -lglib-2.0 
make[3]: Leaving directory '/build/obj-x86_64-linux-gnu'
make[2]: Entering directory '/build/obj-x86_64-linux-gnu'
[100%] Built target test_rtp_endpoint
make[2]: Leaving directory '/build/obj-x86_64-linux-gnu'
make -f tests/server/CMakeFiles/check_build.dir/build.make tests/server/CMakeFiles/check_build.dir/depend
make[3]: Entering directory '/build/obj-x86_64-linux-gnu'
cd /build/obj-x86_64-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /build /build/tests/server /build/obj-x86_64-linux-gnu /build/obj-x86_64-linux-gnu/tests/server /build/obj-x86_64-linux-gnu/tests/server/CMakeFiles/check_build.dir/DependInfo.cmake --color=
Scanning dependencies of target check_build
make[3]: Leaving directory '/build/obj-x86_64-linux-gnu'
make -f tests/server/CMakeFiles/check_build.dir/build.make tests/server/CMakeFiles/check_build.dir/build
make[3]: Nothing to be done for 'tests/server/CMakeFiles/check_build.dir/build'.
make[2]: Entering directory '/build/obj-x86_64-linux-gnu'
[100%] Built target check_build
make[2]: Leaving directory '/build/obj-x86_64-linux-gnu'
make[1]: Entering directory '/build/obj-x86_64-linux-gnu'
/usr/bin/cmake -E cmake_progress_start /build/obj-x86_64-linux-gnu/CMakeFiles 0
make[1]: Leaving directory '/build/obj-x86_64-linux-gnu'
   dh_auto_test -O--parallel
	cd obj-x86_64-linux-gnu && make -j4 -O test ARGS\+=-j4
```
I have waited like this for hours, no change, no error, nothing. Eventually I just had to kill the docker container...

## Context
I am trying to - and I actually did it - edit composite recorder to sort vertically before horizontally and since I am not using an Ubuntu while the VPS I am running kurento is an Ubuntu system I chose to build using docker. I could actually get a build before using the above code. 

## How to reproduce?
1. Clone the `kms-elements` repository. `git clone git@github.com:Kurento/kms-elements.git`
2. Checkout to `6.13.0`, `git checkout 6.13.0` (it actually doesn't matter if it is 6.13.0 or 6.15.0 you can instead try to use 6.15)
3. Run docker with `docker run --rm --mount type=bind,src="$PWD",dst=/hostdir kurento/kurento-buildpackage:bionic --install-kurento 6.13.0 --apt-add-repo --allow-dirty`
4. Wait a few minutes and you should see that it is stuck at
```
make[1]: Leaving directory '/build/obj-x86_64-linux-gnu'
   dh_auto_test -O--parallel
	cd obj-x86_64-linux-gnu && make -j4 -O test ARGS\+=-j4
```

## Expected & current behavior
I expect it to build consistently every time I try since we are using Docker and it is pretty much consistent through every machine. At least when I am using the official release code.

### INFO about Kurento Media Server

* Kurento version:  6.13.0 ( also tried with 6.15.0 didn't change the issue)
* OS:          Arch Linux
* Installation method:
    
  - [] [apt-get]
  - [] [Docker]
  - [] [AWS CloudFormation]
  - [X] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### Run these commands

Since I am not having a problem with my kurento machine most of the below commands are irrelevant. 
Instead:
*Docker version: 19.03.13-ce, build 4484c46d9d
*Docker Image: kurento/kurento-buildpackage:bionic

If any other necessary information is needed please ask.

**Comment by j1elo** [comment]
I see you're using Arch, where everything tends to be always in the latest versions; is it possible that a change in your system might cause some issues with the building process?

Easier way to test it would be to either boot from another partition where you have a different linux installed, or either try with a virtual machine and, e.g. an Ubuntu system.

I've established these test features and tested combinations of them:

* Clone HTTPS vs. SSH, just in case it might make any difference.
* Checkout master vs. 6.13.0.
* Build for xenial vs. bionic.

I haven't tested all combinations, but all I did test were successful and are these:

* HTTPS + master + xenial
* HTTPS + 6.13.0 + xenial
* SSH + master + xenial
* HTTPS + 6.13.0 + bionic
* SSH + 6.13.0 + bionic

Given that all these combinations worked fine, I'm inclined to think I won't be able to find issues if I tried the remaining ones.

My Docker says:

```
$ docker --version
Docker version 19.03.13, build 4484c46d9d
```

Could you try with a VM and see if the build works with a different system?

**Comment by j1elo** [comment]
Now that I see it:

```
make[1]: Leaving directory '/build/obj-x86_64-linux-gnu'
   dh_auto_test -O--parallel
	cd obj-x86_64-linux-gnu && make -j4 -O test ARGS\+=-j4
```

this might mean that a unit test is hanging indefinitely. It might be caused by the IPv6 configuration... could you please set your Docker daemon settings to enable IPv6 and see if the issue still happens?

```
~ $ cat /etc/docker/daemon.json 
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
```

**Comment by shubidubapp** [comment]
Yes this fixed the problem. I guess the ubuntu machine that we also tried to do this also didn't have IPv6 enabled. 

Well actually there weren't any problem. I think it would be good enough if just an error line would be enough instead of hanging indefinetely.

I think the issue can be closed. Thanks for the help.

And thanks Arch Linux for deciding to randomly disable Ipv6 configuration, I should have guessed that..
