### ISSUE TITLE
fixme: stream-start event without group-id in kurento 6.15 - record file created with 0 size

### ISSUE THREAD

**Issue by meyrow** [Kurento/bugtracker#566]
## Prerequisites

* [X] I agree to fill this issue template.
* [X] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

On kurento media server the record file was created but the file size is zero. In kurento media server log file an issue was logged (path to log: /var/log/kurento-media-server),

```
fixme basesink gstbasesink.c:3125 gst_base_sink_default_event() stream-start event without group-id. Consider implementing group-id handling in the upstream elements
fixme default gstutils.c:3766 gst_pad_create_stream_id_internal() nicesrc0:src Creating random stream-id, consider implementing a deterministic way of creating a stream-id
```

## Context

I would like to record a video stream with kurento 6.15.
I used git hub example "kurento-group-call" and it is working excellent !. Thanks !
https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-groupcall.html]

The next step I would like to do, is to record the video of each UserSession / Participant.

In java i wrote this code taking place when a ConnectionStateChangedEvent change state from disconnected to connected.
```
userRecorder = new RecorderEndpoint.Builder(this.pipeline,recordDestination).withMediaProfile(mediaProfileType).build();
userRecorder.connect(this.webRtcEndpoint);
userRecorder.record();
```

That should do the job for activating record on media server.

_On kurento media server the record file was created but the file size is zero_

## How to reproduce?

This issue can be reproduced.
Use the example from https://github.com/Kurento/kurento-tutorial-java/tree/master/kurento-group-call

Modify the java class UserSession.java
https://github.com/Kurento/kurento-tutorial-java/blob/master/kurento-group-call/src/main/java/org/kurento/tutorial/groupcall/UserSession.java

The needed modification is:
On instance WebRtcEndpoint outgoingMedia activate record() api when a ConnectionStateChangedEvent is changed to connected.

## Expected & current behavior

The Expected behavior is that a record file will be created on Kurento Media Server and save the video stream.
The Current behavior is that the record file was created on Kurento Media Server but the size is zero. No video stream was recorded.

## (Optional) Possible solution

The same problem was reported here: #228 (It was closed by a Kurento fix release).

### INFO about Kurento Media Server

* Kurento version:  6.15.0
* Server OS:          Ubuntu 18.04 (Bionic)
* Installation method:
    
  - [X] [apt-get]
  - [X] [Docker]
  - [] [AWS CloudFormation]
  - [] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### INFO about your Application Server

* Programming Language:  Java
* Kurento Client version:     6.15.0

### INFO about end-user clients

* Device(s):    
* OS(es):        Ubuntu 18.04 and Windows 10
* Browser(s):  Chrome 87

## INFO about your environment

The same endpoints and configuration as in the example https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-groupcall.html

No special configuration was done on KMS. The issue exist when running on Ubuntu when KMS is installed local or running a KMS docker. 

### Run these commands

Run KMS and run spring-boot on Group Call App with included modification as described.

The App will activate record and in KMS your will see in log a fixme issue about group-id as shown
```
fixme basesink gstbasesink.c:3125 gst_base_sink_default_event() stream-start event without group-id. Consider implementing group-id handling in the upstream elements
```

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

```
kurento-media-server --version
Kurento Media Server version: 6.15.0
Found modules:
	'core' version 6.15.0
	'elements' version 6.15.0
	'filters' version 6.15.0
```

```
dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
dpkg -l|grep -Pi 'kurento|kms-|gst.*1.5|nice'
ii  gstreamer1.5-libav:amd64                   1.8.1-1kurento1.18.04                            amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                    0.1.18-0kurento1.18.04                           amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64             1.8.1-1kurento5.18.04                            amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64            1.8.1-1kurento2.18.04                            amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64            1.8.1-1kurento5.18.04                            amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64            1.8.1-1kurento1.18.04                            amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64              1.8.1-1kurento5.18.04                            amd64        GStreamer plugin for PulseAudio
ii  kms-core                                   6.15.0-0kurento1.18.04                           amd64        Kurento Core module
ii  kms-elements                               6.15.0-0kurento1.18.04                           amd64        Kurento Elements module
ii  kms-filters                                6.15.0-0kurento1.18.04                           amd64        Kurento Filters module
ii  kms-jsonrpc                                6.15.0-0kurento1.18.04                           amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                                 1.6.3-1kurento1.18.04                            amd64        Kurento jsoncpp library
ii  kurento-media-server                       6.15.0-0kurento1.18.04                           amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64        1.8.1-1kurento5.18.04                            amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64       1.8.1-1kurento2.18.04                            amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                    1.8.1-1kurento2.18.04                            amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                            0.1.18-0kurento1.18.04                           amd64        ICE library (shared library)
ii  libsrtp0:amd64                             1.6.0-0kurento1.18.04                            amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                                 0.9.2-1kurento1.18.04                            amd64        sctp-refimpl library
ii  openh264                                   1.5.0-0kurento1.18.04                            amd64        H.264 Video Codec provided by Cisco Systems, Inc.
ii  openh264-gst-plugins-bad-1.5:amd64         1.8.1-1kurento5.18.04                            amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                     0.10.0-1kurento1.18.04                           amd64        OpenWebRTC specific GStreamer plugins
```

**Comment by Ogulcan-Ozdemir** [comment]
Hi meyrow did you check clients audioinput capability? I was faced same issue. When clients stream did not contain audio data . RecorderEndpoint not write buffered video frames to file. Possible solution would be make sure getUserMedia in browser client contains audio true constraint as well.

**Comment by meyrow** [comment]
Hi Oğulcan,
please correct me if I misunderstood the approach.
You mention: "*Possible solution would be make sure getUserMedia in browser
client contains audio true constraint as well*"
But my record method is inside my Java App server. What you suggest is the
JavaScript approach.

There are 2 kinds of RecorderEndpoint. Java and JavaScript.
If I use Java RecorderEndpoint for activating a record, why should I also
use JavaScript for the same?

**Comment by j1elo** [comment]
You're doing `userRecorder.connect(this.webRtcEndpoint);` but it should be `this.webRtcEndpoint.connect(userRecorder);`

There is a Recorder tutorial here: https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-recorder.html

And keep in mind Troubleshooting tips for the Recorder: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#recorderendpoint

**Comment by meyrow** [comment]
Thanks a lot. The recording is working fine.
