### ISSUE TITLE
Support multiple video streams

### ISSUE THREAD

**Issue by andreikop** [Kurento/bugtracker#568]
I need to send multiple video streams from single video conference peer via WebRTC.
I've tried to send two video streams in one SDP offer, but in reply from Kurento second stream was marked as inactive. It seems like Kurento doesn't support multiple video streams.
I've also found old [question](https://stackoverflow.com/questions/38282548/how-to-send-multiple-media-streams-from-one-client-using-kurento-client-utils-ap?rq=1) on StackOverflow.

It is possible to open a WebRTC session per every video stream. But in this case:
- session start would take more time
- it is impossible to synchronize the streams
- more network ports are used

Am I right that multi-stream is not supported?
Is it planned to develop it?

**Comment by j1elo** [comment]
It's not possible and not planned (neither sponsored by anyone interested) to add support for multiple videos or multiple audios on a single WebRtcEndpoint.

We are using Kurento as part of [OpenVidu](https://openvidu.io/) and we do as you mention: one WebRtcEndpoint for each stream. When a user wants to share their screen, that is indeed treated as an independent user (internally).

To reduce the amount of connections and disconnections between MediaElements in the Kurento Pipeline, especially when the sender has connectivity problems, we use an intermediate PassThrough.

That way, all receivers get their data from a PassThrough. If the sender is disconnected, it only has to connect to the PassThrough again, and the receivers don't need to re-negotiate their WebRTC connection.

Still, it's not an ideal solution, but adding multiple videos to a single WebRtcEndpoint (to all MediaElement implementations, really) would be a big overhaul of all Kurento code, and currently there is not enough commercial interest in such feature.

**Comment by andreikop** [comment]
Thank you for the detailed response!
