### ISSUE TITLE
No dtlssrtpdec check

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#57]
In case `dtlssrtpdec` element is absent, `KmsWebrtcTransportSrc` will still be created successfully without error or message and KMS crashes a bit later in `printf`.

I know the package with that element is listed in dependencies, but just in case I suggest to add check.

**Comment by kirushyk** [comment]
Same for `rtpbin`: `rtpsession` pointers should be initialised with `NULL` in `kmsbasertpendpoint.c` to make checks work correctly in case `rtpbin` is `NULL`.

**Comment by jcaden** [comment]
We are supposing that the system is correctly configured and is a requisite to have all needed plugins installed. In case that they are not installed, is preferred to directly crash the server in order to notice the problem clearly, because it won't be possible to run properly in any case.
