### ISSUE TITLE
Adjacent recordings in same pipeline won't write to disc until all recordings are stopped

### ISSUE THREAD

**Issue by spongessuck** [Kurento/bugtracker#61]
I have an application where 2 peers stream audio/video to each other while it's also recorded on KMS. The 'conference' is broken into two parts, so that as soon as the first part is finished, the recording ends and a new one begins for the second part.

It seems like the first recording won't finish writing to disc until all recordings have stopped. I can play it back while the 2nd stream records, but it doesn't have all the metadata. Even if the video is very small (<10 seconds) it still won't finish in a reasonable amount of time (I've waited about 2 minutes after this short recording without success), but as soon as I disconnect all Recorder Endpoints I can view the video with metadata.

If I only record the first part and turn off recording for the second part, I can get the first recording with metadata fairly quickly while the pipeline is still open, so it seems like it only writes everything when it's not recording anything.

**Comment by dfernandezlop** [comment]
Hi,

Are you calling to the stop method of the recorder to finish the first recorded video? It seems like you aren't doing and you are finishing the videos when the pipeline is released.

Regards.

**Comment by spongessuck** [comment]
Wow... I distinctly remember calling 'stop' on the Recording Endpoint before and getting a reference error. I just tried it again and now it works.

Thanks, sorry for wasting your time.
