### ISSUE TITLE
Multistream in WebRtcEndpoint?

### ISSUE THREAD

**Issue by zarybnicky** [Kurento/bugtracker#62]
I haven't been able to find any info about this - are there any plans for supporting multiple streams in a single WebRtcEndpoint? I've been intending to use Kurento to implement a multi-broadcaster webinar-like application but I didn't expect to find this as an obstacle...

Ideally, I'd like to use one WebRtcPeerSendrecv for all the broadcasters, all of them sending one audio and one video stream and receiving all the streams in a single connection (using a *single* peer!), and all the viewers would have a single peer as well, receiving all the streams.

While I have found Composite, it isn't really what I'm looking for - I'd like to manipulate with each video stream separately in the client.

Is this currently possible with Kurento? I couldn't find any way to accomplish this. The current group call demo uses a separate peer for each received stream.

**Comment by igracia** [comment]
I'm afraid multistream is not supported at the moment. It's in the roadmap, but can't give you an estimate.

**Comment by jcaden** [comment]
Please, use the list to ask questions. Bugtracker is only for bugs.
