### ISSUE TITLE
kurento-client-js: improve documentation

### ISSUE THREAD

**Issue by subpardaemon** [Kurento/bugtracker#64]
Hi,

Regardless of where I looked in the documentation or the source code, I cannot find methods to clean up an unused WebRTCEndpoint or MediaPipeline. While that might not be a huge issue in the nodejs client (after all, removing all the references, at least in my code, to the WebRTCEndpoint(s) or the MediaPipeline, should mark these objects ready for GC -- unless the kurento-client-js libraries still hold them), I don't know if this behaviour wouldn't cause serious memory leaks in the KMS.

A method like kurentoClientObject.destroy({Object}) or MediaPipelineObject.destroy({Object}) could do the trick, simultaneously telling KMS to discard the referenced MediaItem thus freeing up memory and resources (and destroying all dependant objects as well) and kurento-client-js to dereference the {Object}.

**Comment by jcaden** [comment]
You have release and unref methods for this purpose. Additionally, when the websocket is closed for more than 4 minutes, all elements associated only to that session are destroyed.

**Comment by subpardaemon** [comment]
Ah. But then let me suggest to reopen this ticket, because then the problem is the severly cripped API reference for the nodejs client libraries, and the lack of proper documentation for the nodejs API in general. (Btw, I couldn't find any reference to unref(), beside the timers in nodejs in general.)

The nodejs API reference doc is very problematic for the following reasons:

1. Some methods, even key methods like release() are not documented at all. And I don't mean there's no explanation for the method params, I mean the method is _not there at all_. Case in point: release(). By doing `grep -rl release kurento-* | grep '[.]js'` I managed to find references to release in two relevant files only: kurento-client/lib/KurentoClient.js and kurento-client-core/lib/abstracts/MediaObject.js. By plowing through these files, the former only has event listeners to the "release" event, and only in the latter have I managed to find the actual method. Which is nice to finally find it, but honestly I shouldn't have had to jump through loops to unearth it.

2. Inheritance plagues the JSdoc API reference. For some exotic reason a _lot_ of methods are only mentioned at the class that defines them originally, but none of the descendants. These include key methods like connect(), getTag() etc. Other methods _do_ show up in excess, like getChilds() (btw, shouldn't that be getChildren()? ok, just kidding), getName() etc. I don't understand the logic behind this, and it makes perusing the API docs a pain in the butt. Compared to other API docs (which either do away with inheritance completely or follow the chain perfectly) this is also confusing.

3. Same problem with events. I had to dig through files in the inheritance chain to unearth the fact that the WebRtcEndpoint class fires "ConnectionStateChanged" and "MediaStateChanged" events alongside "OnIceCandidate". Also, event properties are not documented at all.

4. The ubiquitous create() method is very poorly documented, despite being a key element in using the nodejs API. For example, I had to dig through 3rd-party examples to find out how I'm supposed to specify parameters for creating new objects through create().

The "Kurento Tutorials" section is also missing some key concept demonstrations. While through looking up most of the examples I was able to gather enough information to start writing my code, I think a section like "Key Concepts" or "How do I..." would be really helpful, with demonstrating code snippets as to how to do the major steps in developing your application, like:

- create a nodejs client and connect it to the KMS instance
- create a media pipeline
- create an endpoint in the pipeline
- connect endpoints to each other
- handle events in endpoints
- disconnect endpoints from each other
- destroying endpoints
- destroying a pipeline

**Comment by igracia** [comment]
I think you've got a point there. We are working right now on improving the API documentation: headers, methods and so on. We'll have a look at that.

As for the "How do I..." part, you are also right. We should include that for all clients.

**Comment by subpardaemon** [comment]
If you need help with writing the "How do I" part, count me in, I'd be glad to help (although I would need heavy revision as I'm still learning how to do things in Kurento). But if it's all the same to you, I'd prefer writing this using promises instead of the callback-style interface that is prevalent in the current documentation.

**Comment by igracia** [comment]
Yeah, that's not a bad idea. Let us see how we can schedule that, and I'll get back to you with some info.

Perhaps the best would be for you to submit a pull-request to the doc-kurento project.

**Comment by subpardaemon** [comment]
OK, I'll be standing by. (Actually, coding like a madman, but that's beside the issue.)

**Comment by subpardaemon** [comment]
BTW, something I can't find in the docs either: are there any methods to decouple/disconnect items from a MediaPipeline? release(), at least on the first blink, seems to release the object on the KMS, but doesn't decouple the objects from each other. And with circular references and whatnot, it could raise hell regarding GC. Or does it do decoupling at a separate place automatically after the server has released the object?

**Comment by igracia** [comment]
Yes, releasing one object destroys it internally, along with all connections. There is also a disconnect method. You can check that in the [Java](https://doc-kurento.readthedocs.io/en/stable/_static/langdoc/javadoc/org/kurento/client/MediaElement.html#disconnect(org.kurento.client.MediaElement)) documentation. Somehow it didn't make it to the JS docs, we'll have to see why.

**Comment by subpardaemon** [comment]
So basically I can call MediaPipeline.disconnect(ChildElement)? I have used disconnect() to decouple viewers from one WebRtcEndpoint and to decouple a RecorderEndpoint from a WebRtcEndpoint, but based on this, I can also decouple the primary WebRtcEndpoint from the serving MediaPipeline, right? And what is the preferred order, first disconnect() then release()?

**Comment by subpardaemon** [comment]
Another documentation-related matter came up while developing our application with KMS. Namely, it is only hinted in the documentation that WEBRTC endpoints should be able to adapt to the peer's requirements. So the question is, not covered by the documentation or the FAQ, is:

If the scenario is a presenter with multiple viewers, let's assume the presenter sends a 720p video stream that consumes 1.5mbps. Now, with a direct WEBRTC connection, the peers can establish a connection that can be consumed mutually, so if say one peer is unable to handle a 720p incoming stream (bandwidth/processing issues, whatever), they can negotiate with sending the right offer/answer SDP pairs.

How does that work with Kurento? When the presenter connects to the signaling server, the latter creates a MediaPipeline, and creates a WEBRTC endpoint whose SDP answer is transmitted back to the presenter, thus the presenter is now connected via a WEBRTC mux to the KMS. However, when a viewer wants to connect, the signaling server creates a new WEBRTC endpoint and connects it to the presenter's WEBRTC endpoint; and here's the real question:

If the viewer's SDP specifies that it somehow can't deal with the presenter's 720p stream, is the negotiation going to collapse, or is there an actual negotiation taking place between the presenter's WEBRTC endpoint and the viewer's WEBRTC endpoint _within_ KMS? And if so, is it possible that KMS creates a downgraded stream for the viewer automatically?

**Comment by igracia** [comment]
> And what is the preferred order, first disconnect() then release()?

`release()` implies a `disconnect()`. If you are going to do both, you might as well do only the `release()`. In any case, can't disconnect after it has been released.

> If the viewer's SDP specifies that it somehow can't deal with the presenter's 720p stream, is the negotiation going to collapse, or is there an actual negotiation taking place between the presenter's WEBRTC endpoint and the viewer's WEBRTC endpoint within KMS? And if so, is it possible that KMS creates a downgraded stream for the viewer automatically?

The downgraded stream thing is simulcast, and for now KMS can't do it. Since the "feedback" form the new viewer will arrive at the presenter's WebRTC, the presenter will downgrade the quality of the stream to meet that of the worst conditioned viewer.

**Comment by subpardaemon** [comment]
Ah-ha. So what you are saying is that when a presenter (P) creates (via the signaling server/Kurento JS API client=SERVER) a MediaPipeline, attaches its own WebRtcEndpoint (WRE), then creates the WebRTC connection, Kurento is presented as a max-capability partner, but when additional viewers (V) connect and create their own WREs which are attached to P's WRE, an active negotiation will happen between all V's WREs and P's WRE just as if they were directly connected? And thus the lowest common denominator will win?

Is there a way to circumvent this behaviour? Like attaching a transcoder endpoint to P's WRE that creates a lower-quality (ie halving the resolution, sticking to VP8) version of the stream, then attaching an artificial WRE to this transcoder, and connect certain viewers to this WRE? Essentially creating a lower-quality version of the same stream within Kurento, and let certain clients connect to that?

**Comment by subpardaemon** [comment]
Found another gotcha in the documentation. Compared to how this affects general useability, it is very much hidden. I'm talking about the default bandwidth clamps on WebRtcEndpoints.

At http://doc-kurento.readthedocs.io/en/stable/_static/langdoc/jsdoc/kurento-client-js/module-elements.WebRtcEndpoint.html , the default settings for setMaxVideoRecvBandwidth and setMaxVideoSendBandwidth are at 500kbps. While I can understand that this is in effect probably to avoid bandwidth congestion situations, it's insufficient even for a 720p video stream in acceptable quality. Having spent about 4 hours trying to find out why Chrome puts a choker on outgoing stream bitrate, it's not funny to finally find out that such an important info is only found in literally the smallest possible font size buried deep in the object's documentation. :/

This information should be printed in big, bold letters, preferably red, probably even invoking the dreaded blink tag, so somewhere someone developing a WebRTC application with Kurento might actually find it.

**Comment by igracia** [comment]
> Is there a way to circumvent this behaviour? Like attaching a transcoder endpoint to P's WRE that creates a lower-quality (ie halving the resolution, sticking to VP8) version of the stream, then attaching an artificial WRE to this transcoder, and connect certain viewers to this WRE? Essentially creating a lower-quality version of the same stream within Kurento, and let certain clients connect to that?

Yes, you could connect a transcoder to isolate the feedback from the viewers back to the presenter.

We have added more information to the headers, but it hasn't made it to the docs yet. You are right: we probably should put it in more places ;-)

**Comment by subpardaemon** [comment]
Uh, wait a second... I've looked around in the docs, and I seem to remember there being a transcoder module. However, upon closer inspection I can't find any such thing neither here http://doc-kurento.readthedocs.io/en/stable/mastering/kurento_modules.html nor here http://doc-kurento.readthedocs.io/en/stable/_static/langdoc/jsdoc/kurento-client-js/index.html . Is it possible? Or should I just attach an RTPEndpoint or a HttpEndpoint to the WebRtcEndpoint?

**Comment by jcaden** [comment]
Could you continue this conversation in the mailing list, please? As this is becoming more a conversation than a bug report.

**Comment by subpardaemon** [comment]
In all fairness, you're right; still, these could be real-life use-cases in the docs. Nevertheless, I'll stop asking these here, and sorry. :) Do you still need help with the docs?

**Comment by igracia** [comment]
It is true that some issues end up being conversations, but always about the issue in hand ;-) Not to worry! The question you are asking would better go in the list.
