### ISSUE TITLE
Include kurento-utils browser build in npm module

### ISSUE THREAD

**Issue by mariotacke** [Kurento/bugtracker#65]
For the [kurento utils](https://www.npmjs.com/package/kurento-utils) npm module, can you include the [browser](https://github.com/kurento/kurento-utils-js#browser) build on npm? It seems like an unnecessary step for a user of the library to have to install and run grunt on the already installed package.

**Comment by tgabi333** [comment]
I think its not unnecessary., because you use all of your npm installed packages in the browser through some module loader (mostly browserify). Since npm is for node, you must pack the sources for browser. 

Most of the time you already have a packager, you're done, not needed to pack this piece.

**Comment by mariotacke** [comment]
You make a good point, but I think that your reasoning is a little too broad to apply in all cases. The library *requires* you to use grunt to build a browser compatible package. My project is not using grunt and running a build task on a node package seems like a hack to me. Including the build along with the other compiled files makes this library more portable and reduces build complexities. It would only be included in the npm package version anyhow.

**Comment by j1elo** [comment]
Closing old issues. In this case we regard kurento-utils-js as a nice to have helper library but users who need more control are encouraged to write directly against the browser's RTCPeerConnection API.
