### ISSUE TITLE
kms-cmake-utils: CMake 3.4 on Fedora couldn't find FindKurentoHelpers.cmake

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#66]
CMake 3.4 on Fedora looks for modules in `share/cmake/Modules/` folders only.
However, https://github.com/Kurento/kms-cmake-utils/blob/master/CMakeLists.txt#L8
puts `.cmake` files in `share/cmake-3.4/Modules/`.

**Comment by dfernandezlop** [comment]
Hi,

Kurento only supports Ubuntu, and this is the way to install a cmake module in Ubuntu.

Sorry for troubles.
