### ISSUE TITLE
Why kms-core checks for gstreamer-check library presence?

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#69]
In CMakeLists.txt there is generic_find for gstreamer-check-1.5.
But it seems not to be used. Or am I wrong?

**Comment by dfernandezlop** [comment]
Hi,

We use gstreamer-check in our tests [1].

This is not a bug, for asking questions please use the kurento public list [2].

I'm closing this thread.

[1] https://github.com/Kurento/kms-core/blob/master/tests/check/element/CMakeLists.txt
[2] https://groups.google.com/forum/#!forum/kurento

**Comment by kirushyk** [comment]
Sorry!

Thank you for clarification.
