### ISSUE TITLE
Missing dependencies from kurento-client-core-js

### ISSUE THREAD

**Issue by tgabi333** [Kurento/bugtracker#70]
As you can see here:

https://github.com/Kurento/kurento-client-core-js/blob/master/lib/abstracts/MediaObject.js

There are several require calls with `kurento-client` and `es6-promise` and `promisecallback` which are not native nor in the package.json.

**Comment by igracia** [comment]
They are declared [here](https://github.com/Kurento/kurento-client-js/blob/master/package.json). If that's ok, you can proceed and close the issue.

**Comment by tgabi333** [comment]
Strictly speaking `kurento-client-core-js` and `kurento-client-js` are different packages.

**Comment by igracia** [comment]
Indeed, though they are indivisible, so to speak. Right  before those `require` statements, you have a `var kurentoClient = require('kurento-client');`. Those dependencies are transitive deps from the `kurento-client-js` project. Having those deps also defined in child projects, would require us to manage the same dependency in many projects. For the sake of maintenance, we decided to keep all in just one place.

**Comment by tgabi333** [comment]
Thanks for the explanation @igracia.
