### ISSUE TITLE
HttpGetEndpoint error in nodejs

### ISSUE THREAD

**Issue by yev** [Kurento/bugtracker#72]
Hello,

I try to build the simple app following this doc http://doc-kurento.readthedocs.io/en/stable/_static/langdoc/jsdoc/kurento-client-js/index.html

When I run my app, I got the weird error in line:
pipeline.create('HttpGetEndpoint', function(error, httpGet)

After a little search on Kurento API docs, seems there is no such a class. Maybe there is a new version of API and the docs dont reflect it?

**Comment by igracia** [comment]
I'm afraid the `HttpGetEndpoint` was deprecated over a year ago. We've removed the example from the README.md file, which in any case shouldn't be there. If you want to learn how to use Kurento, please check the [tutorials](https://doc-kurento.readthedocs.io/en/stable/tutorials.html) as they are more updated.

**Comment by yev** [comment]
Yep, it's removed from Readme, but still present in the documentation...
It was not so difficult to find out that HttpGet class is not present in the source, but anyway this requires to dig... Maybe I will try to make a pull request regarding this issue

**Comment by igracia** [comment]
Is it still present in the documentation? Could you point it?

**Comment by yev** [comment]
I mentioned the doc in the description (http://doc-kurento.readthedocs.io/en/stable/_static/langdoc/jsdoc/kurento-client-js/index.html).
You can search then for HttpGetEndpoint

**Comment by vijay-online-bub** [comment]
You might want to delete HttpGetEndpoint description in below documentation too.It is misleading.


http://kurento.com/kurento-media-element-toolbox
