### ISSUE TITLE
PlayerEndpoint.setPosition freezes video after 30s mark

### ISSUE THREAD

**Issue by s-silva** [Kurento/bugtracker#73]
Setting position beyond 30s on a WEBM video freezes playback, anything below 30s point seems to work fine. Also, this is only happening with Kurento recordings, WEBMs created with FFmpeg had no seeking issues.

Kurento version:
```
Version: 6.3.4~2.g7386d4a
Found modules:
	Module: 'core' version '6.3.2~21.ge287119'
	Module: 'elements' version '6.3.2~18.gbce3157'
	Module: 'filters' version '6.3.1~1.gb3f6a20'
```

Using Kurento node client.

**Comment by dfernandezlop** [comment]
Hi,

Have you checked with the last release of Kurento (6.4.0) or with the development version?

Regards.

**Comment by s-silva** [comment]
Hi @dfernandezlop,

We had the same issue with v6.4.0:
```
Version: 6.4.0
Found modules:
        Module: 'core' version '6.4.0'
        Module: 'elements' version '6.4.0'
        Module: 'filters' version '6.4.0'
```
I'll try the development version and post an update here.

**Comment by s-silva** [comment]
Working on v6.5.0

```
Version: 6.5.0
Found modules:
	Module: 'core' version '6.5.0'
	Module: 'elements' version '6.5.0'
	Module: 'filters' version '6.5.0'
```

Closing the issue. Thanks @dfernandezlop !

**Comment by dfernandezlop** [comment]
You are welcome!
Thanks for your feedback.

**Comment by ricsierdelyi** [comment]
Hi, 

I still have this issue, recording WEBM video and the video freezes upon seeking position beyond 30s.  Can you help me how to solve the issue?

Version: 

`Kurento Media Server version: 6.15.0
Found modules:
	'chroma' version 6.15.0
	'core' version 6.15.0
	'crowddetector' version 6.15.0
	'elements' version 6.15.0
	'filters' version 6.15.0
	'platedetector' version 6.15.0
	'pointerdetector' version 6.15.0`

**Comment by j1elo** [comment]
How long is the same file if you open it in VLC? and in Chrome? (just drag the file directly onto a Chrome tab)
Can you seek fine if you open the file in VLC and Chrome?

**Comment by ricsierdelyi** [comment]
I have just noticed that the audio is there, it is seeking properly every time. Only the video freezes upon seeking above 30s.

**Comment by j1elo** [comment]
Does the problem also happen if `useEncodedMedia: false`?

Note that the file needs to have frequent video keyframes in order to allow for seeking. Otherwise Kurento will stay there waiting until the next keyframe, if the file doesn't have many, then the wait will be long.

You can troubleshoot this, if you see in the logs: "dropping until keyframe" or similar.

Have a look here to learn how to change debug level: https://doc-kurento.readthedocs.io/en/latest/features/logging.html

Then add to the default levels this other one: `kmsutils:5`. After doing that, the exact message is:
```
Start dropping buffers until keyframe
```

**Comment by ricsierdelyi** [comment]
It is working fine if `useEncodedMedia: false`, however Kurento starts transcoding the files and the CPU usage is too high if I play many videos from different browsers at the same time. 

With `useEncodedMedia: true` there is no transcoding and CPU usage is fine. Is there a way to solve this while keeping it on `true`?
