### ISSUE TITLE
KMS 6.4.0, Kurento RTSP/HTTP URI to WebRTC example, Ubuntu 14.04.4 LTS -- Segmentation fault

### ISSUE THREAD

**Issue by LippyThunder** [Kurento/bugtracker#74]
I've installed KMS and the Kurento RTSP/HTTP URI to WebRTC example (https://github.com/lulop-k/kurento-rtsp2webrtc). I've successfully received the stream from Wowza's RTSP test stream (rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov) and from one of our IP cameras (D-Link DCS-2121). However when I've tried connecting to our HD IP camera (Foscam R2) the server threw a segmentation fault producing the attached log file.

The KMS version is 6.4.0. The installed modules can be found in the attached modules.txt file.
I've also tried the latest development version (6.4.1~14.ge488e46) with the same results.

It was tested with Google Chrome (Windows) and Firefox (Linux).

Please let me know if you need any more information.
Thanks in advance.

[media-server_2016-05-19_13-12-18.00000.pid1701.txt](https://github.com/Kurento/bugtracker/files/272559/media-server_2016-05-19_13-12-18.00000.pid1701.txt)
[modules.txt.txt](https://github.com/Kurento/bugtracker/files/272588/modules.txt.txt)

**Comment by LippyThunder** [comment]
I've changed the camera's bit rate from 4M to 1M and it does not crash anymore.

**Comment by igracia** [comment]
Thanks for the feedback!

**Comment by Lily260787** [comment]
Hello !
I'm currently trying to develop a Kurento RTSP/HTTP URI to WebRTC application like, with a D-LINK DCS-4622. I couln't make the Kurento example work and don't really know then how to manage for the rest, could you please share some code to help me out ? 
Thanks in advance,
