### ISSUE TITLE
Can't compile kms-core 6.4.0 on arm architecture

### ISSUE THREAD

**Issue by gianpi90** [Kurento/bugtracker#75]
When I compile kms-core 6.4.0 on rasperry pi with kurento-module-creator 4.0.0, I have this error:

<code>
Error calling code generator: usage: kurento-module-creator

 -c,--codegen \<CODEGEN_DIR\>                 Destination directory for
                                            generated files (required if
                                            --show-values or
                                            --output-model is not present.

 -cf,--config \<CONFIGURATION_FILE\>          Configuration file.

 -d,--delete                                Delete destination directory
                                            before generating files.

 -dr,--deprom \<DEP_ROM_FILE\>                A space separated list of
                                            Kurento Media Element
                                            Description (kmd) files used
                                            as dependencies or folders
                                            containing this files.

 -h,--help                                  Prints this message.

 -it,--internal-templates \<TEMPLATES_DIR\>   Directory that contains
                                            template files.

 -lf,--list-generated-files                 List in the standard output
                                            the names of generated files.

 -maven,--maven-pom                         Generate pom.xml file based on
                                            base file or template.

 -n,--no-overwrite                          Do not overwrite files if they
                                            are already generated.

 -npm,--npm-package                         Generate package.json file
                                            based on base file or
                                            template.

 -o,--output-model \<DIR\>                    Directory where the final
                                            model will be written.

 -r,--rom \<ROM_FILE\>                        A space separated list of
                                            Kurento Media Element
                                            Description (kmd) files or
                                            folders containing this files.

 -s,--show-values \<LIST OF KEYS\>            Show values for provided keys
                                            in kmd.json files.

 -t,--templates \<TEMPLATES_DIR\>             Directory that contains
                                            template files.

 -v,--verbose                               Prints source code while being
                                            generated.

CMake Error at CMake/CodeGenerator.cmake:80 (message):
  Output error: Unrecognized option: -p
</code>

<code>
Call Stack (most recent call first):

  CMake/CodeGenerator.cmake:340 (execute_code_generator)

  CMake/CodeGenerator.cmake:286 (generate_kurento_libraries)

  src/server/CMakeLists.txt:39 (generate_code)

-- Configuring incomplete, errors occurred!</code>

I followed this guide: https://github.com/Kurento/bugtracker/issues/56
How can I resolve this?

Edit: I found this code in CMake/CodeGenerator.cmake of kms-core folder:
rows 336-342

<code>
  # Get reduced kmd
  ###############################################################

  execute_code_generator (OUTPUT_VARIABLE PROCESSOR_OUTPUT
    EXEC_PARAMS ${KTOOL_PROCESSOR_LINE} -p)
</code>
Is this code that throws the error?
How should I modify it?

**Comment by gianpi90** [comment]
ok I have built kms-core 6.4.0, I replace CMake/CodeGenerator.cmake with the same file of the testing branch and modify the version of kurento-module-creator at row 5:

`generic_find(LIBNAME KurentoModuleCreator VERSION ^4.0.0 REQUIRED)`

There are some problems with this file of the master branch when I compile.

**Comment by gianpi90** [comment]
I have some problem with kurento-media-server, so I need the correct file CMake/CodeGenerator.cmake for kms-core.

**Comment by dfernandezlop** [comment]
Hi,

Kurento is designed to be built in Ubuntu, so this is not a bug. Please write to the public list [1] to try getting help.

Best.
[1] https://groups.google.com/forum/#!forum/kurento
