### ISSUE TITLE
GStreamerFilter textoverlay does not work

### ISSUE THREAD

**Issue by voltrevo** [Kurento/bugtracker#78]
I'm running something similar to the magic-mirror in kurento-tutorial-node and am trying to create a GStreamerFilter like this:

```js
    myFilter = Promise.resolve(pipeline.create('GStreamerFilter', {
      // mediaPipeline: pipeline,
      // command: 'clockoverlay time-format="%Y.%m.%D"',
      // command: 'cairotimeoverlay',
      // command: 'capsfilter caps=video/x-raw,framerate=2/1',
      // command: 'timeoverlay',
      command: 'textoverlay font-desc="Sans 24" text="TEST" valignment=top halignment=left shaded-background=true',
      // filterType: 'VIDEO',
    })).catch(err => {
      console.error('pipeline create error for gstreamer:', err);
      throw err;
    });
```

but the following exception is being thrown:

```
pipeline create error for gstreamer: { [Error: Given command is not valid, pad templates does not match] code: 40001, data: { type: 'MARSHALL_ERROR' } }
```

I don't understand what this error means, and am confused because a similar command works using `gst-launch` on the command line:

```
gst-launch-1.0 videotestsrc ! textoverlay font-desc="Sans 24" text="TEST" valignment=top halignment=left shaded-background=true ! ximagesink
```

![screen shot 2016-06-01 at 3 39 48 pm](https://cloud.githubusercontent.com/assets/9291586/15699284/1ef54050-280f-11e6-8903-3bdbd47ffc70.png)

Also, the capsfilter command I have commented out does work with kurento:
```
command: 'capsfilter caps=video/x-raw,framerate=2/1',
```

And works in the same way using `gst-launch`. So I'm not sure what's different about using textoverlay that makes it break when creating a kurento filter but doesn't break when using `gst-launch`.

Is the error message `pad templates does not match` accurate? If so what does it mean? Is there any documentation available that would answer these questions?

**Comment by jcaden** [comment]
Hi, `GStreamerFilter` expects that the element created has a sink pad called 'sink' and a source pad called 'src'. But text overlay hast two sink pads one for video and other for text. That is why it doesn't work as you expect.

I'm closing this bug, if you need further support, please ask in the [mailing list](https://groups.google.com/forum/#!forum/kurento).

**Comment by rachitkohli7** [comment]
Hi Voltrevo,

The code you have written works for me when I don't use valignment and halignment parameters.

`myFilter = Promise.resolve(pipeline.create('GStreamerFilter', {
      // mediaPipeline: pipeline,
      // command: 'clockoverlay time-format="%Y.%m.%D"',
      // command: 'cairotimeoverlay',
      // command: 'capsfilter caps=video/x-raw,framerate=2/1',
      // command: 'timeoverlay',
      command: 'textoverlay font-desc="Sans 24" text="TEST" shaded-background=true',
      // filterType: 'VIDEO',
    })).catch(err => {
      console.error('pipeline create error for gstreamer:', err);
      throw err;
    });`

**Comment by gankurg** [comment]
Hi,
I am sorry, i am new to Kurento 
I want to use textOverlay Filter to display the IP address over the video,
while using filter i am getting following error

GStreamer element cannot be created: no element "textoverlay"

how can i compile kurento with textOverlay filter ?
kindly help
