### ISSUE TITLE
[kurento-utils-js] Warn when choosing audio and video, and camera fails to provide video (if possible)

### ISSUE THREAD

**Issue by Hemanshu1belani** [Kurento/bugtracker#79]
User OS : Ubuntu 14.04 LTS (64 bits)
User Browser : Chrome - 51.0.2704.63 (64-bit)

Use Case : 

A user has a non-working camera  & he tries for a video call.
As he click on video call button I set following media constraints & start the calling process

const MEDIA_CONSTRAINTS_AUDIO_VIDEO = {
    audio: true,
    video: true
};

Because of above constraint var offerVideo is set to true.
Now he gets connected to other participants but both of them could not hear each other neither I get any error from kurentoUtils.

Is there any error callback where kurento identifies that user does not have camera  although the constraint passed has video = true?
or any other way to find out the user camera is not working ?

Steps to Reproduce : Start a 1-1 video call between 2 users without camera ( Chrome ).

Actual Result : Both the user could not hear each other.

Expected Result : Both the user should be able to communicate with each other.

**Comment by dfernandezlop** [comment]
Hi,

It is not a Kurento bug, but a Chrome bug [1].

Regards.
[1] https://bugs.chromium.org/p/chromium/issues/detail?id=403710

**Comment by igracia** [comment]
I think we could add a warning in Kurento-Utils to prevent this. I asked @Hemanshu1belani  to file a feature request.
