### ISSUE TITLE
WEBM audio doesn't work (v6.5.0)

### ISSUE THREAD

**Issue by s-silva** [Kurento/bugtracker#80]
Audio is silent for WEBM recordings created with Kurento.
Works perfectly on v6.4.0, but it failed on both:

```
Version: 6.5.0
Found modules:
    Module: 'core' version '6.5.0'
    Module: 'elements' version '6.5.0'
    Module: 'filters' version '6.5.0'
```

```
Version: 6.5.1~1.gfaf330a
Found modules:
	Module: 'core' version '6.5.0'
	Module: 'elements' version '6.5.0'
	Module: 'filters' version '6.5.0'
```

Probably an issue in recorderEndpoint, I could play the files perfectly by just dragging and dropping the files to a Chrome tab but when I tried to play them through playerEndpoint the audio was silent in the playback stream. Then I tried to open the files using VLC and it had the same issue with audio playback.

The same recorder/playback code works fine when I switch Kurento server version to v6.4.0

**Comment by igracia** [comment]
@jcaden We should check this.

**Comment by jcaden** [comment]
@s-silva Have you found the issue on our demos? Just to be sure that we have the same test environment.

Could you also provide the versions gstreamer plugins installed with 6.4.0 and 6.5.0? Just paste the output of `dpkg -l | grep gst | grep 1.5` in both cases.

Thanks

**Comment by soifs** [comment]
Recorded files didnt have audio on vlc even on 6.4.0. 
i havent tried to play it on playerEndpoint on that version but on 6.5.0 that i tried now there is no audio.
On both versions if i drag n drop the file on the brower i have audio, so the audio is there but cant be played on vlc and playerEndpoint.

**Comment by jcaden** [comment]
@soifs Newer versions of VLC has support for opus but older ones doesn't. Update VLC if you want to play them correctly.

**Comment by soifs** [comment]
@jcaden I am using the latest vlc version (2.2.3)

as i said in kurento list

> I also get no audio on vlc from webm files generated from recorderEndpoint, but i get audio when i play them on firefox/chrome
i see that vlc supports opus since 2.0.4 (try the example file on the link) https://trac.videolan.org/vlc/ticket/7185
Also vlc plays opus audio from webm files generated from MediaRecorder Api (example here https://simpl.info/mediarecorder/ )

Maybe a bug on recorder endpoint?

**Comment by s-silva** [comment]
@jcaden 

v.6.4.0
```bash
ii  gstreamer1.5-libav:amd64                 1.7.0.1~20160224182850.34.g1d2c0c1.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                  0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64           1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64          1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64          1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64          1.7.1.1~20160224182649.23.g036c2d2.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64            1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                     1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad1.5-0:amd64      1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64     1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                  1.7.1.1~20160225111550.199.gba35ee7.trusty amd64        Core GStreamer libraries and elements
```

v6.5.0
```bash
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160128151042.29.gc3ab763.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160205162749.72.ge38c85a.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.7.1.1~20160204085211.114.gd79d60c.trusty amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.7.1.1~20160129140550.53.ga80508b.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.7.1.1~20160129140416.58.gdf10eac.trusty  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.7.1.1~20160129140756.17.g7fa46ee1.trusty amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.7.1.1~20160129140416.58.gdf10eac.trusty  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.7.1.1~20160129140550.53.ga80508b.trusty  amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad1.5-0:amd64  1.7.1.1~20160204085211.114.gd79d60c.trusty amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
```

I'm using node libraries and there were no demos for recorderEndpoint and playerEndpoint. I'll attach two of my test apps which were based on hello-world demo app. And yes, the test apps show the same issue.

Both apps use 127.0.0.1:8888 Kurento URI and has the same setup procedure:
```bash
npm install
bower install
npm start
```

Recorder:
Runs on http://localhost:8080/, click 'Start' to record.

Player:
Runs on https://localhost:8443/, click anywhere on the grey square to start playing the video.

[recorder.tar.gz](https://github.com/Kurento/bugtracker/files/297471/recorder.tar.gz)
[player.tar.gz](https://github.com/Kurento/bugtracker/files/297473/player.tar.gz)

**Comment by jcaden** [comment]
@s-silva It seems that the libraries are outdated for version 6.5.0, should be somethink like 1.8.0~20160530.... Try updating running `sudo apt-get update && sudo apt-get dist-upgrade`. Then test again version 6.5.0, it should work.

**Comment by jcaden** [comment]
@soifs Could you send a video sample that plays correctly on chrome but not in vlc? Do you have a way to create more of this videos?

**Comment by soifs** [comment]
i had the same output to `dpkg -l | grep gst | grep 1.5` like s-silva on the updated kurento server v.6.5.0
```
ii  gstreamer1.5-libav:amd64             1.7.0.1~20151125151140.29.gc3ab763.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.7.1.1~20160119155146.113.gb3802ee.trusty amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.7.1.1~20160119154722.53.ga80508b.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.7.1.1~20160119154813.58.gdf10eac.trusty  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.7.1.1~20160119154839.17.g7fa46ee1.trusty amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.5.1.1~20150619095020.727.g54cb2ae.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.5.1.1~20150619091549.879.gd836d44.trusty amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad1.5-0:amd64  1.7.1.1~20160119155146.113.gb3802ee.trusty amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
```
and here is a sample
[recorder_demo.zip](https://github.com/Kurento/bugtracker/files/297708/recorder_demo.zip)

after `sudo apt-get update && sudo apt-get dist-upgrade` 



```
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
```
sample after the gsteamer update.
[recorder_demo2.zip](https://github.com/Kurento/bugtracker/files/297800/recorder_demo2.zip)

both files show the behavour mentioned above.

**Comment by jcaden** [comment]
It seems that vlc can only play opus in mono, and this video is recorded in stereo, it's the only difference I can see. About the problem with kurento player, we need a little bit more time to test it.

**Comment by s-silva** [comment]
@jcaden thanks! Running `sudo apt-get update && sudo apt-get dist-upgrade` and restarting the server fixed it for me. PlayerEndpoint is working fine now.

VLC still fails to play the audio but it's probably just a limitation in VLC. FFmpeg worked well with the files (tested by extracting audio using FFmpeg).

I'm going to leave the issue open since `dist-upgrade` didn't fix the issue for @soifs.

**Comment by soifs** [comment]
> and restarting
@s-silva 
playerEndpoint works well here too, you can close it :)
So it's vlc's issue not playing stereo.

**Comment by s-silva** [comment]
Cool! Closing the issue.

**Comment by jcaden** [comment]
Great thaht your problem is solved! Thanks for closing.
