### ISSUE TITLE
turnURL parameter in WebRtcEndpoint.conf.ini doesn't support @ characters in usernames

### ISSUE THREAD

**Issue by nahuel** [Kurento/bugtracker#81]
`WebRtcEndpoint.conf`/`turnURL`  syntax is defined as `user:password@address:port(?transport=[udp|tcp|tls])`, so you can't include an `@` character in the username. This makes the free STUN/TURN server http://numb.viagenie.ca/ unusable, because when you register in it the TURN username you get is your mail address.

**Comment by igracia** [comment]
Well, that's not something we have any saying at, as it's the regular way to pass credentials in [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding). Something more concrete [here](https://tools.ietf.org/html/rfc5389#section-10.2.2).

You'll have to escape them. See [this](https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls) SO answer for more info.

**Comment by nahuel** [comment]
Escaping `@` using `%40` in `turnURL` doesn't work. Also note usernames and passwords can't be included in standard TURN uri's: 

https://tools.ietf.org/html/rfc7065#section-4
https://tools.ietf.org/html/rfc7065#appendix-B

The links you cited are related to HTTP, not TURN. For example browsers accepts TURN servers defined as `{"url":"turn:numb.viagenie.ca","username":"ngreco@gmail.com","credential":"mypassword"}` , including any user/password in the url doesn't work. So `WebRtcEndpoint.conf.ini` / `turnURL` doesn't follow RFC 7065. I think adding `turnUsername` & `turnCredential` configuration variables is the right thing to do.

**Comment by igracia** [comment]
You are right, sorry for misguiding you. I'll reopen the issue.

**Comment by idubinets** [comment]
hi guys,

do you have some news about this issue? I also can't use http://numb.viagenie.ca/  because of @ in username

**Comment by j1elo** [comment]
Closing old issues.
The [TURN regex](https://github.com/Kurento/kms-elements/blob/9bdb3cb5cfd84767ee033af36451994d1883b87e/src/gst-plugins/webrtcendpoint/kmswebrtcsession.c#L1647) should be able to separate a username that contains `@` from the rest of the URL: `user@example.com:password@123.456.789:1234`
