### ISSUE TITLE
Running Server with `npm start` in PROD? or forever or PM2 ?

### ISSUE THREAD

**Issue by destromas1** [Kurento/bugtracker#82]
https://github.com/Kurento/kurento-tutorial-node/blob/master/README.md

Here as used `npm start` which by default run `node server.js` , this should be for runnint the app locally , right ? In P{ROD , We should use `forever` or `PM2` ? what you guys officially suggest for PRODUCTION?

**Comment by igracia** [comment]
Well, we suggest never running a tutorial in production, that's the first thing. That code is not production-grade, so to speak. Be that as it may, from what I know the best way is probably `PM2`.

Also, please don't use the bugtracker for questions or asking for help. It's better to post in the list, as there are more followers than here, so you are bound to find help more quickly.
