### ISSUE TITLE
Kurento process memory issues

### ISSUE THREAD

**Issue by yehiyam** [Kurento/bugtracker#85]
We're using Kurento for one to many distribution of WebRTC.

Currently we are using Kurento 6.1.1 on Ubuntu 14.04 in a docker container.

When running tests 60 presenters, and 60 viewers. All viewers are connected to the same presenter.
After about one day, we see that the amount of memory that the kurento process is using is growing in a linear manner.
Using the serverManager->getPipelines->getChilds method, I can verify that I don't have any leaking endpoints.

we also tried Kurento 6.4 and 6.5 but the result is even worse.
This is a production system that runs 24/7.

**KMS Version**:

Version: 6.1.1
Found modules:
    Module: 'core' version '6.1.2'
    Module: 'elements' version '6.1.1'
    Module: 'filters' version '6.1.1'

Even worse on KMS 6.4 and 6.5

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.5.2.1~20150901123759.34.g07a7b16.trusty amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.7.1~20151001151322.10.ge060eb5.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.5.91~20151001151316.36.gdaf52b5.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.5.91~20151001151055.18.g79a42eb.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.5.91~20151001151133.27.g3b1cc74.trusty  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.5.91~20151001151113.10.g1b92d89.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.5.91~20151001151133.27.g3b1cc74.trusty  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.5.91~20151001151055.18.g79a42eb.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.1.2.trusty                              amd64        Kurento core module
ii  kms-elements-6.0                     6.1.1.trusty                              amd64        Kurento elements module
ii  kms-filters-6.0                      6.1.1.trusty                              amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.0.0.trusty                              amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20151001151058.38.g263929e.trusty   amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.1.1.trusty                              amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.5.91~20151001151316.36.gdaf52b5.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.5.91~20151001151055.18.g79a42eb.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.5.91~20151001151012.86.g29e3bbd.trusty  amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.7.1~20151001151322.10.ge060eb5.trusty amd64        ICE library (shared library)
ii  openwebrtc-gst-plugins               0.10.0~20151001151244.100.g61cc54b.trusty amd64        OpenWebRTC specific GStreamer plugin

**Client libraries**

javascript - nodejs v5.6.0
kurento-client 6.2.0

**Browsers tested**

have tested this issue:
- Chrome:
- Native
  **System description:**
  source: Native c++ 
  viewers: chrome 48 (kurento-utils)

**What steps will reproduce the problem?**
1. Create 60 source peers and connect to the KMS
2. Create 60 clients (chrome) and connect to the KMS, all connected to one pipeline (one source)
3. Keep the system running for more than 24 hours

**What is the expected result?**
The memory of the KMS process should not increase
**What happens instead?**
The memory increases. See screenshot
![memory](https://cloud.githubusercontent.com/assets/6139491/16035296/15a7ef06-321f-11e6-8b0c-3e62120879ac.PNG)

**Comment by jcaden** [comment]
@rbenitez Can you create a stability test for this, please?

@yehiyam Could you add some details about how the endpoints are exactly connected? Was the memory problem triggered by some action (ie: browser disconnected, new user added, etc).

**Comment by yehiyam** [comment]
@jcaden The big memory increase was when no action was performed.
Prior to the big increase, we were stress testing the system (adding and removing viewers, i.e. browsers).
Also worth mentioning: we have a timer that periodically samples the statistics from all source peers. We suspect that this is connected to the memory increase.


Another use case in which we notices an increase in memory (although at a much lower rate) is when we connect and disconnect viewers. We noticed that when we connect 60 viewers, the memory increases by about 25 MB, but when we disconnect them the memory falls by only 20 MB. When combined after many cycles, this can add to significant (but slow) increase. (In this test we did not query the statistics)

**Comment by jcaden** [comment]
@yehiyam how long does it take from the stress tests to the memory leak? Some minutes (under 10) or some hours?

**Comment by yehiyam** [comment]
@jcaden Sometimes it happened within an hour and other times it only started overnight (after 5 or 6 hours)

**Comment by rbenitez** [comment]
Hi @yehiyam, I have a question

In this part of the thread, you said:

> 1. Create 60 source peers and connect to the KMS
> 2. Create 60 clients (chrome) and connect to the KMS, all connected to one pipeline (one source)

Do you want to mean that the anothers (59 source) haven't any client connected to them?

Thanks

**Comment by yehiyam** [comment]
@rbenitez 
In this test that was the case.

**Comment by rbenitez** [comment]
Thanks @yehiyam

**Comment by jcaden** [comment]
It seems that this issue is related with #87

**Comment by Lisitskiy** [comment]
Hello. I have same problem with kms from docker. 
Mem Usage grows up very fast. Can be 2Gb per 1h.
Do you have some advices for it ?

**Comment by jcaden** [comment]
We have improved this behavior a little bit on development version, but we are still working on it.

**Comment by Lisitskiy** [comment]
Hi, can you give some advice for this task an #114
Maybe temporary decision?

We have to restart kms twice a day. It is very big problem for our app in production

**Comment by Lisitskiy** [comment]
Hello, do you have any info for this tucket? Our pro server still in problems with it.
Thanks

**Comment by Lisitskiy** [comment]
Hi. Do you have any info about this bug? Maybe some roadmap, when it will be done?
Thanks alot.

**Comment by Lisitskiy** [comment]
@jcaden Hi. Do you have any news about this bug? Maybe some roadmap, when it will be done?
Thanks alot.

**Comment by vasconce1o** [comment]
Hi. I have the same problem. So a try to implement may own project based on gstreamer, and i have the same memory leaks, so, the problem may be on gstreamer implementation.

**Comment by brstgt** [comment]
Are there any news on that? We also encounter leaks in 6.6 and 6.7.1

**Comment by rukesun** [comment]
I also meet this problem. though there is no users and connections, the memory is not free. kms version is 6.7.1
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                       
45284 kurento   20   0 29.3g 2.4g  29m S  0.0  1.9   8683:54 ./sbin/kurento-media-server
