### ISSUE TITLE
Kurento keeps consuming server resources until the point where it times out requests

### ISSUE THREAD

**Issue by kasperkronborg** [Kurento/bugtracker#87]
**KMS Version**:
Version: 6.4.0
Found modules:
Module: 'core' version '6.4.0'
Module: 'elements' version '6.4.0'
Module: 'filters' version '6.4.0'

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.7.0.1~20160224182850.34.g1d2c0c1.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.7.1.1~20160224182649.23.g036c2d2.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.7.1.1~20160224182713.65.ge5dc864.trusty  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.4.0.trusty                               amd64        Kurento core module
ii  kms-elements-6.0                     6.4.0.trusty                               amd64        Kurento elements module
ii  kms-filters-6.0                      6.4.0.trusty                               amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.0.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160224182314.38.g263929e.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.4.0.trusty                               amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.7.1.1~20160224231436.127.g7acabd3.trusty amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.7.1.1~20160224182824.59.ge0bd9ca.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.7.1.1~20160225111550.199.gba35ee7.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160224182402.77.g7bbb87a.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: Node.js
- Version: 6.2.0

**Browsers tested**
- Chrome: 51.0.2704.103 (64-bit), FAILED

**System description:**
KMS is located on it's own server, Ubuntu 14.04.
KMS is not configured to use TURN/STUN
Clients is getting TURN/STUN through a service called XirSys.
Web application is on it's own server, Ubuntu 14.04.

**What steps will reproduce the problem?**
The problem together with our pipeline, has been discussed in details on [Kurento Google Groups](https://groups.google.com/forum/#!topic/kurento/NxhPDtkDbIs)
1. Start KMS.
2. Have 15 speakers and 10 participants join an event.
3. The 15 speakers negotiate a connection which allows both sending and receiving audio and video.
4. The 10 passive participants only receive audio and video.
5. Mix the audio from an other connection (audio source) together with the video of the active speaker.
6. Change the active speaker. 

**What is the expected result?**
To not have KMS consuming more and more resources on the server.

**What happens instead?**
Both CPU and RAM and getting consumed up rapidly to the point where connections are timed out.

**Does it happen with one of the tutorials?**
Not tested with any of the tutorials.

**Please provide any additional information below.**
As mentioned earlier, this problem have been discussed with Jose, on [Kurento Google Groups](https://groups.google.com/forum/#!topic/kurento/NxhPDtkDbIs). He suspect it to be a race condition which should be very uncommon, but we have none the less still been affected by this a couple of times now.

**Comment by jcaden** [comment]
Lets follow the discussion in #85
