### ISSUE TITLE
kms-core cmakelists.txt incorrect check for gstreamer pkg-config file

### ISSUE THREAD

**Issue by roxlu** [Kurento/bugtracker#89]
**KMS Version**: commit e351913efae7a6dbe78acbb2895af4256df38796

I'm trying to compile the kms-core from source (with custom gstreamer) but it fails because the `generic_find()` tries to locate `gstreamer-1.5.pc` but gstreamer generates gstreamer-1.0.pc, even for gstreamer version 1.8.2. This could be easily solved by searching for 1.0 instead. 

See https://github.com/Kurento/kms-core/blob/master/CMakeLists.txt#L34

**Comment by jcaden** [comment]
This is done in purpose as we are using our own gstreamer version. This is basically a fork of gstreamer that we have tested and that we update when we need new changes or bugfixes

**Comment by roxlu** [comment]
Ah! jcaden thanks, maybe it's a good idea to communicatie that in all the repositories?  Or maybe I just didn't see it in the readme.
