### ISSUE TITLE
NPM package 'kurento-browser-extensions' doesn't exist

### ISSUE THREAD

**Issue by hunternet93** [Kurento/bugtracker#9]
kurento-utils optionally depends on kurento-browser-extensions, a non-existent package. This causes Meteor to crash while attempting to install kurento-utils. While that's probably a Meteor bug, it might be a good idea to create a stub package or something.

**Comment by igracia** [comment]
We'll either do that, or remove the dependency.

**Comment by hunternet93** [comment]
What's the timeframe on fixing this? Would anyone mind if I created a stub package with that name until a Kurento dev can fix the issue? Sorry to be a bother, but I'd like to get coding.

**Comment by igracia** [comment]
@hunternet93 We really couldn't get our hands on this. It's such a corner case and something that only affects Meteor, that it's not very likely we fix it anytime soon.

**Comment by mariotacke** [comment]
Looks like this issue has been resolved, there is now a package that gets installed with kurento utils, which has no content. I still think the dependency should just be removed than having a stub project dependency.

**Comment by igracia** [comment]
@mariotacke Probably you are right. Nevertheless, the future of the library is uncertain, so we are not putting much effort into that. If you don't mind, we can close the issue.

**Comment by mariotacke** [comment]
That's fine with me.
