### ISSUE TITLE
kms-elements interface json files are not valid

### ISSUE THREAD

**Issue by metal3d** [Kurento/bugtracker#93]
I'm working on the kurento golang generator and I decided to finish my work but the bad surprise is that some json files are not valid in kms-elements.
I'm using these files to generate golang structures and methods.

Example:
kms-elements/src/server/interface/elements.PlayerEndpoint.kmd.json

The problem is that strings contains real carriage returns instead of "\n".

I will need to fix it myself in my generator. Can you please fix this ?

**Comment by jcaden** [comment]
The json parsing is supossed to be done by KurentoModuleCreator, then you need to provide templates to this program in order to generate code for each language.

He have tested and KurentoModuleCreator is parsing all kmd's correctly. My advice is to use templates for generating the binding as KurentoModuleCreator is also consolidating modules and importing dependencies.

**Comment by metal3d** [comment]
One year ago, the team told me to use this files to generate bindings for Go: https://github.com/metal3d/kurento-go-generator that worked and I was able to connect server. You say  to me that, today, I have to recreate the entire generator ? Only because the file is not valid ?

**Comment by jcaden** [comment]
The way we have always generated clients code is by using KurentoModuleCreator to read kmd files and process different templates for each language. Sorry for the misunderstanding, maybe it could be easy to adapt the generator to use KurentoModuleCreator templates.

**Comment by metal3d** [comment]
Unfortunatly no... so I'm currently testing the generator and I try to
understand the template language. I'm checking how you generate cpp code
and right now I'm able to get Go structures + constructors.
Thanks to point me to generator. I think it's a better solution to use the
same tool as you.
Maybe template documentation exists somewhere ?
One more time: Nice work

**Comment by jcaden** [comment]
Templates are written using Freemaker. Here is a link to the specific version we are using http://freemarker.org/docs/versions_2_3_19.html
