### ISSUE TITLE
KMS 6.5.0, appRTC android to Firefox build 47.0 on MacOsx -- Recorded File corrupted in meta-data

### ISSUE THREAD

**Issue by MariFio** [Kurento/bugtracker#96]
**KMS Version**:

Version: 6.5.0
Found modules:
    Module: 'core' version '6.5.0'
    Module: 'elements' version '6.5.0'
    Module: 'filters' version '6.5.0'

**Other libraries versions**:

ii  gstreamer0.10-nice:amd64  0.1.4-1  amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64    0.1.4-1   amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64   1.7.0.1~20160530102916.35.g90e6470.trusty           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64    0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty            amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64   1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64  1.8.0~20160530103259.265.geca7cfe.trusty            amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64  1.8.0~20160530103107.83.g4885bb3.trusty             amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64    1.8.0~20160530103259.265.geca7cfe.trusty            amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64   1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0   6.5.0.20160530141614.trusty   amd64        Kurento core module
ii  kms-elements-6.0    6.5.0.20160530154355.trusty    amd64        Kurento elements module
ii  kms-filters-6.0  6.5.0.20160530155443.trusty    amd64        Kurento filters module
ii  kms-jsonrpc-1.0  1.1.1.trusty    amd64        Kurento jsonrpc library
ii  kmsjsoncpp      1.6.3~20160530102631.40.gd78deb7.trusty             amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0   6.5.0.20160530172436.trusty   amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64     1.8.0~20160530103612.645.gb68ba3e.trusty            amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64     1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64    1.8.0~20160530103131.368.g0fb3a08.trusty            amd64        Core GStreamer libraries and elements
ii  libnice10:amd64   0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (shared library)

**Client libraries**
- Language: java
- Version: 6.5.0

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: (Not Tested)
- Firefox: (FAILED)
- Native:  Android & iOS Native

**System description:**
STUN / TURN is on Virtual Machine 
KMS is located on the same VM of STUN / TURN
Clients:
- Mobile: Android and iOS with webRTC native code as base (appRTC)
- Web: Firefox 

**What steps will reproduce the problem?**
1. Call from the android device the browser peer
2. Answer on the browser
3. The call is perfectly established
4. When closing the call the recorder create the file and saves the content
5. The video/audio is recorded correctly but the file seems to be corrupted. This means that:
- The audio metadata is audio/x-unknown
- The length in time is forever 20hours / 22 minutes / 42 seconds
- If the video is opened it shows nothing untile 5 minutes where the video starts to be reproduced

**What is the expected result?**
The recorded video meta-data are correctly set and the video is reproduced correctly.

**What happens instead?**
The video is reproduced but due to wrong meta-data (I think) the real video starts after 5 minutes

**Does it happen with one of the tutorials?**
No, I've adapter your signaling examples in a appRTC based android/iOS mobile application

**Please provide any additional information below.**
Another strange think is that:
-> If the call is started from a native webRTC SDK app then the error reveals
-> if the call is started from an openWebRTC SDK app the problems seems to not happen

Could it depend from the mobile SDK?
<img width="448" alt="schermata 2016-07-06 alle 00 00 47" src="https://cloud.githubusercontent.com/assets/3052957/16601516/325a8f42-430d-11e6-85db-3fb90f1730a8.png">

**Comment by jcaden** [comment]
Hi, could you please try using the nightly builds?

I think that the problem is caused by timestamps due to a bug on some clients. We have improved the synchronization algorithm to workaround this problems, maybe this could solve your issue.

**Comment by MariFio** [comment]
Hi José,
I am really so grateful to you for the support. 
Ok I'll try to have a nightly build installed, do I have to follow instruction in the documentation at page 273 and, moreover, do I have to update also client kurento libraries according to latest version of the nightly build?

**Comment by jcaden** [comment]
It's enough if you upgrade your kms. I don't know what do you mean by page 273, sorry.

**Comment by MariFio** [comment]
Hi José sorry for misunderstandings I was referring to the official kurento documentation related to nightly builds. BTW, I've updated kurento... now i am going to try...keep you updated.

**Comment by MariFio** [comment]
I've run my android app with the native webRTC stack (no openWebRTC). 
Now it seems that the file is not corrupted any more. I am able to stream it and to download it correctly but if I right click on the file to check properties now it gives me 0 seconds as its length.

Despite this, everything is working now and the file seems not to be corrupted. 
Do you have an idea on why now it gives 0 seconds but it works? :-) 

Thanks again.
Mario

**Comment by jcaden** [comment]
The 0 length can happen with `webm` videos if they are not correctly closed (calling stopAndWait) or if they are stored using a transport different than file:/// is this your situation.

**Comment by MariFio** [comment]
mmm ok! I'll have a further check on this...
I'm pretty sure that I'm closing the file with stopAndWait but I'll check and be back to you as soon as I can on this. 

For sure I can tell you that I'm using file:///.
Keep you updated on this. 

Thanks for everything.
Mario

**Comment by MariFio** [comment]
So I can confirm that:
- The path of the file begins with file://
- I end the recording operation as specified in previous message.

I do not know probably, could it be that the stopAndWait invocation in the wrong place?

**Comment by MariFio** [comment]
To add more information: the problem still persists in v6.6.0 and 6.6.1-dev.
Is there any update on this?

**Comment by jcaden** [comment]
Can you update the packages version as requested in the bug report? You can add a new comment with this information instead of editing.

**Comment by MariFio** [comment]
Hi José, 
here they are:

`ii  gstreamer0.10-nice:amd64                              0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                               0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64                              1.7.0.1~20160530102916.35.g90e6470.trusty           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                               0.1.13.1~20160530102934.80.gd9ef50e.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64                        1.8.0~20160530103612.645.gb68ba3e.trusty            amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64                       1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64                       1.8.0~20160530103259.265.geca7cfe.trusty            amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64                       1.8.0~20160530103107.83.g4885bb3.trusty             amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64                         1.8.0~20160530103259.265.geca7cfe.trusty            amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                                  1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                          6.5.0.20160530141614.trusty                         amd64        Kurento core module
ii  kms-elements-6.0                                      6.5.0.20160530154355.trusty                         amd64        Kurento elements module
ii  kms-filters-6.0                                       6.5.0.20160530155443.trusty                         amd64        Kurento filters module
ii  kms-jsonrpc-1.0                                       1.1.1.trusty                                        amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                            1.6.3~20160530102631.40.gd78deb7.trusty             amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                              6.5.0.20160530172436.trusty                         amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64                   1.8.0~20160530103612.645.gb68ba3e.trusty            amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64                  1.8.0~20160530103212.387.g21728a3.trusty            amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                               1.8.0~20160530103131.368.g0fb3a08.trusty            amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                                       0.1.13.1~20160909144510.80.gd9ef50e.trusty          amd64        ICE library (shared library)
`

**Comment by jcaden** [comment]
Those are 6.5.0 versiones. The one thats is working is 6.6.1-dev. remember to update kms-core and elements as well, not only media server package.

**Comment by MariFio** [comment]
Sorry, but I downgrade to 6.5.0 because on 6.6.0 ios with libjingle is not streaming any more (I'll open another issue). 
Here a link to the created file: https://www.dropbox.com/s/zfmlphihb55l032/2016-09-25_12-25-55-695.webm?dl=0

Here the updates libraries:

**KMS Version**:

Version: 6.6.1~1.g86ced08
Found modules:
	Module: 'core' version '6.6.1~14.g23f38df'
	Module: 'elements' version '6.6.1~7.gc8ba07e'
	Module: 'filters' version '6.6.1~1.g9acbf2d'

**Other libraries versions**:
`kms@kms-VirtualBox:~$ dpkg -l | egrep -i "kurento|gst.*1.5|nice"
ii  gstreamer0.10-nice:amd64                              0.1.13.1~20160914180028.81.geebfdab.trusty          amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                               0.1.13.1~20160914180028.81.geebfdab.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-libav:amd64                              1.8.2.1~20160909143244.96.g493eee4.trusty           amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                               0.1.13.1~20160914180028.81.geebfdab.trusty          amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64                        1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64                       1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64                       1.8.1.1~20160909143047.112.g9ee4248.trusty          amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64                       1.8.1.1~20160909192513.89.g2685b0f.trusty           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64                         1.8.1.1~20160909143047.112.g9ee4248.trusty          amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                                  1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                          6.6.1~20160923173318.14.g23f38df.trusty             amd64        Kurento core module
ii  kms-elements-6.0                                      6.6.1~20160923175002.7.gc8ba07e.trusty              amd64        Kurento elements module
ii  kms-filters-6.0                                       6.6.1~20160923181422.1.g9acbf2d.trusty              amd64        Kurento filters module
ii  kms-jsonrpc-1.0                                       1.1.2~20160923170947.5.g2e83b88.trusty              amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                            1.6.3~20160909143252.40.gd78deb7.trusty             amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                              6.6.1~20160923183547.1.g86ced08.trusty              amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64                   1.8.1.1~20160909144557.99.gf836e53.trusty           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64                  1.8.1.1~20160909142623.55.g7b19cfd.trusty           amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                               1.8.1.1~20160909144007.170.g0d6031b.trusty          amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                                       0.1.13.1~20160914180028.81.geebfdab.trusty          amd64        ICE library (shared library)
`
