### ISSUE TITLE
The MediaStream 'ended' event is deprecated and will be removed in M53, around September 2016.(Chrome)

### ISSUE THREAD

**Issue by Frenzy88** [Kurento/bugtracker#97]
A minor issue with updating the current kurento utls lib's according to the new chrome event handling. 
chrome warns the following message when using the kurento-util's :
**kurento-utils.js:394** The MediaStream 'ended' event is deprecated and will be removed in M53, around September 2016. Please use the MediaStream 'inactive' event instead. See  
[https://www.chromestatus.com/features/5730404371791872](https://www.chromestatus.com/features/5730404371791872)
 for more details.

**Comment by igracia** [comment]
Thanks! We'll get that fixed, either in this library or in whatever comes next, as the lifetime of the library might be reaching to its end.

**Comment by igracia** [comment]
We finally removed this hook to the `ended` event.
