### ISSUE TITLE
KMS 6.5.0, Ubuntu 14.04 LTS, only audio recording Android clients

### ISSUE THREAD

**Issue by kontonieaktywne1** [Kurento/bugtracker#98]
**KMS Version**:
Version: 6.5.0
Found modules:
        Module: 'core' version '6.5.0'
        Module: 'elements' version '6.5.0'
        Module: 'filters' version '6.5.0'

**Other libraries versions**:
`ii  gstreamer1.5-libav:amd64                 1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                  0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64           1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64          1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64          1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64          1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64            1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                     1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                             6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                         6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                          6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                          1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                               1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                 6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64      1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:amd64     1.2.4-1~ubuntu2                            amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-0:amd64     1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.0-0:amd64                  1.2.4-0ubuntu1                             amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0:amd64                  1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                          0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)
ii  openwebrtc-gst-plugins                   0.10.0~20160530102334.102.g8032e1b.trusty  amd64        OpenWebRTC specific GStreamer plugins`

**Client libraries**

```
Language: java
Version: 6.5.0
```

**Browsers tested**
- Chrome: OK
- Firefox: OK
- Native: Android Fail

**System description:**
    Simple KMS installation with Room Server

**What steps will reproduce the problem?**
1. Start recording Android client on server

**What is the expected result?**
Recordered file with audio and video

**What happens instead?**
Recordered file has only audio

**Please provide any additional information below.**
Follow this discussion:
https://groups.google.com/forum/#!topic/kurento/ITfiiM6_QYc
Android testing version:
https://github.com/kontonieaktywne1/KurentoAndroidExample
Server side code, when problems are occured
https://github.com/kontonieaktywne1/KurentoRoomServerExample

**Comment by yongsgit** [comment]
I have the same issue, but I found that Browser webrtc stream and native android webrtc stream is different.
Audio stream is the same, I think.
BUt Video stream is not the same.
.....
We need support from the support.
Anyone solved this problem?

**Comment by keivanh** [comment]
I have this issue, browsers work fine but Android Google WebRTC library fails to connect to KMS 6.5.0.
Ubuntu 16.04

**Comment by j1elo** [comment]
Closing old issues. A lot has improved since Kurento 6.5 (current version is 6.14)
